-- ============================================
-- LUMA — Treasure Island Tome 3 : Chapitres XII-XV (Le conseil de guerre, le premier meurtre, Ben Gunn)
-- Texte original, domaine public
-- ============================================


with s as (select id from books where title = 'Treasure Island' and is_series = true),
     lang as (select id from languages where code = 'en')
insert into books (language_id, title, theme, description, cecr_level, cover_emoji, total_pages, position, series_id, volume_number)
select lang.id, 'Tome 3 : L''homme de l''île', 'Classique • Robert Louis Stevenson (1883)', 'L''Hispaniola atteint l''île, Jim s''échappe à terre, assiste au premier meurtre de Silver, et rencontre l''étrange marin marronné Ben Gunn.', 'B1-B2', '🏝️', 4, 2, s.id, 3
from lang, s;


with b as (select id from books where title = 'Tome 3 : L''homme de l''île' and series_id = (select id from books where title = 'Treasure Island' and is_series = true))
insert into book_pages (book_id, page_number, sentences)
select b.id, 1, '[{"en": "Jim slipped from the barrel and joined the others on deck. ''Has any one of you ever seen that land ahead?'' asked the captain.", "fr": "Jim se glissa hors du tonneau et rejoignit les autres sur le pont. ''L''un de vous a-t-il déjà vu cette terre devant nous ?'' demanda le capitaine."}, {"en": "''I have, sir,'' said Silver. Captain Smollett showed him a chart, and Long John''s eyes burned, but it was only an accurate copy, without the crosses.", "fr": "''Moi, monsieur,'' dit Silver. Le capitaine Smollett lui montra une carte, et les yeux de Long John s''enflammèrent, mais ce n''était qu''une copie exacte, sans les croix."}, {"en": "Jim finally told Dr. Livesey: ''Get the captain and squire down to the cabin. I have terrible news.''", "fr": "Jim finit par dire au Dr Livesey : ''Faites descendre le capitaine et le châtelain à la cabine. J''ai de terribles nouvelles.''"}, {"en": "Jim told them everything he had overheard in the apple barrel. ''Now, captain,'' said the squire, ''you were right, and I was wrong.''", "fr": "Jim leur raconta tout ce qu''il avait entendu dans le tonneau de pommes. ''Alors, capitaine,'' dit le châtelain, ''vous aviez raison, et j''avais tort.''"}, {"en": "The captain counted their allies: only seven of twenty-six could be trusted, and one of the seven was a boy.", "fr": "Le capitaine compta leurs alliés : seulement sept sur vingt-six pouvaient être considérés comme fiables, et l''un des sept était un enfant."}, {"en": "''We must lay to, and keep a bright lookout,'' said the captain. ''It''s trying on a man, but there''s no help for it till we know our men.''", "fr": "''Nous devons temporiser, et rester bien vigilants,'' dit le capitaine. ''C''est éprouvant, mais on ne peut rien faire tant qu''on ne connaît pas nos hommes.''"}]'::jsonb from b;


with b as (select id from books where title = 'Tome 3 : L''homme de l''île' and series_id = (select id from books where title = 'Treasure Island' and is_series = true))
insert into book_pages (book_id, page_number, sentences)
select b.id, 2, '[{"en": "The next morning, the island''s grey woods and wild stone spires filled Jim with dread. From the first look, he hated the very thought of Treasure Island.", "fr": "Le lendemain matin, les bois gris et les pics de pierre sauvages de l''île remplirent Jim d''appréhension. Dès le premier regard, il détesta jusqu''à l''idée même de l''Île au trésor."}, {"en": "Dr. Livesey sniffed the stagnant air. ''I don''t know about treasure,'' he said, ''but I''ll stake my wig there''s fever here.''", "fr": "Le Dr Livesey renifla l''air stagnant. ''Je ne sais rien du trésor,'' dit-il, ''mais je parierais qu''il y a de la fièvre ici.''"}, {"en": "The captain devised a plan: let the crew go ashore for the afternoon, trusting Silver to keep order among them.", "fr": "Le capitaine conçut un plan : laisser l''équipage descendre à terre pour l''après-midi, faisant confiance à Silver pour maintenir l''ordre parmi eux."}, {"en": "As the boats prepared to leave, Jim had a mad idea: he slipped over the side and hid himself in one of the boats bound for shore.", "fr": "Alors que les canots se préparaient à partir, Jim eut une idée folle : il se glissa par-dessus bord et se cacha dans l''un des canots en route vers le rivage."}, {"en": "His boat reached shore first. Jim leaped out and plunged into the thicket while Silver and the rest were still far behind.", "fr": "Son canot atteignit le rivage en premier. Jim sauta et plongea dans le fourré tandis que Silver et les autres étaient encore loin derrière."}, {"en": "''Jim, Jim!'' Silver shouted after him. But Jim ran on, ducking and breaking through the brush, until he could run no longer.", "fr": "''Jim, Jim !'' cria Silver après lui. Mais Jim continua de courir, se baissant et se frayant un chemin à travers les broussailles, jusqu''à ne plus pouvoir courir."}]'::jsonb from b;


with b as (select id from books where title = 'Tome 3 : L''homme de l''île' and series_id = (select id from books where title = 'Treasure Island' and is_series = true))
insert into book_pages (book_id, page_number, sentences)
select b.id, 3, '[{"en": "Exploring the strange island alone, Jim felt for the first time the joy of exploration—until he heard voices approaching through the marsh.", "fr": "Explorant l''étrange île seul, Jim ressentit pour la première fois la joie de l''exploration—jusqu''à ce qu''il entende des voix approcher à travers le marais."}, {"en": "Creeping closer, he saw Long John Silver pleading with an honest sailor named Tom. ''It''s to save your neck that I''m a-speaking,'' Silver said.", "fr": "Rampant plus près, il vit Long John Silver supplier un honnête marin nommé Tom. ''C''est pour sauver ta peau que je te parle,'' dit Silver."}, {"en": "Suddenly a horrible, long-drawn scream echoed from the marsh. ''That''ll be Alan,'' said Silver, smiling but warier than ever.", "fr": "Soudain un hurlement horrible et prolongé résonna depuis le marais. ''Ce sera Alan,'' dit Silver, souriant mais plus méfiant que jamais."}, {"en": "''You''ve killed Alan, have you?'' cried Tom. ''Kill me too, if you can. But I defy you!'' And he turned to walk away.", "fr": "''Tu as tué Alan, c''est ça ?'' s''écria Tom. ''Tue-moi aussi, si tu peux. Mais je te défie !'' Et il se détourna pour partir."}, {"en": "With a cry, Silver hurled his crutch like a missile, striking Tom''s back with stunning force, then fell upon him with his knife.", "fr": "Avec un cri, Silver lança sa béquille comme un projectile, frappant le dos de Tom avec une force stupéfiante, puis se jeta sur lui avec son couteau."}, {"en": "Jim nearly fainted with horror. Silver blew a whistle to signal his comrades, and Jim fled deeper into the island, terrified of being found next.", "fr": "Jim faillit s''évanouir d''horreur. Silver siffla pour signaler ses complices, et Jim s''enfuit plus profondément dans l''île, terrifié à l''idée d''être le prochain découvert."}]'::jsonb from b;


with b as (select id from books where title = 'Tome 3 : L''homme de l''île' and series_id = (select id from books where title = 'Treasure Island' and is_series = true))
insert into book_pages (book_id, page_number, sentences)
select b.id, 4, '[{"en": "A wild, shaggy figure suddenly leaped behind a tree. Jim''s terror grew, until the figure fell to its knees, hands clasped in supplication.", "fr": "Une silhouette sauvage et hirsute bondit soudain derrière un arbre. La terreur de Jim grandit, jusqu''à ce que la silhouette tombe à genoux, les mains jointes en supplication."}, {"en": "''Who are you?'' Jim asked. ''Ben Gunn,'' the man answered hoarsely. ''I haven''t spoke with a Christian these three years.''", "fr": "''Qui es-tu ?'' demanda Jim. ''Ben Gunn,'' répondit l''homme d''une voix rauque. ''Je n''ai pas parlé à un chrétien depuis trois ans.''"}, {"en": "Ben Gunn had been marooned on the island by pirates. He asked eagerly, ''You mightn''t happen to have a piece of cheese about you, now?''", "fr": "Ben Gunn avait été abandonné sur l''île par des pirates. Il demanda avec impatience : ''Tu n''aurais pas un bout de fromage sur toi, par hasard ?''"}, {"en": "Learning that Silver was aboard, Ben Gunn revealed a secret: ''I''m rich,'' he whispered, and offered to help in exchange for passage home.", "fr": "Apprenant que Silver était à bord, Ben Gunn révéla un secret : ''Je suis riche,'' murmura-t-il, et proposa son aide en échange d''un passage pour rentrer."}, {"en": "Ben Gunn told how he had once sailed with Flint, and had found the island again, searching for the treasure alone for years.", "fr": "Ben Gunn raconta qu''il avait autrefois navigué avec Flint, et avait retrouvé l''île, cherchant le trésor seul pendant des années."}, {"en": "Suddenly a cannon''s roar echoed across the island. ''They have begun to fight!'' cried Jim, and ran toward the sound with Ben Gunn at his side.", "fr": "Soudain le grondement d''un canon résonna à travers l''île. ''Ils ont commencé à se battre !'' s''écria Jim, et courut vers le bruit avec Ben Gunn à ses côtés."}]'::jsonb from b;
