-- ============================================
-- LUMA — Scénarios jouables : Thématique 3 (Entretien d'embauche) — complète
-- ============================================

update scenarios set content = '{"characters": {"patel": "Mr. Patel (recruteur)"}, "start_node": "n1", "nodes": {"n1": {"speaker": "patel", "text": "So, tell me a bit about yourself.", "text_fr": "Alors, parlez-moi un peu de vous.", "choices": [{"text": "I have five years of experience in marketing, strong analytical skills, and I''m looking to grow into a leadership role.", "next": "end_good"}, {"text": "(a long, unstructured answer covering many unrelated topics)", "next": "n2b"}, {"text": "I''m a hard worker.", "next": "n2c"}]}, "n2b": {"speaker": "patel", "text": "Great, and what would you say is your main strength?", "text_fr": "Bien, et quel serait selon vous votre point fort principal ?", "choices": [{"text": "Definitely my ability to manage complex projects.", "next": "end_recover"}]}, "n2c": {"speaker": "patel", "text": "I see. Could you tell me more about your background?", "text_fr": "Je vois. Pouvez-vous m''en dire plus sur votre parcours ?", "choices": [{"text": "Of course — I studied marketing and have worked in the field for five years.", "next": "end_recover"}]}, "end_good": {"speaker": "patel", "text": "That''s a great, concise summary. Let''s dive deeper.", "text_fr": "C''est un résumé excellent et concis. Approfondissons.", "end": true, "ending_label": "Pitch impeccable ⭐"}, "end_recover": {"speaker": "patel", "text": "Good, that gives me a clearer picture now.", "text_fr": "Bien, ça me donne une image plus claire maintenant.", "end": true, "ending_label": "Rattrapé correctement ✅"}}}'::jsonb, is_playable = true
where title = 'Se présenter en 2 minutes'
  and theme_id = (select id from scenario_themes where position = 3 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"chen": "Ms. Chen (recruteuse)"}, "start_node": "n1", "nodes": {"n1": {"speaker": "chen", "text": "Why are you interested in this position specifically?", "text_fr": "Pourquoi ce poste vous intéresse-t-il en particulier ?", "choices": [{"text": "I''ve researched your company''s expansion plans, and this role aligns perfectly with my project management background.", "next": "end_prepared"}, {"text": "I just really need a job right now.", "next": "n2b"}, {"text": "The salary and schedule seem good.", "next": "n2c"}]}, "n2b": {"speaker": "chen", "text": "I understand, but what draws you to this particular role?", "text_fr": "Je comprends, mais qu''est-ce qui vous attire vers ce poste en particulier ?", "choices": [{"text": "Honestly, I think it''s a great opportunity to grow in this industry.", "next": "end_neutral"}]}, "n2c": {"speaker": "chen", "text": "I see. Those are certainly factors, though I''m curious about the role itself.", "text_fr": "Je vois. Ce sont certes des facteurs, mais je suis curieuse de savoir pour le poste lui-même.", "choices": [{"text": "Of course — I''m also genuinely excited about the growth opportunities here.", "next": "end_neutral"}]}, "end_prepared": {"speaker": "chen", "text": "I really appreciate that you''ve done your research.", "text_fr": "J''apprécie vraiment que vous ayez fait vos recherches.", "end": true, "ending_label": "Motivation convaincante ⭐"}, "end_neutral": {"speaker": "chen", "text": "Alright, thank you for clarifying.", "text_fr": "D''accord, merci d''avoir clarifié.", "end": true, "ending_label": "Impression correcte ✅"}}}'::jsonb, is_playable = true
where title = 'Répondre à "pourquoi ce poste ?"'
  and theme_id = (select id from scenario_themes where position = 3 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"laura": "Laura (RH)"}, "start_node": "n1", "nodes": {"n1": {"speaker": "laura", "text": "Would Tuesday at 10am work for you?", "text_fr": "Mardi à 10h, ça vous conviendrait ?", "choices": [{"text": "Yes, that works perfectly.", "next": "end_confirmed"}, {"text": "I''m not available then, could we do Wednesday instead?", "next": "end_alt"}, {"text": "Could we do it in the afternoon instead?", "next": "end_afternoon"}]}, "end_confirmed": {"speaker": "laura", "text": "Great, see you Tuesday at 10!", "text_fr": "Parfait, à mardi 10h !", "end": true, "ending_label": "Entretien confirmé 📅"}, "end_alt": {"speaker": "laura", "text": "Sure, Wednesday at 10 works too.", "text_fr": "Bien sûr, mercredi 10h ça marche aussi.", "end": true, "ending_label": "Entretien recalé 📅"}, "end_afternoon": {"speaker": "laura", "text": "No problem, let''s say 2pm on Tuesday.", "text_fr": "Pas de souci, disons 14h mardi.", "end": true, "ending_label": "Horaire ajusté 📅"}}}'::jsonb, is_playable = true
where title = 'Négocier une date d''entretien'
  and theme_id = (select id from scenario_themes where position = 3 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"ahmed": "Mr. Ahmed (recruteur technique)"}, "start_node": "n1", "nodes": {"n1": {"speaker": "ahmed", "text": "Can you walk me through a project you''re particularly proud of?", "text_fr": "Pouvez-vous me présenter un projet dont vous êtes particulièrement fier ?", "choices": [{"text": "Sure — the context was X, I took action Y, and the result was Z.", "next": "n2"}, {"text": "I''ve worked on a few interesting things.", "next": "n1b"}]}, "n1b": {"speaker": "ahmed", "text": "Could you give me more specifics on one of them?", "text_fr": "Pourriez-vous me donner plus de précisions sur l''un d''eux ?", "choices": [{"text": "Sure, let me walk you through the main one in detail.", "next": "n2"}]}, "n2": {"speaker": "ahmed", "text": "Interesting. Now, a technical one — how would you optimize a slow database query?", "text_fr": "Intéressant. Maintenant, une question technique — comment optimiseriez-vous une requête de base de données lente ?", "choices": [{"text": "I''m not entirely sure of the exact fix, but here''s how I''d approach diagnosing it.", "next": "n3"}, {"text": "(bluff an uncertain, vague technical answer)", "next": "n3b"}, {"text": "I don''t know.", "next": "n3c"}]}, "n3": {"speaker": "ahmed", "text": "I really like that methodical approach.", "text_fr": "J''apprécie vraiment cette approche méthodique.", "choices": [{"text": "Thank you.", "next": "n4"}]}, "n3b": {"speaker": "ahmed", "text": "Hmm, let''s dig a bit deeper into that.", "text_fr": "Hmm, creusons un peu plus ça.", "choices": [{"text": "Actually, let me reconsider and explain my real approach.", "next": "n4"}]}, "n3c": {"speaker": "ahmed", "text": "That''s okay, let''s move on.", "text_fr": "Ce n''est pas grave, passons à la suite.", "choices": [{"text": "I''d like to add that I''d research it thoroughly if faced with this.", "next": "n4"}]}, "n4": {"speaker": "ahmed", "text": "Last one — tell me about a time you disagreed with a colleague.", "text_fr": "Dernière question — parlez-moi d''une fois où vous avez été en désaccord avec un collègue.", "choices": [{"text": "(give a concrete example with a positive resolution)", "next": "end_strong"}, {"text": "(avoid really answering the question)", "next": "end_weak"}]}, "end_strong": {"speaker": "ahmed", "text": "That''s a great example of professional maturity.", "text_fr": "C''est un excellent exemple de maturité professionnelle.", "end": true, "ending_label": "Entretien technique très réussi ⭐"}, "end_weak": {"speaker": "ahmed", "text": "Alright, thank you for your time today.", "text_fr": "D''accord, merci pour votre temps aujourd''hui.", "end": true, "ending_label": "Entretien correct 👍"}}}'::jsonb, is_playable = true
where title = 'Un entretien technique complet'
  and theme_id = (select id from scenario_themes where position = 3 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"novak": "Ms. Novak (recruteuse)"}, "start_node": "n1", "nodes": {"n1": {"speaker": "novak", "text": "Why did you leave your last position?", "text_fr": "Pourquoi avez-vous quitté votre dernier poste ?", "choices": [{"text": "I was looking for new challenges and growth opportunities that weren''t available there.", "next": "n2"}, {"text": "My old boss was terrible, honestly.", "next": "n2b"}]}, "n2": {"speaker": "novak", "text": "That makes sense. And what would you say is your biggest weakness?", "text_fr": "C''est logique. Et quel serait selon vous votre plus grand défaut ?", "choices": [{"text": "I sometimes take on too much, but I''ve been actively working on delegating more.", "next": "end_tactful"}, {"text": "I don''t really have any weaknesses.", "next": "end_overconfident"}]}, "n2b": {"speaker": "novak", "text": "I see. Let''s focus on what you''re looking for going forward.", "text_fr": "Je vois. Concentrons-nous sur ce que vous recherchez pour la suite.", "choices": [{"text": "I''m looking for a role with more ownership and growth.", "next": "end_recovered"}]}, "end_tactful": {"speaker": "novak", "text": "That''s a very self-aware and honest answer.", "text_fr": "C''est une réponse très lucide et honnête.", "end": true, "ending_label": "Question piège bien gérée ⭐"}, "end_overconfident": {"speaker": "novak", "text": "Everyone has areas to improve — I''d encourage you to reflect on that.", "text_fr": "Tout le monde a des points à améliorer — je vous encourage à y réfléchir.", "end": true, "ending_label": "Réponse perçue comme peu sincère 😕"}, "end_recovered": {"speaker": "novak", "text": "Good, that''s useful to know.", "text_fr": "Bien, c''est utile à savoir.", "end": true, "ending_label": "Sujet délicat contourné ✅"}}}'::jsonb, is_playable = true
where title = 'Gérer une question piège'
  and theme_id = (select id from scenario_themes where position = 3 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"director": "le directeur RH"}, "start_node": "n1", "nodes": {"n1": {"speaker": "director", "text": "We''d like to offer you the position, with a salary of $45,000.", "text_fr": "Nous aimerions vous offrir le poste, avec un salaire de 45 000$.", "choices": [{"text": "Thank you! Based on my experience and market research, I was hoping for something closer to $50,000.", "next": "n2"}, {"text": "That sounds great, I accept.", "next": "end_accept"}]}, "n2": {"speaker": "director", "text": "I understand. Let me see what flexibility we have — how about $48,000 plus performance bonuses?", "text_fr": "Je comprends. Voyons quelle flexibilité on a — que diriez-vous de 48 000$ plus des primes de performance ?", "choices": [{"text": "That sounds fair, I''m happy to accept that.", "next": "end_negotiated"}, {"text": "Could we also discuss additional vacation days instead?", "next": "end_alt_benefit"}]}, "end_accept": {"speaker": "director", "text": "Wonderful, welcome to the team!", "text_fr": "Merveilleux, bienvenue dans l''équipe !", "end": true, "ending_label": "Offre acceptée directement 🤝"}, "end_negotiated": {"speaker": "director", "text": "Great, we''ll get the paperwork ready.", "text_fr": "Parfait, on prépare les documents.", "end": true, "ending_label": "Négociation réussie 💰"}, "end_alt_benefit": {"speaker": "director", "text": "That''s a reasonable request, let''s include a few extra days too.", "text_fr": "C''est une demande raisonnable, ajoutons aussi quelques jours de congé.", "end": true, "ending_label": "Package personnalisé 🎯"}}}'::jsonb, is_playable = true
where title = 'Négocier le salaire'
  and theme_id = (select id from scenario_themes where position = 3 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"hr": "Recrutement RH", "manager": "Manager technique", "director": "Directrice"}, "start_node": "n1", "nodes": {"n1": {"speaker": "hr", "text": "Let''s start with a quick screening call. Why this company?", "text_fr": "Commençons par un appel de présélection. Pourquoi cette entreprise ?", "choices": [{"text": "I admire your recent innovation in sustainable products.", "next": "n2"}, {"text": "I saw the job posting and it looked interesting.", "next": "n2b"}]}, "n2": {"speaker": "hr", "text": "Great, you''re moving on to the technical round.", "text_fr": "Parfait, vous passez au tour technique.", "choices": [{"text": "Looking forward to it.", "next": "n3"}]}, "n2b": {"speaker": "hr", "text": "Okay, let''s continue to the next round.", "text_fr": "D''accord, passons au tour suivant.", "choices": [{"text": "Sounds good.", "next": "n3"}]}, "n3": {"speaker": "manager", "text": "Let''s talk technical skills. How would you handle a tight deadline conflict?", "text_fr": "Parlons compétences techniques. Comment géreriez-vous un conflit de délais serrés ?", "choices": [{"text": "I''d prioritize tasks by impact and communicate early with stakeholders.", "next": "n4"}, {"text": "I''d just work overtime until it''s done.", "next": "n4b"}]}, "n4": {"speaker": "manager", "text": "Good strategic thinking. Let''s move to the final round with our director.", "text_fr": "Bonne réflexion stratégique. Passons au tour final avec notre directrice.", "choices": [{"text": "Great, thank you.", "next": "n5"}]}, "n4b": {"speaker": "manager", "text": "I see, though sustainable pacing matters too. Let''s continue.", "text_fr": "Je vois, mais un rythme durable compte aussi. Continuons.", "choices": [{"text": "That''s fair, noted.", "next": "n5"}]}, "n5": {"speaker": "director", "text": "Final question: where do you see yourself in five years?", "text_fr": "Dernière question : où vous voyez-vous dans cinq ans ?", "choices": [{"text": "Growing into a leadership role while deepening my expertise here.", "next": "end_offer"}, {"text": "Honestly, I''m not sure yet.", "next": "end_neutral"}]}, "end_offer": {"speaker": "director", "text": "That aligns really well with our growth plans. We''ll be in touch soon with an offer!", "text_fr": "Ça correspond vraiment bien à nos plans de croissance. On vous recontacte bientôt avec une offre !", "end": true, "ending_label": "Parcours réussi, offre en vue 🎉"}, "end_neutral": {"speaker": "director", "text": "That''s honest. We''ll let you know our decision soon.", "text_fr": "C''est honnête. On vous fera savoir notre décision bientôt.", "end": true, "ending_label": "Parcours complété, résultat incertain 🤞"}}}'::jsonb, is_playable = true
where title = 'Un parcours d''entretien à plusieurs étapes'
  and theme_id = (select id from scenario_themes where position = 3 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"recruiter": "le recruteur", "competitor": "un autre candidat"}, "start_node": "n1", "nodes": {"n1": {"speaker": "recruiter", "text": "For this group exercise, discuss as a team how to solve this business case.", "text_fr": "Pour cet exercice de groupe, discutez en équipe pour résoudre ce cas pratique.", "choices": [{"text": "I''ll suggest we start by clarifying the objective together.", "next": "n2"}, {"text": "(stay quiet and let others lead)", "next": "n2b"}]}, "n2": {"speaker": "competitor", "text": "Good idea, I think we should focus on cost reduction first.", "text_fr": "Bonne idée, je pense qu''on devrait d''abord se concentrer sur la réduction des coûts.", "choices": [{"text": "That''s valid, though I''d also weigh customer impact before deciding.", "next": "n3"}, {"text": "I disagree, we should focus on revenue growth instead.", "next": "n3b"}]}, "n2b": {"speaker": "recruiter", "text": "I noticed you were quiet — what are your thoughts?", "text_fr": "J''ai remarqué que vous étiez silencieux — qu''en pensez-vous ?", "choices": [{"text": "I was actually listening carefully — I think we should balance cost and customer impact.", "next": "n3"}]}, "n3": {"speaker": "recruiter", "text": "Good collaborative thinking there.", "text_fr": "Belle réflexion collaborative.", "choices": [{"text": "Thank you, teamwork matters a lot to me.", "next": "end_collaborative"}]}, "n3b": {"speaker": "competitor", "text": "Interesting, let''s hear both sides then.", "text_fr": "Intéressant, écoutons les deux points de vue alors.", "choices": [{"text": "Agreed, let''s combine both perspectives into a balanced plan.", "next": "end_collaborative"}]}, "end_collaborative": {"speaker": "recruiter", "text": "You stood out for your collaborative approach today.", "text_fr": "Vous vous êtes démarqué par votre approche collaborative aujourd''hui.", "end": true, "ending_label": "Vous vous démarquez du groupe ⭐"}}}'::jsonb, is_playable = true
where title = 'Un entretien collectif face à des concurrents'
  and theme_id = (select id from scenario_themes where position = 3 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"director": "la directrice RH"}, "start_node": "n1", "nodes": {"n1": {"speaker": "director", "text": "We''re impressed and would like to make you an offer of $52,000.", "text_fr": "Nous sommes impressionnés et aimerions vous faire une offre de 52 000$.", "choices": [{"text": "Thank you! I actually have another offer at $58,000 — is there room to match that?", "next": "n2"}, {"text": "That''s wonderful, I accept!", "next": "end_accept"}]}, "n2": {"speaker": "director", "text": "I see. Let me check with leadership — can you give us a day?", "text_fr": "Je vois. Laissez-moi vérifier avec la direction — vous pouvez nous laisser une journée ?", "choices": [{"text": "Of course, take your time.", "next": "n3"}]}, "n3": {"speaker": "director", "text": "Good news — we can offer $57,000 plus additional benefits. Does that work?", "text_fr": "Bonne nouvelle — on peut proposer 57 000$ plus des avantages supplémentaires. Ça vous convient ?", "choices": [{"text": "That''s excellent, I''m happy to accept!", "next": "end_countered"}, {"text": "Very close — could we settle at $58,000 to match exactly?", "next": "end_pushed"}]}, "end_accept": {"speaker": "director", "text": "Fantastic, welcome aboard!", "text_fr": "Fantastique, bienvenue à bord !", "end": true, "ending_label": "Offre acceptée directement 🤝"}, "end_countered": {"speaker": "director", "text": "Perfect, we''re thrilled to have you.", "text_fr": "Parfait, on est ravis de vous accueillir.", "end": true, "ending_label": "Contre-offre bien négociée 💰"}, "end_pushed": {"speaker": "director", "text": "You drive a hard bargain — deal, $58,000 it is!", "text_fr": "Vous négociez serré — marché conclu, va pour 58 000$ !", "end": true, "ending_label": "Négociation maximale réussie 🏆"}}}'::jsonb, is_playable = true
where title = 'Un entretien qui se termine par une contre-offre'
  and theme_id = (select id from scenario_themes where position = 3 and language_id = (select id from languages where code = 'en'));
