-- ============================================
-- LUMA — Exercices pratiques pour les 6 fiches de grammaire C1
-- 7 exercices par fiche. Dernier niveau -> les 36 fiches ont maintenant
-- toutes des exercices pratiques.
-- ============================================

with f as (select id from grammar_fiches where cecr_level = 'C1' and position = 31)
insert into grammar_fiche_exercises (fiche_id, position, type, content)
select f.id, v.position, v.type, v.content::jsonb from f, (values
(1, 'qcm', '{"question": "Complète : Never ___ I seen such dedication.", "options": ["have", "had", "do", "did"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"have\"."}'),(2, 'qcm', '{"question": "Complète : Not only ___ brilliant, but also modest.", "options": ["is she", "she is", "does she", "is her"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"is she\"."}'),(3, 'fill_blank', '{"sentence_before": "Hardly ", "sentence_after": " I sat down when the phone rang. (had)", "correct_answers": ["had"], "feedback_correct": "Correct !", "feedback_incorrect": "Hardly...when → inversion avec had."}'),(4, 'fill_blank', '{"sentence_before": "Little ", "sentence_after": " she know what awaited her. (did)", "correct_answers": ["did"], "feedback_correct": "Correct !", "feedback_incorrect": "Little en tête de phrase → inversion avec did."}'),(5, 'true_false', '{"statement": "Inversion after negative adverbs like ''never'', ''rarely'', ''hardly'' is typical of formal or literary English.", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Relis la règle."}'),(6, 'reorder', '{"words": ["Never", "have", "I", "seen", "such", "a", "mess."], "correct_sentence": "Never have I seen such a mess."}'),(7, 'error_correction', '{"wrong_sentence": "Never I have seen such dedication.", "correct_sentence": "Never have I seen such dedication.", "error_word": "I", "feedback_correct": "Bien vu !", "feedback_incorrect": "Regarde le mot en rouge.", "explanation": "Après un adverbe négatif en tête de phrase → inversion auxiliaire+sujet (have I), pas sujet+auxiliaire."}')
) as v(position, type, content);

with f as (select id from grammar_fiches where cecr_level = 'C1' and position = 32)
insert into grammar_fiche_exercises (fiche_id, position, type, content)
select f.id, v.position, v.type, v.content::jsonb from f, (values
(1, 'qcm', '{"question": "''Study harder,'' she told him. → She told him ___", "options": ["to study harder", "study harder", "that study harder", "studying harder"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"to study harder\"."}'),(2, 'qcm', '{"question": "''I didn''t take it,'' he said. → He denied ___ it.", "options": ["taking", "to take", "take", "took"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"taking\"."}'),(3, 'fill_blank', '{"sentence_before": "''I''ll help you,'' she promised. → She promised ", "sentence_after": " me. (help)", "correct_answers": ["to help"], "feedback_correct": "Correct !", "feedback_incorrect": "promise + infinitif (to help)."}'),(4, 'fill_blank', '{"sentence_before": "''It was me,'' he admitted. → He admitted ", "sentence_after": " responsible. (be)", "correct_answers": ["being"], "feedback_correct": "Correct !", "feedback_incorrect": "admit + gérondif (being)."}'),(5, 'true_false', '{"statement": "''Deny'' and ''admit'' are followed by a gerund, while ''promise'' and ''threaten'' are followed by an infinitive.", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Relis la règle."}'),(6, 'reorder', '{"words": ["She", "advised", "him", "to", "see", "a", "doctor."], "correct_sentence": "She advised him to see a doctor."}'),(7, 'error_correction', '{"wrong_sentence": "He denied to take the money.", "correct_sentence": "He denied taking the money.", "error_word": "to", "feedback_correct": "Bien vu !", "feedback_incorrect": "Regarde le mot en rouge.", "explanation": "\"deny\" est suivi du gérondif (taking), jamais de l''infinitif."}')
) as v(position, type, content);

with f as (select id from grammar_fiches where cecr_level = 'C1' and position = 33)
insert into grammar_fiche_exercises (fiche_id, position, type, content)
select f.id, v.position, v.type, v.content::jsonb from f, (values
(1, 'qcm', '{"question": "Complète (it-cleft) : It was ___ who called, not John.", "options": ["Mary", "that Mary", "Mary who", "she"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"Mary\"."}'),(2, 'qcm', '{"question": "Complète (what-cleft) : ___ I need is a quiet place.", "options": ["What", "That", "It", "Which"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"What\"."}'),(3, 'fill_blank', '{"sentence_before": "It was the manager ", "sentence_after": " made the decision. (who)", "correct_answers": ["who", "that"], "feedback_correct": "Correct !", "feedback_incorrect": "It was X who/that... : structure it-cleft standard."}'),(4, 'fill_blank', '{"sentence_before": "", "sentence_after": " surprised me was her honesty. (What)", "correct_answers": ["What"], "feedback_correct": "Correct !", "feedback_incorrect": "What-cleft : What + verbe... was..."}'),(5, 'true_false', '{"statement": "Cleft sentences are often used to emphasize or correct a specific part of information.", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Relis la règle."}'),(6, 'reorder', '{"words": ["It", "was", "John", "who", "broke", "the", "vase."], "correct_sentence": "It was John who broke the vase."}'),(7, 'error_correction', '{"wrong_sentence": "It was John which broke the vase.", "correct_sentence": "It was John who broke the vase.", "error_word": "which", "feedback_correct": "Bien vu !", "feedback_incorrect": "Regarde le mot en rouge.", "explanation": "Pour une personne (John) → who/that, jamais which."}')
) as v(position, type, content);

with f as (select id from grammar_fiches where cecr_level = 'C1' and position = 34)
insert into grammar_fiche_exercises (fiche_id, position, type, content)
select f.id, v.position, v.type, v.content::jsonb from f, (values
(1, 'qcm', '{"question": "\"Hit the nail on the head\" veut dire :", "options": ["Voir juste", "Se blesser", "Construire quelque chose", "Échouer"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"Voir juste\"."}'),(2, 'qcm', '{"question": "\"Cost an arm and a leg\" veut dire :", "options": ["Coûter très cher", "Être blessé", "Faire un effort physique", "Être gratuit"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"Coûter très cher\"."}'),(3, 'fill_blank', '{"sentence_before": "This laptop ", "sentence_after": ". (idiome : coûte très cher)", "correct_answers": ["costs an arm and a leg"], "feedback_correct": "Correct !", "feedback_incorrect": "Idiome exact : cost an arm and a leg."}'),(4, 'fill_blank', '{"sentence_before": "Let''s ", "sentence_after": " and try a new approach. (idiome : recommencer à zéro)", "correct_answers": ["go back to the drawing board", "start from scratch"], "feedback_correct": "Correct !", "feedback_incorrect": "Idiome de recommencement à zéro."}'),(5, 'true_false', '{"statement": "Idioms should generally not be translated literally into another language.", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Relis la règle."}'),(6, 'reorder', '{"words": ["It''s", "a", "piece", "of", "cake!"], "correct_sentence": "It''s a piece of cake!"}'),(7, 'error_correction', '{"wrong_sentence": "This project cost an arm and a foot.", "correct_sentence": "This project cost an arm and a leg.", "error_word": "foot", "feedback_correct": "Bien vu !", "feedback_incorrect": "Regarde le mot en rouge.", "explanation": "L''idiome exact est \"an arm and a LEG\", pas \"a foot\"."}')
) as v(position, type, content);

with f as (select id from grammar_fiches where cecr_level = 'C1' and position = 35)
insert into grammar_fiche_exercises (fiche_id, position, type, content)
select f.id, v.position, v.type, v.content::jsonb from f, (values
(1, 'qcm', '{"question": "Quelle formule est la plus formelle ?", "options": ["I would like to inform you that...", "Just so you know...", "FYI...", "Heads up..."], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"I would like to inform you that...\"."}'),(2, 'qcm', '{"question": "\"Kids\" est un mot :", "options": ["Informel", "Très formel", "Académique", "Juridique"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"Informel\"."}'),(3, 'fill_blank', '{"sentence_before": "Version formelle de \"get\" : ", "sentence_after": "", "correct_answers": ["receive", "obtain"], "feedback_correct": "Correct !", "feedback_incorrect": "Registre formel : receive/obtain plutôt que get."}'),(4, 'fill_blank', '{"sentence_before": "Version formelle de \"a lot of\" : ", "sentence_after": "", "correct_answers": ["numerous", "a great deal of"], "feedback_correct": "Correct !", "feedback_incorrect": "Registre formel : numerous/a great deal of plutôt que a lot of."}'),(5, 'true_false', '{"statement": "''Gonna'', ''wanna'', and ''gotta'' are typical of casual spoken English, not formal writing.", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Relis la règle."}'),(6, 'reorder', '{"words": ["I", "would", "appreciate", "your", "prompt", "response."], "correct_sentence": "I would appreciate your prompt response."}'),(7, 'error_correction', '{"wrong_sentence": "I would like to inform you that we gonna proceed.", "correct_sentence": "I would like to inform you that we will proceed.", "error_word": "gonna", "feedback_correct": "Bien vu !", "feedback_incorrect": "Regarde le mot en rouge.", "explanation": "\"gonna\" est très informel, incompatible avec un registre soutenu (\"I would like to inform you\")."}')
) as v(position, type, content);

with f as (select id from grammar_fiches where cecr_level = 'C1' and position = 36)
insert into grammar_fiche_exercises (fiche_id, position, type, content)
select f.id, v.position, v.type, v.content::jsonb from f, (values
(1, 'qcm', '{"question": "Quel marqueur introduit une reformulation ?", "options": ["I mean...", "Anyway...", "Well...", "So..."], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"I mean...\"."}'),(2, 'qcm', '{"question": "Pour trouver un compromis, on peut dire :", "options": ["Let''s meet halfway.", "I totally disagree.", "That''s out of the question.", "Whatever."], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"Let''s meet halfway.\"."}'),(3, 'fill_blank', '{"sentence_before": "", "sentence_after": ", I think we should reconsider. (marqueur de discours, bien)", "correct_answers": ["Well"], "feedback_correct": "Correct !", "feedback_incorrect": "Well : marqueur de discours pour introduire une hésitation/réflexion."}'),(4, 'fill_blank', '{"sentence_before": "", "sentence_after": " it doesn''t really matter. (en fin de compte)", "correct_answers": ["At the end of the day"], "feedback_correct": "Correct !", "feedback_incorrect": "Expression figée : at the end of the day."}'),(5, 'true_false', '{"statement": "Discourse markers like ''well'', ''so'', and ''anyway'' help structure spoken English naturally.", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Relis la règle."}'),(6, 'reorder', '{"words": ["Let''s", "agree", "to", "disagree."], "correct_sentence": "Let''s agree to disagree."}'),(7, 'error_correction', '{"wrong_sentence": "Let''s meet halfways on this.", "correct_sentence": "Let''s meet halfway on this.", "error_word": "halfways", "feedback_correct": "Bien vu !", "feedback_incorrect": "Regarde le mot en rouge.", "explanation": "L''expression correcte est \"meet halfway\", sans -s."}')
) as v(position, type, content);
