-- ============================================
-- LUMA — Scénarios jouables : Thématique 1 (Restaurant), lot 1
-- ============================================

update scenarios set content = '{"characters": {"emma": "Emma (serveuse)"}, "start_node": "n1", "nodes": {"n1": {"speaker": "emma", "text": "Are you ready to order?", "text_fr": "Vous êtes prêt à commander ?", "choices": [{"text": "Yes, but does this dish contain nuts?", "next": "n2"}, {"text": "I have a nut allergy, what''s safe for me?", "next": "n2b"}]}, "n2": {"speaker": "emma", "text": "Let me check... yes, it contains almonds.", "text_fr": "Je vérifie... oui, il contient des amandes.", "choices": [{"text": "Okay, I''ll choose something else.", "next": "n3"}, {"text": "Is there a way to make it without almonds?", "next": "n3b"}]}, "n2b": {"speaker": "emma", "text": "We have two safe options: the grilled fish or the vegetable soup.", "text_fr": "On a deux options sûres : le poisson grillé ou la soupe de légumes.", "choices": [{"text": "I''ll have the grilled fish, thank you.", "next": "end_thanks"}]}, "n3": {"speaker": "emma", "text": "No problem, let me suggest something else.", "text_fr": "Pas de souci, laissez-moi vous suggérer autre chose.", "choices": [{"text": "Thank you so much for checking.", "next": "end_thanks"}]}, "n3b": {"speaker": "emma", "text": "I''m afraid not, the almonds are mixed into the sauce.", "text_fr": "Je crains que non, les amandes sont mélangées à la sauce.", "choices": [{"text": "I understand, I''ll pick something else then.", "next": "end_thanks"}]}, "end_thanks": {"speaker": "emma", "text": "Perfect, I''ll make sure your order is completely safe.", "text_fr": "Parfait, je m''assure que votre commande soit totalement sûre.", "end": true, "ending_label": "Commande sécurisée 🎉"}}}'::jsonb, is_playable = true
where title = 'Une allergie à signaler'
  and theme_id = (select id from scenario_themes where position = 1 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"jack": "Jack (serveur)"}, "start_node": "n1", "nodes": {"n1": {"speaker": "jack", "text": "Could we get the bill, please?", "text_fr": "On peut avoir l''addition, s''il vous plaît ?", "choices": [{"text": "Yes, of course, one moment.", "next": "n2"}]}, "n2": {"speaker": "jack", "text": "Here you go. Is service included, you might ask?", "text_fr": "Voilà. Vous vous demandez si le service est inclus ?", "choices": [{"text": "Is service included?", "next": "n3"}, {"text": "I''ll just pay and add a tip myself.", "next": "end_tip"}]}, "n3": {"speaker": "jack", "text": "Yes, a 12.5% service charge is already added.", "text_fr": "Oui, 12,5% de service sont déjà inclus.", "choices": [{"text": "Great, thank you!", "next": "end_included"}]}, "end_tip": {"speaker": "jack", "text": "That''s very kind of you, thank you!", "text_fr": "C''est très gentil, merci !", "end": true, "ending_label": "Pourboire laissé 💰"}, "end_included": {"speaker": "jack", "text": "Thank you, have a great evening!", "text_fr": "Merci, passez une excellente soirée !", "end": true, "ending_label": "Addition réglée ✅"}}}'::jsonb, is_playable = true
where title = 'Payer et laisser un pourboire'
  and theme_id = (select id from scenario_themes where position = 1 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"mark": "Mark (réceptionniste)"}, "start_node": "n1", "nodes": {"n1": {"speaker": "mark", "text": "Good evening, how can I help?", "text_fr": "Bonsoir, comment puis-je vous aider ?", "choices": [{"text": "A table for 4 at 8pm, please.", "next": "n2"}]}, "n2": {"speaker": "mark", "text": "I''m afraid we''re fully booked at 8pm. We have 6:30 or 9:15 available.", "text_fr": "Je crains que nous soyons complets à 20h. On a 18h30 ou 21h15 de libre.", "choices": [{"text": "6:30 works for us.", "next": "end_early"}, {"text": "Is there a waiting list for 8pm?", "next": "n3"}]}, "n3": {"speaker": "mark", "text": "Yes, I can add you — I''ll call if a table frees up.", "text_fr": "Oui, je vous ajoute — je vous appelle si une table se libère.", "choices": [{"text": "Perfect, thank you!", "next": "end_waitlist"}]}, "end_early": {"speaker": "mark", "text": "Great, table for 4 at 6:30, confirmed!", "text_fr": "Parfait, table pour 4 à 18h30, confirmée !", "end": true, "ending_label": "Réservation confirmée ✅"}, "end_waitlist": {"speaker": "mark", "text": "You''re on the list — fingers crossed!", "text_fr": "Vous êtes sur la liste — croisons les doigts !", "end": true, "ending_label": "Sur liste d''attente 🤞"}}}'::jsonb, is_playable = true
where title = 'Une réservation compliquée'
  and theme_id = (select id from scenario_themes where position = 1 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"alex": "Alex (serveur)"}, "start_node": "n1", "nodes": {"n1": {"speaker": "alex", "text": "How is everything?", "text_fr": "Tout se passe bien ?", "choices": [{"text": "Actually, my food is cold.", "next": "n2"}, {"text": "Sorry to bother you, but this isn''t warm at all.", "next": "n2"}]}, "n2": {"speaker": "alex", "text": "I''m so sorry! Should I reheat it or bring a new one?", "text_fr": "Je suis vraiment désolé ! Je le réchauffe ou j''en refais un ?", "choices": [{"text": "A new one would be great, thank you.", "next": "end_new"}, {"text": "Reheating is fine, thank you.", "next": "end_reheat"}]}, "end_new": {"speaker": "alex", "text": "Of course, I''ll bring a fresh plate right away.", "text_fr": "Bien sûr, j''apporte une assiette fraîche tout de suite.", "end": true, "ending_label": "Plat refait 🍽️"}, "end_reheat": {"speaker": "alex", "text": "I''ll have it back to you in two minutes.", "text_fr": "Je vous le ramène dans deux minutes.", "end": true, "ending_label": "Plat réchauffé ✅"}}}'::jsonb, is_playable = true
where title = 'Se plaindre poliment d''un plat'
  and theme_id = (select id from scenario_themes where position = 1 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"ben": "Ben (serveur complice)"}, "start_node": "n1", "nodes": {"n1": {"speaker": "ben", "text": "So, you want us to bring the cake out after the main course?", "text_fr": "Donc, vous voulez qu''on apporte le gâteau après le plat principal ?", "choices": [{"text": "Yes, and could the staff sing happy birthday?", "next": "n2"}, {"text": "Yes, but keep it low-key, just the cake.", "next": "n2b"}]}, "n2": {"speaker": "ben", "text": "Of course! We''ll make it special.", "text_fr": "Bien sûr ! On va rendre ça spécial.", "choices": [{"text": "Perfect, thank you so much!", "next": "end_sing"}]}, "n2b": {"speaker": "ben", "text": "Got it, just a candle and the cake, no fuss.", "text_fr": "Compris, juste une bougie et le gâteau, sans chichi.", "choices": [{"text": "Exactly, thank you.", "next": "end_quiet"}]}, "end_sing": {"speaker": "ben", "text": "The group is going to love it!", "text_fr": "Le groupe va adorer !", "end": true, "ending_label": "Surprise réussie 🎉"}, "end_quiet": {"speaker": "ben", "text": "Simple and sweet, just as you wanted.", "text_fr": "Simple et discret, comme vous le vouliez.", "end": true, "ending_label": "Surprise discrète 🎂"}}}'::jsonb, is_playable = true
where title = 'Un dîner d''anniversaire surprise'
  and theme_id = (select id from scenario_themes where position = 1 and language_id = (select id from languages where code = 'en'));
