-- ============================================
-- LUMA — Scénarios jouables : Thématique 11 (Festival) — complète (11.1 déjà fait)
-- ============================================

update scenarios set content = '{"characters": {"seller": "un vendeur de billets"}, "start_node": "n1", "nodes": {"n1": {"speaker": "seller", "text": "Sorry, we''re officially sold out, but I might have one extra ticket.", "text_fr": "Désolé, c''est officiellement complet, mais j''ai peut-être un billet en plus.", "choices": [{"text": "I''d love that, how much?", "next": "n2"}, {"text": "Is there a waiting list I could join?", "next": "n2b"}]}, "n2": {"speaker": "seller", "text": "Face value, $45 — I just want to see it go to someone who''ll enjoy it.", "text_fr": "Prix normal, 45$ — je veux juste qu''il aille à quelqu''un qui va en profiter.", "choices": [{"text": "Deal, thank you so much!", "next": "end_bought"}]}, "n2b": {"speaker": "seller", "text": "There is, but honestly, I can just give you mine now.", "text_fr": "Il y en a une, mais honnêtement, je peux vous donner le mien maintenant.", "choices": [{"text": "That''s incredibly kind, thank you!", "next": "end_bought"}]}, "end_bought": {"speaker": "seller", "text": "Enjoy the show!", "text_fr": "Profite bien du spectacle !", "end": true, "ending_label": "Billet obtenu à temps 🎫"}}}'::jsonb, is_playable = true
where title = 'Acheter un billet à la dernière minute'
  and theme_id = (select id from scenario_themes where position = 11 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"artist": "l''artiste"}, "start_node": "n1", "nodes": {"n1": {"speaker": "artist", "text": "Thanks for coming to my set! What did you think?", "text_fr": "Merci d''être venu à mon concert ! Qu''en as-tu pensé ?", "choices": [{"text": "It was incredible, especially the third song!", "next": "n2"}, {"text": "I loved the energy, how long have you been performing?", "next": "n2b"}]}, "n2": {"speaker": "artist", "text": "That one''s actually about overcoming a tough year — glad it resonated.", "text_fr": "Celle-là parle en fait de surmonter une année difficile — content que ça t''ait touché.", "choices": [{"text": "It really did, thank you for sharing that.", "next": "end_connect"}]}, "n2b": {"speaker": "artist", "text": "About eight years now, this festival scene is still my favorite.", "text_fr": "Environ huit ans maintenant, la scène festival reste ma préférée.", "choices": [{"text": "It shows, you have a great stage presence.", "next": "end_connect"}]}, "end_connect": {"speaker": "artist", "text": "That really means a lot, thank you for the kind words.", "text_fr": "Ça compte beaucoup, merci pour ces mots gentils.", "end": true, "ending_label": "Belle rencontre artistique 🎤"}}}'::jsonb, is_playable = true
where title = 'Discuter avec un artiste local'
  and theme_id = (select id from scenario_themes where position = 11 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"friend": "ton ami de festival"}, "start_node": "n1", "nodes": {"n1": {"speaker": "friend", "text": "There are three bands we like playing at the same time. What''s the plan?", "text_fr": "Il y a trois groupes qu''on aime qui jouent en même temps. On fait comment ?", "choices": [{"text": "Let''s catch half of each, moving between stages.", "next": "n2"}, {"text": "Let''s just commit fully to the headliner we love most.", "next": "n2b"}]}, "n2": {"speaker": "friend", "text": "Good plan, let''s start with the main stage.", "text_fr": "Bon plan, commençons par la scène principale.", "choices": [{"text": "Let''s go!", "next": "n3"}]}, "n2b": {"speaker": "friend", "text": "Smart, front row for the whole set then.", "text_fr": "Malin, premier rang pour tout le set alors.", "choices": [{"text": "Exactly, let''s get a good spot.", "next": "n3"}]}, "n3": {"speaker": "friend", "text": "This turned out to be a great day of music!", "text_fr": "Cette journée de musique était vraiment géniale !", "choices": [{"text": "Best festival day yet.", "next": "end_great_day"}]}, "end_great_day": {"speaker": "friend", "text": "Can''t wait to do this again next year.", "text_fr": "J''ai hâte de recommencer l''année prochaine.", "end": true, "ending_label": "Journée parfaitement organisée 🎶"}}}'::jsonb, is_playable = true
where title = 'Organiser sa journée entre plusieurs concerts'
  and theme_id = (select id from scenario_themes where position = 11 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"staff": "le personnel du festival"}, "start_node": "n1", "nodes": {"n1": {"speaker": "staff", "text": "Lost and found, how can I help?", "text_fr": "Objets trouvés, comment puis-je vous aider ?", "choices": [{"text": "I lost my phone somewhere near the main stage.", "next": "n2"}, {"text": "I lost my friend, not an object, but still!", "next": "n2b"}]}, "n2": {"speaker": "staff", "text": "Let me check our collection... yes, someone turned in a phone matching that!", "text_fr": "Je vérifie notre collection... oui, quelqu''un a rendu un téléphone qui correspond !", "choices": [{"text": "That''s amazing, thank you so much!", "next": "end_found"}]}, "n2b": {"speaker": "staff", "text": "No worries, we can page them over the announcement system.", "text_fr": "Pas de souci, on peut les appeler via le système d''annonces.", "choices": [{"text": "Perfect, thank you for the help.", "next": "end_reunited"}]}, "end_found": {"speaker": "staff", "text": "Glad we could reunite you with it!", "text_fr": "Content d''avoir pu vous le rendre !", "end": true, "ending_label": "Objet retrouvé 📱"}, "end_reunited": {"speaker": "staff", "text": "Hope you find your friend quickly!", "text_fr": "J''espère que tu retrouveras vite ton ami !", "end": true, "ending_label": "Solution trouvée 📢"}}}'::jsonb, is_playable = true
where title = 'Gérer un objet perdu pendant l''événement'
  and theme_id = (select id from scenario_themes where position = 11 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"stranger": "une personne rencontrée sur place"}, "start_node": "n1", "nodes": {"n1": {"speaker": "stranger", "text": "Great taste in bands, I saw you singing along to every song!", "text_fr": "Super goût musical, je t''ai vu chanter chaque chanson !", "choices": [{"text": "Ha, guilty! Are you a fan of this band too?", "next": "n2"}]}, "n2": {"speaker": "stranger", "text": "Huge fan, been following them for years. I''m Sam, by the way.", "text_fr": "Grand fan, je les suis depuis des années. Je m''appelle Sam, au fait.", "choices": [{"text": "Nice to meet you, Sam! Want to grab a drink between sets?", "next": "end_friend"}]}, "end_friend": {"speaker": "stranger", "text": "I''d love that, let''s go!", "text_fr": "Avec plaisir, allons-y !", "end": true, "ending_label": "Nouvel ami rencontré 😊"}}}'::jsonb, is_playable = true
where title = 'Une rencontre qui devient amicale'
  and theme_id = (select id from scenario_themes where position = 11 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"friend": "ton ami de festival"}, "start_node": "n1", "nodes": {"n1": {"speaker": "friend", "text": "Day one is done! But I heard tomorrow might have rain.", "text_fr": "Le premier jour est fini ! Mais j''ai entendu qu''il pourrait pleuvoir demain.", "choices": [{"text": "Let''s plan for it, ponchos and boots tomorrow.", "next": "n2"}]}, "n2": {"speaker": "friend", "text": "Good call — it did rain, but we managed! Day three now, any regrets?", "text_fr": "Bien vu — il a plu, mais on a géré ! Jour trois maintenant, des regrets ?", "choices": [{"text": "None, this has been an amazing experience overall.", "next": "n3"}]}, "n3": {"speaker": "friend", "text": "Same here. Last big show tonight, let''s make it count!", "text_fr": "Pareil pour moi. Dernier grand concert ce soir, profitons-en à fond !", "choices": [{"text": "Let''s go make some final memories.", "next": "end_finale"}]}, "end_finale": {"speaker": "friend", "text": "Best three days ever, thanks for being here with me.", "text_fr": "Meilleurs trois jours de ma vie, merci d''avoir été là avec moi.", "end": true, "ending_label": "Festival mémorable achevé 🎉"}}}'::jsonb, is_playable = true
where title = 'Un festival sur plusieurs jours avec des rebondissements'
  and theme_id = (select id from scenario_themes where position = 11 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"coordinator": "le coordinateur bénévole"}, "start_node": "n1", "nodes": {"n1": {"speaker": "coordinator", "text": "Welcome aboard! You''ll be helping manage crowd flow near the main gate.", "text_fr": "Bienvenue à bord ! Tu vas aider à gérer le flux de foule près de l''entrée principale.", "choices": [{"text": "Sounds great, what should I do if it gets too crowded?", "next": "n2"}]}, "n2": {"speaker": "coordinator", "text": "Radio me immediately, we have a backup plan ready.", "text_fr": "Contacte-moi immédiatement par radio, on a un plan de secours prêt.", "choices": [{"text": "Got it, I''ll stay alert.", "next": "n3"}]}, "n3": {"speaker": "coordinator", "text": "(later, a real crowd surge happens) Great job managing that calmly!", "text_fr": "(plus tard, une vraie ruée de foule se produit) Bravo d''avoir géré ça calmement !", "choices": [{"text": "Thank you, the training really helped.", "next": "end_success"}]}, "end_success": {"speaker": "coordinator", "text": "You''ve got real leadership potential, thanks for stepping up.", "text_fr": "Tu as un vrai potentiel de leader, merci de t''être investi.", "end": true, "ending_label": "Bénévolat exemplaire 🌟"}}}'::jsonb, is_playable = true
where title = 'Bénévolat sur l''événement avec responsabilités'
  and theme_id = (select id from scenario_themes where position = 11 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"stranger": "une personne à proximité"}, "start_node": "n1", "nodes": {"n1": {"speaker": "stranger", "text": "Help, my friend just fainted from the heat!", "text_fr": "À l''aide, mon ami vient de s''évanouir à cause de la chaleur !", "choices": [{"text": "Let''s get security and some water immediately.", "next": "n2"}]}, "n2": {"speaker": "stranger", "text": "Thank you, I''m panicking a bit.", "text_fr": "Merci, je panique un peu.", "choices": [{"text": "Stay calm, help is on the way, let''s get him some shade.", "next": "n3"}]}, "n3": {"speaker": "stranger", "text": "(medics arrive) He''s going to be okay, just needed rest and fluids.", "text_fr": "(les secours arrivent) Il va bien, il avait juste besoin de repos et de liquides.", "choices": [{"text": "I''m so relieved, glad we acted fast.", "next": "end_helped"}]}, "end_helped": {"speaker": "stranger", "text": "Thank you for staying calm and helping us.", "text_fr": "Merci d''être resté calme et de nous avoir aidés.", "end": true, "ending_label": "Situation d''urgence bien gérée 🙏"}}}'::jsonb, is_playable = true
where title = 'Un incident à gérer en tant que spectateur impliqué'
  and theme_id = (select id from scenario_themes where position = 11 and language_id = (select id from languages where code = 'en'));
