-- ============================================
-- LUMA — Scénarios jouables : Thématique 4 (Voyage) — complète
-- ============================================

update scenarios set content = '{"characters": {"agent": "l''agent d''enregistrement"}, "start_node": "n1", "nodes": {"n1": {"speaker": "agent", "text": "Good morning, passport and ticket please. How many bags?", "text_fr": "Bonjour, passeport et billet s''il vous plaît. Combien de bagages ?", "choices": [{"text": "Just one suitcase, thank you.", "next": "end_one"}, {"text": "Two bags, is that extra?", "next": "n2"}]}, "n2": {"speaker": "agent", "text": "The second bag will be an extra $30.", "text_fr": "Le deuxième bagage coûtera 30$ de plus.", "choices": [{"text": "That''s fine, I''ll pay.", "next": "end_paid"}]}, "end_one": {"speaker": "agent", "text": "Here''s your boarding pass, gate 12.", "text_fr": "Voici votre carte d''embarquement, porte 12.", "end": true, "ending_label": "Enregistrement simple ✅"}, "end_paid": {"speaker": "agent", "text": "All set, here''s your boarding pass.", "text_fr": "C''est réglé, voici votre carte d''embarquement.", "end": true, "ending_label": "Bagages enregistrés 🧳"}}}'::jsonb, is_playable = true
where title = 'Enregistrement et bagages'
  and theme_id = (select id from scenario_themes where position = 4 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"officer": "l''agent des douanes"}, "start_node": "n1", "nodes": {"n1": {"speaker": "officer", "text": "What''s the purpose of your visit?", "text_fr": "Quel est le but de votre visite ?", "choices": [{"text": "Tourism, I''m here for two weeks.", "next": "end_tourism"}, {"text": "Business, I have a meeting tomorrow.", "next": "n2"}]}, "n2": {"speaker": "officer", "text": "Do you have any documents for that meeting?", "text_fr": "Avez-vous des documents pour cette réunion ?", "choices": [{"text": "Yes, right here.", "next": "end_business"}]}, "end_tourism": {"speaker": "officer", "text": "Enjoy your stay!", "text_fr": "Bon séjour !", "end": true, "ending_label": "Passage douane facile ✅"}, "end_business": {"speaker": "officer", "text": "Perfect, welcome.", "text_fr": "Parfait, bienvenue.", "end": true, "ending_label": "Passage douane confirmé ✅"}}}'::jsonb, is_playable = true
where title = 'Une question à la douane'
  and theme_id = (select id from scenario_themes where position = 4 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"agent": "l''agent des bagages"}, "start_node": "n1", "nodes": {"n1": {"speaker": "agent", "text": "I''m sorry, your bag didn''t arrive. Can you describe it?", "text_fr": "Désolé, votre bagage n''est pas arrivé. Pouvez-vous le décrire ?", "choices": [{"text": "It''s a large black suitcase with a red ribbon on the handle.", "next": "n2"}, {"text": "I have the baggage tag number right here.", "next": "n2b"}]}, "n2": {"speaker": "agent", "text": "Thank you, I''ll file a report and we''ll deliver it to your hotel.", "text_fr": "Merci, je fais un rapport et on vous le livrera à l''hôtel.", "choices": [{"text": "Thank you for your help.", "next": "end_ok"}]}, "n2b": {"speaker": "agent", "text": "Perfect, that speeds things up a lot.", "text_fr": "Parfait, ça accélère grandement les choses.", "choices": [{"text": "Great, I hope it arrives soon.", "next": "end_ok"}]}, "end_ok": {"speaker": "agent", "text": "It should arrive within 24 hours.", "text_fr": "Il devrait arriver sous 24 heures.", "end": true, "ending_label": "Réclamation enregistrée ✅"}}}'::jsonb, is_playable = true
where title = 'Retrouver une valise perdue'
  and theme_id = (select id from scenario_themes where position = 4 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"agent": "l''agent au comptoir"}, "start_node": "n1", "nodes": {"n1": {"speaker": "agent", "text": "I''m afraid your flight has been cancelled due to weather.", "text_fr": "Je crains que votre vol soit annulé à cause de la météo.", "choices": [{"text": "What are my options for rebooking?", "next": "n2"}, {"text": "Can I get a refund instead?", "next": "n2b"}]}, "n2": {"speaker": "agent", "text": "We have a flight tomorrow morning, or one this evening with a connection.", "text_fr": "On a un vol demain matin, ou un ce soir avec correspondance.", "choices": [{"text": "I''ll take tomorrow morning, and could I get a hotel voucher?", "next": "n3"}, {"text": "The evening connection works for me.", "next": "end_evening"}]}, "n2b": {"speaker": "agent", "text": "Of course, I can process a full refund.", "text_fr": "Bien sûr, je peux traiter un remboursement complet.", "choices": [{"text": "Thank you, please proceed.", "next": "end_refund"}]}, "n3": {"speaker": "agent", "text": "Yes, since it''s a weather delay we can provide that.", "text_fr": "Oui, comme c''est un retard météo on peut vous en fournir un.", "choices": [{"text": "Perfect, thank you so much.", "next": "end_hotel"}]}, "end_evening": {"speaker": "agent", "text": "Great, you''re rebooked for this evening.", "text_fr": "Parfait, vous êtes reprogrammé pour ce soir.", "end": true, "ending_label": "Vol reprogrammé ✅"}, "end_refund": {"speaker": "agent", "text": "Done, you''ll see the refund in 5-7 days.", "text_fr": "C''est fait, vous verrez le remboursement sous 5-7 jours.", "end": true, "ending_label": "Remboursement obtenu 💰"}, "end_hotel": {"speaker": "agent", "text": "Here''s your voucher and new boarding pass.", "text_fr": "Voici votre bon et votre nouvelle carte d''embarquement.", "end": true, "ending_label": "Situation bien gérée 🏨"}}}'::jsonb, is_playable = true
where title = 'Un vol annulé à gérer'
  and theme_id = (select id from scenario_themes where position = 4 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"attendant": "l''hôtesse", "neighbor": "le voisin de siège"}, "start_node": "n1", "nodes": {"n1": {"speaker": "attendant", "text": "Is everything okay with your seat?", "text_fr": "Tout va bien avec votre siège ?", "choices": [{"text": "Actually, could I move to a window seat if possible?", "next": "n2"}, {"text": "It''s fine, thank you.", "next": "end_stay"}]}, "n2": {"speaker": "attendant", "text": "Let me check... yes, there''s one available in row 14.", "text_fr": "Je vérifie... oui, il y en a un disponible en rangée 14.", "choices": [{"text": "Perfect, thank you!", "next": "n3"}]}, "n3": {"speaker": "neighbor", "text": "Oh, are you moving next to me? I''m heading to Chicago too!", "text_fr": "Oh, vous venez vous asseoir à côté de moi ? Je vais aussi à Chicago !", "choices": [{"text": "Really? What brings you there?", "next": "end_chat"}]}, "end_stay": {"speaker": "attendant", "text": "Great, let me know if you need anything.", "text_fr": "Parfait, dites-moi si vous avez besoin de quoi que ce soit.", "end": true, "ending_label": "Vol tranquille ✈️"}, "end_chat": {"speaker": "neighbor", "text": "Visiting family — this is going to be a nice flight!", "text_fr": "Je rends visite à ma famille — ce vol va être agréable !", "end": true, "ending_label": "Belle rencontre en vol 😊"}}}'::jsonb, is_playable = true
where title = 'Demander un changement de siège et discuter avec son voisin'
  and theme_id = (select id from scenario_themes where position = 4 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"staff": "un agent de l''aéroport"}, "start_node": "n1", "nodes": {"n1": {"speaker": "staff", "text": "Can I help you find something?", "text_fr": "Je peux vous aider à trouver quelque chose ?", "choices": [{"text": "Yes, where''s gate B12?", "next": "n2"}, {"text": "I''m looking for the connecting flights area.", "next": "n2b"}]}, "n2": {"speaker": "staff", "text": "Take the escalator up, then follow signs to Terminal B.", "text_fr": "Prenez l''escalator vers le haut, puis suivez les panneaux vers le Terminal B.", "choices": [{"text": "Thank you very much!", "next": "end_found"}]}, "n2b": {"speaker": "staff", "text": "That''s on the third floor, near the food court.", "text_fr": "C''est au troisième étage, près de l''espace restauration.", "choices": [{"text": "Perfect, thanks for your help.", "next": "end_found"}]}, "end_found": {"speaker": "staff", "text": "You''re welcome, safe travels!", "text_fr": "De rien, bon voyage !", "end": true, "ending_label": "Chemin trouvé 🗺️"}}}'::jsonb, is_playable = true
where title = 'S''orienter dans un aéroport inconnu'
  and theme_id = (select id from scenario_themes where position = 4 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"agent": "l''agent de la compagnie"}, "start_node": "n1", "nodes": {"n1": {"speaker": "agent", "text": "I see you missed your connection. Let''s find a solution.", "text_fr": "Je vois que vous avez raté votre correspondance. Trouvons une solution.", "choices": [{"text": "What''s the next available flight?", "next": "n2"}]}, "n2": {"speaker": "agent", "text": "There''s one in 3 hours, but it''s fully booked. There''s also one tomorrow with a guaranteed seat.", "text_fr": "Il y en a un dans 3 heures, mais complet. Il y en a aussi un demain avec une place garantie.", "choices": [{"text": "Can you put me on standby for the one in 3 hours?", "next": "n3"}, {"text": "I''ll take the guaranteed seat tomorrow.", "next": "n3b"}]}, "n3": {"speaker": "agent", "text": "You''re #2 on the standby list — decent chance!", "text_fr": "Vous êtes 2e sur liste d''attente — bonne chance !", "choices": [{"text": "Fingers crossed, thank you.", "next": "n4"}]}, "n3b": {"speaker": "agent", "text": "Good call, I''ll also arrange a hotel for tonight.", "text_fr": "Bon choix, je vous arrange aussi un hôtel pour ce soir.", "choices": [{"text": "That''s very helpful, thank you.", "next": "end_hotel"}]}, "n4": {"speaker": "agent", "text": "Good news — a seat opened up, you''re confirmed!", "text_fr": "Bonne nouvelle — une place s''est libérée, vous êtes confirmé !", "choices": [{"text": "That''s fantastic, thank you so much!", "next": "end_standby"}]}, "end_hotel": {"speaker": "agent", "text": "You''re all set for tomorrow''s flight.", "text_fr": "Tout est réglé pour le vol de demain.", "end": true, "ending_label": "Solution de secours trouvée 🏨"}, "end_standby": {"speaker": "agent", "text": "Great, enjoy your flight!", "text_fr": "Parfait, bon vol !", "end": true, "ending_label": "Standby réussi 🎉"}}}'::jsonb, is_playable = true
where title = 'Une correspondance ratée avec plusieurs obstacles'
  and theme_id = (select id from scenario_themes where position = 4 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"staff": "le personnel de l''aéroport"}, "start_node": "n1", "nodes": {"n1": {"speaker": "staff", "text": "First, your gate has changed to C22.", "text_fr": "D''abord, votre porte a changé pour la C22.", "choices": [{"text": "Thanks for the heads up, how far is that?", "next": "n2"}]}, "n2": {"speaker": "staff", "text": "About a 10-minute walk. Also, security lines are quite long today.", "text_fr": "Environ 10 minutes à pied. Aussi, les files de sécurité sont longues aujourd''hui.", "choices": [{"text": "I should hurry then, thank you.", "next": "n3"}]}, "n3": {"speaker": "staff", "text": "One more thing — your flight is delayed by 45 minutes.", "text_fr": "Une dernière chose — votre vol a 45 minutes de retard.", "choices": [{"text": "Well, at least I won''t miss it now!", "next": "end_positive"}, {"text": "This trip has been one thing after another.", "next": "end_tired"}]}, "end_positive": {"speaker": "staff", "text": "That''s the spirit! Safe travels.", "text_fr": "Voilà le bon esprit ! Bon voyage.", "end": true, "ending_label": "Imprévus surmontés avec le sourire 😊"}, "end_tired": {"speaker": "staff", "text": "I completely understand, travel days can be exhausting.", "text_fr": "Je comprends totalement, les jours de voyage peuvent être épuisants.", "end": true, "ending_label": "Journée mouvementée gérée 😮‍💨"}}}'::jsonb, is_playable = true
where title = 'Un voyage avec imprévus en cascade'
  and theme_id = (select id from scenario_themes where position = 4 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"passenger": "une passagère âgée"}, "start_node": "n1", "nodes": {"n1": {"speaker": "passenger", "text": "Excuse me, I can''t find my gate and my phone died. Could you help?", "text_fr": "Excusez-moi, je ne trouve pas ma porte et mon téléphone est mort. Pouvez-vous m''aider ?", "choices": [{"text": "Of course, let me look at your ticket.", "next": "n2"}]}, "n2": {"speaker": "passenger", "text": "Thank you, here it is — gate D8.", "text_fr": "Merci, la voici — porte D8.", "choices": [{"text": "That''s actually on my way, I''ll walk you there.", "next": "end_walk"}, {"text": "It''s just down this hall, follow the signs.", "next": "end_directions"}]}, "end_walk": {"speaker": "passenger", "text": "You''re so kind, thank you for walking with me!", "text_fr": "Vous êtes si gentil(le), merci de m''accompagner !", "end": true, "ending_label": "Geste chaleureux 💛"}, "end_directions": {"speaker": "passenger", "text": "Thank you so much for your help!", "text_fr": "Merci beaucoup pour votre aide !", "end": true, "ending_label": "Aide appréciée 🙏"}}}'::jsonb, is_playable = true
where title = 'Aider un autre passager en difficulté'
  and theme_id = (select id from scenario_themes where position = 4 and language_id = (select id from languages where code = 'en'));
