-- ============================================
-- LUMA — Vocabulaire par thème : Niveau 4 et Niveau 5 pour les 10 thèmes
-- 400 nouveaux mots, 120 nouveaux exercices.
-- ============================================

with t as (select id from vocab_themes where slug = 'cuisine')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 4, 'Niveau 4', '[{"en": "mince", "fr": "hacher finement", "level": "B1"}, {"en": "dice", "fr": "couper en dés", "level": "B1"}, {"en": "skewer", "fr": "brochette", "level": "B1"}, {"en": "marinade", "fr": "marinade", "level": "B1"}, {"en": "broth", "fr": "bouillon", "level": "A2"}, {"en": "rind", "fr": "écorce/peau (fruit)", "level": "B1"}, {"en": "peel (noun)", "fr": "épluchure", "level": "A2"}, {"en": "core (fruit)", "fr": "trognon", "level": "A2"}, {"en": "pit (fruit)", "fr": "noyau", "level": "A2"}, {"en": "husk", "fr": "enveloppe (maïs)", "level": "B2"}, {"en": "rinse", "fr": "rincer", "level": "A2"}, {"en": "drain (verb)", "fr": "égoutter", "level": "B1"}, {"en": "strain", "fr": "filtrer/passer", "level": "B1"}, {"en": "sift", "fr": "tamiser", "level": "B1"}, {"en": "whip", "fr": "fouetter", "level": "B1"}, {"en": "sauté", "fr": "faire sauter", "level": "B1"}, {"en": "poach", "fr": "pocher", "level": "B2"}, {"en": "blanch", "fr": "blanchir", "level": "B2"}, {"en": "sear", "fr": "saisir (viande)", "level": "B2"}, {"en": "baste", "fr": "arroser (cuisson)", "level": "B2"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'cuisine') and position = 4)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'cuisine'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"hacher finement\" = ?", "options": ["mince", "skewer", "whip", "dice"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"mince\"."}'),(2, 'qcm', '{"question": "\"marinade\" = ?", "options": ["strain", "rinse", "sift", "marinade"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"marinade\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "peel (noun)", "right": "épluchure"}, {"left": "core (fruit)", "right": "trognon"}, {"left": "pit (fruit)", "right": "noyau"}, {"left": "husk", "right": "enveloppe (maïs)"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "strain", "right": "filtrer/passer"}, {"left": "sift", "right": "tamiser"}, {"left": "whip", "right": "fouetter"}, {"left": "sauté", "right": "faire sauter"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"blanchir\" = ", "sentence_after": "", "correct_answers": ["blanch"], "feedback_correct": "Correct !", "feedback_incorrect": "\"blanchir\" se dit \"blanch\" en anglais."}'),(6, 'true_false', '{"statement": "\"baste\" veut dire \"arroser (cuisson)\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'cuisine')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 5, 'Niveau 5', '[{"en": "reduce (sauce)", "fr": "réduire (sauce)", "level": "B2"}, {"en": "deglaze", "fr": "déglacer", "level": "C1"}, {"en": "char", "fr": "carboniser légèrement", "level": "B2"}, {"en": "brine", "fr": "saumure", "level": "C1"}, {"en": "tenderize", "fr": "attendrir", "level": "B2"}, {"en": "glaze (verb)", "fr": "glacer", "level": "B2"}, {"en": "knead", "fr": "pétrir", "level": "B1"}, {"en": "proof (dough)", "fr": "laisser lever", "level": "B2"}, {"en": "fold (mixing)", "fr": "incorporer délicatement", "level": "B2"}, {"en": "emulsify", "fr": "émulsionner", "level": "C1"}, {"en": "clarify (butter)", "fr": "clarifier", "level": "C1"}, {"en": "temper (chocolate)", "fr": "tempérer", "level": "C1"}, {"en": "shuck", "fr": "décortiquer/écosser", "level": "B2"}, {"en": "truss", "fr": "brider (volaille)", "level": "C1"}, {"en": "flambé", "fr": "flamber", "level": "B2"}, {"en": "marbling", "fr": "persillage (viande)", "level": "C1"}, {"en": "gristle", "fr": "cartilage (viande)", "level": "C1"}, {"en": "rendered fat", "fr": "graisse fondue", "level": "C1"}, {"en": "confit", "fr": "confit", "level": "C1"}, {"en": "julienne", "fr": "coupe en julienne", "level": "B2"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'cuisine') and position = 5)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'cuisine'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"réduire (sauce)\" = ?", "options": ["brine", "tenderize", "julienne", "reduce (sauce)"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"reduce (sauce)\"."}'),(2, 'qcm', '{"question": "\"saumure\" = ?", "options": ["truss", "rendered fat", "gristle", "brine"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"brine\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "knead", "right": "pétrir"}, {"left": "proof (dough)", "right": "laisser lever"}, {"left": "fold (mixing)", "right": "incorporer délicatement"}, {"left": "emulsify", "right": "émulsionner"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "shuck", "right": "décortiquer/écosser"}, {"left": "truss", "right": "brider (volaille)"}, {"left": "flambé", "right": "flamber"}, {"left": "marbling", "right": "persillage (viande)"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"graisse fondue\" = ", "sentence_after": "", "correct_answers": ["rendered fat"], "feedback_correct": "Correct !", "feedback_incorrect": "\"graisse fondue\" se dit \"rendered fat\" en anglais."}'),(6, 'true_false', '{"statement": "\"julienne\" veut dire \"coupe en julienne\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'technologie')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 4, 'Niveau 4', '[{"en": "processor", "fr": "processeur", "level": "B1"}, {"en": "motherboard", "fr": "carte mère", "level": "B2"}, {"en": "graphics card", "fr": "carte graphique", "level": "B1"}, {"en": "RAM", "fr": "mémoire vive", "level": "B1"}, {"en": "cache", "fr": "cache (mémoire)", "level": "B2"}, {"en": "cookie (web)", "fr": "cookie (internet)", "level": "A2"}, {"en": "phishing", "fr": "hameçonnage", "level": "B2"}, {"en": "spam", "fr": "spam", "level": "A2"}, {"en": "VPN", "fr": "VPN", "level": "B1"}, {"en": "two-factor authentication", "fr": "authentification à deux facteurs", "level": "B2"}, {"en": "API", "fr": "interface de programmation", "level": "C1"}, {"en": "chatbot", "fr": "agent conversationnel", "level": "B1"}, {"en": "machine learning", "fr": "apprentissage automatique", "level": "B2"}, {"en": "blockchain", "fr": "chaîne de blocs", "level": "B2"}, {"en": "cryptocurrency", "fr": "cryptomonnaie", "level": "B1"}, {"en": "augmented reality", "fr": "réalité augmentée", "level": "B1"}, {"en": "biometric", "fr": "biométrique", "level": "B2"}, {"en": "thumbnail", "fr": "miniature (image)", "level": "A2"}, {"en": "livestream", "fr": "diffusion en direct", "level": "A2"}, {"en": "influencer", "fr": "influenceur", "level": "A2"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'technologie') and position = 4)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'technologie'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"processeur\" = ?", "options": ["processor", "thumbnail", "graphics card", "API"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"processor\"."}'),(2, 'qcm', '{"question": "\"mémoire vive\" = ?", "options": ["machine learning", "RAM", "cache", "cookie (web)"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"RAM\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "phishing", "right": "hameçonnage"}, {"left": "spam", "right": "spam"}, {"left": "VPN", "right": "VPN"}, {"left": "two-factor authentication", "right": "authentification à deux facteurs"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "machine learning", "right": "apprentissage automatique"}, {"left": "blockchain", "right": "chaîne de blocs"}, {"left": "cryptocurrency", "right": "cryptomonnaie"}, {"left": "augmented reality", "right": "réalité augmentée"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"miniature (image)\" = ", "sentence_after": "", "correct_answers": ["thumbnail"], "feedback_correct": "Correct !", "feedback_incorrect": "\"miniature (image)\" se dit \"thumbnail\" en anglais."}'),(6, 'true_false', '{"statement": "\"influencer\" veut dire \"influenceur\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'technologie')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 5, 'Niveau 5', '[{"en": "throughput", "fr": "débit de traitement", "level": "C1"}, {"en": "middleware", "fr": "intergiciel", "level": "C1"}, {"en": "codebase", "fr": "base de code", "level": "C1"}, {"en": "deprecated", "fr": "obsolète (technique)", "level": "C1"}, {"en": "refactor", "fr": "refactoriser", "level": "C1"}, {"en": "edge case", "fr": "cas limite", "level": "C1"}, {"en": "race condition", "fr": "situation de compétition (code)", "level": "C1"}, {"en": "dependency", "fr": "dépendance (logicielle)", "level": "C1"}, {"en": "sandboxing", "fr": "isolation (sécurité)", "level": "C1"}, {"en": "rollback", "fr": "retour en arrière (version)", "level": "C1"}, {"en": "payload", "fr": "charge utile (données)", "level": "C1"}, {"en": "throttling", "fr": "limitation de débit", "level": "C1"}, {"en": "scalability", "fr": "évolutivité", "level": "C1"}, {"en": "failover", "fr": "basculement de secours", "level": "C1"}, {"en": "uptime", "fr": "temps de disponibilité", "level": "B2"}, {"en": "provisioning", "fr": "provisionnement", "level": "C1"}, {"en": "containerization", "fr": "conteneurisation", "level": "C1"}, {"en": "microservice", "fr": "microservice", "level": "C1"}, {"en": "headless (tech)", "fr": "sans interface", "level": "C1"}, {"en": "webhook", "fr": "webhook", "level": "C1"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'technologie') and position = 5)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'technologie'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"débit de traitement\" = ?", "options": ["dependency", "edge case", "failover", "throughput"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"throughput\"."}'),(2, 'qcm', '{"question": "\"obsolète (technique)\" = ?", "options": ["scalability", "deprecated", "failover", "edge case"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"deprecated\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "race condition", "right": "situation de compétition (code)"}, {"left": "dependency", "right": "dépendance (logicielle)"}, {"left": "sandboxing", "right": "isolation (sécurité)"}, {"left": "rollback", "right": "retour en arrière (version)"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "scalability", "right": "évolutivité"}, {"left": "failover", "right": "basculement de secours"}, {"left": "uptime", "right": "temps de disponibilité"}, {"left": "provisioning", "right": "provisionnement"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"microservice\" = ", "sentence_after": "", "correct_answers": ["microservice"], "feedback_correct": "Correct !", "feedback_incorrect": "\"microservice\" se dit \"microservice\" en anglais."}'),(6, 'true_false', '{"statement": "\"webhook\" veut dire \"webhook\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'sport')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 4, 'Niveau 4', '[{"en": "lineup", "fr": "composition d''équipe", "level": "B1"}, {"en": "substitution", "fr": "remplacement (joueur)", "level": "B1"}, {"en": "possession", "fr": "possession (ballon)", "level": "B1"}, {"en": "tackle", "fr": "tacle", "level": "B1"}, {"en": "dribble", "fr": "dribbler", "level": "A2"}, {"en": "free throw", "fr": "lancer franc", "level": "B1"}, {"en": "overtime rule", "fr": "règle des prolongations", "level": "B1"}, {"en": "home advantage", "fr": "avantage du terrain", "level": "B2"}, {"en": "scouting", "fr": "recrutement (repérage)", "level": "B2"}, {"en": "draft (sport)", "fr": "draft (sport)", "level": "B2"}, {"en": "contract (sport)", "fr": "contrat (sportif)", "level": "B1"}, {"en": "transfer (sport)", "fr": "transfert (sportif)", "level": "B1"}, {"en": "relegation", "fr": "relégation", "level": "C1"}, {"en": "promotion (league)", "fr": "montée (championnat)", "level": "C1"}, {"en": "standings", "fr": "classement", "level": "B1"}, {"en": "tiebreaker", "fr": "match/manche décisif", "level": "B2"}, {"en": "forfeit", "fr": "forfait (abandon)", "level": "B2"}, {"en": "doping", "fr": "dopage", "level": "B1"}, {"en": "anti-doping", "fr": "antidopage", "level": "B1"}, {"en": "suspension (sport)", "fr": "suspension (sportive)", "level": "B1"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'sport') and position = 4)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'sport'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"composition d''équipe\" = ?", "options": ["possession", "suspension (sport)", "lineup", "draft (sport)"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"lineup\"."}'),(2, 'qcm', '{"question": "\"tacle\" = ?", "options": ["tackle", "overtime rule", "contract (sport)", "lineup"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"tackle\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "overtime rule", "right": "règle des prolongations"}, {"left": "home advantage", "right": "avantage du terrain"}, {"left": "scouting", "right": "recrutement (repérage)"}, {"left": "draft (sport)", "right": "draft (sport)"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "relegation", "right": "relégation"}, {"left": "promotion (league)", "right": "montée (championnat)"}, {"left": "standings", "right": "classement"}, {"left": "tiebreaker", "right": "match/manche décisif"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"dopage\" = ", "sentence_after": "", "correct_answers": ["doping"], "feedback_correct": "Correct !", "feedback_incorrect": "\"dopage\" se dit \"doping\" en anglais."}'),(6, 'true_false', '{"statement": "\"suspension (sport)\" veut dire \"suspension (sportive)\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'sport')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 5, 'Niveau 5', '[{"en": "periodization", "fr": "périodisation (entraînement)", "level": "C1"}, {"en": "plyometrics", "fr": "pliométrie", "level": "C1"}, {"en": "overtraining", "fr": "surentraînement", "level": "C1"}, {"en": "tapering", "fr": "affûtage (avant compétition)", "level": "C1"}, {"en": "VO2 max", "fr": "VO2 max", "level": "C1"}, {"en": "lactate threshold", "fr": "seuil lactique", "level": "C1"}, {"en": "proprioception", "fr": "proprioception", "level": "C1"}, {"en": "biomechanics", "fr": "biomécanique", "level": "C1"}, {"en": "sports psychology", "fr": "psychologie du sport", "level": "B2"}, {"en": "visualization (sport)", "fr": "visualisation mentale", "level": "B2"}, {"en": "game plan", "fr": "plan de jeu", "level": "B1"}, {"en": "choke (sport)", "fr": "craquer sous pression", "level": "B2"}, {"en": "in the zone", "fr": "dans sa bulle/en état de flow", "level": "C1"}, {"en": "underdog mentality", "fr": "mentalité d''outsider", "level": "C1"}, {"en": "sportsmanship", "fr": "esprit sportif", "level": "B1"}, {"en": "trash talk", "fr": "provocation verbale", "level": "C1"}, {"en": "home stretch", "fr": "dernière ligne droite", "level": "B2"}, {"en": "photo finish", "fr": "arrivée serrée", "level": "B2"}, {"en": "disqualification", "fr": "disqualification", "level": "B1"}, {"en": "scouting report", "fr": "rapport de recrutement", "level": "C1"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'sport') and position = 5)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'sport'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"périodisation (entraînement)\" = ?", "options": ["periodization", "choke (sport)", "in the zone", "trash talk"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"periodization\"."}'),(2, 'qcm', '{"question": "\"affûtage (avant compétition)\" = ?", "options": ["lactate threshold", "tapering", "overtraining", "scouting report"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"tapering\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "proprioception", "right": "proprioception"}, {"left": "biomechanics", "right": "biomécanique"}, {"left": "sports psychology", "right": "psychologie du sport"}, {"left": "visualization (sport)", "right": "visualisation mentale"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "in the zone", "right": "dans sa bulle/en état de flow"}, {"left": "underdog mentality", "right": "mentalité d''outsider"}, {"left": "sportsmanship", "right": "esprit sportif"}, {"left": "trash talk", "right": "provocation verbale"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"arrivée serrée\" = ", "sentence_after": "", "correct_answers": ["photo finish"], "feedback_correct": "Correct !", "feedback_incorrect": "\"arrivée serrée\" se dit \"photo finish\" en anglais."}'),(6, 'true_false', '{"statement": "\"scouting report\" veut dire \"rapport de recrutement\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'voyage')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 4, 'Niveau 4', '[{"en": "customs declaration", "fr": "déclaration de douane", "level": "B1"}, {"en": "duty-free", "fr": "hors taxes", "level": "B1"}, {"en": "baggage claim", "fr": "récupération des bagages", "level": "A2"}, {"en": "boarding pass", "fr": "carte d''embarquement", "level": "A2"}, {"en": "gate (airport)", "fr": "porte d''embarquement", "level": "A2"}, {"en": "turbulence", "fr": "turbulences", "level": "B1"}, {"en": "standby (flight)", "fr": "liste d''attente (vol)", "level": "B1"}, {"en": "overbook", "fr": "surbooker", "level": "B2"}, {"en": "stopover", "fr": "escale", "level": "B1"}, {"en": "cross-country", "fr": "à travers tout le pays", "level": "B1"}, {"en": "scenic route", "fr": "route panoramique", "level": "B1"}, {"en": "detour", "fr": "détour", "level": "A2"}, {"en": "checkpoint", "fr": "point de contrôle", "level": "B1"}, {"en": "permit (travel)", "fr": "permis/autorisation", "level": "B1"}, {"en": "embassy", "fr": "ambassade", "level": "A2"}, {"en": "consulate", "fr": "consulat", "level": "B1"}, {"en": "repatriation", "fr": "rapatriement", "level": "C1"}, {"en": "evacuation", "fr": "évacuation", "level": "B1"}, {"en": "insurance (travel)", "fr": "assurance voyage", "level": "A2"}, {"en": "itinerary change", "fr": "changement d''itinéraire", "level": "B1"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'voyage') and position = 4)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'voyage'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"déclaration de douane\" = ?", "options": ["stopover", "boarding pass", "duty-free", "customs declaration"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"customs declaration\"."}'),(2, 'qcm', '{"question": "\"carte d''embarquement\" = ?", "options": ["insurance (travel)", "boarding pass", "gate (airport)", "turbulence"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"boarding pass\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "standby (flight)", "right": "liste d''attente (vol)"}, {"left": "overbook", "right": "surbooker"}, {"left": "stopover", "right": "escale"}, {"left": "cross-country", "right": "à travers tout le pays"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "checkpoint", "right": "point de contrôle"}, {"left": "permit (travel)", "right": "permis/autorisation"}, {"left": "embassy", "right": "ambassade"}, {"left": "consulate", "right": "consulat"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"évacuation\" = ", "sentence_after": "", "correct_answers": ["evacuation"], "feedback_correct": "Correct !", "feedback_incorrect": "\"évacuation\" se dit \"evacuation\" en anglais."}'),(6, 'true_false', '{"statement": "\"itinerary change\" veut dire \"changement d''itinéraire\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'voyage')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 5, 'Niveau 5', '[{"en": "visa sponsor", "fr": "parrain de visa", "level": "C1"}, {"en": "digital nomad", "fr": "nomade numérique", "level": "B1"}, {"en": "bleisure travel", "fr": "voyage affaires-loisirs", "level": "C1"}, {"en": "slow travel", "fr": "voyage lent", "level": "B2"}, {"en": "staycation", "fr": "vacances chez soi", "level": "B1"}, {"en": "bucket list", "fr": "liste de rêves à réaliser", "level": "B1"}, {"en": "wanderlust", "fr": "soif de voyager", "level": "C1"}, {"en": "culture shock", "fr": "choc culturel", "level": "B1"}, {"en": "reverse culture shock", "fr": "choc culturel du retour", "level": "C1"}, {"en": "homesick", "fr": "mal du pays", "level": "A2"}, {"en": "travel fatigue", "fr": "fatigue du voyage", "level": "B2"}, {"en": "off-grid", "fr": "hors réseau/isolé", "level": "C1"}, {"en": "eco-lodge", "fr": "éco-logement", "level": "C1"}, {"en": "carbon offsetting (travel)", "fr": "compensation carbone (voyage)", "level": "C1"}, {"en": "overtourism", "fr": "surtourisme", "level": "C1"}, {"en": "gap year", "fr": "année sabbatique", "level": "B1"}, {"en": "volunteer tourism", "fr": "tourisme humanitaire", "level": "B2"}, {"en": "dark tourism", "fr": "tourisme noir/mémoriel", "level": "C1"}, {"en": "bragging rights (travel)", "fr": "fierté du voyageur", "level": "C1"}, {"en": "travel bug", "fr": "virus du voyage (passion)", "level": "B2"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'voyage') and position = 5)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'voyage'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"parrain de visa\" = ?", "options": ["visa sponsor", "slow travel", "volunteer tourism", "overtourism"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"visa sponsor\"."}'),(2, 'qcm', '{"question": "\"voyage lent\" = ?", "options": ["culture shock", "slow travel", "homesick", "dark tourism"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"slow travel\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "wanderlust", "right": "soif de voyager"}, {"left": "culture shock", "right": "choc culturel"}, {"left": "reverse culture shock", "right": "choc culturel du retour"}, {"left": "homesick", "right": "mal du pays"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "eco-lodge", "right": "éco-logement"}, {"left": "carbon offsetting (travel)", "right": "compensation carbone (voyage)"}, {"left": "overtourism", "right": "surtourisme"}, {"left": "gap year", "right": "année sabbatique"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"tourisme noir/mémoriel\" = ", "sentence_after": "", "correct_answers": ["dark tourism"], "feedback_correct": "Correct !", "feedback_incorrect": "\"tourisme noir/mémoriel\" se dit \"dark tourism\" en anglais."}'),(6, 'true_false', '{"statement": "\"travel bug\" veut dire \"virus du voyage (passion)\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'nature')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 4, 'Niveau 4', '[{"en": "photosynthesis", "fr": "photosynthèse", "level": "B1"}, {"en": "pollination", "fr": "pollinisation", "level": "B1"}, {"en": "decompose", "fr": "se décomposer", "level": "B1"}, {"en": "nutrient cycle", "fr": "cycle des nutriments", "level": "B2"}, {"en": "topsoil", "fr": "couche arable", "level": "B2"}, {"en": "groundwater", "fr": "eau souterraine", "level": "B1"}, {"en": "wetland", "fr": "zone humide", "level": "B1"}, {"en": "estuary", "fr": "estuaire", "level": "C1"}, {"en": "tributary", "fr": "affluent (rivière)", "level": "C1"}, {"en": "watershed (geo)", "fr": "bassin hydrographique", "level": "C1"}, {"en": "bedrock", "fr": "roche mère", "level": "C1"}, {"en": "sediment", "fr": "sédiment", "level": "B1"}, {"en": "tectonic plate", "fr": "plaque tectonique", "level": "B1"}, {"en": "seismic", "fr": "sismique", "level": "B2"}, {"en": "magma", "fr": "magma", "level": "A2"}, {"en": "crater", "fr": "cratère", "level": "A2"}, {"en": "canopy layer", "fr": "strate de la canopée", "level": "B2"}, {"en": "understory", "fr": "sous-bois", "level": "C1"}, {"en": "food web", "fr": "réseau trophique", "level": "B2"}, {"en": "apex species", "fr": "espèce dominante", "level": "C1"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'nature') and position = 4)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'nature'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"photosynthèse\" = ?", "options": ["crater", "decompose", "tributary", "photosynthesis"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"photosynthesis\"."}'),(2, 'qcm', '{"question": "\"cycle des nutriments\" = ?", "options": ["decompose", "seismic", "topsoil", "nutrient cycle"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"nutrient cycle\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "wetland", "right": "zone humide"}, {"left": "estuary", "right": "estuaire"}, {"left": "tributary", "right": "affluent (rivière)"}, {"left": "watershed (geo)", "right": "bassin hydrographique"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "tectonic plate", "right": "plaque tectonique"}, {"left": "seismic", "right": "sismique"}, {"left": "magma", "right": "magma"}, {"left": "crater", "right": "cratère"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"sous-bois\" = ", "sentence_after": "", "correct_answers": ["understory"], "feedback_correct": "Correct !", "feedback_incorrect": "\"sous-bois\" se dit \"understory\" en anglais."}'),(6, 'true_false', '{"statement": "\"apex species\" veut dire \"espèce dominante\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'nature')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 5, 'Niveau 5', '[{"en": "carbon cycle", "fr": "cycle du carbone", "level": "B2"}, {"en": "nitrogen fixation", "fr": "fixation de l''azote", "level": "C1"}, {"en": "bioaccumulation", "fr": "bioaccumulation", "level": "C1"}, {"en": "trophic cascade", "fr": "cascade trophique", "level": "C1"}, {"en": "phenology", "fr": "phénologie", "level": "C1"}, {"en": "rewilding", "fr": "réensauvagement", "level": "C1"}, {"en": "habitat fragmentation", "fr": "fragmentation de l''habitat", "level": "C1"}, {"en": "ecological niche", "fr": "niche écologique", "level": "C1"}, {"en": "keystone predator", "fr": "prédateur clé de voûte", "level": "C1"}, {"en": "carrying capacity", "fr": "capacité de charge", "level": "C1"}, {"en": "bioindicator", "fr": "bio-indicateur", "level": "C1"}, {"en": "anthropogenic", "fr": "d''origine humaine", "level": "C1"}, {"en": "greenhouse gas", "fr": "gaz à effet de serre", "level": "B2"}, {"en": "carbon sequestration", "fr": "séquestration du carbone", "level": "C1"}, {"en": "tipping point (climate)", "fr": "point de bascule", "level": "C1"}, {"en": "resilience (ecosystem)", "fr": "résilience (écosystème)", "level": "C1"}, {"en": "biomimicry", "fr": "biomimétisme", "level": "C1"}, {"en": "regenerative agriculture", "fr": "agriculture régénérative", "level": "C1"}, {"en": "monoculture", "fr": "monoculture", "level": "B2"}, {"en": "permaculture", "fr": "permaculture", "level": "B2"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'nature') and position = 5)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'nature'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"cycle du carbone\" = ?", "options": ["carbon cycle", "regenerative agriculture", "nitrogen fixation", "carrying capacity"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"carbon cycle\"."}'),(2, 'qcm', '{"question": "\"cascade trophique\" = ?", "options": ["rewilding", "trophic cascade", "monoculture", "keystone predator"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"trophic cascade\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "habitat fragmentation", "right": "fragmentation de l''habitat"}, {"left": "ecological niche", "right": "niche écologique"}, {"left": "keystone predator", "right": "prédateur clé de voûte"}, {"left": "carrying capacity", "right": "capacité de charge"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "greenhouse gas", "right": "gaz à effet de serre"}, {"left": "carbon sequestration", "right": "séquestration du carbone"}, {"left": "tipping point (climate)", "right": "point de bascule"}, {"left": "resilience (ecosystem)", "right": "résilience (écosystème)"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"agriculture régénérative\" = ", "sentence_after": "", "correct_answers": ["regenerative agriculture"], "feedback_correct": "Correct !", "feedback_incorrect": "\"agriculture régénérative\" se dit \"regenerative agriculture\" en anglais."}'),(6, 'true_false', '{"statement": "\"permaculture\" veut dire \"permaculture\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'mode')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 4, 'Niveau 4', '[{"en": "draping", "fr": "drapé (technique)", "level": "C1"}, {"en": "bespoke", "fr": "fait sur mesure", "level": "C1"}, {"en": "off-the-rack", "fr": "prêt-à-porter", "level": "B2"}, {"en": "hemline", "fr": "longueur d''ourlet", "level": "B2"}, {"en": "neckline", "fr": "encolure", "level": "B1"}, {"en": "silhouette (fashion)", "fr": "silhouette (mode)", "level": "B1"}, {"en": "layering (style)", "fr": "superposition (style)", "level": "B1"}, {"en": "accessorizing", "fr": "accessoirisation", "level": "B1"}, {"en": "color palette", "fr": "palette de couleurs", "level": "B1"}, {"en": "texture (fabric)", "fr": "texture (tissu)", "level": "B1"}, {"en": "pattern mixing", "fr": "mélange de motifs", "level": "B2"}, {"en": "proportion (style)", "fr": "proportion (style)", "level": "B2"}, {"en": "wardrobe staple", "fr": "basique de garde-robe", "level": "B1"}, {"en": "investment piece", "fr": "pièce d''investissement (mode)", "level": "C1"}, {"en": "wear and tear", "fr": "usure", "level": "B1"}, {"en": "mend", "fr": "raccommoder", "level": "B1"}, {"en": "alter (clothes)", "fr": "retoucher (vêtement)", "level": "B1"}, {"en": "consignment shop", "fr": "dépôt-vente", "level": "C1"}, {"en": "closet edit", "fr": "tri de garde-robe", "level": "C1"}, {"en": "personal style", "fr": "style personnel", "level": "B1"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'mode') and position = 4)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'mode'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"drapé (technique)\" = ?", "options": ["texture (fabric)", "draping", "personal style", "mend"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"draping\"."}'),(2, 'qcm', '{"question": "\"longueur d''ourlet\" = ?", "options": ["alter (clothes)", "hemline", "pattern mixing", "wardrobe staple"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"hemline\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "layering (style)", "right": "superposition (style)"}, {"left": "accessorizing", "right": "accessoirisation"}, {"left": "color palette", "right": "palette de couleurs"}, {"left": "texture (fabric)", "right": "texture (tissu)"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "wardrobe staple", "right": "basique de garde-robe"}, {"left": "investment piece", "right": "pièce d''investissement (mode)"}, {"left": "wear and tear", "right": "usure"}, {"left": "mend", "right": "raccommoder"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"dépôt-vente\" = ", "sentence_after": "", "correct_answers": ["consignment shop"], "feedback_correct": "Correct !", "feedback_incorrect": "\"dépôt-vente\" se dit \"consignment shop\" en anglais."}'),(6, 'true_false', '{"statement": "\"personal style\" veut dire \"style personnel\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'mode')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 5, 'Niveau 5', '[{"en": "fashion cycle", "fr": "cycle de la mode", "level": "C1"}, {"en": "trickle-down effect (fashion)", "fr": "effet de diffusion vertical", "level": "C1"}, {"en": "subculture style", "fr": "style de sous-culture", "level": "C1"}, {"en": "streetwear", "fr": "streetwear", "level": "B1"}, {"en": "athleisure", "fr": "athleisure", "level": "B1"}, {"en": "gender-neutral fashion", "fr": "mode non genrée", "level": "B2"}, {"en": "size inclusivity", "fr": "inclusivité des tailles", "level": "C1"}, {"en": "greenwashing (fashion)", "fr": "éco-blanchiment (mode)", "level": "C1"}, {"en": "supply chain (fashion)", "fr": "chaîne d''approvisionnement", "level": "C1"}, {"en": "garment worker", "fr": "ouvrier du textile", "level": "C1"}, {"en": "ethical sourcing", "fr": "approvisionnement éthique", "level": "C1"}, {"en": "counterfeit", "fr": "contrefaçon", "level": "B1"}, {"en": "knockoff", "fr": "copie bon marché", "level": "B1"}, {"en": "brand identity", "fr": "identité de marque", "level": "B2"}, {"en": "iconic (fashion)", "fr": "emblématique (mode)", "level": "B1"}, {"en": "archival piece", "fr": "pièce d''archive (mode)", "level": "C1"}, {"en": "It-bag", "fr": "sac tendance incontournable", "level": "C1"}, {"en": "capsule collection", "fr": "collection capsule", "level": "C1"}, {"en": "runway show", "fr": "défilé de mode", "level": "B1"}, {"en": "front row", "fr": "premier rang (défilé)", "level": "C1"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'mode') and position = 5)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'mode'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"cycle de la mode\" = ?", "options": ["ethical sourcing", "capsule collection", "fashion cycle", "brand identity"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"fashion cycle\"."}'),(2, 'qcm', '{"question": "\"streetwear\" = ?", "options": ["fashion cycle", "brand identity", "knockoff", "streetwear"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"streetwear\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "size inclusivity", "right": "inclusivité des tailles"}, {"left": "greenwashing (fashion)", "right": "éco-blanchiment (mode)"}, {"left": "supply chain (fashion)", "right": "chaîne d''approvisionnement"}, {"left": "garment worker", "right": "ouvrier du textile"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "knockoff", "right": "copie bon marché"}, {"left": "brand identity", "right": "identité de marque"}, {"left": "iconic (fashion)", "right": "emblématique (mode)"}, {"left": "archival piece", "right": "pièce d''archive (mode)"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"collection capsule\" = ", "sentence_after": "", "correct_answers": ["capsule collection"], "feedback_correct": "Correct !", "feedback_incorrect": "\"collection capsule\" se dit \"capsule collection\" en anglais."}'),(6, 'true_false', '{"statement": "\"front row\" veut dire \"premier rang (défilé)\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'sante')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 4, 'Niveau 4', '[{"en": "cardiovascular", "fr": "cardiovasculaire", "level": "B2"}, {"en": "respiratory", "fr": "respiratoire", "level": "B1"}, {"en": "digestive system", "fr": "système digestif", "level": "B1"}, {"en": "nervous system", "fr": "système nerveux", "level": "B1"}, {"en": "hormone", "fr": "hormone", "level": "B1"}, {"en": "metabolism", "fr": "métabolisme", "level": "B1"}, {"en": "antibody", "fr": "anticorps", "level": "B1"}, {"en": "antibiotic", "fr": "antibiotique", "level": "A2"}, {"en": "antiviral", "fr": "antiviral", "level": "B1"}, {"en": "antihistamine", "fr": "antihistaminique", "level": "B2"}, {"en": "painkiller", "fr": "antidouleur", "level": "A2"}, {"en": "anesthesia", "fr": "anesthésie", "level": "B1"}, {"en": "sedative", "fr": "sédatif", "level": "B2"}, {"en": "stimulant", "fr": "stimulant", "level": "B1"}, {"en": "overdose", "fr": "surdose", "level": "B1"}, {"en": "side effects", "fr": "effets secondaires", "level": "B1"}, {"en": "contagious", "fr": "contagieux", "level": "A2"}, {"en": "quarantine", "fr": "quarantaine", "level": "B1"}, {"en": "outbreak", "fr": "épidémie/foyer", "level": "B1"}, {"en": "epidemic", "fr": "épidémie", "level": "B1"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'sante') and position = 4)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'sante'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"cardiovasculaire\" = ?", "options": ["cardiovascular", "epidemic", "antiviral", "overdose"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"cardiovascular\"."}'),(2, 'qcm', '{"question": "\"système nerveux\" = ?", "options": ["nervous system", "hormone", "outbreak", "contagious"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"nervous system\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "antibody", "right": "anticorps"}, {"left": "antibiotic", "right": "antibiotique"}, {"left": "antiviral", "right": "antiviral"}, {"left": "antihistamine", "right": "antihistaminique"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "sedative", "right": "sédatif"}, {"left": "stimulant", "right": "stimulant"}, {"left": "overdose", "right": "surdose"}, {"left": "side effects", "right": "effets secondaires"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"quarantaine\" = ", "sentence_after": "", "correct_answers": ["quarantine"], "feedback_correct": "Correct !", "feedback_incorrect": "\"quarantaine\" se dit \"quarantine\" en anglais."}'),(6, 'true_false', '{"statement": "\"epidemic\" veut dire \"épidémie\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'sante')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 5, 'Niveau 5', '[{"en": "pandemic", "fr": "pandémie", "level": "B1"}, {"en": "public health", "fr": "santé publique", "level": "B1"}, {"en": "herd immunity", "fr": "immunité collective", "level": "C1"}, {"en": "comorbidity", "fr": "comorbidité", "level": "C1"}, {"en": "prognosis", "fr": "pronostic", "level": "C1"}, {"en": "palliative care", "fr": "soins palliatifs", "level": "C1"}, {"en": "telemedicine", "fr": "télémédecine", "level": "B2"}, {"en": "preventative screening", "fr": "dépistage préventif", "level": "C1"}, {"en": "genetic predisposition", "fr": "prédisposition génétique", "level": "C1"}, {"en": "biomarker", "fr": "biomarqueur", "level": "C1"}, {"en": "clinical trial", "fr": "essai clinique", "level": "B2"}, {"en": "placebo effect", "fr": "effet placebo", "level": "B2"}, {"en": "informed consent", "fr": "consentement éclairé", "level": "C1"}, {"en": "informed consent", "fr": "consentement éclairé (bis évité)", "level": "C1"}, {"en": "triage", "fr": "triage (urgences)", "level": "C1"}, {"en": "malpractice", "fr": "faute professionnelle (médicale)", "level": "C1"}, {"en": "health insurance", "fr": "assurance santé", "level": "B1"}, {"en": "copay", "fr": "quote-part (assurance)", "level": "C1"}, {"en": "out-of-pocket cost", "fr": "reste à charge", "level": "C1"}, {"en": "universal healthcare", "fr": "couverture santé universelle", "level": "B2"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'sante') and position = 5)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'sante'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"pandémie\" = ?", "options": ["pandemic", "placebo effect", "palliative care", "malpractice"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"pandemic\"."}'),(2, 'qcm', '{"question": "\"comorbidité\" = ?", "options": ["placebo effect", "comorbidity", "biomarker", "informed consent"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"comorbidity\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "telemedicine", "right": "télémédecine"}, {"left": "preventative screening", "right": "dépistage préventif"}, {"left": "genetic predisposition", "right": "prédisposition génétique"}, {"left": "biomarker", "right": "biomarqueur"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "informed consent", "right": "consentement éclairé"}, {"left": "informed consent", "right": "consentement éclairé (bis évité)"}, {"left": "triage", "right": "triage (urgences)"}, {"left": "malpractice", "right": "faute professionnelle (médicale)"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"quote-part (assurance)\" = ", "sentence_after": "", "correct_answers": ["copay"], "feedback_correct": "Correct !", "feedback_incorrect": "\"quote-part (assurance)\" se dit \"copay\" en anglais."}'),(6, 'true_false', '{"statement": "\"universal healthcare\" veut dire \"couverture santé universelle\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'travail')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 4, 'Niveau 4', '[{"en": "job posting", "fr": "offre d''emploi", "level": "A2"}, {"en": "cover letter", "fr": "lettre de motivation", "level": "A2"}, {"en": "interview panel", "fr": "jury d''entretien", "level": "B1"}, {"en": "job offer", "fr": "proposition d''embauche", "level": "A2"}, {"en": "counteroffer", "fr": "contre-offre", "level": "B2"}, {"en": "benefits package", "fr": "avantages sociaux", "level": "B1"}, {"en": "relocation package", "fr": "aide à la relocalisation", "level": "C1"}, {"en": "non-disclosure agreement", "fr": "accord de confidentialité", "level": "C1"}, {"en": "non-compete clause", "fr": "clause de non-concurrence", "level": "C1"}, {"en": "performance bonus", "fr": "prime de performance", "level": "B1"}, {"en": "commission (sales)", "fr": "commission (vente)", "level": "B1"}, {"en": "quota", "fr": "quota", "level": "B1"}, {"en": "pipeline (sales)", "fr": "pipeline commercial", "level": "C1"}, {"en": "client-facing", "fr": "en contact avec les clients", "level": "C1"}, {"en": "cross-team collaboration", "fr": "collaboration inter-équipes", "level": "C1"}, {"en": "chain of command", "fr": "hiérarchie/chaîne de commandement", "level": "B2"}, {"en": "org chart", "fr": "organigramme", "level": "B2"}, {"en": "job security", "fr": "sécurité de l''emploi", "level": "B1"}, {"en": "career pivot", "fr": "reconversion professionnelle", "level": "C1"}, {"en": "exit interview", "fr": "entretien de départ", "level": "C1"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'travail') and position = 4)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'travail'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"offre d''emploi\" = ?", "options": ["non-compete clause", "job posting", "pipeline (sales)", "interview panel"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"job posting\"."}'),(2, 'qcm', '{"question": "\"proposition d''embauche\" = ?", "options": ["job offer", "career pivot", "non-disclosure agreement", "performance bonus"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"job offer\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "relocation package", "right": "aide à la relocalisation"}, {"left": "non-disclosure agreement", "right": "accord de confidentialité"}, {"left": "non-compete clause", "right": "clause de non-concurrence"}, {"left": "performance bonus", "right": "prime de performance"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "pipeline (sales)", "right": "pipeline commercial"}, {"left": "client-facing", "right": "en contact avec les clients"}, {"left": "cross-team collaboration", "right": "collaboration inter-équipes"}, {"left": "chain of command", "right": "hiérarchie/chaîne de commandement"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"sécurité de l''emploi\" = ", "sentence_after": "", "correct_answers": ["job security"], "feedback_correct": "Correct !", "feedback_incorrect": "\"sécurité de l''emploi\" se dit \"job security\" en anglais."}'),(6, 'true_false', '{"statement": "\"exit interview\" veut dire \"entretien de départ\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'travail')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 5, 'Niveau 5', '[{"en": "golden parachute", "fr": "parachute doré", "level": "C1"}, {"en": "nepotism", "fr": "népotisme", "level": "C1"}, {"en": "meritocracy", "fr": "méritocratie", "level": "C1"}, {"en": "groupthink", "fr": "pensée de groupe", "level": "C1"}, {"en": "devil''s advocate", "fr": "avocat du diable", "level": "C1"}, {"en": "brainstorm (verb)", "fr": "faire un brainstorming", "level": "B1"}, {"en": "action item", "fr": "point d''action", "level": "B2"}, {"en": "stakeholder buy-in", "fr": "adhésion des parties prenantes", "level": "C1"}, {"en": "scope creep", "fr": "dérive du périmètre (projet)", "level": "C1"}, {"en": "deliverable", "fr": "livrable", "level": "B2"}, {"en": "milestone (project)", "fr": "jalon (projet)", "level": "B2"}, {"en": "post-mortem (work)", "fr": "bilan rétrospectif", "level": "C1"}, {"en": "blameless culture", "fr": "culture sans reproche", "level": "C1"}, {"en": "psychological safety", "fr": "sécurité psychologique", "level": "C1"}, {"en": "imposter syndrome", "fr": "syndrome de l''imposteur", "level": "B2"}, {"en": "work friend", "fr": "collègue devenu ami", "level": "C1"}, {"en": "watercooler talk", "fr": "discussions informelles au bureau", "level": "C1"}, {"en": "hybrid work", "fr": "travail hybride", "level": "B1"}, {"en": "presenteeism", "fr": "présentéisme", "level": "C1"}, {"en": "quiet firing", "fr": "licenciement silencieux", "level": "C1"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'travail') and position = 5)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'travail'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"parachute doré\" = ?", "options": ["hybrid work", "deliverable", "golden parachute", "meritocracy"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"golden parachute\"."}'),(2, 'qcm', '{"question": "\"pensée de groupe\" = ?", "options": ["hybrid work", "milestone (project)", "imposter syndrome", "groupthink"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"groupthink\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "action item", "right": "point d''action"}, {"left": "stakeholder buy-in", "right": "adhésion des parties prenantes"}, {"left": "scope creep", "right": "dérive du périmètre (projet)"}, {"left": "deliverable", "right": "livrable"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "blameless culture", "right": "culture sans reproche"}, {"left": "psychological safety", "right": "sécurité psychologique"}, {"left": "imposter syndrome", "right": "syndrome de l''imposteur"}, {"left": "work friend", "right": "collègue devenu ami"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"travail hybride\" = ", "sentence_after": "", "correct_answers": ["hybrid work"], "feedback_correct": "Correct !", "feedback_incorrect": "\"travail hybride\" se dit \"hybrid work\" en anglais."}'),(6, 'true_false', '{"statement": "\"quiet firing\" veut dire \"licenciement silencieux\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'maison')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 4, 'Niveau 4', '[{"en": "load-bearing wall", "fr": "mur porteur", "level": "C1"}, {"en": "subfloor", "fr": "sous-plancher", "level": "C1"}, {"en": "drywall", "fr": "cloison sèche/placo", "level": "C1"}, {"en": "caulking", "fr": "calfeutrage", "level": "C1"}, {"en": "weatherproofing", "fr": "imperméabilisation", "level": "C1"}, {"en": "HVAC", "fr": "chauffage-ventilation-climatisation", "level": "C1"}, {"en": "thermostat", "fr": "thermostat", "level": "A2"}, {"en": "circuit breaker", "fr": "disjoncteur", "level": "B1"}, {"en": "outlet (electrical)", "fr": "prise électrique", "level": "A2"}, {"en": "water heater", "fr": "chauffe-eau", "level": "A2"}, {"en": "septic tank", "fr": "fosse septique", "level": "C1"}, {"en": "gutter (house)", "fr": "gouttière", "level": "B1"}, {"en": "skylight", "fr": "puits de lumière", "level": "B1"}, {"en": "wainscoting", "fr": "lambris", "level": "C1"}, {"en": "crown molding", "fr": "corniche", "level": "C1"}, {"en": "baseboard", "fr": "plinthe", "level": "B1"}, {"en": "subdivision (housing)", "fr": "lotissement", "level": "C1"}, {"en": "appraisal (home)", "fr": "estimation immobilière", "level": "C1"}, {"en": "closing costs", "fr": "frais de clôture (achat)", "level": "C1"}, {"en": "equity (home)", "fr": "valeur nette (maison)", "level": "C1"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'maison') and position = 4)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'maison'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"mur porteur\" = ?", "options": ["subfloor", "caulking", "load-bearing wall", "subdivision (housing)"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"load-bearing wall\"."}'),(2, 'qcm', '{"question": "\"calfeutrage\" = ?", "options": ["HVAC", "caulking", "crown molding", "outlet (electrical)"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"caulking\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "thermostat", "right": "thermostat"}, {"left": "circuit breaker", "right": "disjoncteur"}, {"left": "outlet (electrical)", "right": "prise électrique"}, {"left": "water heater", "right": "chauffe-eau"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "skylight", "right": "puits de lumière"}, {"left": "wainscoting", "right": "lambris"}, {"left": "crown molding", "right": "corniche"}, {"left": "baseboard", "right": "plinthe"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"estimation immobilière\" = ", "sentence_after": "", "correct_answers": ["appraisal (home)"], "feedback_correct": "Correct !", "feedback_incorrect": "\"estimation immobilière\" se dit \"appraisal (home)\" en anglais."}'),(6, 'true_false', '{"statement": "\"equity (home)\" veut dire \"valeur nette (maison)\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'maison')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 5, 'Niveau 5', '[{"en": "zoning laws", "fr": "règles d''urbanisme", "level": "C1"}, {"en": "building code", "fr": "code de la construction", "level": "C1"}, {"en": "easement", "fr": "servitude (immobilier)", "level": "C1"}, {"en": "foreclosure", "fr": "saisie immobilière", "level": "C1"}, {"en": "adjustable-rate mortgage", "fr": "prêt à taux variable", "level": "C1"}, {"en": "fixed-rate mortgage", "fr": "prêt à taux fixe", "level": "C1"}, {"en": "home inspection", "fr": "inspection de la maison", "level": "B1"}, {"en": "contingency (real estate)", "fr": "clause suspensive", "level": "C1"}, {"en": "bidding war", "fr": "guerre des enchères", "level": "C1"}, {"en": "home valuation", "fr": "évaluation immobilière", "level": "C1"}, {"en": "staging (home sale)", "fr": "mise en valeur (vente)", "level": "C1"}, {"en": "flipping (real estate)", "fr": "achat-revente rénové", "level": "C1"}, {"en": "co-housing", "fr": "habitat participatif", "level": "C1"}, {"en": "tiny house", "fr": "micro-maison", "level": "B2"}, {"en": "net-zero home", "fr": "maison à énergie nette nulle", "level": "C1"}, {"en": "passive house", "fr": "maison passive", "level": "C1"}, {"en": "aging in place", "fr": "vieillir chez soi", "level": "C1"}, {"en": "accessory dwelling unit", "fr": "logement annexe", "level": "C1"}, {"en": "shared equity", "fr": "copropriété partagée", "level": "C1"}, {"en": "intergenerational living", "fr": "habitat intergénérationnel", "level": "C1"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'maison') and position = 5)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'maison'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"règles d''urbanisme\" = ?", "options": ["fixed-rate mortgage", "home valuation", "zoning laws", "net-zero home"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"zoning laws\"."}'),(2, 'qcm', '{"question": "\"saisie immobilière\" = ?", "options": ["foreclosure", "accessory dwelling unit", "bidding war", "flipping (real estate)"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"foreclosure\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "home inspection", "right": "inspection de la maison"}, {"left": "contingency (real estate)", "right": "clause suspensive"}, {"left": "bidding war", "right": "guerre des enchères"}, {"left": "home valuation", "right": "évaluation immobilière"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "co-housing", "right": "habitat participatif"}, {"left": "tiny house", "right": "micro-maison"}, {"left": "net-zero home", "right": "maison à énergie nette nulle"}, {"left": "passive house", "right": "maison passive"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"logement annexe\" = ", "sentence_after": "", "correct_answers": ["accessory dwelling unit"], "feedback_correct": "Correct !", "feedback_incorrect": "\"logement annexe\" se dit \"accessory dwelling unit\" en anglais."}'),(6, 'true_false', '{"statement": "\"intergenerational living\" veut dire \"habitat intergénérationnel\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'emotions')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 4, 'Niveau 4', '[{"en": "overwhelmed (feeling)", "fr": "dépassé/submergé", "level": "B1"}, {"en": "burnt out", "fr": "épuisé (émotionnellement)", "level": "B1"}, {"en": "torn (feeling)", "fr": "déchiré/partagé", "level": "B1"}, {"en": "at peace", "fr": "en paix (avec soi)", "level": "B1"}, {"en": "on edge", "fr": "à cran/nerveux", "level": "B1"}, {"en": "bittersweet", "fr": "doux-amer", "level": "B1"}, {"en": "heartwarming", "fr": "touchant/réconfortant", "level": "B1"}, {"en": "gut-wrenching", "fr": "déchirant", "level": "C1"}, {"en": "uplifting", "fr": "réconfortant/porteur d''espoir", "level": "B1"}, {"en": "unsettling", "fr": "déstabilisant/troublant", "level": "C1"}, {"en": "cathartic", "fr": "cathartique/libérateur", "level": "C1"}, {"en": "empowering", "fr": "valorisant/qui renforce", "level": "B2"}, {"en": "disillusioned", "fr": "désillusionné", "level": "C1"}, {"en": "jaded", "fr": "blasé/désabusé", "level": "C1"}, {"en": "wistful", "fr": "nostalgique/mélancolique", "level": "C1"}, {"en": "elated", "fr": "transporté de joie", "level": "C1"}, {"en": "crestfallen", "fr": "abattu/déconfit", "level": "C1"}, {"en": "perplexed", "fr": "perplexe", "level": "B1"}, {"en": "bewildered", "fr": "déconcerté", "level": "B2"}, {"en": "flustered", "fr": "déconcerté/troublé", "level": "B2"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'emotions') and position = 4)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'emotions'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"dépassé/submergé\" = ?", "options": ["overwhelmed (feeling)", "unsettling", "wistful", "bewildered"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"overwhelmed (feeling)\"."}'),(2, 'qcm', '{"question": "\"en paix (avec soi)\" = ?", "options": ["unsettling", "gut-wrenching", "uplifting", "at peace"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"at peace\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "heartwarming", "right": "touchant/réconfortant"}, {"left": "gut-wrenching", "right": "déchirant"}, {"left": "uplifting", "right": "réconfortant/porteur d''espoir"}, {"left": "unsettling", "right": "déstabilisant/troublant"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "disillusioned", "right": "désillusionné"}, {"left": "jaded", "right": "blasé/désabusé"}, {"left": "wistful", "right": "nostalgique/mélancolique"}, {"left": "elated", "right": "transporté de joie"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"perplexe\" = ", "sentence_after": "", "correct_answers": ["perplexed"], "feedback_correct": "Correct !", "feedback_incorrect": "\"perplexe\" se dit \"perplexed\" en anglais."}'),(6, 'true_false', '{"statement": "\"flustered\" veut dire \"déconcerté/troublé\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'emotions')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 5, 'Niveau 5', '[{"en": "emotional intelligence", "fr": "intelligence émotionnelle", "level": "B2"}, {"en": "self-regulation", "fr": "autorégulation", "level": "C1"}, {"en": "emotional labor", "fr": "travail émotionnel", "level": "C1"}, {"en": "compassion fatigue", "fr": "fatigue de la compassion", "level": "C1"}, {"en": "cognitive dissonance", "fr": "dissonance cognitive", "level": "C1"}, {"en": "gaslighting", "fr": "manipulation psychologique", "level": "C1"}, {"en": "validation (emotional)", "fr": "validation émotionnelle", "level": "C1"}, {"en": "attachment style", "fr": "style d''attachement", "level": "C1"}, {"en": "codependency", "fr": "codépendance", "level": "C1"}, {"en": "boundary setting", "fr": "fixer des limites", "level": "C1"}, {"en": "emotional bandwidth", "fr": "capacité émotionnelle disponible", "level": "C1"}, {"en": "venting", "fr": "se défouler/déverser ses émotions", "level": "B2"}, {"en": "bottling up", "fr": "refouler (émotions)", "level": "C1"}, {"en": "emotional trigger", "fr": "déclencheur émotionnel", "level": "C1"}, {"en": "self-soothe", "fr": "s''auto-apaiser", "level": "C1"}, {"en": "emotional baggage", "fr": "bagage émotionnel", "level": "C1"}, {"en": "closure (emotional)", "fr": "tourner la page", "level": "C1"}, {"en": "emotional resilience", "fr": "résilience émotionnelle", "level": "C1"}, {"en": "burnout recovery", "fr": "guérison de l''épuisement", "level": "C1"}, {"en": "radical acceptance", "fr": "acceptation radicale", "level": "C1"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'emotions') and position = 5)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'emotions'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"intelligence émotionnelle\" = ?", "options": ["venting", "emotional resilience", "cognitive dissonance", "emotional intelligence"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"emotional intelligence\"."}'),(2, 'qcm', '{"question": "\"fatigue de la compassion\" = ?", "options": ["emotional bandwidth", "compassion fatigue", "emotional resilience", "gaslighting"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"compassion fatigue\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "validation (emotional)", "right": "validation émotionnelle"}, {"left": "attachment style", "right": "style d''attachement"}, {"left": "codependency", "right": "codépendance"}, {"left": "boundary setting", "right": "fixer des limites"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "bottling up", "right": "refouler (émotions)"}, {"left": "emotional trigger", "right": "déclencheur émotionnel"}, {"left": "self-soothe", "right": "s''auto-apaiser"}, {"left": "emotional baggage", "right": "bagage émotionnel"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"résilience émotionnelle\" = ", "sentence_after": "", "correct_answers": ["emotional resilience"], "feedback_correct": "Correct !", "feedback_incorrect": "\"résilience émotionnelle\" se dit \"emotional resilience\" en anglais."}'),(6, 'true_false', '{"statement": "\"radical acceptance\" veut dire \"acceptation radicale\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);
