-- ============================================
-- LUMA — Import des métadonnées des 135 scénarios
-- (consultables tous ; seuls 4 seront rendus jouables ensuite)
-- ============================================

with lang as (select id from languages where code = 'en')
insert into scenarios (theme_id, format, cecr_level, title, content, is_playable)
select st.id, v.format, v.cecr_level, v.title, v.content::jsonb, false
from lang
join scenario_themes st on st.language_id = lang.id
join (values
  (1, 1, 'court', 'A1-A2', 'Commander un plat simple', '{"synopsis": "Premier repas seul dans un restaurant anglophone. L''objectif est de commander correctement un plat et une boisson."}'),
  (1, 2, 'court', 'A2', 'Une allergie à signaler', '{"synopsis": "L''utilisateur doit signaler une allergie aux fruits à coque avant de commander, et poser des questions sur la composition d''un plat."}'),
  (1, 3, 'court', 'A2', 'Payer et laisser un pourboire', '{"synopsis": "Fin de repas, demander l''addition et gérer le pourboire (culture anglo-saxonne du tipping, différente de la France)."}'),
  (1, 4, 'moyen', 'B1', 'Une réservation compliquée', '{"synopsis": "Appeler pour réserver une table, mais le restaurant est complet à l''heure souhaitée — négocier une alternative."}'),
  (1, 5, 'moyen', 'B1-B2', 'Se plaindre poliment d''un plat', '{"synopsis": "Le plat servi n''est pas ce qui a été commandé, ou arrive froid. Objectif : se plaindre avec assertivité mais politesse (nuance culturelle importante)."}'),
  (1, 6, 'moyen', 'B1', 'Un dîner d''anniversaire surprise', '{"synopsis": "L''utilisateur organise une surprise pour un ami avec la complicité du personnel — coordination logistique en anglais avant l''arrivée du groupe."}'),
  (1, 7, 'long', 'B2-C1', 'Un dîner d''affaires à enjeux', '{"synopsis": "Dîner professionnel où l''utilisateur doit gérer à la fois le small talk, la présentation d''une offre commerciale, et une objection délicate du client — le tout en gérant le service du restaurant en parallèle."}'),
  (1, 8, 'long', 'B2', 'Une soirée qui tourne mal (mauvais service)', '{"synopsis": "Une suite d''incidents de service (attente très longue, erreur de commande, plat manquant) pousse l''utilisateur à devoir gérer sa frustration tout en restant courtois, avec plusieurs points de bascule vers une résolution positive ou un vrai conflit."}'),
  (1, 9, 'long', 'B2-C1', 'Un repas de fiançailles', '{"synopsis": "Un dîner à forte charge émotionnelle où l''utilisateur doit faire sa demande en mariage, gérer les réactions de la famille présente, et improviser un discours — combine vocabulaire émotionnel, formalisme et improvisation orale."}'),
  (2, 1, 'court', 'A2', 'Premier message sur une appli de rencontre', '{"synopsis": "Écrire un premier message engageant à partir du profil d''Alex (passionné de randonnée et de cuisine)."}'),
  (2, 2, 'court', 'A2', 'Fixer le lieu et l''heure', '{"synopsis": "Négocier un lieu et un horaire de rendez-vous par message."}'),
  (2, 3, 'court', 'B1', 'Un compliment maladroit à rattraper', '{"synopsis": "L''utilisateur fait un compliment qui tombe mal (trop familier, ou mal formulé) et doit désamorcer la gêne."}'),
  (2, 4, 'moyen', 'B1', 'Premier rendez-vous dans un café', '{"synopsis": "Gérer une conversation complète de premier rendez-vous — questions personnelles, silences, transition entre sujets."}'),
  (2, 5, 'moyen', 'B1-B2', 'Une conversation qui dévie sur un sujet sensible', '{"synopsis": "La conversation dérive vers la politique ou la religion — gérer un désaccord avec tact sans gâcher la soirée."}'),
  (2, 6, 'moyen', 'A2-B1', 'Proposer un deuxième rendez-vous', '{"synopsis": "La soirée touche à sa fin, il faut évaluer si ça a matché et proposer (ou non) de se revoir, avec les formulations adaptées."}'),
  (2, 7, 'long', 'B2', 'Un date qui évolue sur toute une soirée', '{"synopsis": "Une soirée complète en plusieurs étapes (apéritif, dîner, promenade) où chaque étape influence l''ambiance générale et débouche sur des variantes de fin très différentes."}'),
  (2, 8, 'long', 'B2', 'Rencontrer les amis de l''autre', '{"synopsis": "Premier moment social en groupe — gérer les taquineries amicales, répondre aux questions sur la relation, trouver sa place dans une dynamique de groupe déjà établie."}'),
  (2, 9, 'long', 'B2-C1', 'Une déclaration à un moment clé', '{"synopsis": "Après plusieurs mois de relation, un moment (anniversaire de rencontre, voyage) devient l''occasion d''exprimer des sentiments profonds — travail sur le registre émotionnel et l''expression de la vulnérabilité, dans la continuité du travail amorcé au scénario 1.9."}'),
  (3, 1, 'court', 'A2-B1', 'Se présenter en 2 minutes', '{"synopsis": "Réussir un pitch de présentation personnelle concis et structuré."}'),
  (3, 2, 'court', 'B1', 'Répondre à "pourquoi ce poste ?"', '{"synopsis": "Formuler une motivation crédible et personnalisée plutôt qu''une réponse générique."}'),
  (3, 3, 'court', 'A2', 'Négocier une date d''entretien', '{"synopsis": "Un appel court pour caler une date d''entretien qui ne convient pas initialement."}'),
  (3, 4, 'moyen', 'B1-B2', 'Un entretien technique complet', '{"synopsis": "Répondre à une série de questions techniques et comportementales classiques, avec gestion d''une question à laquelle on ne sait pas répondre."}'),
  (3, 5, 'moyen', 'B2', 'Gérer une question piège', '{"synopsis": "Répondre avec tact à des questions délicates (\"Pourquoi avez-vous quitté votre dernier poste ?\", \"Quel est votre plus grand défaut ?\")."}'),
  (3, 6, 'moyen', 'B2', 'Négocier le salaire', '{"synopsis": "Une offre est faite, en dessous des attentes — négocier sans braquer l''employeur potentiel."}'),
  (3, 7, 'long', 'B2', 'Un parcours d''entretien à plusieurs étapes', '{"synopsis": "Un processus de recrutement complet en 3 tours le même jour, chacun avec un style d''entretien différent, testant l''adaptabilité de l''utilisateur."}'),
  (3, 8, 'long', 'B2-C1', 'Un entretien collectif face à des concurrents', '{"synopsis": "Un assessment center en groupe — étude de cas collective où l''utilisateur doit à la fois collaborer et se démarquer face à d''autres candidats, sans écraser les autres ni s''effacer."}'),
  (3, 9, 'long', 'B2-C1', 'Un entretien qui se termine par une contre-offre', '{"synopsis": "Après un entretien réussi et une offre reçue, l''ancien employeur de l''utilisateur fait une contre-offre pour le retenir — dilemme à trancher, avec un appel à gérer en anglais entre les deux options."}'),
  (4, 1, 'court', 'A1-A2', 'Enregistrement et bagages', '{"synopsis": "Passer l''enregistrement, gérer le poids des bagages."}'),
  (4, 2, 'court', 'A2', 'Une question à la douane', '{"synopsis": "Répondre correctement et calmement aux questions standards de douane."}'),
  (4, 3, 'court', 'B1', 'Retrouver une valise perdue', '{"synopsis": "Signaler une valise manquante au tapis à bagages et remplir une déclaration."}'),
  (4, 4, 'moyen', 'B1-B2', 'Un vol annulé à gérer', '{"synopsis": "Le vol est annulé, négocier un vol de remplacement et un hébergement."}'),
  (4, 5, 'moyen', 'B1', 'Demander un changement de siège et discuter avec son voisin', '{"synopsis": "Gérer une demande logistique puis une conversation de vol avec un inconnu."}'),
  (4, 6, 'moyen', 'A2-B1', 'S''orienter dans un aéroport inconnu', '{"synopsis": "Trouver sa porte d''embarquement dans un grand aéroport avec peu de temps."}'),
  (4, 7, 'long', 'B2', 'Une correspondance ratée avec plusieurs obstacles', '{"synopsis": "Un vol retardé fait rater la correspondance — série d''obstacles à surmonter (file d''attente, recherche de solution, gestion du stress) pour rejoindre la destination finale."}'),
  (4, 8, 'long', 'B2', 'Un voyage avec imprévus en cascade', '{"synopsis": "Une arrivée à destination qui enchaîne plusieurs petits problèmes (taxi qui se perd, réservation d''hôtel introuvable, carte bancaire refusée) à résoudre les uns après les autres."}'),
  (4, 9, 'long', 'B1-B2', 'Aider un autre passager en difficulté', '{"synopsis": "L''utilisateur remarque un passager âgé perdu et en détresse (vol raté, ne parle pas bien anglais) et choisit de l''aider — scénario centré sur l''empathie et la médiation."}'),
  (5, 1, 'court', 'A2', 'Décrire un symptôme simple à un médecin', '{"synopsis": "Décrire un mal de gorge et de la fièvre."}'),
  (5, 2, 'court', 'A1-A2', 'Demander une pharmacie', '{"synopsis": "Demander son chemin vers la pharmacie la plus proche."}'),
  (5, 3, 'court', 'A2-B1', 'Appeler les secours', '{"synopsis": "Un ami se blesse, appeler le 999/911 et donner les informations essentielles clairement."}'),
  (5, 4, 'moyen', 'B1', 'Une visite chez le médecin complète', '{"synopsis": "Consultation complète — antécédents, symptômes, questions sur le traitement."}'),
  (5, 5, 'moyen', 'B1', 'Expliquer une allergie médicamenteuse', '{"synopsis": "Avant une intervention mineure, signaler clairement une allergie à la pénicilline."}'),
  (5, 6, 'moyen', 'B1-B2', 'Accompagner un proche aux urgences', '{"synopsis": "Accompagner et parler au nom d''un proche qui souffre trop pour bien s''exprimer."}'),
  (5, 7, 'long', 'B2', 'Un séjour bref à l''hôpital à l''étranger', '{"synopsis": "Une hospitalisation de courte durée suite à un accident bénin en voyage — gérer le parcours de soin complet et les démarches d''assurance internationale."}'),
  (5, 8, 'long', 'B2', 'Gérer une urgence avec la barrière de la langue', '{"synopsis": "Situation stressante où l''utilisateur, bien qu''apprenant, doit servir d''intermédiaire linguistique partiel pour un autre patient en détresse aux urgences."}'),
  (5, 9, 'long', 'B1-B2', 'Un suivi médical sur plusieurs jours', '{"synopsis": "Une convalescence de quelques jours en voyage nécessitant plusieurs interactions successives (suivi médical, gestion du traitement, ajustement de programme de voyage)."}'),
  (6, 1, 'court', 'A2', 'Négocier le ménage', '{"synopsis": "Établir un planning de ménage équitable."}'),
  (6, 2, 'court', 'A2-B1', 'Se plaindre du bruit', '{"synopsis": "Demander poliment mais fermement de baisser le bruit tard le soir."}'),
  (6, 3, 'court', 'A2', 'Partager les courses', '{"synopsis": "S''organiser pour les courses communes."}'),
  (6, 4, 'moyen', 'B1', 'Une visite d''appartement en colocation', '{"synopsis": "Se présenter et être évalué comme futur colocataire potentiel."}'),
  (6, 5, 'moyen', 'B1-B2', 'Régler un conflit sur les factures', '{"synopsis": "Désaccord sur la répartition des charges (électricité notamment) — négocier une solution équitable."}'),
  (6, 6, 'moyen', 'A2-B1', 'Accueillir un nouveau coloc', '{"synopsis": "Faire visiter l''appartement et expliquer les règles de la maison à un nouvel arrivant."}'),
  (6, 7, 'long', 'B2', 'Une tension qui dégénère et se résout', '{"synopsis": "Une accumulation de petites frustrations (ménage, bruit, invités) éclate en vraie dispute — gérer un conflit interpersonnel complexe et trouver une résolution durable."}'),
  (6, 8, 'long', 'B1-B2', 'Organiser une fête et gérer les conséquences', '{"synopsis": "Organiser une soirée dans l''appartement, gérer les préparatifs collectifs, puis une plainte du voisinage et le nettoyage du lendemain."}'),
  (6, 9, 'long', 'B1-B2', 'Un déménagement collectif à planifier', '{"synopsis": "La colocation entière déménage vers un nouvel appartement — coordonner la logistique collective et gérer les visites avec l''agence."}'),
  (7, 1, 'court', 'A1-A2', 'Demander une taille', '{"synopsis": "Demander un vêtement dans une autre taille."}'),
  (7, 2, 'court', 'A2-B1', 'Négocier un prix au marché', '{"synopsis": "Négocier le prix d''un souvenir sur un marché où le marchandage est culturellement attendu."}'),
  (7, 3, 'court', 'B1', 'Retourner un article défectueux', '{"synopsis": "Retourner un article cassé et obtenir un remboursement ou un échange."}'),
  (7, 4, 'moyen', 'B1', 'Faire du shopping avec un budget serré', '{"synopsis": "Trouver des vêtements dans un budget limité, comparer les options, gérer les tentations de dépassement."}'),
  (7, 5, 'moyen', 'B1-B2', 'Comparer deux produits avec un vendeur', '{"synopsis": "Comparer deux modèles d''un même produit (ordinateur portable) et poser des questions techniques."}'),
  (7, 6, 'moyen', 'A2-B1', 'Un cadeau à trouver dans l''urgence', '{"synopsis": "Trouver rapidement un cadeau d''anniversaire pour quelqu''un dont on connaît peu les goûts."}'),
  (7, 7, 'long', 'B1-B2', 'Une session shopping avec plusieurs boutiques et décisions', '{"synopsis": "Une après-midi shopping complète pour préparer une tenue pour un événement, à travers plusieurs boutiques, avec un ami donnant (parfois insistamment) son avis."}'),
  (7, 8, 'long', 'B2', 'Un litige avec le service client', '{"synopsis": "Un article commandé en ligne n''est jamais arrivé — gérer un litige complexe avec plusieurs niveaux d''escalade."}'),
  (7, 9, 'long', 'B1-B2', 'Préparer une garde-robe pour un événement', '{"synopsis": "Consultation avec un conseil styliste pour préparer plusieurs tenues en vue d''un voyage professionnel important — dialogue orienté conseil et description précise de besoins."}'),
  (8, 1, 'court', 'A2', 'Demander son chemin à un garde du village', '{"synopsis": "Trouver la route vers la forêt enchantée."}'),
  (8, 2, 'court', 'A2-B1', 'Négocier avec un marchand ambulant', '{"synopsis": "Acheter une potion ou un objet utile pour la suite du voyage."}'),
  (8, 3, 'court', 'B1', 'Un premier indice mystérieux', '{"synopsis": "Recevoir un indice énigmatique pour orienter la quête à venir."}'),
  (8, 4, 'moyen', 'B1', 'Explorer une forêt enchantée avec des choix de chemin', '{"synopsis": "Traverser une forêt magique en choisissant son chemin parmi plusieurs sentiers, chacun avec ses propres rencontres."}'),
  (8, 5, 'moyen', 'B1-B2', 'Négocier avec une créature magique', '{"synopsis": "Une créature garde un passage — la convaincre de laisser passer plutôt que de l''affronter."}'),
  (8, 6, 'moyen', 'B1-B2', 'Résoudre une énigme de temple', '{"synopsis": "Un temple ancien propose une série de trois énigmes verbales à résoudre pour accéder au trésor."}'),
  (8, 7, 'long', 'B2', 'Une quête complète pour retrouver un artefact', '{"synopsis": "Une quête épique complète en plusieurs étapes pour retrouver un artefact volé, combinant exploration, dialogue, et une confrontation finale."}'),
  (8, 8, 'long', 'B2-C1', 'Une alliance à nouer entre plusieurs royaumes', '{"synopsis": "Un scénario diplomatique où l''utilisateur doit négocier une alliance entre deux royaumes historiquement en conflit — teste l''argumentation et la diplomatie en anglais soutenu."}'),
  (8, 9, 'long', 'B2', 'Un affrontement final avec plusieurs issues', '{"synopsis": "Le climax de l''arc narratif fantastique — un affrontement final où plusieurs stratégies (combat, négociation, ruse, sacrifice) mènent à des fins radicalement différentes, teste la capacité à argumenter et improviser sous pression narrative."}'),
  (9, 1, 'court', 'A2-B1', 'Créer son personnage et choisir sa classe', '{"synopsis": "Choisir une classe de personnage et justifier son choix, apprenant le vocabulaire du genre."}'),
  (9, 2, 'court', 'B1', 'Un premier piège à désamorcer', '{"synopsis": "Un couloir piégé doit être franchi avec prudence."}'),
  (9, 3, 'court', 'B1', 'Une rencontre avec un PNJ hostile', '{"synopsis": "Une rencontre où le combat n''est pas la seule option."}'),
  (9, 4, 'moyen', 'B1-B2', 'Explorer un donjon à plusieurs salles avec choix tactiques', '{"synopsis": "Explorer un donjon en équipe, avec des décisions tactiques à chaque salle."}'),
  (9, 5, 'moyen', 'B1-B2', 'Négocier avec un dragon plutôt que combattre', '{"synopsis": "Un dragon garde un trésor — tenter la voie diplomatique plutôt que le combat, en s''appuyant sur la ruse verbale et la flatterie stratégique."}'),
  (9, 6, 'moyen', 'B1-B2', 'Gérer l''inventaire et un dilemme moral', '{"synopsis": "Une ressource limitée (une seule potion de soin) doit être attribuée — dilemme moral à trancher en discutant avec Thorne."}'),
  (9, 7, 'long', 'B2', 'Une campagne complète sur plusieurs donjons', '{"synopsis": "Une véritable mini-campagne enchaînant 3 donjons liés par une trame narrative, réutilisant et complexifiant les mécaniques des scénarios précédents."}'),
  (9, 8, 'long', 'B2', 'Une trahison au sein du groupe à gérer', '{"synopsis": "Un membre du groupe s''avère être un agent double travaillant pour l''ennemi — gérer la découverte, la confrontation, et la décision finale (pardon, exclusion, ou pire)."}'),
  (9, 9, 'long', 'B2', 'Un combat de boss final avec plusieurs stratégies possibles', '{"synopsis": "Le combat climactique de la campagne, où la victoire dépend autant de la stratégie collective discutée en dialogue que de choix tactiques narrés — un scénario qui simule un vrai combat de JDR par la conversation."}'),
  (10, 1, 'court', 'B1', 'Interroger un premier témoin', '{"synopsis": "Recueillir un premier témoignage sur un vol dans un immeuble."}'),
  (10, 2, 'court', 'B1', 'Repérer un indice sur une scène de crime', '{"synopsis": "Observer une scène et décider quel indice mérite d''être examiné en priorité."}'),
  (10, 3, 'court', 'B1-B2', 'Une déduction rapide', '{"synopsis": "À partir de 2-3 indices déjà collectés, formuler une première hypothèse."}'),
  (10, 4, 'moyen', 'B2', 'Interroger plusieurs suspects et croiser les indices', '{"synopsis": "Trois interrogatoires courts et successifs, où repérer les incohérences entre les déclarations est la clé."}'),
  (10, 5, 'moyen', 'B2', 'Une filature qui tourne mal', '{"synopsis": "Suivre discrètement un suspect en ville, gérer une situation qui dégénère quand le suspect semble remarquer la filature."}'),
  (10, 6, 'moyen', 'B2', 'Confronter un suspect avec des preuves', '{"synopsis": "Présenter les preuves accumulées pour obtenir des aveux ou au moins une réaction révélatrice."}'),
  (10, 7, 'long', 'B2', 'Une enquête complète avec plusieurs faux coupables', '{"synopsis": "Une enquête complète sur un vol de bijoux dans un manoir, avec au moins deux fausses pistes bien construites avant le vrai coupable — teste la capacité à garder une pensée critique tout au long d''un récit en anglais."}'),
  (10, 8, 'long', 'B2-C1', 'Une affaire qui implique un proche du personnage', '{"synopsis": "L''enquête mène vers un ami proche de l''utilisateur, créant un dilemme émotionnel et professionnel — gérer un conflit d''intérêt tout en menant l''enquête avec intégrité."}'),
  (10, 9, 'long', 'B2-C1', 'Un procès final où l''utilisateur plaide sa déduction', '{"synopsis": "Clôture de l''arc narratif policier — présenter les conclusions de l''enquête devant un tribunal et résister aux contre-arguments de la défense, un exercice d''argumentation formelle."}'),
  (11, 1, 'court', 'A2', 'Retrouver des amis dans la foule', '{"synopsis": "Coordonner un point de rencontre dans une foule dense par message/appel."}'),
  (11, 2, 'court', 'A2-B1', 'Acheter un billet à la dernière minute', '{"synopsis": "Le concert est presque complet — négocier pour obtenir un billet."}'),
  (11, 3, 'court', 'B1', 'Discuter avec un artiste local', '{"synopsis": "Engager une conversation intéressante avec un artisan présent au festival."}'),
  (11, 4, 'moyen', 'B1', 'Organiser sa journée entre plusieurs concerts', '{"synopsis": "Deux concerts intéressants ont lieu en même temps sur des scènes différentes — négocier avec Theo comment répartir la journée."}'),
  (11, 5, 'moyen', 'B1', 'Gérer un objet perdu pendant l''événement', '{"synopsis": "Perdre son téléphone dans la foule et suivre la procédure pour tenter de le récupérer."}'),
  (11, 6, 'moyen', 'A2-B1', 'Une rencontre qui devient amicale', '{"synopsis": "Une conversation spontanée dans la file d''attente qui débouche sur une nouvelle amitié."}'),
  (11, 7, 'long', 'B1-B2', 'Un festival sur plusieurs jours avec des rebondissements', '{"synopsis": "Trois jours de festival narrés en actes successifs, avec des imprévus à gérer collectivement (météo, changement de programmation, fatigue du groupe)."}'),
  (11, 8, 'long', 'B1-B2', 'Bénévolat sur l''événement avec responsabilités', '{"synopsis": "L''utilisateur est bénévole à l''accueil d''un festival, gérant plusieurs situations avec le public au fil de la journée."}'),
  (11, 9, 'long', 'B1-B2', 'Un incident à gérer en tant que spectateur impliqué', '{"synopsis": "Un mouvement de foule crée une situation de stress près de la scène principale — l''utilisateur doit garder son calme, aider si besoin, et communiquer clairement avec la sécurité."}'),
  (12, 1, 'court', 'A2', 'Suivre une visite guidée courte', '{"synopsis": "Suivre une visite guidée et poser une question simple."}'),
  (12, 2, 'court', 'A2-B1', 'Poser une question sur une œuvre', '{"synopsis": "S''intéresser à une sculpture et engager la conversation avec le médiateur."}'),
  (12, 3, 'court', 'A2', 'Acheter un billet combiné', '{"synopsis": "Choisir entre un billet simple et un billet combiné avec une exposition temporaire."}'),
  (12, 4, 'moyen', 'B1', 'Une visite libre avec un audioguide interactif', '{"synopsis": "Naviguer dans le musée en autonomie, en choisissant quelles salles explorer selon ses intérêts."}'),
  (12, 5, 'moyen', 'B1-B2', 'Une discussion avec un conservateur passionné', '{"synopsis": "Une rencontre fortuite avec le conservateur qui propose de partager des anecdotes exclusives sur une pièce rare."}'),
  (12, 6, 'moyen', 'B1', 'Participer à un atelier ponctuel', '{"synopsis": "Un atelier de calligraphie ou de restauration miniature proposé aux visiteurs — suivre les instructions et interagir avec le groupe."}'),
  (12, 7, 'long', 'B1-B2', 'Une exposition immersive avec plusieurs salles thématiques', '{"synopsis": "Une exposition immersive à parcourir en plusieurs salles thématiques liées, chacune avec ses propres interactions et son propre contenu narratif."}'),
  (12, 8, 'long', 'B1-B2', 'Une chasse au trésor culturelle dans le musée', '{"synopsis": "Une chasse au trésor pédagogique dans le musée, résolvant des énigmes culturelles pour progresser, avec un léger esprit de compétition amicale."}'),
  (12, 9, 'long', 'B2-C1', 'Un débat historique animé avec un guide', '{"synopsis": "Le guide propose un débat ouvert sur l''interprétation d''un événement historique controversé présenté dans l''exposition — teste l''argumentation nuancée sur un sujet complexe."}'),
  (13, 1, 'court', 'B1', 'Se présenter à un inconnu lors d''un cocktail', '{"synopsis": "Engager une première conversation de networking naturelle."}'),
  (13, 2, 'court', 'A2-B1', 'Échanger une carte de visite', '{"synopsis": "Clôturer un échange en proposant un contact professionnel."}'),
  (13, 3, 'court', 'B1', 'Poser une question après une conférence', '{"synopsis": "Poser une question pertinente pendant la session de questions-réponses."}'),
  (13, 4, 'moyen', 'B1-B2', 'Naviguer une soirée networking avec plusieurs interlocuteurs', '{"synopsis": "Enchaîner plusieurs conversations courtes dans une soirée networking, en gérant les transitions poliment."}'),
  (13, 5, 'moyen', 'B1-B2', 'Participer à un panel de questions-réponses', '{"synopsis": "L''utilisateur est sollicité pour partager une expérience personnelle pendant un panel ouvert."}'),
  (13, 6, 'moyen', 'B2', 'Proposer une collaboration', '{"synopsis": "Repérer une opportunité de collaboration et la proposer avec tact, sans paraître trop insistant."}'),
  (13, 7, 'long', 'B2', 'Une conférence sur deux jours avec plusieurs rencontres clés', '{"synopsis": "Une conférence professionnelle complète sur deux jours, où les rencontres du premier jour influencent les opportunités du second."}'),
  (13, 8, 'long', 'B2-C1', 'Négocier un partenariat lors de l''événement', '{"synopsis": "Une rencontre de networking débouche sur une vraie négociation de partenariat commercial informelle, à mener avec tact dans un cadre social plutôt qu''une salle de réunion."}'),
  (13, 9, 'long', 'B2-C1', 'Présenter son propre projet devant un public', '{"synopsis": "L''utilisateur présente son propre projet ou son entreprise (pitch) devant un public de la conférence, gère les questions et une objection difficile."}'),
  (14, 1, 'court', 'B1', 'Louer une voiture et comprendre le contrat', '{"synopsis": "Comprendre les options d''assurance et les conditions du contrat de location."}'),
  (14, 2, 'court', 'A2', 'Commander dans un diner américain', '{"synopsis": "Vivre l''expérience typique d''un diner américain, avec son vocabulaire propre."}'),
  (14, 3, 'court', 'A2', 'Demander son chemin sur une aire d''autoroute', '{"synopsis": "S''orienter après une sortie d''autoroute manquée."}'),
  (14, 4, 'moyen', 'B1-B2', 'Une étape imprévue (panne, détour) à gérer', '{"synopsis": "La voiture tombe en panne sur une route isolée — gérer la situation avec le garagiste local."}'),
  (14, 5, 'moyen', 'B1', 'Rencontrer des locaux dans une petite ville', '{"synopsis": "Une halte dans une petite ville typique mène à une rencontre chaleureuse avec des habitants curieux des voyageurs étrangers."}'),
  (14, 6, 'moyen', 'A2-B1', 'Réserver un motel en dernière minute', '{"synopsis": "Trouver un hébergement tard le soir après une longue journée de route."}'),
  (14, 7, 'long', 'B2', 'Un road trip complet sur plusieurs villes avec péripéties', '{"synopsis": "Un road trip narré sur plusieurs étapes (3-4 villes), combinant logistique, rencontres, et gestion d''imprévus sur la durée."}'),
  (14, 8, 'long', 'B1-B2', 'Une amitié qui se noue en chemin', '{"synopsis": "Une rencontre fortuite avec un autre voyageur qui partage une partie du trajet, développant une amitié au fil de plusieurs échanges pendant le voyage."}'),
  (14, 9, 'long', 'B2', 'Un imprévu majeur à résoudre entièrement en anglais', '{"synopsis": "Un accident mineur de la route (accrochage sans gravité) doit être géré de bout en bout — constat, échange avec l''autre conducteur, appel à l''assurance, tout en anglais et sous stress."}'),
  (15, 1, 'court', 'A2', 'Prendre le métro londonien', '{"synopsis": "Comprendre le système de l''Underground et acheter le bon ticket."}'),
  (15, 2, 'court', 'A2-B1', 'Commander dans un pub', '{"synopsis": "Vivre l''expérience du pub anglais, avec ses codes (commander au comptoir, pas de service à table)."}'),
  (15, 3, 'court', 'A1-A2', 'Demander l''heure d''ouverture d''un monument', '{"synopsis": "Se renseigner sur les horaires d''un monument avant de s''y rendre."}'),
  (15, 4, 'moyen', 'B1', 'Une journée touristique avec plusieurs arrêts et choix d''itinéraire', '{"synopsis": "Organiser une journée complète de tourisme entre plusieurs lieux emblématiques, en gérant le temps et les priorités avec Alice."}'),
  (15, 5, 'moyen', 'B1-B2', 'Une rencontre avec un Londonien dans un pub', '{"synopsis": "Une conversation informelle au pub qui permet de découvrir la ville sous un angle plus local et authentique."}'),
  (15, 6, 'moyen', 'A2-B1', 'Un imprévu météo à gérer', '{"synopsis": "Une pluie soudaine et typiquement londonienne bouscule les plans de la journée — s''adapter avec humour et pragmatisme."}'),
  (15, 7, 'long', 'B1-B2', 'Un séjour complet d''une semaine avec plusieurs journées thématiques', '{"synopsis": "Un séjour complet d''une semaine à Londres narré en actes correspondant à différentes journées thématiques, avec des enjeux narratifs qui évoluent au fil du séjour."}'),
  (15, 8, 'long', 'B1-B2', 'Se perdre et retrouver son chemin en interagissant avec plusieurs habitants', '{"synopsis": "Perdu dans un quartier résidentiel londonien loin des zones touristiques, l''utilisateur doit demander son chemin à plusieurs reprises, chaque interaction ayant sa propre tonalité."}'),
  (15, 9, 'long', 'B1-B2', 'Un événement local (marché, festival de quartier) à vivre de bout en bout', '{"synopsis": "Découvrir un marché ou festival de quartier authentique (type Borough Market ou Notting Hill Carnival) et vivre une expérience culturelle complète du début à la fin."}')
) as v(theme_position, scenario_position, format, cecr_level, title, content)
  on st.position = v.theme_position;
