-- ============================================
-- LUMA — Thématique 17 : Sport (complète)
-- ============================================

with th as (select id from scenario_themes where position = 17 and language_id = (select id from languages where code = 'en'))
insert into scenarios (theme_id, format, cecr_level, title, content, is_playable)
select th.id, 'court', 'A2', 'S''inscrire dans une salle de sport', '{"characters": {"staff": "l''employé de la salle"}, "start_node": "n1", "nodes": {"n1": {"speaker": "staff", "text": "Welcome! Are you looking for a monthly or annual membership?", "text_fr": "Bienvenue ! Vous cherchez un abonnement mensuel ou annuel ?", "choices": [{"text": "Monthly, I want to try it out first.", "next": "end_monthly"}, {"text": "Do you offer a free trial day?", "next": "n2"}]}, "n2": {"speaker": "staff", "text": "Yes, we do! You can try a full day for free.", "text_fr": "Oui, tout à fait ! Vous pouvez essayer une journée complète gratuitement.", "choices": [{"text": "Perfect, I''ll start with that.", "next": "end_trial"}]}, "end_monthly": {"speaker": "staff", "text": "Great, here''s your membership card, welcome to the gym!", "text_fr": "Parfait, voici votre carte d''adhésion, bienvenue à la salle !", "end": true, "ending_label": "Inscription réussie 🏋️"}, "end_trial": {"speaker": "staff", "text": "Enjoy your free day, let me know if you have questions!", "text_fr": "Profitez bien de votre journée gratuite, dites-moi si vous avez des questions !", "end": true, "ending_label": "Essai gratuit obtenu ✅"}}}'::jsonb, true from th;

with th as (select id from scenario_themes where position = 17 and language_id = (select id from languages where code = 'en'))
insert into scenarios (theme_id, format, cecr_level, title, content, is_playable)
select th.id, 'court', 'A2-B1', 'Discuter des règles d''un match avec un ami', '{"characters": {"friend": "ton ami"}, "start_node": "n1", "nodes": {"n1": {"speaker": "friend", "text": "Wait, why did the referee stop the game there?", "text_fr": "Attends, pourquoi l''arbitre a arrêté le match là ?", "choices": [{"text": "That was offside, the player was ahead of the last defender.", "next": "end_explained"}, {"text": "Honestly, I''m not totally sure either.", "next": "n2"}]}, "n2": {"speaker": "friend", "text": "Let''s look it up together then, I''m curious now.", "text_fr": "Cherchons ensemble alors, je suis curieux maintenant.", "choices": [{"text": "Good idea, let''s check the replay.", "next": "end_together"}]}, "end_explained": {"speaker": "friend", "text": "Ah, that makes sense now, thanks for explaining!", "text_fr": "Ah, ça a du sens maintenant, merci d''avoir expliqué !", "end": true, "ending_label": "Règle bien expliquée ⚽"}, "end_together": {"speaker": "friend", "text": "Got it now — offside, exactly what you thought!", "text_fr": "Compris maintenant — hors-jeu, exactement ce que tu pensais !", "end": true, "ending_label": "Règle comprise ensemble ⚽"}}}'::jsonb, true from th;

with th as (select id from scenario_themes where position = 17 and language_id = (select id from languages where code = 'en'))
insert into scenarios (theme_id, format, cecr_level, title, content, is_playable)
select th.id, 'court', 'A2-B1', 'Une blessure mineure à l''entraînement', '{"characters": {"coach": "l''entraîneur"}, "start_node": "n1", "nodes": {"n1": {"speaker": "coach", "text": "Are you okay? That looked like a hard fall.", "text_fr": "Ça va ? Ça avait l''air d''une chute difficile.", "choices": [{"text": "I''m fine, just twisted my ankle a little.", "next": "n2"}, {"text": "It hurts more than I expected, actually.", "next": "n2b"}]}, "n2": {"speaker": "coach", "text": "Let''s ice it just in case, better safe than sorry.", "text_fr": "Mettons de la glace au cas où, mieux vaut prévenir que guérir.", "choices": [{"text": "Good idea, thanks for checking on me.", "next": "end_minor"}]}, "n2b": {"speaker": "coach", "text": "Let''s get that looked at by our physio right away.", "text_fr": "Faisons vérifier ça par notre kiné tout de suite.", "choices": [{"text": "Okay, better to be careful.", "next": "end_checked"}]}, "end_minor": {"speaker": "coach", "text": "You''ll be back on the field in no time.", "text_fr": "Tu seras de retour sur le terrain en un rien de temps.", "end": true, "ending_label": "Petite blessure gérée ✅"}, "end_checked": {"speaker": "coach", "text": "Good call getting it checked, health comes first.", "text_fr": "Bien joué de faire vérifier ça, la santé passe avant tout.", "end": true, "ending_label": "Précaution prise sérieusement 🩹"}}}'::jsonb, true from th;

with th as (select id from scenario_themes where position = 17 and language_id = (select id from languages where code = 'en'))
insert into scenarios (theme_id, format, cecr_level, title, content, is_playable)
select th.id, 'moyen', 'B1', 'Un essai pour rejoindre une équipe locale', '{"characters": {"coach": "l''entraîneur de l''équipe"}, "start_node": "n1", "nodes": {"n1": {"speaker": "coach", "text": "Welcome to tryouts! What position do you usually play?", "text_fr": "Bienvenue aux essais ! Quel poste jouez-vous habituellement ?", "choices": [{"text": "Midfield, I like controlling the pace of the game.", "next": "n2"}, {"text": "Honestly, I''m flexible, wherever the team needs me.", "next": "n2b"}]}, "n2": {"speaker": "coach", "text": "Good, we actually need more depth there. Let''s see what you''ve got.", "text_fr": "Bien, on a justement besoin de plus de profondeur là. Voyons ce que vous avez.", "choices": [{"text": "(play with focus and confidence during the tryout)", "next": "n3"}]}, "n2b": {"speaker": "coach", "text": "I appreciate that flexibility, it''s valuable for a squad.", "text_fr": "J''apprécie cette flexibilité, c''est précieux pour une équipe.", "choices": [{"text": "(play with focus and confidence during the tryout)", "next": "n3"}]}, "n3": {"speaker": "coach", "text": "That was a strong session. We''d like to offer you a spot on the team.", "text_fr": "C''était une session solide. On aimerait vous offrir une place dans l''équipe.", "choices": [{"text": "That means a lot, thank you, I''m in!", "next": "end_joined"}]}, "end_joined": {"speaker": "coach", "text": "Welcome to the team, first training is Tuesday!", "text_fr": "Bienvenue dans l''équipe, premier entraînement mardi !", "end": true, "ending_label": "Équipe rejointe 🏆"}}}'::jsonb, true from th;

with th as (select id from scenario_themes where position = 17 and language_id = (select id from languages where code = 'en'))
insert into scenarios (theme_id, format, cecr_level, title, content, is_playable)
select th.id, 'moyen', 'B1', 'Suivre un cours collectif pour la première fois', '{"characters": {"instructor": "l''animatrice du cours"}, "start_node": "n1", "nodes": {"n1": {"speaker": "instructor", "text": "First time in a spin class? Don''t worry, go at your own pace.", "text_fr": "Première fois en cours de spinning ? Ne t''inquiète pas, va à ton propre rythme.", "choices": [{"text": "Thanks, I''m a bit nervous but excited to try.", "next": "n2"}, {"text": "I''ll do my best to keep up with everyone.", "next": "n2b"}]}, "n2": {"speaker": "instructor", "text": "That''s the spirit! Everyone here started as a beginner too.", "text_fr": "Voilà le bon esprit ! Tout le monde ici a commencé en débutant aussi.", "choices": [{"text": "That''s reassuring, thank you.", "next": "n3"}]}, "n2b": {"speaker": "instructor", "text": "No need to keep up with anyone, this is about your own progress.", "text_fr": "Pas besoin de suivre qui que ce soit, il s''agit de ta propre progression.", "choices": [{"text": "That''s a good mindset, I''ll remember that.", "next": "n3"}]}, "n3": {"speaker": "instructor", "text": "(after class) You did amazing for a first timer!", "text_fr": "(après le cours) Tu as été génial pour une première fois !", "choices": [{"text": "Thank you, I really enjoyed it, I''ll be back!", "next": "end_success"}]}, "end_success": {"speaker": "instructor", "text": "Can''t wait to see you at the next class!", "text_fr": "J''ai hâte de te revoir au prochain cours !", "end": true, "ending_label": "Premier cours réussi 🚴"}}}'::jsonb, true from th;

with th as (select id from scenario_themes where position = 17 and language_id = (select id from languages where code = 'en'))
insert into scenarios (theme_id, format, cecr_level, title, content, is_playable)
select th.id, 'moyen', 'B1-B2', 'Regarder un match dans un pub sportif', '{"characters": {"stranger": "un supporter à côté de toi"}, "start_node": "n1", "nodes": {"n1": {"speaker": "stranger", "text": "Come on, that should''ve been a penalty! Did you see that?", "text_fr": "Allez, ça aurait dû être un penalty ! T''as vu ça ?", "choices": [{"text": "I know, right? The referee completely missed it.", "next": "n2"}, {"text": "Honestly, I think it was a fair call, no contact really.", "next": "n2b"}]}, "n2": {"speaker": "stranger", "text": "Exactly! Fans like you get it. Which team are you supporting?", "text_fr": "Exactement ! Les fans comme toi comprennent. Tu supportes quelle équipe ?", "choices": [{"text": "I''m actually neutral tonight, just enjoying the game.", "next": "end_bonded"}]}, "n2b": {"speaker": "stranger", "text": "Ha, fair point actually, I might be a bit biased!", "text_fr": "Ha, bon point en fait, je suis peut-être un peu partial !", "choices": [{"text": "Happens to all of us with our team!", "next": "end_bonded"}]}, "end_bonded": {"speaker": "stranger", "text": "Great chatting with a fellow football fan, cheers!", "text_fr": "Sympa de discuter avec un autre fan de foot, santé !", "end": true, "ending_label": "Soirée match conviviale 🍺⚽"}}}'::jsonb, true from th;

with th as (select id from scenario_themes where position = 17 and language_id = (select id from languages where code = 'en'))
insert into scenarios (theme_id, format, cecr_level, title, content, is_playable)
select th.id, 'long', 'B2', 'Préparer et courir un marathon', '{"characters": {"trainer": "ton coach de course", "runner": "un autre coureur"}, "start_node": "n1", "nodes": {"n1": {"speaker": "trainer", "text": "Twelve weeks until race day. Ready to commit to the training plan?", "text_fr": "Douze semaines avant la course. Prêt à t''engager dans le plan d''entraînement ?", "choices": [{"text": "Absolutely, I''ve been waiting for this challenge.", "next": "n2"}]}, "n2": {"speaker": "trainer", "text": "(weeks later) Your long runs are improving fast, how''s your body feeling?", "text_fr": "(semaines plus tard) Tes longues sorties s''améliorent vite, comment se sent ton corps ?", "choices": [{"text": "Tired but strong, I really feel the progress.", "next": "n3"}, {"text": "Honestly, my knees have been a bit sore.", "next": "n3b"}]}, "n3": {"speaker": "trainer", "text": "That''s exactly what we want to hear, keep it up.", "text_fr": "C''est exactement ce qu''on veut entendre, continue comme ça.", "choices": [{"text": "Will do, feeling ready for race day.", "next": "n4"}]}, "n3b": {"speaker": "trainer", "text": "Let''s adjust your training load a bit to protect your joints.", "text_fr": "Ajustons un peu ta charge d''entraînement pour protéger tes articulations.", "choices": [{"text": "Good idea, better safe for race day.", "next": "n4"}]}, "n4": {"speaker": "runner", "text": "(race day, at mile 20) You doing okay? This is the tough part.", "text_fr": "(jour de la course, au 32e km) Ça va ? C''est la partie difficile.", "choices": [{"text": "Hanging in there, let''s push through together.", "next": "end_finish"}]}, "end_finish": {"speaker": "runner", "text": "We did it! Crossing that finish line together!", "text_fr": "On l''a fait ! On franchit la ligne d''arrivée ensemble !", "end": true, "ending_label": "Marathon terminé 🏅"}}}'::jsonb, true from th;

with th as (select id from scenario_themes where position = 17 and language_id = (select id from languages where code = 'en'))
insert into scenarios (theme_id, format, cecr_level, title, content, is_playable)
select th.id, 'long', 'B1-B2', 'Une saison complète avec une équipe amateur', '{"characters": {"captain": "le capitaine de l''équipe"}, "start_node": "n1", "nodes": {"n1": {"speaker": "captain", "text": "First match of the season tomorrow, nervous?", "text_fr": "Premier match de la saison demain, nerveux ?", "choices": [{"text": "A little, but mostly excited to finally play.", "next": "n2"}]}, "n2": {"speaker": "captain", "text": "(after losing the first match) Tough start, but we''ll bounce back.", "text_fr": "(après avoir perdu le premier match) Début difficile, mais on va rebondir.", "choices": [{"text": "Agreed, let''s analyze what went wrong and improve.", "next": "n3"}]}, "n3": {"speaker": "captain", "text": "(mid-season) We''re on a winning streak now, great teamwork lately!", "text_fr": "(mi-saison) On enchaîne les victoires maintenant, super travail d''équipe dernièrement !", "choices": [{"text": "The chemistry has really come together.", "next": "n4"}]}, "n4": {"speaker": "captain", "text": "(final match) This is it, the championship decider!", "text_fr": "(match final) On y est, le match décisif du championnat !", "choices": [{"text": "Let''s give it everything we''ve got.", "next": "end_champions"}]}, "end_champions": {"speaker": "captain", "text": "We''re champions! What a season this has been!", "text_fr": "On est champions ! Quelle saison ça a été !", "end": true, "ending_label": "Saison couronnée de succès 🏆"}}}'::jsonb, true from th;

with th as (select id from scenario_themes where position = 17 and language_id = (select id from languages where code = 'en'))
insert into scenarios (theme_id, format, cecr_level, title, content, is_playable)
select th.id, 'long', 'B2-C1', 'Un entretien avec un coach sportif professionnel', '{"characters": {"coach": "un coach professionnel"}, "start_node": "n1", "nodes": {"n1": {"speaker": "coach", "text": "So, what''s your main goal with training — performance, health, or both?", "text_fr": "Alors, quel est ton objectif principal avec l''entraînement — performance, santé, ou les deux ?", "choices": [{"text": "Mainly performance, I want to compete at a higher level.", "next": "n2"}, {"text": "A balance of both, I want to stay fit long-term.", "next": "n2b"}]}, "n2": {"speaker": "coach", "text": "Then we''ll need a structured plan with periodized intensity.", "text_fr": "Alors il nous faudra un plan structuré avec une intensité périodisée.", "choices": [{"text": "I''m ready to commit to whatever it takes.", "next": "n3"}]}, "n2b": {"speaker": "coach", "text": "Smart approach, sustainability matters more than short bursts of intensity.", "text_fr": "Approche intelligente, la durabilité compte plus que des pics d''intensité courts.", "choices": [{"text": "That aligns with what I''m looking for, yes.", "next": "n3"}]}, "n3": {"speaker": "coach", "text": "Let''s also talk nutrition and recovery — they''re just as important as training.", "text_fr": "Parlons aussi nutrition et récupération — elles sont tout aussi importantes que l''entraînement.", "choices": [{"text": "I''ve been neglecting recovery honestly, good point.", "next": "n4"}]}, "n4": {"speaker": "coach", "text": "We''ll build that into your plan then. I think we''ll work well together.", "text_fr": "On intégrera ça dans ton plan alors. Je pense qu''on va bien travailler ensemble.", "choices": [{"text": "I''m looking forward to this journey.", "next": "end_partnership"}]}, "end_partnership": {"speaker": "coach", "text": "Let''s get started — your first session is Monday.", "text_fr": "C''est parti — ta première séance est lundi.", "end": true, "ending_label": "Partenariat coach établi 💪"}}}'::jsonb, true from th;
