-- ============================================
-- LUMA — Treasure Island Tome 2 : Chapitres VII-XI (Bristol, Long John Silver, le tonneau de pommes)
-- Texte original, domaine public
-- ============================================


with s as (select id from books where title = 'Treasure Island' and is_series = true),
     lang as (select id from languages where code = 'en')
insert into books (language_id, title, theme, description, cecr_level, cover_emoji, total_pages, position, series_id, volume_number)
select lang.id, 'Tome 2 : Le cuisinier de bord', 'Classique • Robert Louis Stevenson (1883)', 'Jim rencontre le charismatique cuisinier de bord Long John Silver, l''Hispaniola prend la mer, et Jim surprend un terrible complot de mutinerie caché dans un tonneau de pommes.', 'B1-B2', '🍎', 5, 2, s.id, 2
from lang, s;


with b as (select id from books where title = 'Tome 2 : Le cuisinier de bord' and series_id = (select id from books where title = 'Treasure Island' and is_series = true))
insert into book_pages (book_id, page_number, sentences)
select b.id, 1, '[{"en": "It was longer than the squire imagined ere we were ready for the sea. I lived on at the hall, full of sea-dreams and charming anticipations of strange islands and adventures.", "fr": "Ce fut plus long que le châtelain ne l''avait imaginé avant que nous soyons prêts pour la mer. Je vivais au manoir, plein de rêves de mer et de charmantes anticipations d''îles étranges et d''aventures."}, {"en": "A letter arrived from Bristol: ''The ship is bought and fitted. You never imagined a sweeter schooner; name, Hispaniola.''", "fr": "Une lettre arriva de Bristol : ''Le navire est acheté et équipé. Vous n''avez jamais imaginé une plus jolie goélette ; son nom, l''Hispaniola.''"}, {"en": "The squire wrote of finding a ship''s cook by chance: ''Long John Silver, he is called, and has lost a leg... I thought I had only found a cook, but it was a crew I had discovered.''", "fr": "Le châtelain écrivait avoir trouvé un cuisinier de navire par hasard : ''On l''appelle Long John Silver, et il a perdu une jambe... Je pensais n''avoir trouvé qu''un cuisinier, mais c''est un équipage que j''avais découvert.''"}, {"en": "You can fancy the excitement into which that letter put me. The next morning, Redruth and I set out on foot for Bristol.", "fr": "Vous pouvez imaginer l''excitation dans laquelle cette lettre me plongea. Le lendemain matin, Redruth et moi partîmes à pied pour Bristol."}, {"en": "The smell of tar and salt was something new to me. I was going to sea myself, bound for an unknown island, to seek for buried treasure!", "fr": "L''odeur du goudron et du sel était nouvelle pour moi. J''allais moi-même prendre la mer, en route vers une île inconnue, à la recherche d''un trésor enfoui !"}, {"en": "We met Squire Trelawney, dressed like a sea-officer. ''Sail!'' says he. ''We sail tomorrow!''", "fr": "Nous rencontrâmes le châtelain Trelawney, habillé comme un officier de marine. ''Naviguer !'' dit-il. ''Nous partons demain !''"}]'::jsonb from b;


with b as (select id from books where title = 'Tome 2 : Le cuisinier de bord' and series_id = (select id from books where title = 'Treasure Island' and is_series = true))
insert into book_pages (book_id, page_number, sentences)
select b.id, 2, '[{"en": "The squire gave me a note for John Silver at the sign of the Spy-glass tavern. A man came out on a crutch, hopping about like a bird.", "fr": "Le châtelain me donna un billet pour John Silver, à l''enseigne de la taverne du Longue-Vue. Un homme sortit sur une béquille, sautillant comme un oiseau."}, {"en": "His left leg was cut off close by the hip. He was very tall and strong, with a face as big as a ham, intelligent and smiling.", "fr": "Sa jambe gauche était coupée près de la hanche. Il était très grand et fort, avec un visage large comme un jambon, intelligent et souriant."}, {"en": "One customer suddenly rose and made for the door. I recognized him at a glance. ''Stop him! It''s Black Dog!'' I cried.", "fr": "Un client se leva soudainement et se dirigea vers la porte. Je le reconnus au premier coup d''œil. ''Arrêtez-le ! C''est Chien Noir !'' m''écriai-je."}, {"en": "Silver seemed convincingly astonished, and sent two men running after Black Dog, though they lost him in the crowd.", "fr": "Silver parut authentiquement stupéfait, et envoya deux hommes courir après Chien Noir, bien qu''ils le perdissent dans la foule."}, {"en": "''You and me should get on well, Hawkins,'' said Silver, wiping tears of laughter from his cheeks after ''forgetting'' Black Dog''s unpaid bill.", "fr": "''Vous et moi devrions bien nous entendre, Hawkins,'' dit Silver, essuyant des larmes de rire de ses joues après avoir ''oublié'' l''addition impayée de Chien Noir."}, {"en": "At the inn, Dr. Livesey said, ''I don''t put much faith in your discoveries, but I will say this, John Silver suits me.''", "fr": "À l''auberge, le Dr Livesey dit : ''Je ne fais pas grande confiance à vos découvertes, mais je dirai ceci : John Silver me convient.''"}]'::jsonb from b;


with b as (select id from books where title = 'Tome 2 : Le cuisinier de bord' and series_id = (select id from books where title = 'Treasure Island' and is_series = true))
insert into book_pages (book_id, page_number, sentences)
select b.id, 3, '[{"en": "Aboard the Hispaniola, I soon observed that things were not the same between Mr. Trelawney and Captain Smollett.", "fr": "À bord de l''Hispaniola, je remarquai bientôt que les choses n''étaient pas les mêmes entre M. Trelawney et le capitaine Smollett."}, {"en": "''I don''t like this cruise; I don''t like the men; and I don''t like my officer,'' the captain said bluntly.", "fr": "''Je n''aime pas cette croisière ; je n''aime pas les hommes ; et je n''aime pas mon officier,'' dit le capitaine sans détour."}, {"en": "''There''s been too much blabbing already,'' the captain warned. ''I hear you have a map of an island where treasure is hidden.''", "fr": "''Il y a déjà eu trop de bavardages,'' avertit le capitaine. ''J''entends dire que vous avez une carte d''une île où un trésor est caché.''"}, {"en": "The captain asked that the powder and arms be moved under the cabin, away from the crew, fearing a mutiny.", "fr": "Le capitaine demanda que la poudre et les armes soient déplacées sous la cabine, loin de l''équipage, craignant une mutinerie."}, {"en": "Dr. Livesey agreed to the captain''s precautions, though the squire remained furious at being doubted.", "fr": "Le Dr Livesey accepta les précautions du capitaine, bien que le châtelain restât furieux d''être ainsi mis en doute."}, {"en": "When Silver saw the powder being moved, he simply said, ''Aye, aye, sir,'' and obediently returned to his galley.", "fr": "Quand Silver vit qu''on déplaçait la poudre, il dit simplement : ''À vos ordres, monsieur,'' et retourna docilement à sa cuisine."}]'::jsonb from b;


with b as (select id from books where title = 'Tome 2 : Le cuisinier de bord' and series_id = (select id from books where title = 'Treasure Island' and is_series = true))
insert into book_pages (book_id, page_number, sentences)
select b.id, 4, '[{"en": "As the anchor rose, Long John struck up the old song, and the whole crew bore chorus: ''Fifteen men on the dead man''s chest— Yo-ho-ho, and a bottle of rum!''", "fr": "Alors que l''ancre se levait, Long John entonna la vieille chanson, et tout l''équipage reprit en chœur : ''Quinze hommes sur le coffre du mort— Yo-ho-ho, et une bouteille de rhum !''"}, {"en": "Mr. Arrow, the mate, turned out worse than feared: he began appearing on deck drunk, though no one could discover where he got the drink.", "fr": "M. Arrow, le second, se révéla pire que redouté : il commença à apparaître sur le pont ivre, bien que personne ne pût découvrir où il se procurait l''alcool."}, {"en": "One dark night, with a heavy sea, Mr. Arrow disappeared entirely and was seen no more. ''Overboard!'' said the captain simply.", "fr": "Une nuit sombre, par forte mer, M. Arrow disparut entièrement et ne fut plus jamais revu. ''Passé par-dessus bord !'' dit simplement le capitaine."}, {"en": "Silver kept a parrot named Captain Flint in the galley, which he had taught to scream ''Pieces of eight! Pieces of eight!''", "fr": "Silver gardait un perroquet nommé Capitaine Flint dans la cuisine, qu''il avait dressé à crier ''Pièces de huit ! Pièces de huit !''"}, {"en": "To me, Silver was unweariedly kind, always glad to see me in the galley. I began to see that here was one of the best of possible shipmates.", "fr": "Envers moi, Silver était infatigablement gentil, toujours content de me voir dans la cuisine. Je commençai à croire que c''était l''un des meilleurs compagnons de bord possibles."}, {"en": "It was about the last day of our outward voyage. We were heading for the island with a bright lookout day and night.", "fr": "C''était à peu près le dernier jour de notre traversée. Nous voguions vers l''île avec une vigie active jour et nuit."}]'::jsonb from b;


with b as (select id from books where title = 'Tome 2 : Le cuisinier de bord' and series_id = (select id from books where title = 'Treasure Island' and is_series = true))
insert into book_pages (book_id, page_number, sentences)
select b.id, 5, '[{"en": "Wanting an apple, I climbed into the apple barrel on deck. Finding it nearly empty, I sat down inside just as a heavy man sat close by.", "fr": "Ayant envie d''une pomme, je grimpai dans le tonneau de pommes sur le pont. Le trouvant presque vide, je m''assis à l''intérieur juste au moment où un homme corpulent s''assit tout près."}, {"en": "It was Silver''s voice. Before I had heard a dozen words, I understood the lives of all the honest men aboard depended upon me alone.", "fr": "C''était la voix de Silver. Avant d''avoir entendu une dizaine de mots, je compris que la vie de tous les honnêtes hommes à bord dépendait de moi seul."}, {"en": "''Flint was cap''n; I was quartermaster,'' Silver was saying, boasting of his years as a pirate under the fearsome Captain Flint.", "fr": "''Flint était capitaine ; j''étais quartier-maître,'' disait Silver, se vantant de ses années de piraterie sous le redoutable capitaine Flint."}, {"en": "Silver was recruiting young Dick to join a mutiny, speaking of becoming ''gentlemen of fortune''—his polite term for pirates.", "fr": "Silver était en train de recruter le jeune Dick pour une mutinerie, parlant de devenir des ''gentlemen de fortune''—son terme poli pour désigner les pirates."}, {"en": "Israel Hands grew impatient: ''I want to go into that cabin. I want their pickles and wines.'' But Silver held firm control.", "fr": "Israel Hands devenait impatient : ''Je veux entrer dans cette cabine. Je veux leurs conserves et leurs vins.'' Mais Silver gardait un contrôle ferme."}, {"en": "''I mean this squire and doctor shall find the stuff, and help us get it aboard,'' Silver explained. ''Then we''ll see.'' I lay trembling in the barrel, having learned their terrible plan.", "fr": "''Je veux que ce châtelain et ce docteur trouvent le butin, et nous aident à le charger à bord,'' expliqua Silver. ''Ensuite, on verra.'' Je restai tremblant dans le tonneau, ayant appris leur terrible plan."}]'::jsonb from b;
