-- ============================================
-- LUMA — Scénarios jouables : Thématique 6 (Colocation) — complète
-- ============================================

update scenarios set content = '{"characters": {"roommate": "ton coloc Tom"}, "start_node": "n1", "nodes": {"n1": {"speaker": "roommate", "text": "Hey, could we set up a cleaning schedule? The kitchen''s been a mess.", "text_fr": "Hé, on pourrait mettre en place un planning ménage ? La cuisine est en désordre.", "choices": [{"text": "Good idea, how about we alternate weeks?", "next": "end_alternate"}, {"text": "Sure, what did you have in mind?", "next": "n2"}]}, "n2": {"speaker": "roommate", "text": "Maybe I do kitchen, you do bathroom, and we split common areas?", "text_fr": "Peut-être moi la cuisine, toi la salle de bain, et on partage les espaces communs ?", "choices": [{"text": "That works for me.", "next": "end_split"}]}, "end_alternate": {"speaker": "roommate", "text": "Perfect, let''s start this week.", "text_fr": "Parfait, on commence cette semaine.", "end": true, "ending_label": "Planning ménage fixé 🧹"}, "end_split": {"speaker": "roommate", "text": "Sounds fair to me, thanks for being flexible.", "text_fr": "Ça me semble juste, merci d''être flexible.", "end": true, "ending_label": "Répartition équitable ✅"}}}'::jsonb, is_playable = true
where title = 'Négocier le ménage'
  and theme_id = (select id from scenario_themes where position = 6 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"roommate": "ta coloc Lisa"}, "start_node": "n1", "nodes": {"n1": {"speaker": "roommate", "text": "Hi, I hope I didn''t wake you last night with the music.", "text_fr": "Salut, j''espère que je ne t''ai pas réveillé hier soir avec la musique.", "choices": [{"text": "Actually, yeah, could you keep it a bit lower after 11pm?", "next": "end_direct"}, {"text": "It''s okay, just try to be a bit more mindful next time.", "next": "end_soft"}]}, "end_direct": {"speaker": "roommate", "text": "Oh, I''m really sorry, I''ll be more careful.", "text_fr": "Oh, je suis vraiment désolé, je ferai plus attention.", "end": true, "ending_label": "Message clair et bien reçu ✅"}, "end_soft": {"speaker": "roommate", "text": "Thanks for understanding, I''ll keep it down.", "text_fr": "Merci de ta compréhension, je vais baisser le son.", "end": true, "ending_label": "Situation apaisée 😊"}}}'::jsonb, is_playable = true
where title = 'Se plaindre du bruit'
  and theme_id = (select id from scenario_themes where position = 6 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"roommate": "ton coloc Dan"}, "start_node": "n1", "nodes": {"n1": {"speaker": "roommate", "text": "I bought groceries again this week, should we split the cost?", "text_fr": "J''ai encore acheté les courses cette semaine, on partage le coût ?", "choices": [{"text": "Of course, how much do I owe you?", "next": "n2"}, {"text": "Maybe we should alternate who buys groceries instead.", "next": "end_alternate"}]}, "n2": {"speaker": "roommate", "text": "It came to about $40 total, so $20 each.", "text_fr": "Ça fait environ 40$ au total, donc 20$ chacun.", "choices": [{"text": "Here you go, thanks for handling it.", "next": "end_paid"}]}, "end_alternate": {"speaker": "roommate", "text": "That''s actually a great idea, less hassle for both of us.", "text_fr": "C''est une excellente idée, moins de tracas pour nous deux.", "end": true, "ending_label": "Nouveau système adopté ✅"}, "end_paid": {"speaker": "roommate", "text": "Thanks, appreciate it!", "text_fr": "Merci, j''apprécie !", "end": true, "ending_label": "Courses réglées 🛒"}}}'::jsonb, is_playable = true
where title = 'Partager les courses'
  and theme_id = (select id from scenario_themes where position = 6 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"current": "un coloc actuel"}, "start_node": "n1", "nodes": {"n1": {"speaker": "current", "text": "Welcome! So this would be your room, and we share the kitchen and living room.", "text_fr": "Bienvenue ! Voici ta chambre, et on partage la cuisine et le salon.", "choices": [{"text": "It looks great. What''s the vibe like here usually?", "next": "n2"}]}, "n2": {"speaker": "current", "text": "Pretty chill, we cook together sometimes but everyone respects each other''s space.", "text_fr": "Plutôt tranquille, on cuisine parfois ensemble mais tout le monde respecte l''espace des autres.", "choices": [{"text": "That sounds exactly like what I''m looking for.", "next": "n3"}, {"text": "How do you split bills and chores?", "next": "n3b"}]}, "n3": {"speaker": "current", "text": "Great, I think you''d fit right in here!", "text_fr": "Super, je pense que tu t''intégrerais très bien ici !", "choices": [{"text": "I''d love to move in, if that''s possible.", "next": "end_yes"}]}, "n3b": {"speaker": "current", "text": "We use an app to split bills evenly, and rotate chores weekly.", "text_fr": "On utilise une appli pour partager les factures équitablement, et on tourne les tâches chaque semaine.", "choices": [{"text": "That''s very organized, I like it.", "next": "end_yes"}]}, "end_yes": {"speaker": "current", "text": "Awesome, welcome to the flat!", "text_fr": "Génial, bienvenue dans l''appartement !", "end": true, "ending_label": "Nouvelle coloc trouvée 🏠"}}}'::jsonb, is_playable = true
where title = 'Une visite d''appartement en colocation'
  and theme_id = (select id from scenario_themes where position = 6 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"roommate": "ton coloc Ryan"}, "start_node": "n1", "nodes": {"n1": {"speaker": "roommate", "text": "I think the electricity bill is too high, are you leaving lights on?", "text_fr": "Je trouve la facture d''électricité trop élevée, tu laisses les lumières allumées ?", "choices": [{"text": "I don''t think so, but let''s check together to be sure.", "next": "n2"}, {"text": "Actually, I think it''s your gaming setup using more power.", "next": "n2b"}]}, "n2": {"speaker": "roommate", "text": "Fair enough, let''s go through the apartment.", "text_fr": "D''accord, faisons le tour de l''appartement.", "choices": [{"text": "Good idea, that''ll clear things up.", "next": "end_investigate"}]}, "n2b": {"speaker": "roommate", "text": "Hmm, that''s possible, I hadn''t thought of that.", "text_fr": "Hmm, c''est possible, je n''y avais pas pensé.", "choices": [{"text": "No hard feelings, let''s just figure it out together.", "next": "end_investigate"}]}, "end_investigate": {"speaker": "roommate", "text": "Thanks for staying calm about this, let''s find a fair solution.", "text_fr": "Merci d''être resté calme là-dessus, trouvons une solution équitable.", "end": true, "ending_label": "Conflit désamorcé 🤝"}}}'::jsonb, is_playable = true
where title = 'Régler un conflit sur les factures'
  and theme_id = (select id from scenario_themes where position = 6 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"newbie": "le nouveau coloc"}, "start_node": "n1", "nodes": {"n1": {"speaker": "newbie", "text": "Hi, I''m so excited to move in! Any house rules I should know?", "text_fr": "Salut, je suis ravi(e) d''emménager ! Il y a des règles à connaître ?", "choices": [{"text": "Just the basics — clean up after cooking, and quiet after 11pm.", "next": "n2"}]}, "n2": {"speaker": "newbie", "text": "Sounds totally reasonable, I can handle that.", "text_fr": "Ça me semble tout à fait raisonnable, je peux gérer ça.", "choices": [{"text": "Great, let me show you around the place.", "next": "end_welcome"}]}, "end_welcome": {"speaker": "newbie", "text": "Thanks, I already feel at home!", "text_fr": "Merci, je me sens déjà chez moi !", "end": true, "ending_label": "Accueil réussi 🏡"}}}'::jsonb, is_playable = true
where title = 'Accueillir un nouveau coloc'
  and theme_id = (select id from scenario_themes where position = 6 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"roommate": "ta coloc Mia"}, "start_node": "n1", "nodes": {"n1": {"speaker": "roommate", "text": "I''m honestly getting frustrated, it feels like I''m doing all the cleaning lately.", "text_fr": "Honnêtement je commence à être frustrée, j''ai l''impression de faire tout le ménage ces derniers temps.", "choices": [{"text": "You''re right, I''ve been slacking, I''m sorry.", "next": "n2"}, {"text": "I didn''t realize that, can we talk about it calmly?", "next": "n2b"}]}, "n2": {"speaker": "roommate", "text": "I appreciate you owning that. Let''s make a clearer schedule.", "text_fr": "J''apprécie que tu le reconnaisses. Faisons un planning plus clair.", "choices": [{"text": "Agreed, let''s write one up together tonight.", "next": "n3"}]}, "n2b": {"speaker": "roommate", "text": "Yes, I''d like that, I don''t want this to become resentment.", "text_fr": "Oui, j''aimerais ça, je ne veux pas que ça devienne du ressentiment.", "choices": [{"text": "Neither do I, let''s fix this together.", "next": "n3"}]}, "n3": {"speaker": "roommate", "text": "Thanks for hearing me out, I feel better already.", "text_fr": "Merci de m''avoir écoutée, je me sens déjà mieux.", "choices": [{"text": "I''m glad, we''re a good team.", "next": "end_resolved"}]}, "end_resolved": {"speaker": "roommate", "text": "We really are. Let''s keep communicating like this.", "text_fr": "C''est vrai. Continuons à communiquer comme ça.", "end": true, "ending_label": "Tension résolue en profondeur 💙"}}}'::jsonb, is_playable = true
where title = 'Une tension qui dégénère et se résout'
  and theme_id = (select id from scenario_themes where position = 6 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"roommate": "ton coloc Leo"}, "start_node": "n1", "nodes": {"n1": {"speaker": "roommate", "text": "Want to throw a party this Saturday? It''s been a while.", "text_fr": "Ça te dit d''organiser une fête samedi ? Ça fait longtemps.", "choices": [{"text": "Sure, but let''s warn the neighbors in advance.", "next": "n2"}, {"text": "I''m a bit worried about the mess afterward, honestly.", "next": "n2b"}]}, "n2": {"speaker": "roommate", "text": "Good call, I''ll drop a note in their mailboxes.", "text_fr": "Bonne idée, je vais mettre un mot dans leurs boîtes aux lettres.", "choices": [{"text": "Perfect, let''s plan it then.", "next": "n3"}]}, "n2b": {"speaker": "roommate", "text": "Fair point, let''s agree we both clean up together after.", "text_fr": "Bon point, mettons-nous d''accord pour nettoyer ensemble après.", "choices": [{"text": "Deal, that makes me feel better about it.", "next": "n3"}]}, "n3": {"speaker": "roommate", "text": "(the party happens, and the next morning...) Well, that got a bit wild!", "text_fr": "(la fête a lieu, et le lendemain matin...) Eh bien, ça a un peu dérapé !", "choices": [{"text": "It really did, let''s clean this up together like we planned.", "next": "end_cleaned"}]}, "end_cleaned": {"speaker": "roommate", "text": "Teamwork makes it go fast. Worth it though!", "text_fr": "Le travail d''équipe rend ça rapide. Ça valait le coup quand même !", "end": true, "ending_label": "Fête réussie, conséquences gérées 🎉"}}}'::jsonb, is_playable = true
where title = 'Organiser une fête et gérer les conséquences'
  and theme_id = (select id from scenario_themes where position = 6 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"roommate1": "coloc 1", "roommate2": "coloc 2"}, "start_node": "n1", "nodes": {"n1": {"speaker": "roommate1", "text": "So, the move is in two weeks. Who''s handling the moving truck?", "text_fr": "Alors, le déménagement est dans deux semaines. Qui s''occupe du camion ?", "choices": [{"text": "I can book it, I know a good rental place.", "next": "n2"}]}, "n2": {"speaker": "roommate2", "text": "Great, I''ll handle packing the kitchen stuff then.", "text_fr": "Super, je vais m''occuper d''emballer la cuisine alors.", "choices": [{"text": "Perfect, I''ll take care of the living room.", "next": "n3"}]}, "n3": {"speaker": "roommate1", "text": "Sounds like we''ve got a solid plan. Let''s make a shared checklist too.", "text_fr": "On dirait qu''on a un bon plan. Faisons aussi une liste partagée.", "choices": [{"text": "Good idea, I''ll set that up tonight.", "next": "end_organized"}]}, "end_organized": {"speaker": "roommate2", "text": "This is going to go so much smoother with a plan like this.", "text_fr": "Ça va être bien plus fluide avec un plan comme ça.", "end": true, "ending_label": "Déménagement bien organisé 📦"}}}'::jsonb, is_playable = true
where title = 'Un déménagement collectif à planifier'
  and theme_id = (select id from scenario_themes where position = 6 and language_id = (select id from languages where code = 'en'));
