-- ============================================
-- LUMA — Import d'un gros lot de nouvelles grilles (10 thèmes, A1 à C1)
-- Générées automatiquement puis vérifiées (pas de conflit de lettres)
-- ============================================

with lang as (select id from languages where code = 'en')
insert into word_puzzles (language_id, type, title, cecr_level, rows, cols, words)
select lang.id, v.type, v.title, v.cecr_level, v.rows, v.cols, v.words::jsonb from lang, (values
  ('crossword', 'Animaux', 'A1', 6, 5, '[{"answer": "HORSE", "clue": "Grand animal qu''on peut monter (large animal you can ride)", "direction": "across", "row": 2, "col": 0}, {"answer": "MOUSE", "clue": "Petit rongeur (small rodent)", "direction": "down", "row": 1, "col": 1}, {"answer": "BIRD", "clue": "Animal qui vole et pond des œufs (animal that flies and lays eggs)", "direction": "down", "row": 0, "col": 2}, {"answer": "FISH", "clue": "Animal qui nage et respire sous l''eau (animal that swims and breathes underwater)", "direction": "down", "row": 0, "col": 3}]'),
  ('fleche', 'Nourriture', 'A1', 4, 6, '[{"answer": "RICE", "clue": "Céréale blanche très cultivée en Asie (staple grain in Asia)", "direction": "across", "row": 1, "col": 0}, {"answer": "MEAT", "clue": "Viande en anglais", "direction": "down", "row": 0, "col": 3}, {"answer": "EGG", "clue": "Pondu par une poule (laid by a hen)", "direction": "across", "row": 1, "col": 3}, {"answer": "TEA", "clue": "Boisson chaude très populaire au Royaume-Uni (popular hot drink in the UK)", "direction": "across", "row": 3, "col": 3}, {"answer": "EAT", "clue": "Manger, en anglais", "direction": "down", "row": 1, "col": 3}]'),
  ('crossword', 'Famille', 'A1', 9, 7, '[{"answer": "BROTHER", "clue": "Garçon des mêmes parents que soi (male sibling)", "direction": "across", "row": 4, "col": 0}, {"answer": "MOTHER", "clue": "Parent féminin (female parent)", "direction": "down", "row": 3, "col": 2}, {"answer": "FATHER", "clue": "Parent masculin (male parent)", "direction": "down", "row": 2, "col": 3}, {"answer": "SISTER", "clue": "Fille des mêmes parents que soi (female sibling)", "direction": "down", "row": 0, "col": 5}, {"answer": "PARENT", "clue": "Père ou mère (mother or father)", "direction": "down", "row": 2, "col": 1}]'),
  ('fleche', 'Voyage', 'A2', 7, 7, '[{"answer": "TICKET", "clue": "Document nécessaire pour monter à bord (needed to board)", "direction": "across", "row": 2, "col": 1}, {"answer": "TRAIN", "clue": "Moyen de transport sur rails (transport on rails)", "direction": "down", "row": 2, "col": 1}, {"answer": "HOTEL", "clue": "Lieu où on dort en voyage (place to sleep while travelling)", "direction": "down", "row": 0, "col": 6}, {"answer": "TRIP", "clue": "Synonyme de voyage court (short journey)", "direction": "down", "row": 0, "col": 2}, {"answer": "MAP", "clue": "Sert à s''orienter (used to find your way)", "direction": "across", "row": 4, "col": 0}]'),
  ('crossword', 'Météo', 'A2', 4, 6, '[{"answer": "STORM", "clue": "Tempête violente (violent weather event)", "direction": "across", "row": 0, "col": 0}, {"answer": "RAIN", "clue": "Tombe du ciel quand il fait gris (falls from grey skies)", "direction": "down", "row": 0, "col": 3}, {"answer": "SNOW", "clue": "Blanc et froid en hiver (white and cold in winter)", "direction": "down", "row": 0, "col": 0}, {"answer": "WIND", "clue": "Fait bouger les feuilles (makes leaves move)", "direction": "across", "row": 2, "col": 2}, {"answer": "SUN", "clue": "Brille dans le ciel le jour (shines in the sky by day)", "direction": "across", "row": 3, "col": 1}]'),
  ('fleche', 'Travail', 'B1', 12, 7, '[{"answer": "MANAGER", "clue": "Responsable d''équipe (team leader)", "direction": "across", "row": 5, "col": 0}, {"answer": "MEETING", "clue": "Réunion professionnelle (professional gathering)", "direction": "down", "row": 5, "col": 0}, {"answer": "OFFICE", "clue": "Lieu de travail typique (typical workplace)", "direction": "down", "row": 0, "col": 5}, {"answer": "SALARY", "clue": "Rémunération mensuelle (monthly pay)", "direction": "down", "row": 4, "col": 1}, {"answer": "EMAIL", "clue": "Message électronique professionnel (professional electronic message)", "direction": "down", "row": 5, "col": 5}]'),
  ('crossword', 'Émotions', 'B1', 9, 6, '[{"answer": "AFRAID", "clue": "Qui a peur (scared)", "direction": "across", "row": 4, "col": 0}, {"answer": "HAPPY", "clue": "Content, joyeux (glad, joyful)", "direction": "down", "row": 3, "col": 0}, {"answer": "ANGRY", "clue": "En colère (furious)", "direction": "down", "row": 4, "col": 3}, {"answer": "PROUD", "clue": "Fier de soi (satisfied with achievement)", "direction": "down", "row": 3, "col": 2}, {"answer": "BORED", "clue": "Qui s''ennuie (feeling nothing interesting to do)", "direction": "down", "row": 0, "col": 5}]'),
  ('fleche', 'Maison', 'A2', 9, 7, '[{"answer": "KITCHEN", "clue": "Pièce où on cuisine (room for cooking)", "direction": "across", "row": 4, "col": 0}, {"answer": "WINDOW", "clue": "Laisse entrer la lumière (lets light in)", "direction": "down", "row": 3, "col": 1}, {"answer": "GARDEN", "clue": "Espace vert extérieur (outdoor green space)", "direction": "down", "row": 0, "col": 5}, {"answer": "DOOR", "clue": "S''ouvre pour entrer (opens to enter)", "direction": "across", "row": 6, "col": 1}, {"answer": "ROOF", "clue": "Protège la maison de la pluie (protects house from rain)", "direction": "across", "row": 7, "col": 0}]'),
  ('crossword', 'Sport', 'A2', 9, 9, '[{"answer": "TENNIS", "clue": "Sport avec une raquette et une balle jaune (racket sport)", "direction": "across", "row": 3, "col": 0}, {"answer": "SOCCER", "clue": "Sport le plus populaire au monde, avec un ballon rond (world''s most popular ball sport)", "direction": "down", "row": 3, "col": 5}, {"answer": "BOXING", "clue": "Sport de combat avec des gants (combat sport with gloves)", "direction": "down", "row": 0, "col": 4}, {"answer": "SWIM", "clue": "Se déplacer dans l''eau (move through water)", "direction": "across", "row": 3, "col": 5}, {"answer": "RUN", "clue": "Se déplacer vite à pied (move fast on foot)", "direction": "down", "row": 1, "col": 2}]'),
  ('crossword', 'Voyage avancé', 'B2', 8, 10, '[{"answer": "ARRIVE", "clue": "Le contraire de partir (opposite of depart)", "direction": "across", "row": 3, "col": 0}, {"answer": "DEPART", "clue": "Quitter un lieu, prendre son vol (leave, take off)", "direction": "down", "row": 2, "col": 5}, {"answer": "CANCEL", "clue": "Annuler un vol (call off a flight)", "direction": "down", "row": 2, "col": 0}, {"answer": "DELAY", "clue": "Retard d''un vol (flight being late)", "direction": "across", "row": 2, "col": 5}, {"answer": "BOARD", "clue": "Monter dans l''avion (get on the plane)", "direction": "down", "row": 0, "col": 1}]'),
  ('fleche', 'Vocabulaire avancé', 'C1', 9, 9, '[{"answer": "RELUCTANT", "clue": "Unwilling, hesitant to do something", "direction": "across", "row": 1, "col": 0}, {"answer": "RELIABLE", "clue": "Trustworthy, can be depended on", "direction": "down", "row": 1, "col": 0}, {"answer": "THOROUGH", "clue": "Complete and detailed, leaving nothing out", "direction": "down", "row": 1, "col": 5}, {"answer": "PERSUADE", "clue": "To convince someone to do something", "direction": "down", "row": 0, "col": 1}, {"answer": "CONCISE", "clue": "Short and clear, without unnecessary words", "direction": "down", "row": 1, "col": 4}]')
) as v(type, title, cecr_level, rows, cols, words);
