-- ============================================
-- LUMA — Scénarios jouables : Thématique 2 (Rendez-vous amoureux) — complète
-- ============================================

update scenarios set content = '{"characters": {"alex": "Alex (match)"}, "start_node": "n1", "nodes": {"n1": {"speaker": "alex", "text": "Profile: \"Hiking enthusiast, terrible cook trying to improve. Ask me about my last trail disaster.\"", "text_fr": "Profil : \"Passionné(e) de randonnée, cuisinier(ère) désastreux(se) qui essaie de s''améliorer. Demande-moi mon dernier désastre en rando.\"", "choices": [{"text": "Haha, I have to hear about this trail disaster.", "next": "end_playful"}, {"text": "I love hiking too! What''s your favorite trail?", "next": "end_classic"}, {"text": "Hi, how are you?", "next": "end_generic"}]}, "end_playful": {"speaker": "alex", "text": "Oh no, okay, buckle up — it involves a bear and my sandwich!", "text_fr": "Oh non, accroche-toi — ça implique un ours et mon sandwich !", "end": true, "ending_label": "Accroche réussie 🎉"}, "end_classic": {"speaker": "alex", "text": "I love the coastal trail near my place! You?", "text_fr": "J''adore le sentier côtier près de chez moi ! Et toi ?", "end": true, "ending_label": "Bonne conversation ✅"}, "end_generic": {"speaker": "alex", "text": "Good, thanks.", "text_fr": "Bien, merci.", "end": true, "ending_label": "Conversation un peu froide 😐"}}}'::jsonb, is_playable = true
where title = 'Premier message sur une appli de rencontre'
  and theme_id = (select id from scenario_themes where position = 2 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"alex": "Alex"}, "start_node": "n1", "nodes": {"n1": {"speaker": "alex", "text": "So, are you free this week? I know a nice little coffee place downtown.", "text_fr": "Alors, tu es libre cette semaine ? Je connais un joli café en centre-ville.", "choices": [{"text": "Sounds great, how about Thursday evening?", "next": "end_thursday"}, {"text": "I''d prefer somewhere quieter, if that''s okay.", "next": "n2b"}, {"text": "I''m actually pretty busy this week, could we do next week instead?", "next": "end_nextweek"}]}, "n2b": {"speaker": "alex", "text": "Sure, no problem — there''s a quiet tea house nearby too.", "text_fr": "Bien sûr, pas de souci — il y a aussi un salon de thé calme pas loin.", "choices": [{"text": "That sounds perfect.", "next": "end_teahouse"}]}, "end_thursday": {"speaker": "alex", "text": "Perfect, Thursday it is!", "text_fr": "Parfait, va pour jeudi !", "end": true, "ending_label": "Rendez-vous fixé 📅"}, "end_teahouse": {"speaker": "alex", "text": "Great, see you there!", "text_fr": "Génial, on se voit là-bas !", "end": true, "ending_label": "Rendez-vous fixé 📅"}, "end_nextweek": {"speaker": "alex", "text": "No worries, next week works too!", "text_fr": "Pas de souci, la semaine prochaine ça marche aussi !", "end": true, "ending_label": "Rendez-vous décalé 📅"}}}'::jsonb, is_playable = true
where title = 'Fixer le lieu et l''heure'
  and theme_id = (select id from scenario_themes where position = 2 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"sam": "Sam (le date)"}, "start_node": "n1", "nodes": {"n1": {"speaker": "sam", "text": "\"You look surprisingly good for a first date.\" ... Surprisingly?", "text_fr": "\"Tu es étonnamment bien habillé(e) pour un premier rendez-vous.\" ... Étonnamment ?", "choices": [{"text": "Oh no, I meant that as a compliment, sorry, that came out wrong!", "next": "end_direct"}, {"text": "(laugh nervously without explaining)", "next": "end_awkward"}, {"text": "What I meant was, you exceeded my already high expectations!", "next": "end_witty"}]}, "end_direct": {"speaker": "sam", "text": "Ha, okay, apology accepted!", "text_fr": "Ha, ok, excuses acceptées !", "end": true, "ending_label": "Malaise rattrapé 😅"}, "end_awkward": {"speaker": "sam", "text": "...Right. Anyway.", "text_fr": "...D''accord. Bon, sinon.", "end": true, "ending_label": "Ambiance un peu froide 😬"}, "end_witty": {"speaker": "sam", "text": "Smooth save! I''ll give you that.", "text_fr": "Bien rattrapé ! Je te l''accorde.", "end": true, "ending_label": "Rattrapage brillant ✨"}}}'::jsonb, is_playable = true
where title = 'Un compliment maladroit à rattraper'
  and theme_id = (select id from scenario_themes where position = 2 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"date": "ton date"}, "start_node": "n1", "nodes": {"n1": {"speaker": "date", "text": "So, tell me something about yourself that''s not on your profile.", "text_fr": "Alors, dis-moi quelque chose sur toi qui n''est pas sur ton profil.", "choices": [{"text": "I actually used to play in a band.", "next": "n2"}, {"text": "I''m terrified of birds, oddly enough.", "next": "n2b"}]}, "n2": {"speaker": "date", "text": "No way, what did you play?", "text_fr": "Sans blague, tu jouais de quoi ?", "choices": [{"text": "Drums, though I wasn''t very good.", "next": "n3"}]}, "n2b": {"speaker": "date", "text": "Birds? That''s random, ha! Any story behind that?", "text_fr": "Les oiseaux ? C''est original, ha ! Il y a une histoire derrière ça ?", "choices": [{"text": "Long story, but yes, involving a parrot.", "next": "n3"}]}, "n3": {"speaker": "date", "text": "I''d love to hear it sometime. So, what do you do for fun these days?", "text_fr": "J''aimerais l''entendre un jour. Sinon, tu fais quoi pour te détendre en ce moment ?", "choices": [{"text": "Mostly hiking and trying new recipes.", "next": "n4"}, {"text": "Honestly, mostly binge-watching shows.", "next": "n4b"}]}, "n4": {"speaker": "date", "text": "That''s a great combo. We should cook something together sometime.", "text_fr": "Belle combinaison. On devrait cuisiner ensemble un jour.", "choices": [{"text": "I''d really like that.", "next": "end_good"}]}, "n4b": {"speaker": "date", "text": "Same honestly, no judgment here!", "text_fr": "Pareil pour moi honnêtement, aucun jugement !", "choices": [{"text": "Glad we agree on that.", "next": "end_good"}]}, "end_good": {"speaker": "date", "text": "This has been really nice. I''d love to do this again.", "text_fr": "C''était vraiment agréable. J''aimerais recommencer.", "end": true, "ending_label": "Belle connexion 💫"}}}'::jsonb, is_playable = true
where title = 'Premier rendez-vous dans un café'
  and theme_id = (select id from scenario_themes where position = 2 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"date": "ton date"}, "start_node": "n1", "nodes": {"n1": {"speaker": "date", "text": "So, do you follow politics much?", "text_fr": "Sinon, tu suis un peu la politique ?", "choices": [{"text": "A little, but I''d rather not get into it on a first date.", "next": "n2"}, {"text": "Sure, what''s on your mind?", "next": "n2b"}]}, "n2": {"speaker": "date", "text": "Fair enough, totally understandable. Let''s talk about something lighter.", "text_fr": "Entendu, tout à fait compréhensible. Parlons de quelque chose de plus léger.", "choices": [{"text": "Thanks for understanding.", "next": "end_smooth"}]}, "n2b": {"speaker": "date", "text": "Honestly, I''ve been pretty stressed about the news lately.", "text_fr": "Honnêtement, j''ai été assez stressé(e) par les infos ces derniers temps.", "choices": [{"text": "I get that, it can be a lot. Let''s find something more relaxing to talk about.", "next": "end_redirect"}, {"text": "I understand, want to talk it through?", "next": "end_deep"}]}, "end_smooth": {"speaker": "date", "text": "So, favorite movie of all time?", "text_fr": "Alors, film préféré de tous les temps ?", "end": true, "ending_label": "Sujet évité avec tact ✅"}, "end_redirect": {"speaker": "date", "text": "Yeah, you''re right. What''s your favorite way to unwind?", "text_fr": "Oui, tu as raison. Comment tu te détends le mieux ?", "end": true, "ending_label": "Ambiance redevenue légère 😊"}, "end_deep": {"speaker": "date", "text": "Thanks, I appreciate that. It means a lot that you''re willing to listen.", "text_fr": "Merci, j''apprécie. Ça compte beaucoup que tu sois prêt(e) à écouter.", "end": true, "ending_label": "Vraie connexion émotionnelle 💙"}}}'::jsonb, is_playable = true
where title = 'Une conversation qui dévie sur un sujet sensible'
  and theme_id = (select id from scenario_themes where position = 2 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"date": "ton date"}, "start_node": "n1", "nodes": {"n1": {"speaker": "date", "text": "I had a really good time tonight.", "text_fr": "J''ai vraiment passé un bon moment ce soir.", "choices": [{"text": "Me too! Would you like to do this again sometime?", "next": "end_direct"}, {"text": "Same here. I''ll text you, if that''s okay?", "next": "end_text"}]}, "end_direct": {"speaker": "date", "text": "I''d love that! How about next Friday?", "text_fr": "J''adorerais ça ! Vendredi prochain ça te va ?", "end": true, "ending_label": "Deuxième date confirmée 🎉"}, "end_text": {"speaker": "date", "text": "Definitely, I''d like that.", "text_fr": "Avec plaisir, ça me plairait.", "end": true, "ending_label": "Contact maintenu ✅"}}}'::jsonb, is_playable = true
where title = 'Proposer un deuxième rendez-vous'
  and theme_id = (select id from scenario_themes where position = 2 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"date": "ton date"}, "start_node": "n1", "nodes": {"n1": {"speaker": "date", "text": "Dinner was great. Want to keep the night going? There''s a nice bar nearby.", "text_fr": "Le dîner était excellent. Tu veux continuer la soirée ? Il y a un bon bar pas loin.", "choices": [{"text": "I''d love that.", "next": "n2"}, {"text": "How about a walk instead? It''s such a nice evening.", "next": "n2b"}]}, "n2": {"speaker": "date", "text": "Great, this place has amazing live music too.", "text_fr": "Génial, cet endroit a aussi une super musique live.", "choices": [{"text": "Perfect, I love live music.", "next": "n3"}]}, "n2b": {"speaker": "date", "text": "I love that idea, let''s walk by the river.", "text_fr": "J''adore l''idée, marchons le long de la rivière.", "choices": [{"text": "Sounds perfect.", "next": "n3"}]}, "n3": {"speaker": "date", "text": "So, can I be honest about something?", "text_fr": "Je peux être honnête sur quelque chose ?", "choices": [{"text": "Of course, what''s up?", "next": "n4"}]}, "n4": {"speaker": "date", "text": "I was really nervous about tonight, but I''m glad I came.", "text_fr": "J''étais vraiment nerveux(se) pour ce soir, mais je suis content(e) d''être venu(e).", "choices": [{"text": "I was nervous too, honestly. This has been really great though.", "next": "n5"}, {"text": "You didn''t seem nervous at all!", "next": "n5b"}]}, "n5": {"speaker": "date", "text": "I''m really glad we''re both being honest.", "text_fr": "Je suis vraiment content(e) qu''on soit tous les deux honnêtes.", "choices": [{"text": "Me too. I don''t want tonight to end.", "next": "end_connection"}]}, "n5b": {"speaker": "date", "text": "Ha, good acting then! But seriously, this has been great.", "text_fr": "Ha, bonne comédie alors ! Mais sérieusement, c''était génial.", "choices": [{"text": "It really has.", "next": "end_connection"}]}, "end_connection": {"speaker": "date", "text": "I really hope this isn''t the last time.", "text_fr": "J''espère vraiment que ce n''est pas la dernière fois.", "end": true, "ending_label": "Soirée mémorable 🌙"}}}'::jsonb, is_playable = true
where title = 'Un date qui évolue sur toute une soirée'
  and theme_id = (select id from scenario_themes where position = 2 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"friend": "Jordan (ami·e du date)", "date": "ton date"}, "start_node": "n1", "nodes": {"n1": {"speaker": "date", "text": "Everyone, this is the person I''ve been telling you about!", "text_fr": "Tout le monde, voici la personne dont je vous ai parlé !", "choices": [{"text": "Hi everyone, great to finally meet you all!", "next": "n2"}]}, "n2": {"speaker": "friend", "text": "So, how did you two actually meet?", "text_fr": "Alors, comment vous vous êtes vraiment rencontrés ?", "choices": [{"text": "Actually, it''s a pretty funny story...", "next": "n3"}, {"text": "We met through a dating app, nothing too exciting!", "next": "n3b"}]}, "n3": {"speaker": "friend", "text": "Now I have to hear this!", "text_fr": "Maintenant il faut que j''entende ça !", "choices": [{"text": "(tell the story with enthusiasm)", "next": "n4"}]}, "n3b": {"speaker": "friend", "text": "Ha, well, whatever works!", "text_fr": "Ha, tant que ça marche !", "choices": [{"text": "Exactly!", "next": "n4"}]}, "n4": {"speaker": "friend", "text": "Well, I can already tell you''re a good match for them.", "text_fr": "En tout cas, je vois déjà que vous allez bien ensemble.", "choices": [{"text": "That means a lot, thank you.", "next": "end_approved"}]}, "end_approved": {"speaker": "date", "text": "See, I told you they''d love you.", "text_fr": "Tu vois, je t''avais dit qu''ils t''adoreraient.", "end": true, "ending_label": "Approuvé par les amis 👍"}}}'::jsonb, is_playable = true
where title = 'Rencontrer les amis de l''autre'
  and theme_id = (select id from scenario_themes where position = 2 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"partner": "ton/ta partenaire"}, "start_node": "n1", "nodes": {"n1": {"speaker": "partner", "text": "It''s been a few months now... I feel like I need to tell you something.", "text_fr": "Ça fait quelques mois maintenant... j''ai besoin de te dire quelque chose.", "choices": [{"text": "You can tell me anything.", "next": "n2"}]}, "n2": {"speaker": "partner", "text": "I think... I think I''m falling in love with you.", "text_fr": "Je crois... je crois que je tombe amoureux/amoureuse de toi.", "choices": [{"text": "I feel exactly the same way.", "next": "end_mutual"}, {"text": "I really care about you, but I need a bit more time.", "next": "end_honest"}]}, "end_mutual": {"speaker": "partner", "text": "I was so nervous to say that, but I''m so happy right now.", "text_fr": "J''étais si nerveux/nerveuse de dire ça, mais je suis tellement heureux/heureuse là.", "end": true, "ending_label": "Amour partagé 💕"}, "end_honest": {"speaker": "partner", "text": "Thank you for being honest with me, that means a lot.", "text_fr": "Merci d''être honnête avec moi, ça compte beaucoup.", "end": true, "ending_label": "Honnêteté respectée 💙"}}}'::jsonb, is_playable = true
where title = 'Une déclaration à un moment clé'
  and theme_id = (select id from scenario_themes where position = 2 and language_id = (select id from languages where code = 'en'));
