-- ============================================
-- LUMA — Treasure Island Tome 6 (FINAL) : Chapitres XXVIII-XXXIV (Le camp ennemi, jusqu'au retour final)
-- Texte original, domaine public
-- ============================================


with s as (select id from books where title = 'Treasure Island' and is_series = true),
     lang as (select id from languages where code = 'en')
insert into books (language_id, title, theme, description, cecr_level, cover_emoji, total_pages, position, series_id, volume_number)
select lang.id, 'Tome 6 : Le trésor de Flint', 'Classique • Robert Louis Stevenson (1883)', 'Jim tombe aux mains des pirates, Silver retourne la mutinerie à son avantage, la chasse au trésor révèle son terrible secret, et l''aventure se conclut sur le retour triomphant à Bristol.', 'B1-B2', '💰', 3, 2, s.id, 6
from lang, s;


with b as (select id from books where title = 'Tome 6 : Le trésor de Flint' and series_id = (select id from books where title = 'Treasure Island' and is_series = true))
insert into book_pages (book_id, page_number, sentences)
select b.id, 1, '[{"en": "Jim discovered his friends were gone and the stockade now held six pirates. To his shock, Silver explained: ''Ship''s gone. We bargained with the doctor.''", "fr": "Jim découvrit que ses amis avaient disparu et que la palissade abritait maintenant six pirates. À son choc, Silver expliqua : ''Le navire est parti. Nous avons négocié avec le docteur.''"}, {"en": "Silver revealed that Dr. Livesey had traded the stockade, stores, and firewood to the pirates, abandoning Jim along with the rest of the party.", "fr": "Silver révéla que le Dr Livesey avait échangé la palissade, les provisions et le bois de chauffage aux pirates, abandonnant Jim avec le reste du groupe."}, {"en": "Jim boldly confessed everything: he had overheard their mutiny plans, cut the ship adrift, and killed their comrades. ''The laugh''s on my side,'' he declared fearlessly.", "fr": "Jim avoua tout avec audace : il avait surpris leurs plans de mutinerie, largué le navire, et tué leurs complices. ''Le rire est de mon côté,'' déclara-t-il sans crainte."}, {"en": "The mutineers, furious, gave Silver the black spot—a sign of mutiny against their own captain—cut from a page of Dick''s Bible.", "fr": "Les mutins, furieux, donnèrent à Silver la marque noire—un signe de mutinerie contre leur propre capitaine—découpée dans une page de la Bible de Dick."}, {"en": "Silver cleverly turned the mutiny back on his accusers, revealing the treasure map given to him by the doctor, and was re-elected captain by his stunned crew.", "fr": "Silver retourna habilement la mutinerie contre ses accusateurs, révélant la carte au trésor que lui avait donnée le docteur, et fut réélu capitaine par son équipage stupéfait."}, {"en": "The next morning, Dr. Livesey arrived to treat the wounded pirates. Silver, wanting to speak with Jim privately, arranged a parole for him.", "fr": "Le lendemain matin, le Dr Livesey arriva pour soigner les pirates blessés. Silver, voulant parler à Jim en privé, obtint pour lui une liberté conditionnelle."}]'::jsonb from b;


with b as (select id from books where title = 'Tome 6 : Le trésor de Flint' and series_id = (select id from books where title = 'Treasure Island' and is_series = true))
insert into book_pages (book_id, page_number, sentences)
select b.id, 2, '[{"en": "Jim gave his word of honour not to escape, then confessed to the doctor how he had recaptured the ship and hidden it safely at North Inlet.", "fr": "Jim donna sa parole d''honneur de ne pas s''échapper, puis avoua au docteur comment il avait repris le navire et l''avait caché en sécurité à l''Anse Nord."}, {"en": "The doctor, astonished, offered Silver a cryptic warning: ''Look out for squalls when you find it''—hinting at a plan Jim did not yet understand.", "fr": "Le docteur, stupéfait, offrit à Silver un avertissement énigmatique : ''Méfiez-vous des grains quand vous le trouverez''—laissant entendre un plan que Jim ne comprenait pas encore."}, {"en": "Silver led the pirates and their hostage Jim, tethered by a rope, on the treasure hunt following Flint''s map and the pointer of a skeleton''s bones.", "fr": "Silver mena les pirates et son otage Jim, attaché par une corde, à la chasse au trésor en suivant la carte de Flint et l''indication des ossements d''un squelette."}, {"en": "A ghostly voice suddenly sang out from the trees—Flint''s old sea-song—terrifying the superstitious pirates until Silver guessed it was really Ben Gunn playing tricks.", "fr": "Une voix fantomatique chanta soudain depuis les arbres—la vieille chanson de marin de Flint—terrifiant les pirates superstitieux jusqu''à ce que Silver devine qu''il s''agissait en réalité de Ben Gunn jouant des tours."}, {"en": "At last they reached the tall pine marked on the chart—only to find a great empty pit. The treasure was gone; someone had already dug it up.", "fr": "Ils atteignirent enfin le grand pin marqué sur la carte—pour ne trouver qu''une grande fosse vide. Le trésor avait disparu ; quelqu''un l''avait déjà déterré."}, {"en": "As the furious pirates turned on Silver, shots rang out from the trees: Dr. Livesey, Gray, and Ben Gunn had been lying in ambush all along.", "fr": "Alors que les pirates furieux se retournaient contre Silver, des coups de feu retentirent depuis les arbres : le Dr Livesey, Gray, et Ben Gunn étaient en embuscade depuis le début."}]'::jsonb from b;


with b as (select id from books where title = 'Tome 6 : Le trésor de Flint' and series_id = (select id from books where title = 'Treasure Island' and is_series = true))
insert into book_pages (book_id, page_number, sentences)
select b.id, 3, '[{"en": "It was revealed that Ben Gunn had found Flint''s treasure long ago and moved it all to his own cave—which is why the doctor had so freely given up map and stockade.", "fr": "On révéla que Ben Gunn avait trouvé le trésor de Flint depuis longtemps et l''avait déplacé dans sa propre grotte—c''est pourquoi le docteur avait si facilement abandonné la carte et la palissade."}, {"en": "The survivors sailed the Hispaniola home, carrying sacks of ancient coins from every nation, leaving the last three mutineers marooned on the island.", "fr": "Les survivants ramenèrent l''Hispaniola chez eux, transportant des sacs de pièces anciennes de toutes les nations, laissant les trois derniers mutins abandonnés sur l''île."}, {"en": "Silver himself escaped one night with a small sack of coins, never to be seen again by Jim, who suspected he lived out his days peacefully far from the gallows.", "fr": "Silver lui-même s''échappa une nuit avec un petit sac de pièces, ne devant plus jamais être revu par Jim, qui soupçonna qu''il finit ses jours paisiblement, loin de la potence."}, {"en": "Years later, Jim still dreamed of the island''s roaring surf, and of Captain Flint''s parrot screeching forever in his memory: ''Pieces of eight! Pieces of eight!''", "fr": "Des années plus tard, Jim rêvait encore du ressac tonitruant de l''île, et du perroquet du capitaine Flint criant pour toujours dans sa mémoire : ''Pièces de huit ! Pièces de huit !''"}]'::jsonb from b;
