-- ============================================
-- LUMA — Ajout des traductions FR aux 4 scénarios jouables
-- ============================================


update scenarios set content = '{"characters": {"tom": "Tom (serveur)"}, "start_node": "n1", "nodes": {"n1": {"speaker": "tom", "text": "Hi there! Are you ready to order, or do you need a few more minutes?", "text_fr": "Bonjour ! Êtes-vous prêt à commander, ou avez-vous besoin de quelques minutes ?", "choices": [{"text": "I''m ready, thank you.", "next": "n2"}, {"text": "Could I have a few more minutes, please?", "next": "n1b"}]}, "n1b": {"speaker": "tom", "text": "No problem, take your time! (Tom comes back a minute later)", "text_fr": "Pas de problème, prenez votre temps ! (Tom revient une minute plus tard)", "choices": [{"text": "(Continuer)", "next": "n2"}]}, "n2": {"speaker": "tom", "text": "Great, what can I get you?", "text_fr": "Très bien, que puis-je vous servir ?", "choices": [{"text": "I''ll have the grilled chicken, please.", "next": "n3"}, {"text": "What do you recommend?", "next": "n2b"}]}, "n2b": {"speaker": "tom", "text": "The grilled chicken is very popular today!", "text_fr": "Le poulet grillé est très demandé aujourd''hui !", "choices": [{"text": "Sounds great, I''ll have that.", "next": "n3"}, {"text": "I''ll stick with the pasta instead, please.", "next": "n3"}]}, "n3": {"speaker": "tom", "text": "Perfect choice. Anything to drink?", "text_fr": "Excellent choix. Une boisson avec ça ?", "choices": [{"text": "Just water, please.", "next": "end_water"}, {"text": "A glass of orange juice, please.", "next": "end_juice"}]}, "end_water": {"speaker": "tom", "text": "Coming right up! By the way, tap water is free here, but bottled water is charged extra.", "text_fr": "Tout de suite ! Au fait, l''eau du robinet est gratuite ici, mais l''eau en bouteille est payante.", "end": true, "ending_label": "Repas commandé avec succès 🎉"}, "end_juice": {"speaker": "tom", "text": "One orange juice, coming right up! I''ll bring your order shortly.", "text_fr": "Un jus d''orange, tout de suite ! Je vous apporte votre commande sous peu.", "end": true, "ending_label": "Repas commandé avec succès 🎉"}}}'::jsonb
where title = 'Commander un plat simple'
  and theme_id = (select id from scenario_themes where position = 1 and language_id = (select id from languages where code = 'en'));


update scenarios set content = '{"characters": {"gareth": "Gareth (garde du village)"}, "start_node": "n1", "nodes": {"n1": {"speaker": "gareth", "text": "Halt! What business do you have in these parts, traveler?", "text_fr": "Halte ! Quelles affaires vous amènent dans ces contrées, voyageur ?", "choices": [{"text": "I''m looking for the path to the Enchanted Forest.", "next": "end_direct"}, {"text": "Just passing through.", "next": "n1b"}, {"text": "I''m on a quest to find a lost artifact.", "next": "end_quest"}]}, "n1b": {"speaker": "gareth", "text": "Passing through, you say? These woods aren''t for wandering souls. State your purpose clearly.", "text_fr": "De passage, dites-vous ? Ces bois ne sont pas faits pour les âmes errantes. Exposez clairement votre but.", "choices": [{"text": "Fine — I seek the path to the Enchanted Forest.", "next": "end_direct"}, {"text": "I mean no harm, I promise.", "next": "end_neutral"}]}, "end_direct": {"speaker": "gareth", "text": "The Enchanted Forest lies beyond the old bridge. Beware — strange creatures roam there after dusk.", "text_fr": "La Forêt Enchantée se trouve au-delà du vieux pont. Méfiez-vous — d''étranges créatures y rôdent après le crépuscule.", "end": true, "ending_label": "Chemin obtenu clairement 🗺️"}, "end_quest": {"speaker": "gareth", "text": "A lost artifact, you say? Then you''ll need to head north, past the old bridge. I''ll mark it on your map myself.", "text_fr": "Un artefact perdu, dites-vous ? Alors il vous faudra aller vers le nord, au-delà du vieux pont. Je vais moi-même le marquer sur votre carte.", "end": true, "ending_label": "Confiance gagnée ⭐"}, "end_neutral": {"speaker": "gareth", "text": "Hmph. Very well. The forest is north of here. Stay alert.", "text_fr": "Humpf. Très bien. La forêt est au nord d''ici. Restez sur vos gardes.", "end": true, "ending_label": "Passage autorisé, méfiance restante 😐"}}}'::jsonb
where title = 'Demander son chemin à un garde du village'
  and theme_id = (select id from scenario_themes where position = 8 and language_id = (select id from languages where code = 'en'));


update scenarios set content = '{"characters": {"jess": "Jess (amie)"}, "start_node": "n1", "nodes": {"n1": {"speaker": "jess", "text": "Where are you? I can''t see you anywhere!", "text_fr": "Où es-tu ? Je ne te vois nulle part !", "choices": [{"text": "I''m right next to the food truck with the red sign, near the main stage.", "next": "end_precise"}, {"text": "I''m near the stage.", "next": "n1b"}, {"text": "Let''s just meet at the big fountain in ten minutes.", "next": "end_meetup"}]}, "n1b": {"speaker": "jess", "text": "There are like five stages here! Can you be more specific?", "text_fr": "Il y a genre cinq scènes ici ! Tu peux être plus précis ?", "choices": [{"text": "Sorry! I''m at the smaller stage on the east side, by the food trucks.", "next": "end_precise"}, {"text": "Actually, let''s just meet at the fountain instead.", "next": "end_meetup"}]}, "end_precise": {"speaker": "jess", "text": "Got it, I see you now! Be right there!", "text_fr": "Ça y est, je te vois ! J''arrive tout de suite !", "end": true, "ending_label": "Retrouvailles rapides ✅"}, "end_meetup": {"speaker": "jess", "text": "Perfect, see you at the fountain in ten!", "text_fr": "Parfait, on se retrouve à la fontaine dans dix minutes !", "end": true, "ending_label": "Point de rendez-vous fixé ✅"}}}'::jsonb
where title = 'Retrouver des amis dans la foule'
  and theme_id = (select id from scenario_themes where position = 11 and language_id = (select id from languages where code = 'en'));


update scenarios set content = '{"characters": {"peggy": "Peggy (serveuse)"}, "start_node": "n1", "nodes": {"n1": {"speaker": "peggy", "text": "What can I get you, hon?", "text_fr": "Qu''est-ce que je vous sers, mon chou ?", "choices": [{"text": "I''ll have the classic burger with fries, please.", "next": "end_classic"}, {"text": "What''s the special today?", "next": "n1b"}, {"text": "Can I get the burger with extra cheese and bacon?", "next": "end_custom"}]}, "n1b": {"speaker": "peggy", "text": "Today''s special is meatloaf with mashed potatoes and gravy!", "text_fr": "Le plat du jour, c''est le pain de viande avec purée et sauce !", "choices": [{"text": "That sounds great, I''ll have that.", "next": "end_special"}, {"text": "I think I''ll stick with the classic burger.", "next": "end_classic"}]}, "end_classic": {"speaker": "peggy", "text": "One classic burger with fries, coming right up, hon!", "text_fr": "Un burger classique avec des frites, tout de suite, mon chou !", "end": true, "ending_label": "Commande passée 🍔"}, "end_custom": {"speaker": "peggy", "text": "Extra cheese and bacon, got it! That''ll be a little extra, is that okay?", "text_fr": "Fromage et bacon en plus, c''est noté ! Ça fera un petit supplément, ça vous va ?", "end": true, "ending_label": "Commande personnalisée 🍔"}, "end_special": {"speaker": "peggy", "text": "Great choice! One meatloaf special, coming right up!", "text_fr": "Excellent choix ! Un plat du jour, tout de suite !", "end": true, "ending_label": "Plat du jour choisi 🍽️"}}}'::jsonb
where title = 'Commander dans un diner américain'
  and theme_id = (select id from scenario_themes where position = 14 and language_id = (select id from languages where code = 'en'));
