-- ============================================
-- LUMA — Thème 6 (Colocation) : 3 scénarios COURTS x4
-- ============================================


update scenarios set content = '{"characters": {"roommate": "ton/ta coloc"}, "start_node": "n1", "nodes": {"n1": {"speaker": "roommate", "text": "Hey, can we talk about splitting the cleaning duties? It''s been a bit uneven lately.", "text_fr": "Hé, on peut parler de partager les tâches ménagères ? Ça a été un peu déséquilibré dernièrement.", "choices": [{"text": "Yeah, definitely, let''s figure out a fair system.", "text_fr": "Ouais, carrément, trouvons un système équitable.", "next": "n2"}, {"text": "I agree, I''ve been meaning to bring this up too.", "text_fr": "Je suis d''accord, je voulais aussi aborder ça.", "next": "n2"}]}, "n2": {"speaker": "roommate", "text": "What if we alternate weeks — one person does kitchen, the other bathroom?", "text_fr": "Et si on alternait les semaines — une personne fait la cuisine, l''autre la salle de bain ?", "choices": [{"text": "That sounds fair, I like that idea.", "text_fr": "Ça semble juste, j''aime cette idée.", "next": "n3"}, {"text": "What about a shared chore chart instead, with specific days?", "text_fr": "Et un tableau de tâches partagé plutôt, avec des jours spécifiques ?", "next": "n3b"}]}, "n3": {"speaker": "roommate", "text": "Great, let''s start this week — I''ll take the kitchen first.", "text_fr": "Super, commençons cette semaine — je prends la cuisine en premier.", "choices": [{"text": "Perfect, I''ll handle the bathroom then.", "text_fr": "Parfait, je m''occupe de la salle de bain alors.", "next": "n4"}]}, "n3b": {"speaker": "roommate", "text": "I like that too, more structure could help us both remember.", "text_fr": "J''aime bien aussi, plus de structure pourrait nous aider tous les deux à s''en souvenir.", "choices": [{"text": "Let''s make the chart together right now.", "text_fr": "Faisons le tableau ensemble maintenant.", "next": "n4"}]}, "n4": {"speaker": "roommate", "text": "Sounds good. Should we also split the common areas, like the living room?", "text_fr": "Ça marche. On devrait aussi partager les espaces communs, comme le salon ?", "choices": [{"text": "Yes, let''s alternate that too, weekly.", "text_fr": "Oui, alternons ça aussi, chaque semaine.", "next": "n5"}, {"text": "Maybe we both just clean it together on Sundays?", "text_fr": "On pourrait juste le nettoyer ensemble le dimanche ?", "next": "n5"}]}, "n5": {"speaker": "roommate", "text": "That works for me. I think this will make things much smoother.", "text_fr": "Ça me va. Je pense que ça va rendre les choses beaucoup plus fluides.", "choices": [{"text": "Agreed, thanks for bringing this up.", "text_fr": "D''accord, merci d''avoir soulevé ça.", "next": "end_agreed"}]}, "end_agreed": {"speaker": "roommate", "text": "Of course, teamwork makes this place feel like home.", "text_fr": "Bien sûr, le travail d''équipe rend cet endroit chaleureux.", "end": true, "ending_label": "Ménage négocié équitablement 🧹🤝"}}}'::jsonb, is_playable = true
where title = 'Négocier le ménage'
  and theme_id = (select id from scenario_themes where position = 6 and language_id = (select id from languages where code = 'en'));


update scenarios set content = '{"characters": {"roommate": "ton/ta coloc"}, "start_node": "n1", "nodes": {"n1": {"speaker": "roommate", "text": "(Loud music is playing at 1am through the wall.)", "text_fr": "(De la musique forte joue à 1h du matin à travers le mur.)", "choices": [{"text": "(Knock gently on their door.)", "text_fr": "(Frappe doucement à leur porte.)", "next": "n2"}, {"text": "(Send a polite text message instead.)", "text_fr": "(Envoie plutôt un message texte poli.)", "next": "n2b"}]}, "n2": {"speaker": "roommate", "text": "Oh, hey! Sorry, is it too loud?", "text_fr": "Oh, salut ! Désolé, c''est trop fort ?", "choices": [{"text": "Yeah, I have an early morning tomorrow, could you turn it down?", "text_fr": "Ouais, j''ai une matinée tôt demain, tu pourrais baisser un peu ?", "next": "n3"}, {"text": "A little, would you mind using headphones instead?", "text_fr": "Un peu, ça te dérangerait d''utiliser des écouteurs plutôt ?", "next": "n3"}]}, "n2b": {"speaker": "roommate", "text": "(Replies quickly) Oh sorry! Didn''t realize it was that late, turning it down now.", "text_fr": "(Répond rapidement) Oh désolé ! J''avais pas réalisé qu''il était si tard, je baisse maintenant.", "choices": [{"text": "Thanks, I really appreciate it.", "text_fr": "Merci, j''apprécie vraiment.", "next": "n4"}]}, "n3": {"speaker": "roommate", "text": "Of course, sorry about that, I lost track of time.", "text_fr": "Bien sûr, désolé pour ça, j''ai perdu la notion du temps.", "choices": [{"text": "No worries, it happens to everyone.", "text_fr": "Pas de souci, ça arrive à tout le monde.", "next": "n4"}]}, "n4": {"speaker": "roommate", "text": "I''ll be more mindful of the time going forward.", "text_fr": "Je vais faire plus attention à l''heure à l''avenir.", "choices": [{"text": "I appreciate that, thanks for understanding.", "text_fr": "J''apprécie ça, merci de comprendre.", "next": "end_resolved"}]}, "end_resolved": {"speaker": "roommate", "text": "No problem at all, sleep well!", "text_fr": "Aucun problème, bonne nuit !", "end": true, "ending_label": "Bruit géré avec politesse 🔇😴"}}}'::jsonb, is_playable = true
where title = 'Se plaindre du bruit'
  and theme_id = (select id from scenario_themes where position = 6 and language_id = (select id from languages where code = 'en'));
