-- ============================================
-- LUMA — Treasure Island Tome 4 : Chapitres XVI-XXI (L'abandon du navire, la palissade, l'attaque)
-- Texte original, domaine public
-- ============================================


with s as (select id from books where title = 'Treasure Island' and is_series = true),
     lang as (select id from languages where code = 'en')
insert into books (language_id, title, theme, description, cecr_level, cover_emoji, total_pages, position, series_id, volume_number)
select lang.id, 'Tome 4 : La palissade assiégée', 'Classique • Robert Louis Stevenson (1883)', 'Le navire est abandonné, Tom Redruth tombe au combat, Silver tente une négociation ratée, et la palissade repousse un assaut sanglant des mutins.', 'B1-B2', '⚔️', 6, 2, s.id, 4
from lang, s;


with b as (select id from books where title = 'Tome 4 : La palissade assiégée' and series_id = (select id from books where title = 'Treasure Island' and is_series = true))
insert into book_pages (book_id, page_number, sentences)
select b.id, 1, '[{"en": "Dr. Livesey now took up the narration. Jim had slipped ashore, and the doctor and Hunter went to explore, discovering a stockade with a spring of clear water on a knoll.", "fr": "Le Dr Livesey reprit maintenant le récit. Jim s''était glissé à terre, et le docteur et Hunter allèrent explorer, découvrant une palissade avec une source d''eau claire sur un tertre."}, {"en": "Suddenly there came ringing over the island the cry of a man at the point of death. ''Jim Hawkins is gone,'' was the doctor''s first thought.", "fr": "Soudain retentit sur l''île le cri d''un homme à l''agonie. ''Jim Hawkins est mort,'' fut la première pensée du docteur."}, {"en": "The doctor rushed back to the ship and, with Captain Smollett''s help, began loading the jolly-boat with muskets, powder, food, and the medicine chest.", "fr": "Le docteur se précipita vers le navire et, avec l''aide du capitaine Smollett, commença à charger le canot d''armes, de poudre, de nourriture et de la trousse médicale."}, {"en": "Captain Smollett warned the six mutineers left aboard: ''If any one of you six make a signal, that man''s dead.''", "fr": "Le capitaine Smollett avertit les six mutins restés à bord : ''Si l''un de vous six fait un signal, cet homme est mort.''"}, {"en": "Before leaving, Smollett gave one sailor, Abraham Gray, a final chance. ''I am leaving this ship, and I order you to follow your captain,'' he called.", "fr": "Avant de partir, Smollett donna une dernière chance à un marin, Abraham Gray. ''Je quitte ce navire, et je t''ordonne de suivre ton capitaine,'' appela-t-il."}, {"en": "After a tense pause, Gray burst from the forecastle with a knife cut on his cheek and ran to join the captain. ''I''m with you, sir,'' he said.", "fr": "Après une pause tendue, Gray surgit du gaillard d''avant avec une coupure de couteau à la joue et courut rejoindre le capitaine. ''Je suis avec vous, monsieur,'' dit-il."}]'::jsonb from b;


with b as (select id from books where title = 'Tome 4 : La palissade assiégée' and series_id = (select id from books where title = 'Treasure Island' and is_series = true))
insert into book_pages (book_id, page_number, sentences)
select b.id, 2, '[{"en": "The little boat was dangerously overloaded with five men and all their stores, riding low in the water as the ebb tide swept them off course.", "fr": "Le petit canot était dangereusement surchargé avec cinq hommes et toutes leurs provisions, s''enfonçant dans l''eau tandis que le jusant les déportait de leur route."}, {"en": "To their horror, they saw the mutineers preparing the ship''s cannon, with Israel Hands—Flint''s former gunner—in command of it.", "fr": "À leur horreur, ils virent les mutins préparer le canon du navire, avec Israel Hands—l''ancien canonnier de Flint—aux commandes."}, {"en": "Squire Trelawney, the best shot among them, fired at Hands but missed as the pirate ducked, striking another man instead.", "fr": "Le châtelain Trelawney, le meilleur tireur du groupe, visa Hands mais le manqua alors que le pirate se baissait, touchant un autre homme à la place."}, {"en": "The cannon fired just as the crew leaned hard to one side; the boat sank gently in three feet of water, spilling half their stores and powder.", "fr": "Le canon tira juste au moment où l''équipage se pencha fortement d''un côté ; le canot coula doucement dans soixante centimètres d''eau, renversant la moitié de leurs provisions et de leur poudre."}, {"en": "No lives were lost, but only two of five guns remained usable, and they had to wade ashore, abandoning the jolly-boat entirely.", "fr": "Aucune vie ne fut perdue, mais seulement deux des cinq fusils restaient utilisables, et ils durent patauger jusqu''au rivage, abandonnant complètement le canot."}, {"en": "Racing for the stockade, they exchanged fire with seven mutineers led by Job Anderson, killing one and scattering the rest into the trees.", "fr": "Courant vers la palissade, ils échangèrent des tirs avec sept mutins menés par Job Anderson, en tuant un et dispersant les autres dans les arbres."}]'::jsonb from b;


with b as (select id from books where title = 'Tome 4 : La palissade assiégée' and series_id = (select id from books where title = 'Treasure Island' and is_series = true))
insert into book_pages (book_id, page_number, sentences)
select b.id, 3, '[{"en": "But poor old Tom Redruth was struck by a pistol shot and fell. The squire dropped to his knees beside him, weeping like a child.", "fr": "Mais le pauvre vieux Tom Redruth fut frappé par un coup de pistolet et tomba. Le châtelain tomba à genoux à ses côtés, pleurant comme un enfant."}, {"en": "''Would that be respectful like, from me to you, squire?'' Redruth asked when begged for forgiveness. Soon after, without another word, he passed away.", "fr": "''Ça serait respectueux, de ma part envers vous, châtelain ?'' demanda Redruth quand on le supplia de pardonner. Peu après, sans un mot de plus, il s''éteignit."}, {"en": "Captain Smollett raised the British colours atop the log-house, refusing to strike them despite the enemy''s cannon fire. ''Strike my colours! No, sir, not I,'' he declared.", "fr": "Le capitaine Smollett hissa les couleurs britanniques au sommet de la cabane, refusant de les abaisser malgré les tirs de canon ennemis. ''Baisser mes couleurs ! Non, monsieur, certainement pas,'' déclara-t-il."}, {"en": "Through his spyglass, the doctor saw the mutineers hauling away their stolen provisions in a gig, with Silver himself commanding from the stern.", "fr": "À travers sa longue-vue, le docteur vit les mutins emporter leurs provisions volées dans un canot, avec Silver lui-même commandant depuis la poupe."}, {"en": "Just as the captain began his ship''s log, a hail came from outside: ''Doctor! Squire! Captain!'' And Jim Hawkins climbed safely over the stockade.", "fr": "Juste au moment où le capitaine commençait son journal de bord, un appel vint de l''extérieur : ''Docteur ! Châtelain ! Capitaine !'' Et Jim Hawkins escalada la palissade, sain et sauf."}, {"en": "Ben Gunn, seeing the British flag, refused to approach the stockade himself, insisting he first speak privately with ''a born gentleman'' about his own mysterious plans.", "fr": "Ben Gunn, voyant le drapeau britannique, refusa lui-même de s''approcher de la palissade, insistant pour d''abord parler en privé avec ''un vrai gentleman'' de ses propres plans mystérieux."}]'::jsonb from b;


with b as (select id from books where title = 'Tome 4 : La palissade assiégée' and series_id = (select id from books where title = 'Treasure Island' and is_series = true))
insert into book_pages (book_id, page_number, sentences)
select b.id, 4, '[{"en": "A cannonball crashed through the trees nearby, and Jim and Ben Gunn fled in different directions as the bombardment continued for an hour.", "fr": "Un boulet de canon s''écrasa dans les arbres tout près, et Jim et Ben Gunn s''enfuirent dans des directions différentes tandis que le bombardement se poursuivit une heure."}, {"en": "Jim finally made his way back to the stockade and was warmly welcomed, finding the log-house filled with sand, smoke, and poor Tom Redruth''s body under a flag.", "fr": "Jim finit par retrouver son chemin vers la palissade et fut chaleureusement accueilli, trouvant la cabane remplie de sable, de fumée, et le corps du pauvre Tom Redruth sous un drapeau."}, {"en": "Captain Smollett organized watches and set everyone to work. The doctor confided to Jim: ''That man Smollett is a better man than I am.''", "fr": "Le capitaine Smollett organisa des tours de garde et mit tout le monde au travail. Le docteur confia à Jim : ''Cet homme, Smollett, est meilleur homme que moi.''"}, {"en": "The party decided their best hope was to kill off the buccaneers one by one, aided by rum and the island''s unhealthy climate working against their enemies.", "fr": "Le groupe décida que leur meilleur espoir était d''éliminer les flibustiers un par un, aidés par le rhum et le climat malsain de l''île qui jouaient contre leurs ennemis."}, {"en": "The next morning, Jim was woken by a cry of surprise: ''Flag of truce! Silver himself!''", "fr": "Le lendemain matin, Jim fut réveillé par un cri de surprise : ''Drapeau de trêve ! Silver en personne !''"}, {"en": "Silver, dressed in his finest coat, struggled up the knoll on his crutch to negotiate. ''These poor lads have chosen me cap''n, after your desertion,'' he announced.", "fr": "Silver, vêtu de son plus beau manteau, gravit péniblement le tertre sur sa béquille pour négocier. ''Ces pauvres gars m''ont choisi comme capitaine, après votre désertion,'' annonça-t-il."}]'::jsonb from b;


with b as (select id from books where title = 'Tome 4 : La palissade assiégée' and series_id = (select id from books where title = 'Treasure Island' and is_series = true))
insert into book_pages (book_id, page_number, sentences)
select b.id, 5, '[{"en": "Silver demanded the treasure map, offering the captain''s party a choice: join the pirates aboard ship, or stay behind with divided supplies.", "fr": "Silver exigea la carte au trésor, offrant au groupe du capitaine un choix : rejoindre les pirates à bord du navire, ou rester avec des provisions partagées."}, {"en": "Captain Smollett refused flatly: ''You can''t find the treasure. You can''t sail the ship. You can''t fight us. I''ll put a bullet in your back when next I meet you.''", "fr": "Le capitaine Smollett refusa catégoriquement : ''Vous ne pouvez pas trouver le trésor. Vous ne pouvez pas naviguer le navire. Vous ne pouvez pas nous battre. Je vous mettrai une balle dans le dos la prochaine fois que je vous rencontrerai.''"}, {"en": "Furious, Silver spat into the spring and stumbled away, swearing: ''Before an hour''s out, I''ll stove in your old block house like a rum puncheon!''", "fr": "Furieux, Silver cracha dans la source et s''éloigna en trébuchant, jurant : ''Avant une heure, je démolirai votre vieille cabane comme un tonneau de rhum !''"}, {"en": "Captain Smollett prepared his small garrison for the coming assault, positioning each defender at a loophole around the log-house.", "fr": "Le capitaine Smollett prépara sa petite garnison pour l''assaut à venir, positionnant chaque défenseur à une meurtrière autour de la cabane."}, {"en": "With a loud huzza, a cloud of pirates leaped from the woods and swarmed over the stockade fence like monkeys, despite heavy fire from the defenders.", "fr": "Avec un grand cri, une nuée de pirates jaillit des bois et grimpa par-dessus la clôture de la palissade comme des singes, malgré les tirs nourris des défenseurs."}, {"en": "Four boarders reached the log-house itself. Job Anderson roared ''At ''em, all hands!'' as fighting broke out inside amid smoke and confusion.", "fr": "Quatre assaillants atteignirent la cabane elle-même. Job Anderson rugit ''Sur eux, tout le monde !'' tandis que le combat éclatait à l''intérieur au milieu de la fumée et de la confusion."}]'::jsonb from b;


with b as (select id from books where title = 'Tome 4 : La palissade assiégée' and series_id = (select id from books where title = 'Treasure Island' and is_series = true))
insert into book_pages (book_id, page_number, sentences)
select b.id, 6, '[{"en": "Jim grabbed a cutlass and rushed outside, narrowly dodging Anderson''s blow before Gray cut the boatswain down from behind.", "fr": "Jim saisit un sabre et se précipita dehors, esquivant de justesse le coup d''Anderson avant que Gray n''abatte le maître d''équipage par-derrière."}, {"en": "In moments, the battle was won: five pirates lay dead or dying, and the rest fled into the woods, leaving the defenders victorious but wounded.", "fr": "En quelques instants, la bataille était gagnée : cinq pirates gisaient morts ou mourants, et les autres s''enfuirent dans les bois, laissant les défenseurs victorieux mais blessés."}, {"en": "Sadly, Joyce had been shot through the head and Hunter lay stunned, while Captain Smollett himself was wounded. ''Five against three leaves us four to nine,'' he said. ''That''s better odds than we had at starting.''", "fr": "Tristement, Joyce avait été tué d''une balle dans la tête et Hunter gisait assommé, tandis que le capitaine Smollett lui-même était blessé. ''Cinq contre trois nous laisse quatre contre neuf,'' dit-il. ''C''est un meilleur rapport que celui qu''on avait au départ.''"}]'::jsonb from b;
