-- ============================================
-- LUMA — Oz Tome 2 : Chapitres IV-VII (La forêt, l'Homme de Fer-Blanc, le Lion, le fossé)
-- Texte original, domaine public
-- ============================================


with s as (select id from books where title = 'The Wonderful Wizard of Oz' and is_series = true),
     lang as (select id from languages where code = 'en')
insert into books (language_id, title, theme, description, cecr_level, cover_emoji, total_pages, position, series_id, volume_number)
select lang.id, 'Tome 2 : La forêt et les compagnons', 'Classique • L. Frank Baum (1900)', 'Dorothy et l''Épouvantail traversent la forêt, sauvent l''Homme de Fer-Blanc rouillé, rencontrent le Lion Peureux, et affrontent un fossé infranchissable.', 'B1', '🪓', 9, 1, s.id, 2
from lang, s;


with b as (select id from books where title = 'Tome 2 : La forêt et les compagnons' and series_id = (select id from books where title = 'The Wonderful Wizard of Oz' and is_series = true))
insert into book_pages (book_id, page_number, sentences)
select b.id, 1, '[{"en": "After a few hours the road began to be rough, and the walking grew so difficult that the Scarecrow often stumbled over the yellow bricks, which were here very uneven.", "fr": "Après quelques heures, la route commença à devenir accidentée, et marcher devint si difficile que l''Épouvantail trébuchait souvent sur les briques jaunes, très inégales à cet endroit."}, {"en": "As for the Scarecrow, having no brains, he walked straight ahead, and so stepped into the holes and fell at full length on the hard bricks.", "fr": "Quant à l''Épouvantail, n''ayant pas de cervelle, il marchait tout droit, et tombait donc dans les trous et s''étalait de tout son long sur les briques dures."}, {"en": "It never hurt him, however, and Dorothy would pick him up and set him upon his feet again, while he joined her in laughing merrily at his own mishap.", "fr": "Cela ne lui faisait jamais mal, cependant, et Dorothy le relevait et le remettait sur pied, tandis qu''il riait joyeusement avec elle de sa propre mésaventure."}, {"en": "At noon they sat down by the roadside, near a little brook, and Dorothy opened her basket and got out some bread. She offered a piece to the Scarecrow, but he refused.", "fr": "À midi ils s''assirent au bord de la route, près d''un petit ruisseau, et Dorothy ouvrit son panier et sortit du pain. Elle en offrit un morceau à l''Épouvantail, mais il refusa."}, {"en": "''I am never hungry,'' he said, ''and it is a lucky thing I am not, for my mouth is only painted, and if I should cut a hole in it, the straw I am stuffed with would come out.''", "fr": "''Je n''ai jamais faim,'' dit-il, ''et c''est une chance, car ma bouche n''est que peinte, et si j''y faisais un trou, la paille dont je suis rempli s''échapperait.''"}, {"en": "''Tell me something about yourself and the country you came from,'' said the Scarecrow. So she told him all about Kansas, and how gray everything was there.", "fr": "''Parlez-moi un peu de vous et du pays d''où vous venez,'' dit l''Épouvantail. Alors elle lui raconta tout sur le Kansas, et à quel point tout y était gris."}]'::jsonb from b;


with b as (select id from books where title = 'Tome 2 : La forêt et les compagnons' and series_id = (select id from books where title = 'The Wonderful Wizard of Oz' and is_series = true))
insert into book_pages (book_id, page_number, sentences)
select b.id, 2, '[{"en": "The Scarecrow listened carefully, and said, ''I cannot understand why you should wish to leave this beautiful country and go back to the dry, gray place you call Kansas.''", "fr": "L''Épouvantail écouta attentivement, et dit : ''Je ne comprends pas pourquoi vous voudriez quitter ce beau pays pour retourner dans cet endroit sec et gris que vous appelez le Kansas.''"}, {"en": "''That is because you have no brains,'' answered the girl. ''No matter how dreary and gray our homes are, we people of flesh and blood would rather live there than in any other country. There is no place like home.''", "fr": "''C''est parce que vous n''avez pas de cervelle,'' répondit la fillette. ''Peu importe combien nos foyers sont tristes et gris, nous les gens de chair et de sang préférons y vivre plutôt qu''ailleurs. Il n''y a pas d''endroit comme chez soi.''"}, {"en": "''Won''t you tell me a story, while we are resting?'' asked the child. The Scarecrow answered: ''My life has been so short that I really know nothing whatever. I was only made day before yesterday.''", "fr": "''Vous ne voudriez pas me raconter une histoire, pendant qu''on se repose ?'' demanda l''enfant. L''Épouvantail répondit : ''Ma vie a été si courte que je ne sais vraiment rien. J''ai été fabriqué avant-hier seulement.''"}, {"en": "He then told her how the farmer had painted his eyes, his nose and his mouth, and how an old crow had told him that brains were the only things worth having in the world.", "fr": "Il lui raconta ensuite comment le fermier avait peint ses yeux, son nez et sa bouche, et comment un vieux corbeau lui avait dit que la cervelle était la seule chose qui valait la peine d''être possédée au monde."}, {"en": "''By good luck you came along and pulled me off the stake, and from what you say I am sure the Great Oz will give me brains as soon as we get to the Emerald City.''", "fr": "''Par chance vous êtes passée et m''avez retiré du poteau, et d''après ce que vous dites, je suis sûr que le Grand Oz me donnera de la cervelle dès qu''on arrivera à la Cité d''Émeraude.''"}, {"en": "Toward evening they came to a great forest, where the trees grew so big and close together that their branches met over the road of yellow brick. It was almost dark under the trees.", "fr": "Vers le soir ils arrivèrent à une grande forêt, où les arbres poussaient si grands et si serrés que leurs branches se rejoignaient au-dessus de la route de briques jaunes. Il faisait presque nuit sous les arbres."}]'::jsonb from b;


with b as (select id from books where title = 'Tome 2 : La forêt et les compagnons' and series_id = (select id from books where title = 'The Wonderful Wizard of Oz' and is_series = true))
insert into book_pages (book_id, page_number, sentences)
select b.id, 3, '[{"en": "''If you see any house, or any place where we can pass the night,'' Dorothy said, ''you must tell me; for it is very uncomfortable walking in the dark.''", "fr": "''Si tu vois une maison, ou un endroit où on pourrait passer la nuit,'' dit Dorothy, ''tu dois me le dire ; car c''est très inconfortable de marcher dans le noir.''"}, {"en": "Soon after the Scarecrow stopped. ''I see a little cottage at the right of us,'' he said, ''built of logs and branches. Shall we go there?''", "fr": "Peu après l''Épouvantail s''arrêta. ''Je vois une petite chaumière à notre droite,'' dit-il, ''construite en rondins et en branches. On y va ?''"}, {"en": "So the Scarecrow led her through the trees until they reached the cottage, and Dorothy entered and found a bed of dried leaves in one corner. She lay down at once, and with Toto beside her soon fell into a sound sleep.", "fr": "Alors l''Épouvantail la guida à travers les arbres jusqu''à la chaumière, et Dorothy entra et trouva un lit de feuilles séchées dans un coin. Elle s''allongea aussitôt, et avec Toto à ses côtés s''endormit profondément."}, {"en": "When Dorothy awoke the sun was shining through the trees and Toto had long been out chasing birds and squirrels. There was the Scarecrow, still standing patiently in his corner, waiting for her.", "fr": "Quand Dorothy se réveilla, le soleil brillait à travers les arbres et Toto était déjà dehors depuis longtemps à chasser oiseaux et écureuils. L''Épouvantail était là, toujours debout patiemment dans son coin, à l''attendre."}, {"en": "''We must go and search for water,'' she said to him. ''To wash my face clean after the dust of the road, and to drink, so the dry bread will not stick in my throat.''", "fr": "''On doit aller chercher de l''eau,'' lui dit-elle. ''Pour me laver le visage de la poussière de la route, et pour boire, pour que le pain sec ne me reste pas dans la gorge.''"}, {"en": "They left the cottage and walked through the trees until they found a little spring of clear water, where Dorothy drank and bathed and ate her breakfast.", "fr": "Ils quittèrent la chaumière et marchèrent à travers les arbres jusqu''à trouver une petite source d''eau claire, où Dorothy but, se lava et prit son petit-déjeuner."}]'::jsonb from b;


with b as (select id from books where title = 'Tome 2 : La forêt et les compagnons' and series_id = (select id from books where title = 'The Wonderful Wizard of Oz' and is_series = true))
insert into book_pages (book_id, page_number, sentences)
select b.id, 4, '[{"en": "When she had finished her meal, she was startled to hear a deep groan near by. ''What was that?'' she asked timidly. ''I cannot imagine,'' replied the Scarecrow; ''but we can go and see.''", "fr": "Quand elle eut fini son repas, elle fut surprise d''entendre un profond gémissement à proximité. ''Qu''est-ce que c''était ?'' demanda-t-elle timidement. ''Je ne peux pas imaginer,'' répondit l''Épouvantail ; ''mais on peut aller voir.''"}, {"en": "One of the big trees had been partly chopped through, and standing beside it, with an uplifted axe in his hands, was a man made entirely of tin. He stood perfectly motionless, as if he could not stir at all.", "fr": "Un des grands arbres avait été partiellement coupé, et debout à côté, une hache levée dans les mains, se tenait un homme entièrement fait d''étain. Il se tenait parfaitement immobile, comme s''il ne pouvait pas bouger du tout."}, {"en": "''Did you groan?'' asked Dorothy. ''Yes,'' answered the tin man, ''I did. I''ve been groaning for more than a year, and no one has ever heard me before or come to help me.''", "fr": "''C''est vous qui avez gémi ?'' demanda Dorothy. ''Oui,'' répondit l''homme de fer-blanc, ''c''est moi. Je gémis depuis plus d''un an, et personne ne m''avait jamais entendu ni n''était venu m''aider.''"}, {"en": "''Get an oil-can and oil my joints,'' he answered. ''They are rusted so badly that I cannot move them at all; if I am well oiled I shall soon be all right again.''", "fr": "''Prenez une burette et huilez mes articulations,'' répondit-il. ''Elles sont si rouillées que je ne peux plus du tout les bouger ; si je suis bien huilé, je serai vite de nouveau en bon état.''"}, {"en": "Dorothy at once ran back to the cottage and found the oil-can. ''Oil my neck, first,'' replied the Tin Woodman. So she oiled it, and the Scarecrow took hold of the tin head and moved it gently until it worked freely.", "fr": "Dorothy courut aussitôt à la chaumière et trouva la burette. ''Huilez mon cou, d''abord,'' répondit l''Homme de Fer-Blanc. Alors elle l''huila, et l''Épouvantail saisit la tête en fer-blanc et la bougea doucement jusqu''à ce qu''elle fonctionne librement."}, {"en": "So they oiled his legs until he could move them freely; and he thanked them again and again for his release. ''I might have stood there always if you had not come along,'' he said; ''so you have certainly saved my life.''", "fr": "Alors ils huilèrent ses jambes jusqu''à ce qu''il puisse les bouger librement ; et il les remercia encore et encore pour sa délivrance. ''J''aurais pu rester debout là pour toujours si vous n''étiez pas passés,'' dit-il ; ''vous m''avez donc certainement sauvé la vie.''"}]'::jsonb from b;


with b as (select id from books where title = 'Tome 2 : La forêt et les compagnons' and series_id = (select id from books where title = 'The Wonderful Wizard of Oz' and is_series = true))
insert into book_pages (book_id, page_number, sentences)
select b.id, 5, '[{"en": "''We are on our way to the Emerald City to see the Great Oz,'' she answered. ''I want him to send me back to Kansas, and the Scarecrow wants him to put a few brains into his head.''", "fr": "''Nous sommes en route vers la Cité d''Émeraude pour voir le Grand Oz,'' répondit-elle. ''Je veux qu''il me renvoie au Kansas, et l''Épouvantail veut qu''il lui mette un peu de cervelle dans la tête.''"}, {"en": "The Tin Woodman appeared to think deeply for a moment. Then he said: ''Do you suppose Oz could give me a heart?'' ''Why, I guess so,'' Dorothy answered.", "fr": "L''Homme de Fer-Blanc parut réfléchir profondément un moment. Puis il dit : ''Pensez-vous qu''Oz pourrait me donner un cœur ?'' ''Eh bien, je suppose que oui,'' répondit Dorothy."}, {"en": "''So, if you will allow me to join your party, I will also go to the Emerald City and ask Oz to help me.'' ''Come along,'' said the Scarecrow heartily, and Dorothy added that she would be pleased to have his company.", "fr": "''Alors, si vous me permettez de me joindre à vous, j''irai aussi à la Cité d''Émeraude demander de l''aide à Oz.'' ''Venez donc,'' dit chaleureusement l''Épouvantail, et Dorothy ajouta qu''elle serait ravie d''avoir sa compagnie."}, {"en": "It was a bit of good luck to have their new comrade join the party, for soon they came to a place where the trees grew so thick over the road that the travelers could not pass. But the Tin Woodman set to work with his axe and cleared a passage.", "fr": "Ce fut une chance d''avoir leur nouveau compagnon, car bientôt ils arrivèrent à un endroit où les arbres poussaient si dru au-dessus de la route que les voyageurs ne pouvaient plus passer. Mais l''Homme de Fer-Blanc se mit au travail avec sa hache et dégagea un passage."}, {"en": "''I don''t know enough,'' replied the Scarecrow cheerfully, when asked why he stumbled. ''My head is stuffed with straw, you know, and that is why I am going to Oz to ask him for some brains.''", "fr": "''Je n''en sais pas assez,'' répondit joyeusement l''Épouvantail, quand on lui demanda pourquoi il trébuchait. ''Ma tête est rembourrée de paille, vous savez, et c''est pourquoi je vais voir Oz pour lui demander de la cervelle.''"}, {"en": "So, while they were walking through the forest, the Tin Woodman told the following story: ''I was born the son of a woodman who chopped down trees in the forest and sold the wood for a living.''", "fr": "Alors, tandis qu''ils marchaient dans la forêt, l''Homme de Fer-Blanc raconta cette histoire : ''Je suis né fils d''un bûcheron qui abattait des arbres dans la forêt et vendait le bois pour vivre.''"}]'::jsonb from b;


with b as (select id from books where title = 'Tome 2 : La forêt et les compagnons' and series_id = (select id from books where title = 'The Wonderful Wizard of Oz' and is_series = true))
insert into book_pages (book_id, page_number, sentences)
select b.id, 6, '[{"en": "He told how he had fallen in love with a Munchkin girl, and how the Wicked Witch of the East had enchanted his axe so that it cut off first his legs, then his arms, then his head, then split his body in two.", "fr": "Il raconta comment il était tombé amoureux d''une jeune Munchkin, et comment la Méchante Sorcière de l''Est avait enchanté sa hache pour qu''elle lui coupe d''abord les jambes, puis les bras, puis la tête, puis fende son corps en deux."}, {"en": "Each time, a tinsmith had replaced the lost part with tin, until at last he was entirely made of tin, but had no heart, and so lost all his love for the Munchkin maiden.", "fr": "Chaque fois, un ferblantier avait remplacé la partie perdue par de l''étain, jusqu''à ce qu''il soit enfin entièrement fait d''étain, mais sans cœur, et perdit ainsi tout son amour pour la jeune Munchkin."}, {"en": "''I had time to think that the greatest loss I had known was the loss of my heart. While I was in love I was the happiest man on earth; but no one can love who has not a heart, and so I am resolved to ask Oz to give me one.''", "fr": "''J''ai eu le temps de penser que la plus grande perte que j''aie connue était la perte de mon cœur. Quand j''étais amoureux, j''étais l''homme le plus heureux du monde ; mais personne ne peut aimer sans cœur, et je suis donc résolu à demander à Oz de m''en donner un.''"}, {"en": "''All the same,'' said the Scarecrow, ''I shall ask for brains instead of a heart; for a fool would not know what to do with a heart if he had one.''", "fr": "''Tout de même,'' dit l''Épouvantail, ''je demanderai de la cervelle plutôt qu''un cœur ; car un idiot ne saurait pas quoi faire d''un cœur s''il en avait un.''"}, {"en": "''I shall take the heart,'' returned the Tin Woodman; ''for brains do not make one happy, and happiness is the best thing in the world.''", "fr": "''Moi je prendrai le cœur,'' répondit l''Homme de Fer-Blanc ; ''car la cervelle ne rend pas heureux, et le bonheur est la meilleure chose au monde.''"}, {"en": "All this time Dorothy and her companions had been walking through the thick woods. Now and then there came a deep growl from some wild animal hidden among the trees.", "fr": "Pendant tout ce temps, Dorothy et ses compagnons avaient marché dans les bois épais. De temps en temps venait un grognement profond de quelque animal sauvage caché parmi les arbres."}]'::jsonb from b;


with b as (select id from books where title = 'Tome 2 : La forêt et les compagnons' and series_id = (select id from books where title = 'The Wonderful Wizard of Oz' and is_series = true))
insert into book_pages (book_id, page_number, sentences)
select b.id, 7, '[{"en": "Just then there came from the forest a terrible roar, and the next moment a great Lion bounded into the road. With one blow of his paw he sent the Scarecrow spinning over and over to the edge of the road.", "fr": "C''est alors qu''un rugissement terrible sortit de la forêt, et l''instant suivant un grand Lion bondit sur la route. D''un coup de patte il envoya l''Épouvantail tournoyer jusqu''au bord de la route."}, {"en": "Little Toto ran barking toward the Lion, and the great beast had opened his mouth to bite the dog, when Dorothy rushed forward and slapped the Lion upon his nose as hard as she could.", "fr": "Le petit Toto courut en aboyant vers le Lion, et la grande bête avait ouvert la gueule pour mordre le chien, quand Dorothy se précipita et gifla le Lion sur le nez aussi fort qu''elle put."}, {"en": "''Don''t you dare to bite Toto! You ought to be ashamed of yourself, a big beast like you, to bite a poor little dog!'' ''I didn''t bite him,'' said the Lion. ''No, but you tried to,'' she retorted. ''You are nothing but a big coward.''", "fr": "''N''ose surtout pas mordre Toto ! Tu devrais avoir honte, une grosse bête comme toi, de mordre un pauvre petit chien !'' ''Je ne l''ai pas mordu,'' dit le Lion. ''Non, mais tu as essayé,'' rétorqua-t-elle. ''Tu n''es qu''un gros lâche.''"}, {"en": "''I know it,'' said the Lion, hanging his head in shame. ''I''ve always known it. But how can I help it?'' ''It''s a mystery,'' replied the Lion. ''I suppose I was born that way.''", "fr": "''Je le sais,'' dit le Lion, baissant la tête de honte. ''Je l''ai toujours su. Mais comment puis-je faire autrement ?'' ''C''est un mystère,'' répondit le Lion. ''Je suppose que je suis né comme ça.''"}, {"en": "''All the other animals in the forest naturally expect me to be brave, for the Lion is everywhere thought to be the King of Beasts. I learned that if I roared very loudly every living thing was frightened and got out of my way.''", "fr": "''Tous les autres animaux de la forêt s''attendent naturellement à ce que je sois courageux, car le Lion est partout considéré comme le Roi des Bêtes. J''ai appris que si je rugissais très fort, chaque créature vivante prenait peur et s''écartait de mon chemin.''"}, {"en": "''Perhaps you have heart disease,'' said the Tin Woodman. ''It may be,'' said the Lion. ''If you have,'' continued the Tin Woodman, ''you ought to be glad, for it proves you have a heart. For my part, I have no heart.''", "fr": "''Vous avez peut-être une maladie de cœur,'' dit l''Homme de Fer-Blanc. ''C''est possible,'' dit le Lion. ''Si c''est le cas,'' continua l''Homme de Fer-Blanc, ''vous devriez être content, car ça prouve que vous avez un cœur. Pour ma part, je n''en ai pas.''"}]'::jsonb from b;


with b as (select id from books where title = 'Tome 2 : La forêt et les compagnons' and series_id = (select id from books where title = 'The Wonderful Wizard of Oz' and is_series = true))
insert into book_pages (book_id, page_number, sentences)
select b.id, 8, '[{"en": "''I am going to the Great Oz to ask him to give me some brains,'' remarked the Scarecrow. ''And I am going to ask him to give me a heart,'' said the Woodman. ''And I am going to ask him to send Toto and me back to Kansas,'' added Dorothy.", "fr": "''Je vais voir le Grand Oz pour lui demander de la cervelle,'' remarqua l''Épouvantail. ''Et moi je vais lui demander un cœur,'' dit l''Homme de Fer-Blanc. ''Et moi je vais lui demander de renvoyer Toto et moi au Kansas,'' ajouta Dorothy."}, {"en": "''Do you think Oz could give me courage?'' asked the Cowardly Lion. ''Just as easily as he could give me brains,'' said the Scarecrow. ''Then, if you don''t mind, I''ll go with you,'' said the Lion.", "fr": "''Pensez-vous qu''Oz pourrait me donner du courage ?'' demanda le Lion Peureux. ''Aussi facilement qu''il pourrait me donner de la cervelle,'' dit l''Épouvantail. ''Alors, si ça ne vous dérange pas, je viens avec vous,'' dit le Lion."}, {"en": "So once more the little company set off upon the journey, the Lion walking with stately strides at Dorothy''s side. Toto did not approve of this new comrade at first, but after a time he became more at ease.", "fr": "Alors une fois de plus la petite troupe se remit en route, le Lion marchant à grandes enjambées majestueuses aux côtés de Dorothy. Toto n''approuvait pas ce nouveau compagnon au début, mais avec le temps il se sentit plus à l''aise."}, {"en": "Once, the Tin Woodman stepped upon a beetle and killed it. This made him very unhappy, for he was always careful not to hurt any living creature, and he wept several tears of sorrow, which rusted his jaw shut.", "fr": "Une fois, l''Homme de Fer-Blanc marcha sur un scarabée et le tua. Cela le rendit très triste, car il faisait toujours attention à ne blesser aucune créature vivante, et il versa quelques larmes de chagrin, qui rouillèrent sa mâchoire."}, {"en": "The Scarecrow seized the oil-can and oiled the Woodman''s jaws. ''This will serve me a lesson,'' said he, ''to look where I step. For crying rusts my jaws so that I cannot speak.''", "fr": "L''Épouvantail saisit la burette et huila les mâchoires de l''Homme de Fer-Blanc. ''Cela me servira de leçon,'' dit-il, ''de regarder où je marche. Car pleurer rouille mes mâchoires au point que je ne peux plus parler.''"}, {"en": "They were obliged to camp out that night under a large tree in the forest. The Scarecrow found a tree full of nuts and filled Dorothy''s basket with them, so that she would not be hungry for a long time.", "fr": "Ils furent obligés de camper cette nuit-là sous un grand arbre dans la forêt. L''Épouvantail trouva un arbre plein de noix et en remplit le panier de Dorothy, pour qu''elle n''ait pas faim pendant longtemps."}]'::jsonb from b;


with b as (select id from books where title = 'Tome 2 : La forêt et les compagnons' and series_id = (select id from books where title = 'The Wonderful Wizard of Oz' and is_series = true))
insert into book_pages (book_id, page_number, sentences)
select b.id, 9, '[{"en": "When it was daylight, the girl bathed her face in a little rippling brook, and soon after they all started toward the Emerald City.", "fr": "Quand le jour se leva, la fillette se lava le visage dans un petit ruisseau clapotant, et peu après ils se dirigèrent tous vers la Cité d''Émeraude."}, {"en": "They had hardly been walking an hour when they saw before them a great ditch that crossed the road and divided the forest as far as they could see on either side.", "fr": "Ils marchaient depuis à peine une heure quand ils virent devant eux un grand fossé qui traversait la route et divisait la forêt aussi loin qu''ils pouvaient voir de chaque côté."}, {"en": "It was a very wide ditch, and when they crept up to the edge and looked into it they could see it was also very deep, and there were many big, jagged rocks at the bottom.", "fr": "C''était un fossé très large, et quand ils s''approchèrent du bord et regardèrent dedans, ils virent qu''il était aussi très profond, avec beaucoup de gros rochers dentelés au fond."}, {"en": "''What shall we do?'' asked Dorothy despairingly. But the Scarecrow said, ''We cannot fly, that is certain. Neither can we climb down into this great ditch. Therefore, if we cannot jump over it, we must stop where we are.''", "fr": "''Qu''est-ce qu''on va faire ?'' demanda Dorothy avec désespoir. Mais l''Épouvantail dit : ''On ne peut pas voler, c''est certain. On ne peut pas non plus descendre dans ce grand fossé. Donc, si on ne peut pas sauter par-dessus, on doit rester où on est.''"}, {"en": "''I think I could jump over it,'' said the Cowardly Lion, after measuring the distance carefully in his mind. ''Then we are all right,'' answered the Scarecrow, ''for you can carry us all over on your back, one at a time.''", "fr": "''Je pense que je pourrais sauter par-dessus,'' dit le Lion Peureux, après avoir soigneusement mesuré la distance dans sa tête. ''Alors tout va bien,'' répondit l''Épouvantail, ''car vous pouvez tous nous porter de l''autre côté sur votre dos, un par un.''"}]'::jsonb from b;
