-- ============================================
-- LUMA — Vocabulaire par thème : Niveau 2 et Niveau 3 pour les 10 thèmes
-- 400 nouveaux mots, 120 nouveaux exercices.
-- ============================================

with t as (select id from vocab_themes where slug = 'cuisine')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 2, 'Niveau 2', '[{"en": "chop", "fr": "couper/hacher", "level": "A2"}, {"en": "marinate", "fr": "mariner", "level": "B1"}, {"en": "grate", "fr": "râper", "level": "B1"}, {"en": "whisk", "fr": "fouetter", "level": "B1"}, {"en": "bland", "fr": "fade (goût)", "level": "B1"}, {"en": "savory", "fr": "salé/savoureux", "level": "B2"}, {"en": "crispy", "fr": "croustillant", "level": "A2"}, {"en": "stale", "fr": "rassis", "level": "B1"}, {"en": "portion", "fr": "portion", "level": "A2"}, {"en": "leftover", "fr": "reste (adj)", "level": "B1"}, {"en": "preheat", "fr": "préchauffer", "level": "A2"}, {"en": "drizzle", "fr": "arroser (d''un filet)", "level": "B2"}, {"en": "garnish", "fr": "garniture", "level": "B1"}, {"en": "tender", "fr": "tendre", "level": "B1"}, {"en": "overcooked", "fr": "trop cuit", "level": "A2"}, {"en": "undercooked", "fr": "pas assez cuit", "level": "A2"}, {"en": "takeout", "fr": "à emporter", "level": "A2"}, {"en": "reservation", "fr": "réservation", "level": "A2"}, {"en": "allergy", "fr": "allergie", "level": "A2"}, {"en": "vegetarian", "fr": "végétarien", "level": "A1"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'cuisine') and position = 2)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'cuisine'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"couper/hacher\" = ?", "options": ["preheat", "vegetarian", "allergy", "chop"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"chop\"."}'),(2, 'qcm', '{"question": "\"fouetter\" = ?", "options": ["whisk", "stale", "undercooked", "drizzle"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"whisk\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "crispy", "right": "croustillant"}, {"left": "stale", "right": "rassis"}, {"left": "portion", "right": "portion"}, {"left": "leftover", "right": "reste (adj)"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "garnish", "right": "garniture"}, {"left": "tender", "right": "tendre"}, {"left": "overcooked", "right": "trop cuit"}, {"left": "undercooked", "right": "pas assez cuit"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"réservation\" = ", "sentence_after": "", "correct_answers": ["reservation"], "feedback_correct": "Correct !", "feedback_incorrect": "\"réservation\" se dit \"reservation\" en anglais."}'),(6, 'true_false', '{"statement": "\"vegetarian\" veut dire \"végétarien\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'cuisine')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 3, 'Niveau 3', '[{"en": "simmering", "fr": "qui mijote", "level": "B2"}, {"en": "caramelize", "fr": "caraméliser", "level": "B2"}, {"en": "zest", "fr": "zeste", "level": "B1"}, {"en": "infuse", "fr": "infuser", "level": "B1"}, {"en": "umami", "fr": "umami (saveur)", "level": "C1"}, {"en": "fermented", "fr": "fermenté", "level": "B2"}, {"en": "aromatic", "fr": "aromatique", "level": "B1"}, {"en": "wholesome", "fr": "sain/nourrissant", "level": "B2"}, {"en": "indulgent", "fr": "gourmand/excessif", "level": "C1"}, {"en": "palate", "fr": "palais (goût)", "level": "C1"}, {"en": "condiment", "fr": "condiment", "level": "B1"}, {"en": "staple", "fr": "aliment de base", "level": "B1"}, {"en": "gourmet", "fr": "gastronomique", "level": "B1"}, {"en": "bite-sized", "fr": "à croquer", "level": "B1"}, {"en": "plating", "fr": "dressage (assiette)", "level": "C1"}, {"en": "texture", "fr": "texture", "level": "A2"}, {"en": "overindulge", "fr": "abuser (nourriture)", "level": "C1"}, {"en": "craving", "fr": "envie irrésistible", "level": "B1"}, {"en": "nutritious", "fr": "nutritif", "level": "B1"}, {"en": "bitter", "fr": "amer", "level": "A2"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'cuisine') and position = 3)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'cuisine'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"qui mijote\" = ?", "options": ["nutritious", "simmering", "condiment", "indulgent"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"simmering\"."}'),(2, 'qcm', '{"question": "\"infuser\" = ?", "options": ["bitter", "zest", "infuse", "fermented"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"infuse\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "aromatic", "right": "aromatique"}, {"left": "wholesome", "right": "sain/nourrissant"}, {"left": "indulgent", "right": "gourmand/excessif"}, {"left": "palate", "right": "palais (goût)"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "gourmet", "right": "gastronomique"}, {"left": "bite-sized", "right": "à croquer"}, {"left": "plating", "right": "dressage (assiette)"}, {"left": "texture", "right": "texture"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"envie irrésistible\" = ", "sentence_after": "", "correct_answers": ["craving"], "feedback_correct": "Correct !", "feedback_incorrect": "\"envie irrésistible\" se dit \"craving\" en anglais."}'),(6, 'true_false', '{"statement": "\"bitter\" veut dire \"amer\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'technologie')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 2, 'Niveau 2', '[{"en": "firmware", "fr": "micrologiciel", "level": "C1"}, {"en": "hardware", "fr": "matériel", "level": "B1"}, {"en": "software", "fr": "logiciel", "level": "A2"}, {"en": "bandwidth", "fr": "bande passante", "level": "B2"}, {"en": "server", "fr": "serveur", "level": "B1"}, {"en": "interface", "fr": "interface", "level": "B1"}, {"en": "bug", "fr": "bogue", "level": "A2"}, {"en": "patch", "fr": "correctif", "level": "B2"}, {"en": "router", "fr": "routeur", "level": "B1"}, {"en": "streaming", "fr": "diffusion en continu", "level": "A2"}, {"en": "encryption", "fr": "chiffrement", "level": "C1"}, {"en": "firewall", "fr": "pare-feu", "level": "B2"}, {"en": "plug in", "fr": "brancher", "level": "A1"}, {"en": "shortcut", "fr": "raccourci", "level": "A2"}, {"en": "touchscreen", "fr": "écran tactile", "level": "A2"}, {"en": "compatible", "fr": "compatible", "level": "B1"}, {"en": "crash (verb)", "fr": "planter (logiciel)", "level": "A2"}, {"en": "restart", "fr": "redémarrer", "level": "A1"}, {"en": "outdated", "fr": "obsolète", "level": "B1"}, {"en": "subscription", "fr": "abonnement", "level": "A2"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'technologie') and position = 2)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'technologie'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"micrologiciel\" = ?", "options": ["subscription", "encryption", "plug in", "firmware"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"firmware\"."}'),(2, 'qcm', '{"question": "\"bande passante\" = ?", "options": ["patch", "shortcut", "firewall", "bandwidth"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"bandwidth\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "bug", "right": "bogue"}, {"left": "patch", "right": "correctif"}, {"left": "router", "right": "routeur"}, {"left": "streaming", "right": "diffusion en continu"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "plug in", "right": "brancher"}, {"left": "shortcut", "right": "raccourci"}, {"left": "touchscreen", "right": "écran tactile"}, {"left": "compatible", "right": "compatible"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"redémarrer\" = ", "sentence_after": "", "correct_answers": ["restart"], "feedback_correct": "Correct !", "feedback_incorrect": "\"redémarrer\" se dit \"restart\" en anglais."}'),(6, 'true_false', '{"statement": "\"subscription\" veut dire \"abonnement\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'technologie')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 3, 'Niveau 3', '[{"en": "artificial intelligence", "fr": "intelligence artificielle", "level": "B1"}, {"en": "algorithm", "fr": "algorithme", "level": "B1"}, {"en": "data breach", "fr": "fuite de données", "level": "C1"}, {"en": "cybersecurity", "fr": "cybersécurité", "level": "B2"}, {"en": "virtual reality", "fr": "réalité virtuelle", "level": "B1"}, {"en": "automation", "fr": "automatisation", "level": "B2"}, {"en": "scalable", "fr": "évolutif (système)", "level": "C1"}, {"en": "latency", "fr": "latence", "level": "C1"}, {"en": "interface (verb)", "fr": "s''interfacer", "level": "C1"}, {"en": "obsolescence", "fr": "obsolescence", "level": "C1"}, {"en": "glitchy", "fr": "buggé/instable", "level": "B2"}, {"en": "hands-free", "fr": "mains libres", "level": "B1"}, {"en": "plug-and-play", "fr": "prêt à l''emploi", "level": "B2"}, {"en": "offline", "fr": "hors ligne", "level": "A2"}, {"en": "sync", "fr": "synchroniser", "level": "A2"}, {"en": "throttle", "fr": "brider (débit)", "level": "C1"}, {"en": "bloatware", "fr": "logiciel superflu préinstallé", "level": "C1"}, {"en": "open-source", "fr": "open-source", "level": "B1"}, {"en": "proprietary", "fr": "propriétaire (logiciel)", "level": "C1"}, {"en": "interoperable", "fr": "interopérable", "level": "C1"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'technologie') and position = 3)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'technologie'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"intelligence artificielle\" = ?", "options": ["artificial intelligence", "virtual reality", "scalable", "obsolescence"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"artificial intelligence\"."}'),(2, 'qcm', '{"question": "\"cybersécurité\" = ?", "options": ["obsolescence", "cybersecurity", "hands-free", "open-source"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"cybersecurity\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "scalable", "right": "évolutif (système)"}, {"left": "latency", "right": "latence"}, {"left": "interface (verb)", "right": "s''interfacer"}, {"left": "obsolescence", "right": "obsolescence"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "plug-and-play", "right": "prêt à l''emploi"}, {"left": "offline", "right": "hors ligne"}, {"left": "sync", "right": "synchroniser"}, {"left": "throttle", "right": "brider (débit)"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"open-source\" = ", "sentence_after": "", "correct_answers": ["open-source"], "feedback_correct": "Correct !", "feedback_incorrect": "\"open-source\" se dit \"open-source\" en anglais."}'),(6, 'true_false', '{"statement": "\"interoperable\" veut dire \"interopérable\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'sport')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 2, 'Niveau 2', '[{"en": "stretching", "fr": "étirements", "level": "A2"}, {"en": "endurance", "fr": "endurance", "level": "B1"}, {"en": "cardio", "fr": "cardio", "level": "A2"}, {"en": "agility", "fr": "agilité", "level": "B1"}, {"en": "flexibility", "fr": "souplesse", "level": "B1"}, {"en": "strength training", "fr": "musculation", "level": "B1"}, {"en": "cramp", "fr": "crampe", "level": "A2"}, {"en": "sprain", "fr": "entorse", "level": "B1"}, {"en": "substitute", "fr": "remplaçant (joueur)", "level": "B1"}, {"en": "penalty", "fr": "pénalité", "level": "A2"}, {"en": "draw (match)", "fr": "match nul", "level": "B1"}, {"en": "underdog", "fr": "outsider", "level": "B2"}, {"en": "rivalry", "fr": "rivalité", "level": "B1"}, {"en": "home turf", "fr": "terrain à domicile", "level": "B2"}, {"en": "spectator", "fr": "spectateur", "level": "A2"}, {"en": "cheer", "fr": "encourager", "level": "A2"}, {"en": "commentator", "fr": "commentateur", "level": "B1"}, {"en": "qualify", "fr": "se qualifier", "level": "A2"}, {"en": "eliminate", "fr": "éliminer", "level": "A2"}, {"en": "undefeated", "fr": "invaincu", "level": "B1"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'sport') and position = 2)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'sport'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"étirements\" = ?", "options": ["stretching", "penalty", "draw (match)", "underdog"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"stretching\"."}'),(2, 'qcm', '{"question": "\"agilité\" = ?", "options": ["agility", "cheer", "cardio", "penalty"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"agility\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "cramp", "right": "crampe"}, {"left": "sprain", "right": "entorse"}, {"left": "substitute", "right": "remplaçant (joueur)"}, {"left": "penalty", "right": "pénalité"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "rivalry", "right": "rivalité"}, {"left": "home turf", "right": "terrain à domicile"}, {"left": "spectator", "right": "spectateur"}, {"left": "cheer", "right": "encourager"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"se qualifier\" = ", "sentence_after": "", "correct_answers": ["qualify"], "feedback_correct": "Correct !", "feedback_incorrect": "\"se qualifier\" se dit \"qualify\" en anglais."}'),(6, 'true_false', '{"statement": "\"undefeated\" veut dire \"invaincu\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'sport')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 3, 'Niveau 3', '[{"en": "overtime", "fr": "prolongation", "level": "B1"}, {"en": "stamina", "fr": "résistance", "level": "B2"}, {"en": "comeback", "fr": "retour en force", "level": "B1"}, {"en": "dominant", "fr": "dominant", "level": "B1"}, {"en": "underperform", "fr": "être en dessous du niveau", "level": "C1"}, {"en": "benchwarmer", "fr": "joueur remplaçant", "level": "C1"}, {"en": "hat-trick", "fr": "triplé (buts)", "level": "B2"}, {"en": "nail-biter", "fr": "match à suspense", "level": "C1"}, {"en": "underdog story", "fr": "histoire d''outsider", "level": "C1"}, {"en": "adrenaline rush", "fr": "montée d''adrénaline", "level": "B2"}, {"en": "burnout (sport)", "fr": "épuisement sportif", "level": "C1"}, {"en": "peak performance", "fr": "performance optimale", "level": "B2"}, {"en": "resilience", "fr": "résilience", "level": "B2"}, {"en": "discipline", "fr": "discipline", "level": "A2"}, {"en": "consistency", "fr": "régularité", "level": "B2"}, {"en": "momentum", "fr": "élan/dynamique", "level": "B2"}, {"en": "clutch (adj)", "fr": "décisif sous pression", "level": "C1"}, {"en": "upset (noun)", "fr": "surprise (résultat)", "level": "B2"}, {"en": "veteran (sport)", "fr": "joueur expérimenté", "level": "B1"}, {"en": "rookie", "fr": "débutant/recrue", "level": "B1"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'sport') and position = 3)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'sport'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"prolongation\" = ?", "options": ["veteran (sport)", "underdog story", "overtime", "clutch (adj)"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"overtime\"."}'),(2, 'qcm', '{"question": "\"dominant\" = ?", "options": ["dominant", "hat-trick", "momentum", "benchwarmer"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"dominant\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "hat-trick", "right": "triplé (buts)"}, {"left": "nail-biter", "right": "match à suspense"}, {"left": "underdog story", "right": "histoire d''outsider"}, {"left": "adrenaline rush", "right": "montée d''adrénaline"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "resilience", "right": "résilience"}, {"left": "discipline", "right": "discipline"}, {"left": "consistency", "right": "régularité"}, {"left": "momentum", "right": "élan/dynamique"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"surprise (résultat)\" = ", "sentence_after": "", "correct_answers": ["upset (noun)"], "feedback_correct": "Correct !", "feedback_incorrect": "\"surprise (résultat)\" se dit \"upset (noun)\" en anglais."}'),(6, 'true_false', '{"statement": "\"rookie\" veut dire \"débutant/recrue\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'voyage')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 2, 'Niveau 2', '[{"en": "connecting flight", "fr": "vol de correspondance", "level": "B1"}, {"en": "checked baggage", "fr": "bagage enregistré", "level": "B1"}, {"en": "carry-on", "fr": "bagage à main", "level": "A2"}, {"en": "visa", "fr": "visa", "level": "A2"}, {"en": "border", "fr": "frontière", "level": "A2"}, {"en": "accommodation", "fr": "hébergement", "level": "B1"}, {"en": "guesthouse", "fr": "maison d''hôtes", "level": "A2"}, {"en": "tour guide", "fr": "guide touristique", "level": "A2"}, {"en": "off the beaten path", "fr": "hors des sentiers battus", "level": "B2"}, {"en": "must-see", "fr": "incontournable", "level": "B1"}, {"en": "local cuisine", "fr": "cuisine locale", "level": "A2"}, {"en": "cultural shock", "fr": "choc culturel", "level": "B1"}, {"en": "time zone", "fr": "fuseau horaire", "level": "A2"}, {"en": "delay", "fr": "retard", "level": "A2"}, {"en": "connecting", "fr": "de correspondance", "level": "A2"}, {"en": "overbooked", "fr": "surbooké", "level": "B2"}, {"en": "refundable", "fr": "remboursable", "level": "B1"}, {"en": "nonrefundable", "fr": "non remboursable", "level": "B1"}, {"en": "expedition", "fr": "expédition", "level": "B1"}, {"en": "road trip", "fr": "road trip", "level": "A2"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'voyage') and position = 2)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'voyage'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"vol de correspondance\" = ?", "options": ["tour guide", "connecting flight", "time zone", "border"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"connecting flight\"."}'),(2, 'qcm', '{"question": "\"visa\" = ?", "options": ["visa", "must-see", "expedition", "tour guide"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"visa\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "guesthouse", "right": "maison d''hôtes"}, {"left": "tour guide", "right": "guide touristique"}, {"left": "off the beaten path", "right": "hors des sentiers battus"}, {"left": "must-see", "right": "incontournable"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "time zone", "right": "fuseau horaire"}, {"left": "delay", "right": "retard"}, {"left": "connecting", "right": "de correspondance"}, {"left": "overbooked", "right": "surbooké"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"non remboursable\" = ", "sentence_after": "", "correct_answers": ["nonrefundable"], "feedback_correct": "Correct !", "feedback_incorrect": "\"non remboursable\" se dit \"nonrefundable\" en anglais."}'),(6, 'true_false', '{"statement": "\"road trip\" veut dire \"road trip\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'voyage')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 3, 'Niveau 3', '[{"en": "nomadic", "fr": "nomade", "level": "B2"}, {"en": "immersive", "fr": "immersif", "level": "B2"}, {"en": "itinerant", "fr": "itinérant", "level": "C1"}, {"en": "hospitality", "fr": "hospitalité", "level": "B1"}, {"en": "cultural immersion", "fr": "immersion culturelle", "level": "B2"}, {"en": "off-season", "fr": "hors saison", "level": "B1"}, {"en": "peak season", "fr": "haute saison", "level": "B1"}, {"en": "all-inclusive", "fr": "tout compris", "level": "B1"}, {"en": "visa-free", "fr": "sans visa", "level": "B2"}, {"en": "remote destination", "fr": "destination reculée", "level": "B2"}, {"en": "indigenous", "fr": "indigène/autochtone", "level": "B2"}, {"en": "carbon footprint", "fr": "empreinte carbone", "level": "B2"}, {"en": "sustainable tourism", "fr": "tourisme durable", "level": "B2"}, {"en": "expat", "fr": "expatrié", "level": "B1"}, {"en": "repatriate", "fr": "rapatrier", "level": "C1"}, {"en": "cross-border", "fr": "transfrontalier", "level": "C1"}, {"en": "visa run", "fr": "voyage pour renouveler son visa", "level": "C1"}, {"en": "layover", "fr": "escale longue", "level": "B1"}, {"en": "overland", "fr": "par voie terrestre", "level": "B2"}, {"en": "acclimatize", "fr": "s''acclimater", "level": "B2"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'voyage') and position = 3)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'voyage'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"nomade\" = ?", "options": ["carbon footprint", "nomadic", "visa-free", "cross-border"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"nomadic\"."}'),(2, 'qcm', '{"question": "\"hospitalité\" = ?", "options": ["carbon footprint", "hospitality", "off-season", "cultural immersion"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"hospitality\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "peak season", "right": "haute saison"}, {"left": "all-inclusive", "right": "tout compris"}, {"left": "visa-free", "right": "sans visa"}, {"left": "remote destination", "right": "destination reculée"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "sustainable tourism", "right": "tourisme durable"}, {"left": "expat", "right": "expatrié"}, {"left": "repatriate", "right": "rapatrier"}, {"left": "cross-border", "right": "transfrontalier"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"escale longue\" = ", "sentence_after": "", "correct_answers": ["layover"], "feedback_correct": "Correct !", "feedback_incorrect": "\"escale longue\" se dit \"layover\" en anglais."}'),(6, 'true_false', '{"statement": "\"acclimatize\" veut dire \"s''acclimater\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'nature')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 2, 'Niveau 2', '[{"en": "species", "fr": "espèce", "level": "A2"}, {"en": "predator", "fr": "prédateur", "level": "B1"}, {"en": "prey", "fr": "proie", "level": "B1"}, {"en": "migration", "fr": "migration", "level": "B1"}, {"en": "extinct", "fr": "éteint (espèce)", "level": "B1"}, {"en": "coral reef", "fr": "récif corallien", "level": "B1"}, {"en": "glacier", "fr": "glacier", "level": "A2"}, {"en": "volcano", "fr": "volcan", "level": "A2"}, {"en": "erosion", "fr": "érosion", "level": "B1"}, {"en": "fossil", "fr": "fossile", "level": "A2"}, {"en": "canopy", "fr": "canopée", "level": "B2"}, {"en": "terrain", "fr": "terrain", "level": "A2"}, {"en": "watershed", "fr": "bassin versant", "level": "C1"}, {"en": "marine life", "fr": "vie marine", "level": "B1"}, {"en": "carbon emission", "fr": "émission de carbone", "level": "B2"}, {"en": "solar power", "fr": "énergie solaire", "level": "A2"}, {"en": "wind turbine", "fr": "éolienne", "level": "B1"}, {"en": "organic", "fr": "biologique", "level": "A2"}, {"en": "compost", "fr": "compost", "level": "A2"}, {"en": "air quality", "fr": "qualité de l''air", "level": "B1"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'nature') and position = 2)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'nature'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"espèce\" = ?", "options": ["fossil", "carbon emission", "species", "glacier"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"species\"."}'),(2, 'qcm', '{"question": "\"migration\" = ?", "options": ["species", "predator", "migration", "compost"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"migration\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "glacier", "right": "glacier"}, {"left": "volcano", "right": "volcan"}, {"left": "erosion", "right": "érosion"}, {"left": "fossil", "right": "fossile"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "watershed", "right": "bassin versant"}, {"left": "marine life", "right": "vie marine"}, {"left": "carbon emission", "right": "émission de carbone"}, {"left": "solar power", "right": "énergie solaire"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"biologique\" = ", "sentence_after": "", "correct_answers": ["organic"], "feedback_correct": "Correct !", "feedback_incorrect": "\"biologique\" se dit \"organic\" en anglais."}'),(6, 'true_false', '{"statement": "\"air quality\" veut dire \"qualité de l''air\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'nature')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 3, 'Niveau 3', '[{"en": "carbon-neutral", "fr": "neutre en carbone", "level": "B2"}, {"en": "reforestation", "fr": "reboisement", "level": "B1"}, {"en": "overfishing", "fr": "surpêche", "level": "B2"}, {"en": "poaching", "fr": "braconnage", "level": "B2"}, {"en": "invasive species", "fr": "espèce invasive", "level": "B2"}, {"en": "food chain", "fr": "chaîne alimentaire", "level": "B1"}, {"en": "carbon offset", "fr": "compensation carbone", "level": "C1"}, {"en": "keystone species", "fr": "espèce clé de voûte", "level": "C1"}, {"en": "permafrost", "fr": "pergélisol", "level": "C1"}, {"en": "acid rain", "fr": "pluie acide", "level": "B1"}, {"en": "ozone layer", "fr": "couche d''ozone", "level": "B1"}, {"en": "carbon sink", "fr": "puits de carbone", "level": "C1"}, {"en": "eco-friendly", "fr": "écologique", "level": "A2"}, {"en": "green energy", "fr": "énergie verte", "level": "A2"}, {"en": "environmental impact", "fr": "impact environnemental", "level": "B1"}, {"en": "mitigate", "fr": "atténuer", "level": "C1"}, {"en": "resilient ecosystem", "fr": "écosystème résilient", "level": "C1"}, {"en": "apex predator", "fr": "superprédateur", "level": "C1"}, {"en": "symbiosis", "fr": "symbiose", "level": "C1"}, {"en": "thriving", "fr": "florissant/prospère", "level": "B2"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'nature') and position = 3)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'nature'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"neutre en carbone\" = ?", "options": ["environmental impact", "keystone species", "reforestation", "carbon-neutral"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"carbon-neutral\"."}'),(2, 'qcm', '{"question": "\"braconnage\" = ?", "options": ["ozone layer", "carbon offset", "thriving", "poaching"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"poaching\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "carbon offset", "right": "compensation carbone"}, {"left": "keystone species", "right": "espèce clé de voûte"}, {"left": "permafrost", "right": "pergélisol"}, {"left": "acid rain", "right": "pluie acide"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "eco-friendly", "right": "écologique"}, {"left": "green energy", "right": "énergie verte"}, {"left": "environmental impact", "right": "impact environnemental"}, {"left": "mitigate", "right": "atténuer"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"superprédateur\" = ", "sentence_after": "", "correct_answers": ["apex predator"], "feedback_correct": "Correct !", "feedback_incorrect": "\"superprédateur\" se dit \"apex predator\" en anglais."}'),(6, 'true_false', '{"statement": "\"thriving\" veut dire \"florissant/prospère\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'mode')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 2, 'Niveau 2', '[{"en": "tailor", "fr": "tailleur (métier)", "level": "B1"}, {"en": "hem", "fr": "ourlet", "level": "B1"}, {"en": "stitch", "fr": "point de couture", "level": "B1"}, {"en": "pattern", "fr": "motif", "level": "A2"}, {"en": "designer", "fr": "créateur/styliste", "level": "A2"}, {"en": "collection", "fr": "collection", "level": "A2"}, {"en": "catwalk", "fr": "podium (défilé)", "level": "B1"}, {"en": "boutique", "fr": "boutique", "level": "A1"}, {"en": "outlet", "fr": "magasin d''usine", "level": "B1"}, {"en": "layer (clothing)", "fr": "superposer", "level": "B1"}, {"en": "thrift store", "fr": "friperie", "level": "B1"}, {"en": "vintage", "fr": "vintage", "level": "B1"}, {"en": "statement piece", "fr": "pièce forte (look)", "level": "B2"}, {"en": "versatile", "fr": "polyvalent", "level": "B1"}, {"en": "tight-fitting", "fr": "ajusté", "level": "B1"}, {"en": "loose-fitting", "fr": "ample", "level": "B1"}, {"en": "footwear", "fr": "chaussures (général)", "level": "B1"}, {"en": "tailored", "fr": "sur mesure", "level": "B1"}, {"en": "sustainable fashion", "fr": "mode durable", "level": "B1"}, {"en": "fast fashion", "fr": "mode éphémère", "level": "B2"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'mode') and position = 2)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'mode'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"tailleur (métier)\" = ?", "options": ["tight-fitting", "hem", "fast fashion", "tailor"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"tailor\"."}'),(2, 'qcm', '{"question": "\"motif\" = ?", "options": ["thrift store", "pattern", "loose-fitting", "layer (clothing)"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"pattern\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "catwalk", "right": "podium (défilé)"}, {"left": "boutique", "right": "boutique"}, {"left": "outlet", "right": "magasin d''usine"}, {"left": "layer (clothing)", "right": "superposer"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "statement piece", "right": "pièce forte (look)"}, {"left": "versatile", "right": "polyvalent"}, {"left": "tight-fitting", "right": "ajusté"}, {"left": "loose-fitting", "right": "ample"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"sur mesure\" = ", "sentence_after": "", "correct_answers": ["tailored"], "feedback_correct": "Correct !", "feedback_incorrect": "\"sur mesure\" se dit \"tailored\" en anglais."}'),(6, 'true_false', '{"statement": "\"fast fashion\" veut dire \"mode éphémère\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'mode')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 3, 'Niveau 3', '[{"en": "haute couture", "fr": "haute couture", "level": "B2"}, {"en": "silhouette", "fr": "silhouette", "level": "B2"}, {"en": "embroidery", "fr": "broderie", "level": "B1"}, {"en": "tailoring", "fr": "confection sur mesure", "level": "B1"}, {"en": "upcycled", "fr": "recyclé de façon créative", "level": "C1"}, {"en": "capsule wardrobe", "fr": "garde-robe capsule", "level": "C1"}, {"en": "dress code", "fr": "code vestimentaire", "level": "B1"}, {"en": "understated", "fr": "sobre/discret (style)", "level": "C1"}, {"en": "flashy", "fr": "tape-à-l''œil", "level": "B1"}, {"en": "timeless", "fr": "intemporel", "level": "B1"}, {"en": "runway", "fr": "podium de défilé", "level": "B1"}, {"en": "swatch", "fr": "échantillon (tissu)", "level": "C1"}, {"en": "drape", "fr": "tomber (vêtement)", "level": "C1"}, {"en": "cut (fashion)", "fr": "coupe (vêtement)", "level": "B1"}, {"en": "monochrome", "fr": "monochrome", "level": "B1"}, {"en": "accessorize", "fr": "accessoiriser", "level": "B1"}, {"en": "overdressed", "fr": "trop habillé", "level": "B1"}, {"en": "underdressed", "fr": "pas assez habillé", "level": "B1"}, {"en": "chic", "fr": "chic", "level": "A2"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'mode') and position = 3)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'mode'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"haute couture\" = ?", "options": ["timeless", "underdressed", "haute couture", "dress code"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"haute couture\"."}'),(2, 'qcm', '{"question": "\"confection sur mesure\" = ?", "options": ["tailoring", "chic", "swatch", "timeless"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"tailoring\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "dress code", "right": "code vestimentaire"}, {"left": "understated", "right": "sobre/discret (style)"}, {"left": "flashy", "right": "tape-à-l''œil"}, {"left": "timeless", "right": "intemporel"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "drape", "right": "tomber (vêtement)"}, {"left": "cut (fashion)", "right": "coupe (vêtement)"}, {"left": "monochrome", "right": "monochrome"}, {"left": "accessorize", "right": "accessoiriser"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"pas assez habillé\" = ", "sentence_after": "", "correct_answers": ["underdressed"], "feedback_correct": "Correct !", "feedback_incorrect": "\"pas assez habillé\" se dit \"underdressed\" en anglais."}'),(6, 'true_false', '{"statement": "\"silhouette\" veut dire \"silhouette\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'sante')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 2, 'Niveau 2', '[{"en": "diagnosis", "fr": "diagnostic", "level": "B1"}, {"en": "treatment", "fr": "traitement", "level": "A2"}, {"en": "side effect", "fr": "effet secondaire", "level": "B1"}, {"en": "dosage", "fr": "dosage", "level": "B1"}, {"en": "physical therapy", "fr": "kinésithérapie", "level": "B1"}, {"en": "blood pressure", "fr": "tension artérielle", "level": "B1"}, {"en": "chronic", "fr": "chronique", "level": "B1"}, {"en": "infection", "fr": "infection", "level": "A2"}, {"en": "vaccine", "fr": "vaccin", "level": "A2"}, {"en": "first aid", "fr": "premiers secours", "level": "A2"}, {"en": "emergency room", "fr": "urgences (hôpital)", "level": "A2"}, {"en": "stitches (medical)", "fr": "points de suture", "level": "B1"}, {"en": "cast (medical)", "fr": "plâtre", "level": "A2"}, {"en": "crutches", "fr": "béquilles", "level": "B1"}, {"en": "insomnia", "fr": "insomnie", "level": "B1"}, {"en": "mental health", "fr": "santé mentale", "level": "B1"}, {"en": "stress relief", "fr": "soulagement du stress", "level": "B1"}, {"en": "nutrient", "fr": "nutriment", "level": "B1"}, {"en": "hydration", "fr": "hydratation", "level": "B1"}, {"en": "posture", "fr": "posture", "level": "A2"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'sante') and position = 2)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'sante'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"diagnostic\" = ?", "options": ["insomnia", "nutrient", "mental health", "diagnosis"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"diagnosis\"."}'),(2, 'qcm', '{"question": "\"dosage\" = ?", "options": ["stitches (medical)", "dosage", "insomnia", "physical therapy"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"dosage\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "chronic", "right": "chronique"}, {"left": "infection", "right": "infection"}, {"left": "vaccine", "right": "vaccin"}, {"left": "first aid", "right": "premiers secours"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "cast (medical)", "right": "plâtre"}, {"left": "crutches", "right": "béquilles"}, {"left": "insomnia", "right": "insomnie"}, {"left": "mental health", "right": "santé mentale"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"nutriment\" = ", "sentence_after": "", "correct_answers": ["nutrient"], "feedback_correct": "Correct !", "feedback_incorrect": "\"nutriment\" se dit \"nutrient\" en anglais."}'),(6, 'true_false', '{"statement": "\"posture\" veut dire \"posture\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'sante')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 3, 'Niveau 3', '[{"en": "chronic condition", "fr": "maladie chronique", "level": "B2"}, {"en": "preventive care", "fr": "soins préventifs", "level": "B2"}, {"en": "holistic", "fr": "holistique", "level": "C1"}, {"en": "underlying condition", "fr": "condition sous-jacente", "level": "C1"}, {"en": "relapse", "fr": "rechute", "level": "B2"}, {"en": "remission", "fr": "rémission", "level": "C1"}, {"en": "intolerance", "fr": "intolérance", "level": "B1"}, {"en": "autoimmune", "fr": "auto-immun", "level": "C1"}, {"en": "inflammation", "fr": "inflammation", "level": "B1"}, {"en": "well-rounded diet", "fr": "alimentation équilibrée", "level": "B1"}, {"en": "burnout (health)", "fr": "épuisement (santé)", "level": "B2"}, {"en": "mindfulness", "fr": "pleine conscience", "level": "B1"}, {"en": "resilience (mental)", "fr": "résilience mentale", "level": "B2"}, {"en": "therapy session", "fr": "séance de thérapie", "level": "B1"}, {"en": "prescription refill", "fr": "renouvellement d''ordonnance", "level": "B1"}, {"en": "bedside manner", "fr": "tact envers le patient", "level": "C1"}, {"en": "outpatient", "fr": "patient externe", "level": "C1"}, {"en": "in-patient", "fr": "patient hospitalisé", "level": "C1"}, {"en": "recovery time", "fr": "temps de convalescence", "level": "B1"}, {"en": "dietary restriction", "fr": "restriction alimentaire", "level": "B1"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'sante') and position = 3)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'sante'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"maladie chronique\" = ?", "options": ["burnout (health)", "chronic condition", "dietary restriction", "autoimmune"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"chronic condition\"."}'),(2, 'qcm', '{"question": "\"condition sous-jacente\" = ?", "options": ["bedside manner", "resilience (mental)", "burnout (health)", "underlying condition"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"underlying condition\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "intolerance", "right": "intolérance"}, {"left": "autoimmune", "right": "auto-immun"}, {"left": "inflammation", "right": "inflammation"}, {"left": "well-rounded diet", "right": "alimentation équilibrée"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "resilience (mental)", "right": "résilience mentale"}, {"left": "therapy session", "right": "séance de thérapie"}, {"left": "prescription refill", "right": "renouvellement d''ordonnance"}, {"left": "bedside manner", "right": "tact envers le patient"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"patient hospitalisé\" = ", "sentence_after": "", "correct_answers": ["in-patient"], "feedback_correct": "Correct !", "feedback_incorrect": "\"patient hospitalisé\" se dit \"in-patient\" en anglais."}'),(6, 'true_false', '{"statement": "\"dietary restriction\" veut dire \"restriction alimentaire\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'travail')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 2, 'Niveau 2', '[{"en": "supervisor", "fr": "superviseur", "level": "A2"}, {"en": "performance review", "fr": "évaluation de performance", "level": "B1"}, {"en": "onboarding", "fr": "intégration (nouvel employé)", "level": "B1"}, {"en": "headhunter", "fr": "chasseur de têtes", "level": "B1"}, {"en": "shift (work)", "fr": "poste/équipe de travail", "level": "A2"}, {"en": "probation period", "fr": "période d''essai", "level": "B1"}, {"en": "severance", "fr": "indemnité de licenciement", "level": "C1"}, {"en": "layoff", "fr": "licenciement (économique)", "level": "B1"}, {"en": "remote work", "fr": "télétravail", "level": "A2"}, {"en": "work-life balance", "fr": "équilibre vie pro/perso", "level": "B1"}, {"en": "networking", "fr": "réseautage", "level": "B1"}, {"en": "mentor", "fr": "mentor", "level": "A2"}, {"en": "proactive", "fr": "proactif", "level": "B1"}, {"en": "multitask", "fr": "faire plusieurs choses à la fois", "level": "B1"}, {"en": "delegate", "fr": "déléguer", "level": "B1"}, {"en": "stakeholder", "fr": "partie prenante", "level": "B2"}, {"en": "kpi", "fr": "indicateur clé de performance", "level": "B2"}, {"en": "workflow", "fr": "flux de travail", "level": "B1"}, {"en": "micromanage", "fr": "microgérer", "level": "C1"}, {"en": "upskill", "fr": "monter en compétences", "level": "C1"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'travail') and position = 2)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'travail'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"superviseur\" = ?", "options": ["supervisor", "layoff", "networking", "proactive"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"supervisor\"."}'),(2, 'qcm', '{"question": "\"chasseur de têtes\" = ?", "options": ["layoff", "headhunter", "stakeholder", "upskill"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"headhunter\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "severance", "right": "indemnité de licenciement"}, {"left": "layoff", "right": "licenciement (économique)"}, {"left": "remote work", "right": "télétravail"}, {"left": "work-life balance", "right": "équilibre vie pro/perso"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "proactive", "right": "proactif"}, {"left": "multitask", "right": "faire plusieurs choses à la fois"}, {"left": "delegate", "right": "déléguer"}, {"left": "stakeholder", "right": "partie prenante"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"flux de travail\" = ", "sentence_after": "", "correct_answers": ["workflow"], "feedback_correct": "Correct !", "feedback_incorrect": "\"flux de travail\" se dit \"workflow\" en anglais."}'),(6, 'true_false', '{"statement": "\"upskill\" veut dire \"monter en compétences\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'travail')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 3, 'Niveau 3', '[{"en": "corporate ladder", "fr": "échelle hiérarchique", "level": "B2"}, {"en": "glass ceiling", "fr": "plafond de verre", "level": "C1"}, {"en": "golden handshake", "fr": "prime de départ généreuse", "level": "C1"}, {"en": "headcount", "fr": "effectif (personnel)", "level": "C1"}, {"en": "cross-functional", "fr": "transversal (équipe)", "level": "C1"}, {"en": "bandwidth (work)", "fr": "disponibilité/capacité", "level": "C1"}, {"en": "touch base", "fr": "faire le point", "level": "B2"}, {"en": "circle back", "fr": "revenir sur un sujet plus tard", "level": "B2"}, {"en": "low-hanging fruit", "fr": "solution facile/rapide", "level": "C1"}, {"en": "bottleneck", "fr": "goulot d''étranglement", "level": "C1"}, {"en": "scalability", "fr": "capacité à évoluer", "level": "C1"}, {"en": "pivot (business)", "fr": "changer de stratégie", "level": "B2"}, {"en": "streamline", "fr": "simplifier/rationaliser", "level": "C1"}, {"en": "synergy", "fr": "synergie", "level": "C1"}, {"en": "buy-in", "fr": "adhésion (soutien)", "level": "C1"}, {"en": "red tape", "fr": "bureaucratie excessive", "level": "C1"}, {"en": "moonlighting", "fr": "travail au noir en plus", "level": "C1"}, {"en": "severance package", "fr": "indemnité de départ", "level": "C1"}, {"en": "quiet quitting", "fr": "démission silencieuse", "level": "C1"}, {"en": "gig economy", "fr": "économie des petits boulots", "level": "B2"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'travail') and position = 3)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'travail'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"échelle hiérarchique\" = ?", "options": ["severance package", "red tape", "low-hanging fruit", "corporate ladder"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"corporate ladder\"."}'),(2, 'qcm', '{"question": "\"effectif (personnel)\" = ?", "options": ["corporate ladder", "pivot (business)", "scalability", "headcount"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"headcount\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "touch base", "right": "faire le point"}, {"left": "circle back", "right": "revenir sur un sujet plus tard"}, {"left": "low-hanging fruit", "right": "solution facile/rapide"}, {"left": "bottleneck", "right": "goulot d''étranglement"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "streamline", "right": "simplifier/rationaliser"}, {"left": "synergy", "right": "synergie"}, {"left": "buy-in", "right": "adhésion (soutien)"}, {"left": "red tape", "right": "bureaucratie excessive"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"indemnité de départ\" = ", "sentence_after": "", "correct_answers": ["severance package"], "feedback_correct": "Correct !", "feedback_incorrect": "\"indemnité de départ\" se dit \"severance package\" en anglais."}'),(6, 'true_false', '{"statement": "\"gig economy\" veut dire \"économie des petits boulots\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'maison')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 2, 'Niveau 2', '[{"en": "mortgage", "fr": "prêt immobilier", "level": "B1"}, {"en": "deposit (rent)", "fr": "caution", "level": "B1"}, {"en": "real estate agent", "fr": "agent immobilier", "level": "A2"}, {"en": "open house", "fr": "visite libre (immobilier)", "level": "B1"}, {"en": "appliance", "fr": "appareil électroménager", "level": "A2"}, {"en": "plumbing", "fr": "plomberie", "level": "B1"}, {"en": "electrician", "fr": "électricien", "level": "A2"}, {"en": "insulation", "fr": "isolation", "level": "B1"}, {"en": "ventilation", "fr": "ventilation", "level": "B1"}, {"en": "basement", "fr": "sous-sol", "level": "A2"}, {"en": "attic", "fr": "grenier", "level": "A2"}, {"en": "staircase", "fr": "escalier", "level": "A2"}, {"en": "hallway", "fr": "couloir", "level": "A1"}, {"en": "closet", "fr": "placard", "level": "A1"}, {"en": "fixtures", "fr": "installations fixes", "level": "B1"}, {"en": "floor plan", "fr": "plan de la maison", "level": "B1"}, {"en": "curb appeal", "fr": "attrait extérieur (maison)", "level": "C1"}, {"en": "neighbourhood", "fr": "quartier", "level": "A2"}, {"en": "garden shed", "fr": "cabanon de jardin", "level": "B1"}, {"en": "driveway", "fr": "allée (voiture)", "level": "A2"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'maison') and position = 2)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'maison'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"prêt immobilier\" = ?", "options": ["mortgage", "deposit (rent)", "insulation", "open house"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"mortgage\"."}'),(2, 'qcm', '{"question": "\"visite libre (immobilier)\" = ?", "options": ["appliance", "attic", "open house", "basement"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"open house\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "electrician", "right": "électricien"}, {"left": "insulation", "right": "isolation"}, {"left": "ventilation", "right": "ventilation"}, {"left": "basement", "right": "sous-sol"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "hallway", "right": "couloir"}, {"left": "closet", "right": "placard"}, {"left": "fixtures", "right": "installations fixes"}, {"left": "floor plan", "right": "plan de la maison"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"quartier\" = ", "sentence_after": "", "correct_answers": ["neighbourhood"], "feedback_correct": "Correct !", "feedback_incorrect": "\"quartier\" se dit \"neighbourhood\" en anglais."}'),(6, 'true_false', '{"statement": "\"driveway\" veut dire \"allée (voiture)\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'maison')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 3, 'Niveau 3', '[{"en": "open-plan", "fr": "plan ouvert", "level": "B1"}, {"en": "fixer-upper", "fr": "maison à rénover", "level": "C1"}, {"en": "move-in ready", "fr": "prêt à emménager", "level": "B1"}, {"en": "homeowner''s association", "fr": "copropriété (association)", "level": "C1"}, {"en": "subletting", "fr": "sous-location", "level": "B2"}, {"en": "tenancy", "fr": "location (statut)", "level": "B2"}, {"en": "eviction", "fr": "expulsion", "level": "C1"}, {"en": "gentrification", "fr": "embourgeoisement (quartier)", "level": "C1"}, {"en": "energy-efficient", "fr": "économe en énergie", "level": "B1"}, {"en": "smart home", "fr": "maison connectée", "level": "B1"}, {"en": "upcycle (home)", "fr": "recycler créativement", "level": "C1"}, {"en": "declutter", "fr": "désencombrer", "level": "B1"}, {"en": "mismatched décor", "fr": "décoration dépareillée", "level": "C1"}, {"en": "statement piece (décor)", "fr": "pièce maîtresse (déco)", "level": "C1"}, {"en": "ambiance", "fr": "ambiance", "level": "B1"}, {"en": "cosy nook", "fr": "coin douillet", "level": "B2"}, {"en": "multi-generational household", "fr": "foyer multigénérationnel", "level": "C1"}, {"en": "housework", "fr": "tâches ménagères", "level": "A2"}, {"en": "chore", "fr": "corvée", "level": "A2"}, {"en": "upkeep", "fr": "entretien (maison)", "level": "B2"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'maison') and position = 3)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'maison'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"plan ouvert\" = ?", "options": ["upcycle (home)", "open-plan", "move-in ready", "declutter"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"open-plan\"."}'),(2, 'qcm', '{"question": "\"copropriété (association)\" = ?", "options": ["chore", "statement piece (décor)", "homeowner''s association", "cosy nook"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"homeowner''s association\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "eviction", "right": "expulsion"}, {"left": "gentrification", "right": "embourgeoisement (quartier)"}, {"left": "energy-efficient", "right": "économe en énergie"}, {"left": "smart home", "right": "maison connectée"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "mismatched décor", "right": "décoration dépareillée"}, {"left": "statement piece (décor)", "right": "pièce maîtresse (déco)"}, {"left": "ambiance", "right": "ambiance"}, {"left": "cosy nook", "right": "coin douillet"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"tâches ménagères\" = ", "sentence_after": "", "correct_answers": ["housework"], "feedback_correct": "Correct !", "feedback_incorrect": "\"tâches ménagères\" se dit \"housework\" en anglais."}'),(6, 'true_false', '{"statement": "\"upkeep\" veut dire \"entretien (maison)\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'emotions')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 2, 'Niveau 2', '[{"en": "frustrated", "fr": "frustré", "level": "A2"}, {"en": "relieved", "fr": "soulagé", "level": "A2"}, {"en": "embarrassed", "fr": "gêné", "level": "A2"}, {"en": "proud", "fr": "fier", "level": "A1"}, {"en": "disappointed", "fr": "déçu", "level": "A2"}, {"en": "nostalgic", "fr": "nostalgique", "level": "B1"}, {"en": "hopeful", "fr": "plein d''espoir", "level": "A2"}, {"en": "insecure", "fr": "peu sûr de soi", "level": "B1"}, {"en": "content (adj)", "fr": "satisfait/content", "level": "B1"}, {"en": "restless", "fr": "agité/impatient", "level": "B1"}, {"en": "indifferent", "fr": "indifférent", "level": "B1"}, {"en": "skeptical", "fr": "sceptique", "level": "B1"}, {"en": "optimistic", "fr": "optimiste", "level": "A2"}, {"en": "pessimistic", "fr": "pessimiste", "level": "A2"}, {"en": "compassionate", "fr": "compatissant", "level": "B1"}, {"en": "assertive", "fr": "affirmé/sûr de soi", "level": "B2"}, {"en": "timid", "fr": "timide", "level": "A2"}, {"en": "reserved", "fr": "réservé (caractère)", "level": "B1"}, {"en": "outspoken", "fr": "franc/direct", "level": "B2"}, {"en": "thoughtful", "fr": "attentionné/réfléchi", "level": "B1"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'emotions') and position = 2)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'emotions'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"frustré\" = ?", "options": ["assertive", "frustrated", "nostalgic", "optimistic"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"frustrated\"."}'),(2, 'qcm', '{"question": "\"fier\" = ?", "options": ["proud", "restless", "thoughtful", "disappointed"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"proud\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "hopeful", "right": "plein d''espoir"}, {"left": "insecure", "right": "peu sûr de soi"}, {"left": "content (adj)", "right": "satisfait/content"}, {"left": "restless", "right": "agité/impatient"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "optimistic", "right": "optimiste"}, {"left": "pessimistic", "right": "pessimiste"}, {"left": "compassionate", "right": "compatissant"}, {"left": "assertive", "right": "affirmé/sûr de soi"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"réservé (caractère)\" = ", "sentence_after": "", "correct_answers": ["reserved"], "feedback_correct": "Correct !", "feedback_incorrect": "\"réservé (caractère)\" se dit \"reserved\" en anglais."}'),(6, 'true_false', '{"statement": "\"thoughtful\" veut dire \"attentionné/réfléchi\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'emotions')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 3, 'Niveau 3', '[{"en": "overjoyed", "fr": "aux anges", "level": "B1"}, {"en": "devastated", "fr": "dévasté", "level": "B1"}, {"en": "apprehensive", "fr": "appréhensif", "level": "B2"}, {"en": "conflicted", "fr": "partagé/en conflit intérieur", "level": "B2"}, {"en": "vulnerable", "fr": "vulnérable", "level": "B1"}, {"en": "self-conscious", "fr": "complexé/mal à l''aise", "level": "B2"}, {"en": "melancholic", "fr": "mélancolique", "level": "C1"}, {"en": "euphoric", "fr": "euphorique", "level": "C1"}, {"en": "disheartened", "fr": "découragé", "level": "B2"}, {"en": "indignant", "fr": "indigné", "level": "C1"}, {"en": "apathetic", "fr": "apathique", "level": "C1"}, {"en": "temperamental", "fr": "lunatique/capricieux", "level": "C1"}, {"en": "level-headed", "fr": "pondéré/calme", "level": "C1"}, {"en": "hot-tempered", "fr": "colérique", "level": "B2"}, {"en": "tactful", "fr": "diplomate/plein de tact", "level": "C1"}, {"en": "blunt (personality)", "fr": "direct/brusque", "level": "B2"}, {"en": "introspective", "fr": "introspectif", "level": "C1"}, {"en": "unfazed", "fr": "imperturbable", "level": "C1"}, {"en": "guarded (emotionally)", "fr": "sur la réserve", "level": "C1"}, {"en": "candid", "fr": "franc/spontané", "level": "C1"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'emotions') and position = 3)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'emotions'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"aux anges\" = ?", "options": ["self-conscious", "candid", "overjoyed", "tactful"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"overjoyed\"."}'),(2, 'qcm', '{"question": "\"partagé/en conflit intérieur\" = ?", "options": ["disheartened", "level-headed", "hot-tempered", "conflicted"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"conflicted\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "melancholic", "right": "mélancolique"}, {"left": "euphoric", "right": "euphorique"}, {"left": "disheartened", "right": "découragé"}, {"left": "indignant", "right": "indigné"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "level-headed", "right": "pondéré/calme"}, {"left": "hot-tempered", "right": "colérique"}, {"left": "tactful", "right": "diplomate/plein de tact"}, {"left": "blunt (personality)", "right": "direct/brusque"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"imperturbable\" = ", "sentence_after": "", "correct_answers": ["unfazed"], "feedback_correct": "Correct !", "feedback_incorrect": "\"imperturbable\" se dit \"unfazed\" en anglais."}'),(6, 'true_false', '{"statement": "\"candid\" veut dire \"franc/spontané\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);
