-- ============================================
-- LUMA — Exercices pratiques pour les 8 fiches de grammaire A1
-- 7 exercices par fiche : 2 QCM, 2 texte à trous, 1 Vrai/Faux, 1 reorder,
-- 1 correction d'erreur. Contenu vérifié avec la même rigueur que l'audit.
-- ============================================

with f as (select id from grammar_fiches where cecr_level = 'A1' and position = 1)
insert into grammar_fiche_exercises (fiche_id, position, type, content)
select f.id, v.position, v.type, v.content::jsonb from f, (values
(1, 'qcm', '{"question": "Complète : She ___ a teacher.", "options": ["am", "is", "are", "be"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"is\"."}'),(2, 'qcm', '{"question": "Complète : ___ they ready?", "options": ["Is", "Are", "Am", "Be"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"Are\"."}'),(3, 'fill_blank', '{"sentence_before": "I ", "sentence_after": " not sure. (négation)", "correct_answers": ["am not", "''m not"], "feedback_correct": "Correct !", "feedback_incorrect": "\"Je ne suis pas\" = I am not / I''m not."}'),(4, 'fill_blank', '{"sentence_before": "", "sentence_after": " he your brother? (question)", "correct_answers": ["Is"], "feedback_correct": "Correct !", "feedback_incorrect": "Question avec to be : Is + sujet ?"}'),(5, 'true_false', '{"statement": "\"I amn''t tired\" is correct English.", "correct_answer": false, "feedback_correct": "Correct !", "feedback_incorrect": "La forme négative de \"I am\" est toujours \"I''m not\", jamais \"amn''t\"."}'),(6, 'reorder', '{"words": ["Is", "she", "a", "doctor?"], "correct_sentence": "Is she a doctor?"}'),(7, 'error_correction', '{"wrong_sentence": "She are my sister.", "correct_sentence": "She is my sister.", "error_word": "are", "feedback_correct": "Bien vu !", "feedback_incorrect": "Regarde le mot en rouge.", "explanation": "\"She\" (3e pers. singulier) se conjugue avec \"is\", pas \"are\"."}')
) as v(position, type, content);

with f as (select id from grammar_fiches where cecr_level = 'A1' and position = 2)
insert into grammar_fiche_exercises (fiche_id, position, type, content)
select f.id, v.position, v.type, v.content::jsonb from f, (values
(1, 'qcm', '{"question": "Complète : He ___ to work by car.", "options": ["go", "goes", "going", "went"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"goes\"."}'),(2, 'qcm', '{"question": "Complète : Do you ___ coffee?", "options": ["like", "likes", "liking", "liked"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"like\"."}'),(3, 'fill_blank', '{"sentence_before": "She ", "sentence_after": " (not, eat) meat. (habitude)", "correct_answers": ["doesn''t eat", "does not eat"], "feedback_correct": "Correct !", "feedback_incorrect": "3e personne + négation : doesn''t + base verbale."}'),(4, 'fill_blank', '{"sentence_before": "", "sentence_after": " it rain a lot here? (question)", "correct_answers": ["Does"], "feedback_correct": "Correct !", "feedback_incorrect": "Question 3e personne : Does + sujet + base verbale ?"}'),(5, 'true_false', '{"statement": "The verb needs an ''-s'' with he/she/it in the present simple.", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Relis la règle."}'),(6, 'reorder', '{"words": ["Does", "he", "play", "tennis?"], "correct_sentence": "Does he play tennis?"}'),(7, 'error_correction', '{"wrong_sentence": "He like pizza.", "correct_sentence": "He likes pizza.", "error_word": "like", "feedback_correct": "Bien vu !", "feedback_incorrect": "Regarde le mot en rouge.", "explanation": "3e personne du singulier → ajoute -s : \"likes\"."}')
) as v(position, type, content);

with f as (select id from grammar_fiches where cecr_level = 'A1' and position = 3)
insert into grammar_fiche_exercises (fiche_id, position, type, content)
select f.id, v.position, v.type, v.content::jsonb from f, (values
(1, 'qcm', '{"question": "Complète : There ___ a cat on the sofa.", "options": ["is", "are", "be", "been"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"is\"."}'),(2, 'qcm', '{"question": "Complète : I need ___ umbrella.", "options": ["a", "an", "the", "Ø"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"an\"."}'),(3, 'fill_blank', '{"sentence_before": "There ", "sentence_after": " five books on the table. (pluriel)", "correct_answers": ["are"], "feedback_correct": "Correct !", "feedback_incorrect": "Pluriel → there are."}'),(4, 'fill_blank', '{"sentence_before": "", "sentence_after": " there a supermarket near here? (question)", "correct_answers": ["Is"], "feedback_correct": "Correct !", "feedback_incorrect": "Singulier → Is there... ?"}'),(5, 'true_false', '{"statement": "''An'' is used before a consonant sound.", "correct_answer": false, "feedback_correct": "Correct !", "feedback_incorrect": "''An'' s''utilise devant un SON voyelle, pas devant une consonne."}'),(6, 'reorder', '{"words": ["Are", "there", "any", "questions?"], "correct_sentence": "Are there any questions?"}'),(7, 'error_correction', '{"wrong_sentence": "There is many books.", "correct_sentence": "There are many books.", "error_word": "is", "feedback_correct": "Bien vu !", "feedback_incorrect": "Regarde le mot en rouge.", "explanation": "\"many books\" est pluriel → there ARE, pas is."}')
) as v(position, type, content);

with f as (select id from grammar_fiches where cecr_level = 'A1' and position = 4)
insert into grammar_fiche_exercises (fiche_id, position, type, content)
select f.id, v.position, v.type, v.content::jsonb from f, (values
(1, 'qcm', '{"question": "Complète : This is ___ book.", "options": ["my", "mine", "I", "me"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"my\"."}'),(2, 'qcm', '{"question": "Complète : Is this bag ___?", "options": ["your", "yours", "you", "ur"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"yours\"."}'),(3, 'fill_blank', '{"sentence_before": "I ", "sentence_after": " two sisters. (have got)", "correct_answers": ["have got", "''ve got"], "feedback_correct": "Correct !", "feedback_incorrect": "Possession, forme britannique : have got."}'),(4, 'fill_blank', '{"sentence_before": "I don''t have ", "sentence_after": " time. (négation)", "correct_answers": ["any"], "feedback_correct": "Correct !", "feedback_incorrect": "Négation + indénombrable : don''t have any."}'),(5, 'true_false', '{"statement": "''His'' and ''her'' agree with the possessor, not with the object owned.", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Relis la règle."}'),(6, 'reorder', '{"words": ["Have", "you", "got", "a", "pen?"], "correct_sentence": "Have you got a pen?"}'),(7, 'error_correction', '{"wrong_sentence": "He loves her job.", "correct_sentence": "He loves his job.", "error_word": "her", "feedback_correct": "Bien vu !", "feedback_incorrect": "Regarde le mot en rouge.", "explanation": "Il aime SON travail (à lui) → his, pas her."}')
) as v(position, type, content);

with f as (select id from grammar_fiches where cecr_level = 'A1' and position = 5)
insert into grammar_fiche_exercises (fiche_id, position, type, content)
select f.id, v.position, v.type, v.content::jsonb from f, (values
(1, 'qcm', '{"question": "Complète : I ___ reading a book right now.", "options": ["am", "is", "are", "be"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"am\"."}'),(2, 'qcm', '{"question": "Complète : What ___ you doing?", "options": ["is", "are", "am", "be"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"are\"."}'),(3, 'fill_blank', '{"sentence_before": "She ", "sentence_after": " to me right now. (not, listen)", "correct_answers": ["isn''t listening", "is not listening"], "feedback_correct": "Correct !", "feedback_incorrect": "Present continuous négatif : isn''t + verbe-ing."}'),(4, 'fill_blank', '{"sentence_before": "", "sentence_after": " it raining outside? (question)", "correct_answers": ["Is"], "feedback_correct": "Correct !", "feedback_incorrect": "Question : Is it + verbe-ing ?"}'),(5, 'true_false', '{"statement": "''Know'' can be used in the present continuous, like ''I am knowing the answer''.", "correct_answer": false, "feedback_correct": "Correct !", "feedback_incorrect": "''Know'' est un verbe d''état, il reste toujours au present simple : ''I know''."}'),(6, 'reorder', '{"words": ["What", "are", "you", "doing?"], "correct_sentence": "What are you doing?"}'),(7, 'error_correction', '{"wrong_sentence": "I am knowing the answer.", "correct_sentence": "I know the answer.", "error_word": "knowing", "feedback_correct": "Bien vu !", "feedback_incorrect": "Regarde le mot en rouge.", "explanation": "''know'' est un verbe d''état → jamais en -ing."}')
) as v(position, type, content);

with f as (select id from grammar_fiches where cecr_level = 'A1' and position = 6)
insert into grammar_fiche_exercises (fiche_id, position, type, content)
select f.id, v.position, v.type, v.content::jsonb from f, (values
(1, 'qcm', '{"question": "Complète : I ___ football yesterday.", "options": ["play", "plays", "played", "playing"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"played\"."}'),(2, 'qcm', '{"question": "Complète : ___ you watch the film?", "options": ["Do", "Did", "Does", "Were"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"Did\"."}'),(3, 'fill_blank', '{"sentence_before": "She ", "sentence_after": " French for two years. (study, régulier)", "correct_answers": ["studied"], "feedback_correct": "Correct !", "feedback_incorrect": "Consonne + y → y devient ied."}'),(4, 'fill_blank', '{"sentence_before": "They ", "sentence_after": " the movie. (not, like)", "correct_answers": ["didn''t like", "did not like"], "feedback_correct": "Correct !", "feedback_incorrect": "Négation passé : didn''t + base verbale."}'),(5, 'true_false', '{"statement": "''Did you worked?'' is correct English.", "correct_answer": false, "feedback_correct": "Correct !", "feedback_incorrect": "Après did, le verbe reste à la base : ''Did you work?''."}'),(6, 'reorder', '{"words": ["Did", "she", "arrive", "on", "time?"], "correct_sentence": "Did she arrive on time?"}'),(7, 'error_correction', '{"wrong_sentence": "Did you worked yesterday?", "correct_sentence": "Did you work yesterday?", "error_word": "worked", "feedback_correct": "Bien vu !", "feedback_incorrect": "Regarde le mot en rouge.", "explanation": "Après \"did\", le verbe reste à la base : \"work\", pas \"worked\"."}')
) as v(position, type, content);

with f as (select id from grammar_fiches where cecr_level = 'A1' and position = 7)
insert into grammar_fiche_exercises (fiche_id, position, type, content)
select f.id, v.position, v.type, v.content::jsonb from f, (values
(1, 'qcm', '{"question": "Complète : I ___ to the cinema last night.", "options": ["go", "goes", "went", "gone"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"went\"."}'),(2, 'qcm', '{"question": "Complète : She ___ a bear in the forest.", "options": ["see", "sees", "saw", "seen"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"saw\"."}'),(3, 'fill_blank', '{"sentence_before": "We ", "sentence_after": " a great time. (have, irrégulier)", "correct_answers": ["had"], "feedback_correct": "Correct !", "feedback_incorrect": "have → had (irrégulier)."}'),(4, 'fill_blank', '{"sentence_before": "He ", "sentence_after": " the answer. (not, know)", "correct_answers": ["didn''t know", "did not know"], "feedback_correct": "Correct !", "feedback_incorrect": "Négation passé : didn''t + base verbale, même pour les irréguliers."}'),(5, 'true_false', '{"statement": "The past simple of ''go'' is ''goed''.", "correct_answer": false, "feedback_correct": "Correct !", "feedback_incorrect": "''go'' est irrégulier : went, pas goed."}'),(6, 'reorder', '{"words": ["They", "took", "the", "train."], "correct_sentence": "They took the train."}'),(7, 'error_correction', '{"wrong_sentence": "I goed to the party.", "correct_sentence": "I went to the party.", "error_word": "goed", "feedback_correct": "Bien vu !", "feedback_incorrect": "Regarde le mot en rouge.", "explanation": "\"go\" est irrégulier → went, jamais goed."}')
) as v(position, type, content);

with f as (select id from grammar_fiches where cecr_level = 'A1' and position = 8)
insert into grammar_fiche_exercises (fiche_id, position, type, content)
select f.id, v.position, v.type, v.content::jsonb from f, (values
(1, 'qcm', '{"question": "Complète : I don''t have ___ money.", "options": ["many", "much", "few", "a few"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"much\"."}'),(2, 'qcm', '{"question": "Complète : There are ___ people here.", "options": ["much", "many", "little", "a little"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"many\"."}'),(3, 'fill_blank', '{"sentence_before": "She has ", "sentence_after": " friends in London. (peu, dénombrable)", "correct_answers": ["a few"], "feedback_correct": "Correct !", "feedback_incorrect": "Dénombrable + sens positif : a few."}'),(4, 'fill_blank', '{"sentence_before": "The cat is ", "sentence_after": " the table. (sous)", "correct_answers": ["under"], "feedback_correct": "Correct !", "feedback_incorrect": "\"sous\" = under."}'),(5, 'true_false', '{"statement": "''Many'' is used with uncountable nouns, like ''many water''.", "correct_answer": false, "feedback_correct": "Correct !", "feedback_incorrect": "''Many'' s''utilise avec du dénombrable. Pour l''indénombrable, on utilise ''much''."}'),(6, 'reorder', '{"words": ["The", "book", "is", "on", "the", "shelf."], "correct_sentence": "The book is on the shelf."}'),(7, 'error_correction', '{"wrong_sentence": "I don''t have many money.", "correct_sentence": "I don''t have much money.", "error_word": "many", "feedback_correct": "Bien vu !", "feedback_incorrect": "Regarde le mot en rouge.", "explanation": "\"money\" est indénombrable → much, pas many."}')
) as v(position, type, content);
