-- ============================================
-- LUMA — Scénarios jouables : Thématique 14 (Road trip USA) — complète (14.2 déjà fait)
-- ============================================

update scenarios set content = '{"characters": {"agent": "l''agent de location"}, "start_node": "n1", "nodes": {"n1": {"speaker": "agent", "text": "Would you like full insurance coverage or the basic plan?", "text_fr": "Vous voulez une couverture d''assurance complète ou le plan de base ?", "choices": [{"text": "Full coverage, better safe than sorry for a road trip.", "next": "n2"}, {"text": "What''s the difference exactly?", "next": "n2b"}]}, "n2": {"speaker": "agent", "text": "Smart choice, it covers everything including tire damage.", "text_fr": "Bon choix, ça couvre tout y compris les dommages aux pneus.", "choices": [{"text": "Perfect, let''s go with that.", "next": "end_full"}]}, "n2b": {"speaker": "agent", "text": "Basic only covers accidents, full covers theft, tires, and windows too.", "text_fr": "Le basique ne couvre que les accidents, le complet couvre aussi le vol, les pneus et les vitres.", "choices": [{"text": "I''ll take full coverage then, for peace of mind.", "next": "end_full"}]}, "end_full": {"speaker": "agent", "text": "Great, here are your keys and contract. Safe travels!", "text_fr": "Parfait, voici vos clés et le contrat. Bon voyage !", "end": true, "ending_label": "Location bien comprise 🚗"}}}'::jsonb, is_playable = true
where title = 'Louer une voiture et comprendre le contrat'
  and theme_id = (select id from scenario_themes where position = 14 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"local": "un voyageur local"}, "start_node": "n1", "nodes": {"n1": {"speaker": "local", "text": "Need help finding something?", "text_fr": "Besoin d''aide pour trouver quelque chose ?", "choices": [{"text": "Yes, what''s the fastest route to Denver from here?", "next": "n2"}]}, "n2": {"speaker": "local", "text": "Take exit 45, it''ll save you almost an hour.", "text_fr": "Prenez la sortie 45, ça vous fera gagner presque une heure.", "choices": [{"text": "That''s a huge help, thank you!", "next": "end_directions"}]}, "end_directions": {"speaker": "local", "text": "No problem, safe travels out there!", "text_fr": "Pas de souci, bonne route !", "end": true, "ending_label": "Itinéraire optimisé 🗺️"}}}'::jsonb, is_playable = true
where title = 'Demander son chemin sur une aire d''autoroute'
  and theme_id = (select id from scenario_themes where position = 14 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"mechanic": "le mécanicien de la station-service"}, "start_node": "n1", "nodes": {"n1": {"speaker": "mechanic", "text": "Looks like your car overheated. Give me an hour to check it.", "text_fr": "On dirait que votre voiture a surchauffé. Laissez-moi une heure pour vérifier.", "choices": [{"text": "Take your time, safety first.", "next": "n2"}, {"text": "Is there anything I can do to help speed things up?", "next": "n2b"}]}, "n2": {"speaker": "mechanic", "text": "Good call, better to fix it right than rush and have issues later.", "text_fr": "Bonne décision, mieux vaut bien réparer plutôt que se précipiter et avoir des problèmes plus tard.", "choices": [{"text": "Agreed, I''ll grab a coffee while I wait.", "next": "end_fixed"}]}, "n2b": {"speaker": "mechanic", "text": "Not really, but I appreciate the offer to help!", "text_fr": "Pas vraiment, mais j''apprécie la proposition d''aide !", "choices": [{"text": "Alright, I''ll wait patiently then.", "next": "end_fixed"}]}, "end_fixed": {"speaker": "mechanic", "text": "All fixed! Just needed more coolant.", "text_fr": "Tout est réparé ! Il manquait juste du liquide de refroidissement.", "end": true, "ending_label": "Panne résolue 🔧"}}}'::jsonb, is_playable = true
where title = 'Une étape imprévue (panne, détour) à gérer'
  and theme_id = (select id from scenario_themes where position = 14 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"local": "une habitante du coin"}, "start_node": "n1", "nodes": {"n1": {"speaker": "local", "text": "Passing through? Not many tourists stop in our little town.", "text_fr": "Vous êtes de passage ? Peu de touristes s''arrêtent dans notre petite ville.", "choices": [{"text": "It''s charming here, what should I see while I''m around?", "next": "n2"}]}, "n2": {"speaker": "local", "text": "Definitely check out the old mill, and Mabel''s diner has the best pie in the state!", "text_fr": "Allez voir le vieux moulin absolument, et le diner de Mabel a la meilleure tarte de l''État !", "choices": [{"text": "I''ll definitely check both out, thank you!", "next": "end_recommend"}]}, "end_recommend": {"speaker": "local", "text": "Enjoy your stay, and say hi to Mabel for me!", "text_fr": "Bon séjour, et dites bonjour à Mabel de ma part !", "end": true, "ending_label": "Belle rencontre locale 🏘️"}}}'::jsonb, is_playable = true
where title = 'Rencontrer des locaux dans une petite ville'
  and theme_id = (select id from scenario_themes where position = 14 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"receptionist": "le réceptionniste"}, "start_node": "n1", "nodes": {"n1": {"speaker": "receptionist", "text": "We have one room left, a double queen, $89 tonight.", "text_fr": "Il nous reste une chambre, deux lits queen, 89$ ce soir.", "choices": [{"text": "We''ll take it, thank you!", "next": "end_booked"}, {"text": "Is breakfast included in that price?", "next": "n2"}]}, "n2": {"speaker": "receptionist", "text": "Yes, continental breakfast from 6 to 10am.", "text_fr": "Oui, petit-déjeuner continental de 6h à 10h.", "choices": [{"text": "Perfect, we''ll take the room.", "next": "end_booked"}]}, "end_booked": {"speaker": "receptionist", "text": "Great, here''s your key. Room 12, down the hall.", "text_fr": "Parfait, voici votre clé. Chambre 12, au fond du couloir.", "end": true, "ending_label": "Chambre réservée juste à temps 🛏️"}}}'::jsonb, is_playable = true
where title = 'Réserver un motel en dernière minute'
  and theme_id = (select id from scenario_themes where position = 14 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"friend": "ton compagnon de route"}, "start_node": "n1", "nodes": {"n1": {"speaker": "friend", "text": "First stop, Nashville! Music city, here we come.", "text_fr": "Premier arrêt, Nashville ! La ville de la musique, nous voilà.", "choices": [{"text": "Let''s find some live music tonight.", "next": "n2"}]}, "n2": {"speaker": "friend", "text": "(after Nashville) On to New Orleans next, though there''s a storm warning.", "text_fr": "(après Nashville) Direction La Nouvelle-Orléans ensuite, même s''il y a une alerte tempête.", "choices": [{"text": "Let''s take an alternate route to be safe.", "next": "n3"}]}, "n3": {"speaker": "friend", "text": "Good call, we avoided the worst of it. Final stop: the coast!", "text_fr": "Bonne décision, on a évité le pire. Dernier arrêt : la côte !", "choices": [{"text": "This trip has honestly exceeded my expectations.", "next": "end_journey"}]}, "end_journey": {"speaker": "friend", "text": "Same here — what an unforgettable adventure!", "text_fr": "Pareil pour moi — quelle aventure inoubliable !", "end": true, "ending_label": "Road trip épique achevé 🛣️"}}}'::jsonb, is_playable = true
where title = 'Un road trip complet sur plusieurs villes avec péripéties'
  and theme_id = (select id from scenario_themes where position = 14 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"traveler": "un autre voyageur"}, "start_node": "n1", "nodes": {"n1": {"speaker": "traveler", "text": "Mind if I join you at this table? Traveling solo can get lonely.", "text_fr": "Ça vous dérange si je me joins à vous ? Voyager seul peut devenir solitaire.", "choices": [{"text": "Not at all, please sit! Where are you headed?", "next": "n2"}]}, "n2": {"speaker": "traveler", "text": "West coast, eventually. You?", "text_fr": "La côte ouest, éventuellement. Et vous ?", "choices": [{"text": "Same direction actually — want to travel together for a bit?", "next": "n3"}]}, "n3": {"speaker": "traveler", "text": "I''d really love that, this trip just got a lot better.", "text_fr": "J''adorerais ça, ce voyage vient de s''améliorer énormément.", "choices": [{"text": "Same here, safety and fun in numbers!", "next": "end_friendship"}]}, "end_friendship": {"speaker": "traveler", "text": "To new friendships and open roads!", "text_fr": "Aux nouvelles amitiés et aux routes ouvertes !", "end": true, "ending_label": "Amitié de voyage née 🚗💛"}}}'::jsonb, is_playable = true
where title = 'Une amitié qui se noue en chemin'
  and theme_id = (select id from scenario_themes where position = 14 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"officer": "un policier local"}, "start_node": "n1", "nodes": {"n1": {"speaker": "officer", "text": "Sir/Ma''am, your car was reported for a broken taillight. License and registration, please.", "text_fr": "Monsieur/Madame, votre voiture a été signalée pour un feu arrière cassé. Permis et carte grise, s''il vous plaît.", "choices": [{"text": "Here you go, officer. I wasn''t aware, I''ll get it fixed right away.", "next": "n2"}]}, "n2": {"speaker": "officer", "text": "I appreciate your cooperation. I''ll let you off with a warning this time.", "text_fr": "J''apprécie votre coopération. Je vous laisse un avertissement cette fois.", "choices": [{"text": "Thank you so much, I''ll have it repaired at the next town.", "next": "end_resolved"}]}, "end_resolved": {"speaker": "officer", "text": "Sounds good, drive safe out there.", "text_fr": "Parfait, conduisez prudemment.", "end": true, "ending_label": "Imprévu géré entièrement en anglais 🚓"}}}'::jsonb, is_playable = true
where title = 'Un imprévu majeur à résoudre entièrement en anglais'
  and theme_id = (select id from scenario_themes where position = 14 and language_id = (select id from languages where code = 'en'));
