-- ============================================
-- LUMA — Thématique 16 : Road trip en Australie (complète)
-- ============================================

with th as (select id from scenario_themes where position = 16 and language_id = (select id from languages where code = 'en'))
insert into scenarios (theme_id, format, cecr_level, title, content, is_playable)
select th.id, 'court', 'A2', 'Trouver une auberge de jeunesse à Sydney', '{"characters": {"receptionist": "la réceptionniste"}, "start_node": "n1", "nodes": {"n1": {"speaker": "receptionist", "text": "G''day! Looking for a bed for the night, or something longer term?", "text_fr": "Salut ! Vous cherchez un lit pour la nuit, ou quelque chose de plus long terme ?", "choices": [{"text": "Just tonight, do you have any dorm beds free?", "next": "n2"}, {"text": "Actually, I''m looking for a weekly rate, I''ll be job hunting.", "next": "n2b"}]}, "n2": {"speaker": "receptionist", "text": "Yep, one bed left in the 6-share dorm, $35 for the night.", "text_fr": "Ouais, il reste un lit dans le dortoir de 6, 35$ la nuit.", "choices": [{"text": "Perfect, I''ll take it.", "next": "end_night"}]}, "n2b": {"speaker": "receptionist", "text": "We''ve got a weekly rate, $210, and we post local job ads on the noticeboard too.", "text_fr": "On a un tarif hebdomadaire, 210$, et on affiche des offres d''emploi locales sur le tableau aussi.", "choices": [{"text": "That''s really helpful, I''ll take the weekly rate.", "next": "end_week"}]}, "end_night": {"speaker": "receptionist", "text": "Sweet, here''s your key, dorm''s just down the hall.", "text_fr": "Super, voici votre clé, le dortoir est juste au bout du couloir.", "end": true, "ending_label": "Logement trouvé 🏨"}, "end_week": {"speaker": "receptionist", "text": "Good luck with the job hunt, mate!", "text_fr": "Bonne chance pour la recherche d''emploi !", "end": true, "ending_label": "Base installée pour la recherche d''emploi 💼"}}}'::jsonb, true from th;

with th as (select id from scenario_themes where position = 16 and language_id = (select id from languages where code = 'en'))
insert into scenarios (theme_id, format, cecr_level, title, content, is_playable)
select th.id, 'court', 'A2-B1', 'Postuler à un job saisonnier dans une ferme', '{"characters": {"farmer": "le fermier"}, "start_node": "n1", "nodes": {"n1": {"speaker": "farmer", "text": "So you''re after fruit picking work? Ever done it before?", "text_fr": "Donc vous cherchez du travail de cueillette ? Vous en avez déjà fait ?", "choices": [{"text": "No, but I''m a fast learner and used to physical work.", "next": "n2"}, {"text": "Yes, I picked grapes back home for a season.", "next": "n2b"}]}, "n2": {"speaker": "farmer", "text": "Fair enough, we''ll start you slow and see how you go.", "text_fr": "D''accord, on va vous démarrer doucement et voir comment ça se passe.", "choices": [{"text": "Sounds good, I''m ready to work hard.", "next": "end_hired"}]}, "n2b": {"speaker": "farmer", "text": "Even better, that experience will help a lot here.", "text_fr": "Encore mieux, cette expérience va bien aider ici.", "choices": [{"text": "Great, when can I start?", "next": "end_hired"}]}, "end_hired": {"speaker": "farmer", "text": "Start tomorrow at 6am, bring a hat and sunscreen!", "text_fr": "Vous commencez demain à 6h, apportez un chapeau et de la crème solaire !", "end": true, "ending_label": "Job saisonnier obtenu 🍇"}}}'::jsonb, true from th;

with th as (select id from scenario_themes where position = 16 and language_id = (select id from languages where code = 'en'))
insert into scenarios (theme_id, format, cecr_level, title, content, is_playable)
select th.id, 'court', 'A2-B1', 'Une rencontre avec la faune sauvage sur la route', '{"characters": {"local": "un local rencontré à une station essence"}, "start_node": "n1", "nodes": {"n1": {"speaker": "local", "text": "Careful on this stretch — kangaroos cross the road a lot at dusk.", "text_fr": "Attention sur ce tronçon — les kangourous traversent souvent la route au crépuscule.", "choices": [{"text": "Thanks for the warning, should I avoid driving at that time?", "next": "n2"}, {"text": "I actually saw one already, it was amazing!", "next": "n2b"}]}, "n2": {"speaker": "local", "text": "Best to avoid dawn and dusk if you can, or just drive slow and stay alert.", "text_fr": "Mieux vaut éviter l''aube et le crépuscule si possible, ou rouler lentement et rester attentif.", "choices": [{"text": "Good advice, I''ll be extra careful.", "next": "end_careful"}]}, "n2b": {"speaker": "local", "text": "Ha, they''re everywhere out here! Just don''t hit one, they can total a car.", "text_fr": "Ha, il y en a partout par ici ! Évitez juste d''en percuter un, ça peut détruire une voiture.", "choices": [{"text": "Noted, I''ll keep my eyes peeled.", "next": "end_careful"}]}, "end_careful": {"speaker": "local", "text": "Safe travels out there, mate.", "text_fr": "Bonne route.", "end": true, "ending_label": "Conseil de sécurité reçu 🦘"}}}'::jsonb, true from th;

with th as (select id from scenario_themes where position = 16 and language_id = (select id from languages where code = 'en'))
insert into scenarios (theme_id, format, cecr_level, title, content, is_playable)
select th.id, 'moyen', 'B1', 'Un entretien pour un job de serveur à Sydney', '{"characters": {"manager": "le gérant du restaurant"}, "start_node": "n1", "nodes": {"n1": {"speaker": "manager", "text": "Have you got your RSA certificate? We can''t hire without it for a bar role.", "text_fr": "Vous avez votre certificat RSA ? On ne peut pas embaucher sans ça pour un poste de bar.", "choices": [{"text": "Yes, I got it last week online, here''s the certificate.", "next": "n2"}, {"text": "Not yet, but I can get it done this week if needed.", "next": "n2b"}]}, "n2": {"speaker": "manager", "text": "Perfect, that''s sorted then. What''s your availability like?", "text_fr": "Parfait, c''est réglé alors. Vos disponibilités sont comment ?", "choices": [{"text": "I''m free every day, very flexible with my schedule.", "next": "n3"}]}, "n2b": {"speaker": "manager", "text": "Alright, get that sorted and come back — I like your attitude though.", "text_fr": "D''accord, réglez ça et revenez — j''aime bien votre attitude cependant.", "choices": [{"text": "I''ll have it done by Friday, thank you for the chance.", "next": "n3"}]}, "n3": {"speaker": "manager", "text": "Great, that flexibility is exactly what we need for weekend shifts.", "text_fr": "Parfait, cette flexibilité est exactement ce qu''il nous faut pour les shifts du week-end.", "choices": [{"text": "Happy to help wherever needed.", "next": "end_hired"}]}, "end_hired": {"speaker": "manager", "text": "Welcome to the team, we''ll start you on Saturday.", "text_fr": "Bienvenue dans l''équipe, vous commencez samedi.", "end": true, "ending_label": "Job de serveur obtenu 🍽️"}}}'::jsonb, true from th;

with th as (select id from scenario_themes where position = 16 and language_id = (select id from languages where code = 'en'))
insert into scenarios (theme_id, format, cecr_level, title, content, is_playable)
select th.id, 'moyen', 'B1', 'Obtenir son Tax File Number', '{"characters": {"agent": "l''agent des impôts (téléphone)"}, "start_node": "n1", "nodes": {"n1": {"speaker": "agent", "text": "So you''re on a working holiday visa? You''ll need a Tax File Number before you start any job.", "text_fr": "Donc vous êtes en visa vacances-travail ? Il vous faut un numéro fiscal avant de commencer tout emploi.", "choices": [{"text": "How do I apply for that?", "next": "n2"}]}, "n2": {"speaker": "agent", "text": "You can apply online through our website, it takes about 10 minutes.", "text_fr": "Vous pouvez faire la demande en ligne sur notre site, ça prend environ 10 minutes.", "choices": [{"text": "How long until I receive it?", "next": "n3"}]}, "n3": {"speaker": "agent", "text": "Usually 10 to 28 business days by mail, so apply as early as possible.", "text_fr": "Généralement 10 à 28 jours ouvrés par courrier, donc faites-en la demande au plus tôt.", "choices": [{"text": "Thank you, I''ll apply today then.", "next": "end_applied"}]}, "end_applied": {"speaker": "agent", "text": "Perfect, good luck with your working holiday!", "text_fr": "Parfait, bonne chance pour votre séjour vacances-travail !", "end": true, "ending_label": "Démarche administrative comprise 📋"}}}'::jsonb, true from th;

with th as (select id from scenario_themes where position = 16 and language_id = (select id from languages where code = 'en'))
insert into scenarios (theme_id, format, cecr_level, title, content, is_playable)
select th.id, 'moyen', 'B1-B2', 'Une panne au milieu de l''Outback', '{"characters": {"trucker": "un chauffeur de road train"}, "start_node": "n1", "nodes": {"n1": {"speaker": "trucker", "text": "Broken down out here? That''s no joke, mate, nearest town is 200km away.", "text_fr": "En panne ici ? C''est du sérieux, la ville la plus proche est à 200km.", "choices": [{"text": "Do you have a way to call for help, or should I use my satellite phone?", "next": "n2"}, {"text": "Could you tow me to the nearest service station?", "next": "n2b"}]}, "n2": {"speaker": "trucker", "text": "Satellite phone''s your best bet out here, no signal for miles.", "text_fr": "Le téléphone satellite est votre meilleure option ici, pas de réseau sur des kilomètres.", "choices": [{"text": "Good thing I brought one, thanks for confirming.", "next": "n3"}]}, "n2b": {"speaker": "trucker", "text": "I can''t tow with this rig, but I''ll radio ahead for help.", "text_fr": "Je ne peux pas remorquer avec ce camion, mais je vais appeler par radio pour de l''aide.", "choices": [{"text": "I really appreciate that, thank you.", "next": "n3"}]}, "n3": {"speaker": "trucker", "text": "Always carry extra water out here — you''ve got some, right?", "text_fr": "Il faut toujours avoir de l''eau en plus ici — vous en avez, hein ?", "choices": [{"text": "Yes, I always keep several bottles in the car.", "next": "end_safe"}]}, "end_safe": {"speaker": "trucker", "text": "Smart traveler. Help should reach you within a few hours.", "text_fr": "Voyageur prévoyant. Les secours devraient arriver dans quelques heures.", "end": true, "ending_label": "Panne gérée en sécurité 🚛"}}}'::jsonb, true from th;

with th as (select id from scenario_themes where position = 16 and language_id = (select id from languages where code = 'en'))
insert into scenarios (theme_id, format, cecr_level, title, content, is_playable)
select th.id, 'long', 'B1-B2', 'Un mois de travail saisonnier complet dans une ferme', '{"characters": {"farmer": "le fermier", "coworker": "un collègue backpacker"}, "start_node": "n1", "nodes": {"n1": {"speaker": "farmer", "text": "First day, welcome aboard. We start at dawn, finish around 2 usually.", "text_fr": "Premier jour, bienvenue. On commence à l''aube, on finit vers 14h généralement.", "choices": [{"text": "Sounds good, I''m ready to get started.", "next": "n2"}]}, "n2": {"speaker": "coworker", "text": "First season here? It''s tough at first, but you get used to it.", "text_fr": "Première saison ici ? C''est dur au début, mais on s''y habitue.", "choices": [{"text": "I appreciate the heads up, any tips for beginners?", "next": "n3"}]}, "n3": {"speaker": "coworker", "text": "Drink water constantly, and don''t rush — steady pace wins the day.", "text_fr": "Buvez de l''eau constamment, et ne vous précipitez pas — un rythme régulier gagne la journée.", "choices": [{"text": "Good advice, I''ll pace myself.", "next": "n4"}]}, "n4": {"speaker": "farmer", "text": "(two weeks later) You''ve picked up the pace really well.", "text_fr": "(deux semaines plus tard) Vous avez vraiment bien pris le rythme.", "choices": [{"text": "Thanks, it''s been a great learning experience.", "next": "n5"}]}, "n5": {"speaker": "farmer", "text": "(end of the month) You''ve earned your 88 days toward your second-year visa.", "text_fr": "(fin du mois) Vous avez gagné vos 88 jours pour votre visa de deuxième année.", "choices": [{"text": "That''s such a relief, thank you for the opportunity.", "next": "end_completed"}]}, "end_completed": {"speaker": "farmer", "text": "You''ve earned it. Good luck with the rest of your trip!", "text_fr": "Vous l''avez mérité. Bonne chance pour la suite de votre voyage !", "end": true, "ending_label": "Mois de travail régional validé 🌾"}}}'::jsonb, true from th;

with th as (select id from scenario_themes where position = 16 and language_id = (select id from languages where code = 'en'))
insert into scenarios (theme_id, format, cecr_level, title, content, is_playable)
select th.id, 'long', 'B2', 'Un road trip de la côte est avec plusieurs arrêts', '{"characters": {"friend": "ton compagnon de route"}, "start_node": "n1", "nodes": {"n1": {"speaker": "friend", "text": "Starting in Cairns, ending in Melbourne — that''s a huge stretch of coast!", "text_fr": "On commence à Cairns, on finit à Melbourne — c''est un énorme tronçon de côte !", "choices": [{"text": "Let''s plan stops at the Whitsundays and Byron Bay along the way.", "next": "n2"}]}, "n2": {"speaker": "friend", "text": "Great picks. The Whitsundays were incredible — what''s next after Byron?", "text_fr": "Excellents choix. Les Whitsundays étaient incroyables — quoi après Byron ?", "choices": [{"text": "Let''s stop in Sydney for a few days to work and refill the budget.", "next": "n3"}]}, "n3": {"speaker": "friend", "text": "Smart, we could both pick up some casual hospitality work there.", "text_fr": "Malin, on pourrait tous les deux trouver du travail occasionnel dans l''hôtellerie là-bas.", "choices": [{"text": "Exactly the plan, then we finish the trip down to Melbourne.", "next": "n4"}]}, "n4": {"speaker": "friend", "text": "(after Sydney) Budget''s refilled, ready for the final stretch!", "text_fr": "(après Sydney) Budget renfloué, prêt pour la dernière étape !", "choices": [{"text": "Let''s make these last few days count.", "next": "end_journey"}]}, "end_journey": {"speaker": "friend", "text": "What an incredible way to see this country, working and traveling both.", "text_fr": "Quelle incroyable façon de découvrir ce pays, en travaillant et en voyageant à la fois.", "end": true, "ending_label": "Road trip travail-voyage réussi 🏄"}}}'::jsonb, true from th;

with th as (select id from scenario_themes where position = 16 and language_id = (select id from languages where code = 'en'))
insert into scenarios (theme_id, format, cecr_level, title, content, is_playable)
select th.id, 'long', 'B2', 'Valider son visa working holiday via le travail régional', '{"characters": {"agent": "l''agent d''immigration", "farmer": "l''employeur régional"}, "start_node": "n1", "nodes": {"n1": {"speaker": "agent", "text": "To qualify for your second-year visa, you need 88 days of specified regional work. Understood?", "text_fr": "Pour obtenir votre visa de deuxième année, il vous faut 88 jours de travail régional spécifique. Compris ?", "choices": [{"text": "Yes, I''ve already found a farm willing to hire me.", "next": "n2"}, {"text": "What counts as \"specified work\" exactly?", "next": "n2b"}]}, "n2": {"speaker": "agent", "text": "Great, make sure they give you proper payslips as proof.", "text_fr": "Parfait, assurez-vous qu''ils vous donnent de vraies fiches de paie comme preuve.", "choices": [{"text": "Understood, I''ll keep every document.", "next": "n3"}]}, "n2b": {"speaker": "agent", "text": "Agriculture, mining, and construction in regional areas mostly qualify.", "text_fr": "L''agriculture, les mines et la construction en zones régionales sont généralement éligibles.", "choices": [{"text": "That''s helpful, I''ll look for farm work then.", "next": "n3"}]}, "n3": {"speaker": "farmer", "text": "(months later) Here''s your final payslip — that''s your 88 days complete!", "text_fr": "(des mois plus tard) Voici votre dernière fiche de paie — vos 88 jours sont complets !", "choices": [{"text": "Thank you so much, this means everything for my visa application.", "next": "n4"}]}, "n4": {"speaker": "agent", "text": "(back at the office) Everything checks out — your second-year visa is approved!", "text_fr": "(de retour au bureau) Tout est en règle — votre visa de deuxième année est approuvé !", "choices": [{"text": "That''s amazing news, thank you for your help throughout this!", "next": "end_approved"}]}, "end_approved": {"speaker": "agent", "text": "Congratulations, enjoy your extended time in Australia!", "text_fr": "Félicitations, profitez bien de votre séjour prolongé en Australie !", "end": true, "ending_label": "Visa de 2e année obtenu 🎉🇦🇺"}}}'::jsonb, true from th;
