-- ============================================
-- LUMA — Exercices pratiques pour les 6 fiches de grammaire B2
-- 7 exercices par fiche, même méthode que les niveaux précédents.
-- ============================================

with f as (select id from grammar_fiches where cecr_level = 'B2' and position = 25)
insert into grammar_fiche_exercises (fiche_id, position, type, content)
select f.id, v.position, v.type, v.content::jsonb from f, (values
(1, 'qcm', '{"question": "Complète : If I had known, I ___ have called you.", "options": ["will", "would", "would have", "had"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"would\"."}'),(2, 'qcm', '{"question": "Complète : If I had studied medicine, I ___ a doctor now. (mixed)", "options": ["would be", "would have been", "will be", "was"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"would be\"."}'),(3, 'fill_blank', '{"sentence_before": "If she ", "sentence_after": " harder, she would have passed. (study, third conditional)", "correct_answers": ["had studied"], "feedback_correct": "Correct !", "feedback_incorrect": "Condition passée irréelle → if + past perfect."}'),(4, 'fill_blank', '{"sentence_before": "If I weren''t so tired, I ", "sentence_after": " out tonight. (go, mixed, présent)", "correct_answers": ["would go"], "feedback_correct": "Correct !", "feedback_incorrect": "Condition présente + conséquence présente irréelle."}'),(5, 'true_false', '{"statement": "The third conditional talks about an unreal past situation and its unreal past consequence.", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Relis la règle."}'),(6, 'reorder', '{"words": ["If", "I", "had", "known,", "I", "would", "have", "called", "you."], "correct_sentence": "If I had known, I would have called you."}'),(7, 'error_correction', '{"wrong_sentence": "If I had studied, I would passed the exam.", "correct_sentence": "If I had studied, I would have passed the exam.", "error_word": "passed", "feedback_correct": "Bien vu !", "feedback_incorrect": "Regarde le mot en rouge.", "explanation": "would HAVE + participe passé, pas would + passé simple."}')
) as v(position, type, content);

with f as (select id from grammar_fiches where cecr_level = 'B2' and position = 26)
insert into grammar_fiche_exercises (fiche_id, position, type, content)
select f.id, v.position, v.type, v.content::jsonb from f, (values
(1, 'qcm', '{"question": "Complète : By the time we arrived, the film ___ already started.", "options": ["has", "had", "was", "is"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"had\"."}'),(2, 'qcm', '{"question": "Complète : She ___ been waiting for an hour when the bus finally came.", "options": ["has", "had", "was", "is"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"had\"."}'),(3, 'fill_blank', '{"sentence_before": "I ", "sentence_after": " such a beautiful sunset before that day. (never, see, past perfect)", "correct_answers": ["had never seen"], "feedback_correct": "Correct !", "feedback_incorrect": "Action antérieure à une autre action passée → past perfect."}'),(4, 'fill_blank', '{"sentence_before": "They ", "sentence_after": " when I called. (already, leave, past perfect)", "correct_answers": ["had already left"], "feedback_correct": "Correct !", "feedback_incorrect": "past perfect pour une action déjà terminée avant un moment passé."}'),(5, 'true_false', '{"statement": "The past perfect describes an action that happened before another action in the past.", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Relis la règle."}'),(6, 'reorder', '{"words": ["She", "had", "finished", "her", "work", "before", "noon."], "correct_sentence": "She had finished her work before noon."}'),(7, 'error_correction', '{"wrong_sentence": "I had never saw such a big dog.", "correct_sentence": "I had never seen such a big dog.", "error_word": "saw", "feedback_correct": "Bien vu !", "feedback_incorrect": "Regarde le mot en rouge.", "explanation": "had + participe passé (seen), pas le prétérit (saw)."}')
) as v(position, type, content);

with f as (select id from grammar_fiches where cecr_level = 'B2' and position = 27)
insert into grammar_fiche_exercises (fiche_id, position, type, content)
select f.id, v.position, v.type, v.content::jsonb from f, (values
(1, 'qcm', '{"question": "Complète : The book ___ have been written by Shakespeare.", "options": ["is said to", "says", "said", "is saying"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"is said to\"."}'),(2, 'qcm', '{"question": "Complète : She was given ___ by her boss.", "options": ["a promotion", "to a promotion", "promoted", "promoting"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"a promotion\"."}'),(3, 'fill_blank', '{"sentence_before": "The Mona Lisa ", "sentence_after": " to have been painted around 1503-1506. (believe)", "correct_answers": ["is believed"], "feedback_correct": "Correct !", "feedback_incorrect": "is believed to + infinitif : structure académique passive."}'),(4, 'fill_blank', '{"sentence_before": "The results ", "sentence_after": " tomorrow. (announce, passif futur)", "correct_answers": ["will be announced"], "feedback_correct": "Correct !", "feedback_incorrect": "Passif futur = will be + participe passé."}'),(5, 'true_false', '{"statement": "The passive with double-object verbs (give, send, offer) can front either object.", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Relis la règle."}'),(6, 'reorder', '{"words": ["He", "was", "offered", "a", "new", "job."], "correct_sentence": "He was offered a new job."}'),(7, 'error_correction', '{"wrong_sentence": "He is said to has a lot of money.", "correct_sentence": "He is said to have a lot of money.", "error_word": "has", "feedback_correct": "Bien vu !", "feedback_incorrect": "Regarde le mot en rouge.", "explanation": "is said to + base verbale (have), pas la forme conjuguée (has)."}')
) as v(position, type, content);

with f as (select id from grammar_fiches where cecr_level = 'B2' and position = 28)
insert into grammar_fiche_exercises (fiche_id, position, type, content)
select f.id, v.position, v.type, v.content::jsonb from f, (values
(1, 'qcm', '{"question": "Complète : She was tired; ___, she finished the marathon.", "options": ["however", "because", "so", "and"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"however\"."}'),(2, 'qcm', '{"question": "Complète : ___ the traffic, we arrived on time.", "options": ["Although", "Despite", "Because", "So"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"Despite\"."}'),(3, 'fill_blank', '{"sentence_before": "The results were unclear; ", "sentence_after": ", further research is needed.", "correct_answers": ["thus", "consequently", "therefore"], "feedback_correct": "Correct !", "feedback_incorrect": "Plusieurs connecteurs de conséquence formels sont interchangeables ici."}'),(4, 'fill_blank', '{"sentence_before": "", "sentence_after": " the rain, we went for a walk. (malgré, +nom)", "correct_answers": ["Despite", "In spite of"], "feedback_correct": "Correct !", "feedback_incorrect": "malgré + nom → Despite/In spite of."}'),(5, 'true_false', '{"statement": "''However'' is an adverb and needs its own clause or a semicolon, while ''although'' is a conjunction that joins clauses directly.", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Relis la règle."}'),(6, 'reorder', '{"words": ["Although", "it", "was", "raining,", "we", "went", "out."], "correct_sentence": "Although it was raining, we went out."}'),(7, 'error_correction', '{"wrong_sentence": "Although the rain, we went out.", "correct_sentence": "Despite the rain, we went out.", "error_word": "Although", "feedback_correct": "Bien vu !", "feedback_incorrect": "Regarde le mot en rouge.", "explanation": "\"although\" a besoin d''une proposition complète, pas d''un nom seul. Ici il faut \"Despite\" + nom."}')
) as v(position, type, content);

with f as (select id from grammar_fiches where cecr_level = 'B2' and position = 29)
insert into grammar_fiche_exercises (fiche_id, position, type, content)
select f.id, v.position, v.type, v.content::jsonb from f, (values
(1, 'qcm', '{"question": "\"Bring up\" (dans une conversation) veut dire :", "options": ["Évoquer", "Élever", "Apporter", "Monter"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"Évoquer\"."}'),(2, 'qcm', '{"question": "\"Get away with\" veut dire :", "options": ["S''en sortir sans punition", "Partir avec quelqu''un", "Emporter", "Échapper physiquement"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"S''en sortir sans punition\"."}'),(3, 'fill_blank', '{"sentence_before": "The meeting was ", "sentence_after": " until next week. (postponer, put off)", "correct_answers": ["put off"], "feedback_correct": "Correct !", "feedback_incorrect": "Reporter = put off."}'),(4, 'fill_blank', '{"sentence_before": "The plan ", "sentence_after": " at the last minute. (échouer, fall through)", "correct_answers": ["fell through"], "feedback_correct": "Correct !", "feedback_incorrect": "Échouer (projet) = fall through."}'),(5, 'true_false', '{"statement": "''Look into'' means to investigate something.", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Relis la règle."}'),(6, 'reorder', '{"words": ["I", "need", "to", "deal", "with", "this", "problem."], "correct_sentence": "I need to deal with this problem."}'),(7, 'error_correction', '{"wrong_sentence": "The project fell down at the last minute.", "correct_sentence": "The project fell through at the last minute.", "error_word": "down", "feedback_correct": "Bien vu !", "feedback_incorrect": "Regarde le mot en rouge.", "explanation": "\"fall through\" (échouer) est le bon phrasal verb, pas \"fall down\" (tomber physiquement)."}')
) as v(position, type, content);

with f as (select id from grammar_fiches where cecr_level = 'B2' and position = 30)
insert into grammar_fiche_exercises (fiche_id, position, type, content)
select f.id, v.position, v.type, v.content::jsonb from f, (values
(1, 'qcm', '{"question": "Complète : I wish I ___ taller.", "options": ["am", "was", "were", "will be"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"were\"."}'),(2, 'qcm', '{"question": "Complète : I''d rather you ___ smoke in here.", "options": ["don''t", "didn''t", "not", "won''t"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"didn''t\"."}'),(3, 'fill_blank', '{"sentence_before": "If only I ", "sentence_after": " the truth earlier! (know, regret)", "correct_answers": ["had known"], "feedback_correct": "Correct !", "feedback_incorrect": "if only + past perfect pour un regret passé."}'),(4, 'fill_blank', '{"sentence_before": "You ", "sentence_after": " hurry, or you''ll miss the train. (had better)", "correct_answers": ["had better", "''d better"], "feedback_correct": "Correct !", "feedback_incorrect": "Conseil pressant → had better."}'),(5, 'true_false', '{"statement": "''Had better'' is stronger than ''should'' and often implies a negative consequence if not followed.", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Relis la règle."}'),(6, 'reorder', '{"words": ["I", "wish", "I", "had", "more", "time."], "correct_sentence": "I wish I had more time."}'),(7, 'error_correction', '{"wrong_sentence": "I wish I am taller.", "correct_sentence": "I wish I were taller.", "error_word": "am", "feedback_correct": "Bien vu !", "feedback_incorrect": "Regarde le mot en rouge.", "explanation": "wish + passé simple (were) pour un souhait présent irréel, jamais le présent."}')
) as v(position, type, content);
