-- ============================================
-- LUMA — 4 nouveaux thèmes de vocabulaire : Musique, Animaux, Fruits &
-- Légumes, Vie sociale. 5 niveaux x 20 mots chacun, exercices inclus.
-- ============================================

insert into vocab_themes (language_id, slug, title, icon, position, words)
select id, v.slug, v.title, v.icon, v.position, '[]'::jsonb
from languages, (values
('musique', 'Musique', '🎵', 11),('animaux', 'Animaux', '🐾', 12),('fruits_legumes', 'Fruits & Légumes', '🍎', 13),('sociale', 'Vie sociale', '🤝', 14)
) as v(slug, title, icon, position)
where languages.code = 'en';

with t as (select id from vocab_themes where slug = 'musique')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 1, 'Niveau 1', '[{"en": "song", "fr": "chanson", "level": "A1"}, {"en": "singer", "fr": "chanteur", "level": "A1"}, {"en": "guitar", "fr": "guitare", "level": "A1"}, {"en": "piano", "fr": "piano", "level": "A1"}, {"en": "drum", "fr": "tambour/batterie", "level": "A1"}, {"en": "concert", "fr": "concert", "level": "A1"}, {"en": "band", "fr": "groupe (musique)", "level": "A1"}, {"en": "melody", "fr": "mélodie", "level": "A2"}, {"en": "rhythm", "fr": "rythme", "level": "A2"}, {"en": "lyrics", "fr": "paroles (chanson)", "level": "A2"}, {"en": "album", "fr": "album", "level": "A1"}, {"en": "radio", "fr": "radio", "level": "A1"}, {"en": "headphones", "fr": "écouteurs", "level": "A1"}, {"en": "microphone", "fr": "microphone", "level": "A1"}, {"en": "chorus", "fr": "refrain", "level": "A2"}, {"en": "tune", "fr": "air (mélodie)", "level": "A2"}, {"en": "instrument", "fr": "instrument", "level": "A1"}, {"en": "orchestra", "fr": "orchestre", "level": "A2"}, {"en": "dance (music)", "fr": "danse", "level": "A1"}, {"en": "sound", "fr": "son", "level": "A1"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'musique') and position = 1)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'musique'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"chanson\" = ?", "options": ["instrument", "song", "lyrics", "tune"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"song\"."}'),(2, 'qcm', '{"question": "\"piano\" = ?", "options": ["tune", "microphone", "piano", "rhythm"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"piano\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "band", "right": "groupe (musique)"}, {"left": "melody", "right": "mélodie"}, {"left": "rhythm", "right": "rythme"}, {"left": "lyrics", "right": "paroles (chanson)"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "headphones", "right": "écouteurs"}, {"left": "microphone", "right": "microphone"}, {"left": "chorus", "right": "refrain"}, {"left": "tune", "right": "air (mélodie)"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"orchestre\" = ", "sentence_after": "", "correct_answers": ["orchestra"], "feedback_correct": "Correct !", "feedback_incorrect": "\"orchestre\" se dit \"orchestra\" en anglais."}'),(6, 'true_false', '{"statement": "\"sound\" veut dire \"son\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'musique')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 2, 'Niveau 2', '[{"en": "violin", "fr": "violon", "level": "A2"}, {"en": "cello", "fr": "violoncelle", "level": "B1"}, {"en": "trumpet", "fr": "trompette", "level": "A2"}, {"en": "saxophone", "fr": "saxophone", "level": "A2"}, {"en": "harmony", "fr": "harmonie", "level": "B1"}, {"en": "tempo", "fr": "tempo", "level": "B1"}, {"en": "pitch (music)", "fr": "hauteur (note)", "level": "B1"}, {"en": "chord", "fr": "accord (musique)", "level": "B1"}, {"en": "scale (music)", "fr": "gamme (musique)", "level": "B1"}, {"en": "composer", "fr": "compositeur", "level": "A2"}, {"en": "conductor", "fr": "chef d''orchestre", "level": "B1"}, {"en": "genre (music)", "fr": "genre musical", "level": "A2"}, {"en": "playlist", "fr": "playlist", "level": "A1"}, {"en": "recording studio", "fr": "studio d''enregistrement", "level": "B1"}, {"en": "soundtrack", "fr": "bande originale", "level": "A2"}, {"en": "cover (song)", "fr": "reprise (chanson)", "level": "B1"}, {"en": "remix", "fr": "remix", "level": "A2"}, {"en": "backup singer", "fr": "choriste", "level": "B1"}, {"en": "tour (music)", "fr": "tournée", "level": "A2"}, {"en": "fan base", "fr": "base de fans", "level": "B1"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'musique') and position = 2)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'musique'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"violon\" = ?", "options": ["violin", "saxophone", "playlist", "recording studio"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"violin\"."}'),(2, 'qcm', '{"question": "\"saxophone\" = ?", "options": ["chord", "soundtrack", "saxophone", "backup singer"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"saxophone\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "pitch (music)", "right": "hauteur (note)"}, {"left": "chord", "right": "accord (musique)"}, {"left": "scale (music)", "right": "gamme (musique)"}, {"left": "composer", "right": "compositeur"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "playlist", "right": "playlist"}, {"left": "recording studio", "right": "studio d''enregistrement"}, {"left": "soundtrack", "right": "bande originale"}, {"left": "cover (song)", "right": "reprise (chanson)"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"choriste\" = ", "sentence_after": "", "correct_answers": ["backup singer"], "feedback_correct": "Correct !", "feedback_incorrect": "\"choriste\" se dit \"backup singer\" en anglais."}'),(6, 'true_false', '{"statement": "\"fan base\" veut dire \"base de fans\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'musique')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 3, 'Niveau 3', '[{"en": "acoustic", "fr": "acoustique", "level": "B1"}, {"en": "amplifier", "fr": "amplificateur", "level": "B1"}, {"en": "feedback (sound)", "fr": "larsen", "level": "B2"}, {"en": "setlist", "fr": "liste des morceaux", "level": "B1"}, {"en": "encore", "fr": "rappel (concert)", "level": "B1"}, {"en": "headliner", "fr": "tête d''affiche", "level": "B1"}, {"en": "gig", "fr": "concert (informel)", "level": "B1"}, {"en": "jam session", "fr": "bœuf musical", "level": "B1"}, {"en": "improvise", "fr": "improviser", "level": "B1"}, {"en": "vocal range", "fr": "tessiture vocale", "level": "B2"}, {"en": "falsetto", "fr": "fausset", "level": "C1"}, {"en": "a cappella", "fr": "a cappella", "level": "B1"}, {"en": "sync (music)", "fr": "synchronisation musicale", "level": "C1"}, {"en": "sample (music)", "fr": "échantillon (musique)", "level": "B2"}, {"en": "beat drop", "fr": "chute du rythme", "level": "B2"}, {"en": "bassline", "fr": "ligne de basse", "level": "B1"}, {"en": "riff", "fr": "riff", "level": "B1"}, {"en": "breakdown (music)", "fr": "break (musique)", "level": "B2"}, {"en": "crescendo", "fr": "crescendo", "level": "B1"}, {"en": "unplugged", "fr": "acoustique/débranché", "level": "B1"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'musique') and position = 3)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'musique'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"acoustique\" = ?", "options": ["vocal range", "improvise", "acoustic", "jam session"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"acoustic\"."}'),(2, 'qcm', '{"question": "\"liste des morceaux\" = ?", "options": ["gig", "acoustic", "setlist", "sync (music)"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"setlist\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "gig", "right": "concert (informel)"}, {"left": "jam session", "right": "bœuf musical"}, {"left": "improvise", "right": "improviser"}, {"left": "vocal range", "right": "tessiture vocale"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "sync (music)", "right": "synchronisation musicale"}, {"left": "sample (music)", "right": "échantillon (musique)"}, {"left": "beat drop", "right": "chute du rythme"}, {"left": "bassline", "right": "ligne de basse"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"break (musique)\" = ", "sentence_after": "", "correct_answers": ["breakdown (music)"], "feedback_correct": "Correct !", "feedback_incorrect": "\"break (musique)\" se dit \"breakdown (music)\" en anglais."}'),(6, 'true_false', '{"statement": "\"unplugged\" veut dire \"acoustique/débranché\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'musique')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 4, 'Niveau 4', '[{"en": "syncopation", "fr": "syncope (rythme)", "level": "C1"}, {"en": "dissonance", "fr": "dissonance", "level": "C1"}, {"en": "polyphony", "fr": "polyphonie", "level": "C1"}, {"en": "counterpoint", "fr": "contrepoint", "level": "C1"}, {"en": "arrangement (music)", "fr": "arrangement musical", "level": "B2"}, {"en": "orchestration", "fr": "orchestration", "level": "C1"}, {"en": "session musician", "fr": "musicien de studio", "level": "C1"}, {"en": "royalties (music)", "fr": "droits d''auteur", "level": "B2"}, {"en": "streaming rights", "fr": "droits de diffusion", "level": "C1"}, {"en": "chart-topping", "fr": "numéro un des charts", "level": "C1"}, {"en": "one-hit wonder", "fr": "artiste à un seul succès", "level": "C1"}, {"en": "underground scene", "fr": "scène underground", "level": "B2"}, {"en": "mainstream (music)", "fr": "grand public (musique)", "level": "B2"}, {"en": "indie label", "fr": "label indépendant", "level": "B2"}, {"en": "record deal", "fr": "contrat de disque", "level": "B1"}, {"en": "music production", "fr": "production musicale", "level": "B1"}, {"en": "mastering (audio)", "fr": "mastering (audio)", "level": "C1"}, {"en": "mixing (audio)", "fr": "mixage (audio)", "level": "B2"}, {"en": "soundcheck", "fr": "balance (son)", "level": "B1"}, {"en": "stage presence", "fr": "présence scénique", "level": "B2"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'musique') and position = 4)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'musique'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"syncope (rythme)\" = ?", "options": ["syncopation", "dissonance", "arrangement (music)", "mainstream (music)"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"syncopation\"."}'),(2, 'qcm', '{"question": "\"contrepoint\" = ?", "options": ["counterpoint", "music production", "soundcheck", "syncopation"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"counterpoint\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "session musician", "right": "musicien de studio"}, {"left": "royalties (music)", "right": "droits d''auteur"}, {"left": "streaming rights", "right": "droits de diffusion"}, {"left": "chart-topping", "right": "numéro un des charts"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "mainstream (music)", "right": "grand public (musique)"}, {"left": "indie label", "right": "label indépendant"}, {"left": "record deal", "right": "contrat de disque"}, {"left": "music production", "right": "production musicale"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"mixage (audio)\" = ", "sentence_after": "", "correct_answers": ["mixing (audio)"], "feedback_correct": "Correct !", "feedback_incorrect": "\"mixage (audio)\" se dit \"mixing (audio)\" en anglais."}'),(6, 'true_false', '{"statement": "\"stage presence\" veut dire \"présence scénique\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'musique')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 5, 'Niveau 5', '[{"en": "musicology", "fr": "musicologie", "level": "C1"}, {"en": "ethnomusicology", "fr": "ethnomusicologie", "level": "C1"}, {"en": "timbre", "fr": "timbre (son)", "level": "C1"}, {"en": "resonance (sound)", "fr": "résonance", "level": "C1"}, {"en": "overtone", "fr": "harmonique", "level": "C1"}, {"en": "modulation (music)", "fr": "modulation (musique)", "level": "C1"}, {"en": "improvisational jazz", "fr": "jazz improvisé", "level": "C1"}, {"en": "avant-garde", "fr": "avant-gardiste", "level": "C1"}, {"en": "discography", "fr": "discographie", "level": "B2"}, {"en": "homage (music)", "fr": "hommage musical", "level": "C1"}, {"en": "sampling culture", "fr": "culture du sampling", "level": "C1"}, {"en": "ghostwriting (music)", "fr": "écriture pour un autre artiste", "level": "C1"}, {"en": "needle drop", "fr": "utilisation d''une chanson existante", "level": "C1"}, {"en": "liner notes", "fr": "notes de pochette", "level": "C1"}, {"en": "bootleg recording", "fr": "enregistrement pirate", "level": "C1"}, {"en": "live album", "fr": "album live", "level": "B1"}, {"en": "unplugged session", "fr": "session acoustique", "level": "B2"}, {"en": "tribute band", "fr": "groupe hommage", "level": "B2"}, {"en": "cover band", "fr": "groupe de reprises", "level": "B1"}, {"en": "fusion genre", "fr": "genre fusion", "level": "C1"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'musique') and position = 5)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'musique'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"musicologie\" = ?", "options": ["cover band", "fusion genre", "unplugged session", "musicology"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"musicology\"."}'),(2, 'qcm', '{"question": "\"résonance\" = ?", "options": ["musicology", "fusion genre", "resonance (sound)", "homage (music)"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"resonance (sound)\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "improvisational jazz", "right": "jazz improvisé"}, {"left": "avant-garde", "right": "avant-gardiste"}, {"left": "discography", "right": "discographie"}, {"left": "homage (music)", "right": "hommage musical"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "needle drop", "right": "utilisation d''une chanson existante"}, {"left": "liner notes", "right": "notes de pochette"}, {"left": "bootleg recording", "right": "enregistrement pirate"}, {"left": "live album", "right": "album live"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"groupe hommage\" = ", "sentence_after": "", "correct_answers": ["tribute band"], "feedback_correct": "Correct !", "feedback_incorrect": "\"groupe hommage\" se dit \"tribute band\" en anglais."}'),(6, 'true_false', '{"statement": "\"fusion genre\" veut dire \"genre fusion\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'animaux')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 1, 'Niveau 1', '[{"en": "paw", "fr": "patte", "level": "A2"}, {"en": "tail", "fr": "queue", "level": "A1"}, {"en": "fur", "fr": "fourrure", "level": "A2"}, {"en": "feather", "fr": "plume", "level": "A2"}, {"en": "claw", "fr": "griffe", "level": "A2"}, {"en": "beak", "fr": "bec", "level": "A2"}, {"en": "mane", "fr": "crinière", "level": "B1"}, {"en": "hoof", "fr": "sabot", "level": "B1"}, {"en": "whisker", "fr": "moustache (animal)", "level": "B1"}, {"en": "fang", "fr": "croc", "level": "B1"}, {"en": "herd", "fr": "troupeau", "level": "A2"}, {"en": "flock", "fr": "troupeau (oiseaux/moutons)", "level": "B1"}, {"en": "pack (animals)", "fr": "meute", "level": "A2"}, {"en": "litter (animals)", "fr": "portée (animaux)", "level": "B1"}, {"en": "breed (noun)", "fr": "race (animale)", "level": "A2"}, {"en": "tame", "fr": "apprivoisé", "level": "A2"}, {"en": "wild (animal)", "fr": "sauvage", "level": "A1"}, {"en": "pet", "fr": "animal de compagnie", "level": "A1"}, {"en": "stray", "fr": "errant (animal)", "level": "B1"}, {"en": "domesticated", "fr": "domestiqué", "level": "B1"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'animaux') and position = 1)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'animaux'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"patte\" = ?", "options": ["domesticated", "whisker", "paw", "claw"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"paw\"."}'),(2, 'qcm', '{"question": "\"plume\" = ?", "options": ["tail", "feather", "fur", "flock"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"feather\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "mane", "right": "crinière"}, {"left": "hoof", "right": "sabot"}, {"left": "whisker", "right": "moustache (animal)"}, {"left": "fang", "right": "croc"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "pack (animals)", "right": "meute"}, {"left": "litter (animals)", "right": "portée (animaux)"}, {"left": "breed (noun)", "right": "race (animale)"}, {"left": "tame", "right": "apprivoisé"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"animal de compagnie\" = ", "sentence_after": "", "correct_answers": ["pet"], "feedback_correct": "Correct !", "feedback_incorrect": "\"animal de compagnie\" se dit \"pet\" en anglais."}'),(6, 'true_false', '{"statement": "\"domesticated\" veut dire \"domestiqué\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'animaux')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 2, 'Niveau 2', '[{"en": "predator", "fr": "prédateur", "level": "A2"}, {"en": "prey", "fr": "proie", "level": "A2"}, {"en": "carnivore", "fr": "carnivore", "level": "A2"}, {"en": "herbivore", "fr": "herbivore", "level": "A2"}, {"en": "omnivore", "fr": "omnivore", "level": "B1"}, {"en": "nocturnal", "fr": "nocturne", "level": "A2"}, {"en": "hibernate", "fr": "hiberner", "level": "A2"}, {"en": "migrate (animal)", "fr": "migrer", "level": "A2"}, {"en": "camouflage", "fr": "camouflage", "level": "A2"}, {"en": "venomous", "fr": "venimeux", "level": "B1"}, {"en": "endangered species", "fr": "espèce en voie de disparition", "level": "B1"}, {"en": "habitat", "fr": "habitat", "level": "A2"}, {"en": "mammal", "fr": "mammifère", "level": "A2"}, {"en": "reptile", "fr": "reptile", "level": "A2"}, {"en": "amphibian", "fr": "amphibien", "level": "B1"}, {"en": "species", "fr": "espèce", "level": "A2"}, {"en": "extinct", "fr": "éteint (espèce)", "level": "B1"}, {"en": "offspring", "fr": "progéniture", "level": "B1"}, {"en": "mate (verb)", "fr": "s''accoupler", "level": "B1"}, {"en": "territory", "fr": "territoire", "level": "A2"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'animaux') and position = 2)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'animaux'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"prédateur\" = ?", "options": ["predator", "species", "amphibian", "venomous"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"predator\"."}'),(2, 'qcm', '{"question": "\"herbivore\" = ?", "options": ["mammal", "herbivore", "venomous", "migrate (animal)"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"herbivore\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "hibernate", "right": "hiberner"}, {"left": "migrate (animal)", "right": "migrer"}, {"left": "camouflage", "right": "camouflage"}, {"left": "venomous", "right": "venimeux"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "mammal", "right": "mammifère"}, {"left": "reptile", "right": "reptile"}, {"left": "amphibian", "right": "amphibien"}, {"left": "species", "right": "espèce"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"progéniture\" = ", "sentence_after": "", "correct_answers": ["offspring"], "feedback_correct": "Correct !", "feedback_incorrect": "\"progéniture\" se dit \"offspring\" en anglais."}'),(6, 'true_false', '{"statement": "\"territory\" veut dire \"territoire\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'animaux')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 3, 'Niveau 3', '[{"en": "instinct", "fr": "instinct", "level": "B1"}, {"en": "adapt (biology)", "fr": "s''adapter", "level": "A2"}, {"en": "evolve", "fr": "évoluer", "level": "B1"}, {"en": "gestation", "fr": "gestation", "level": "B1"}, {"en": "molt", "fr": "muer", "level": "B2"}, {"en": "shed (skin)", "fr": "muer (peau)", "level": "B2"}, {"en": "regenerate", "fr": "se régénérer", "level": "B1"}, {"en": "symbiosis", "fr": "symbiose", "level": "B1"}, {"en": "parasite", "fr": "parasite", "level": "B1"}, {"en": "host (biology)", "fr": "hôte (biologie)", "level": "B2"}, {"en": "scavenger", "fr": "charognard", "level": "B1"}, {"en": "apex predator", "fr": "superprédateur", "level": "B2"}, {"en": "food chain", "fr": "chaîne alimentaire", "level": "B1"}, {"en": "ecosystem", "fr": "écosystème", "level": "B1"}, {"en": "biodiversity", "fr": "biodiversité", "level": "B1"}, {"en": "conservation", "fr": "conservation (nature)", "level": "B1"}, {"en": "poaching", "fr": "braconnage", "level": "B1"}, {"en": "sanctuary (animal)", "fr": "sanctuaire animalier", "level": "B1"}, {"en": "rehabilitation (wildlife)", "fr": "réhabilitation (faune)", "level": "B2"}, {"en": "tagging (wildlife)", "fr": "baguage/marquage", "level": "B2"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'animaux') and position = 3)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'animaux'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"instinct\" = ?", "options": ["biodiversity", "symbiosis", "scavenger", "instinct"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"instinct\"."}'),(2, 'qcm', '{"question": "\"gestation\" = ?", "options": ["food chain", "gestation", "apex predator", "evolve"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"gestation\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "regenerate", "right": "se régénérer"}, {"left": "symbiosis", "right": "symbiose"}, {"left": "parasite", "right": "parasite"}, {"left": "host (biology)", "right": "hôte (biologie)"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "food chain", "right": "chaîne alimentaire"}, {"left": "ecosystem", "right": "écosystème"}, {"left": "biodiversity", "right": "biodiversité"}, {"left": "conservation", "right": "conservation (nature)"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"sanctuaire animalier\" = ", "sentence_after": "", "correct_answers": ["sanctuary (animal)"], "feedback_correct": "Correct !", "feedback_incorrect": "\"sanctuaire animalier\" se dit \"sanctuary (animal)\" en anglais."}'),(6, 'true_false', '{"statement": "\"tagging (wildlife)\" veut dire \"baguage/marquage\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'animaux')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 4, 'Niveau 4', '[{"en": "bioluminescence", "fr": "bioluminescence", "level": "C1"}, {"en": "echolocation", "fr": "écholocalisation", "level": "C1"}, {"en": "metamorphosis", "fr": "métamorphose", "level": "B1"}, {"en": "dormancy", "fr": "dormance", "level": "C1"}, {"en": "keystone species", "fr": "espèce clé de voûte", "level": "C1"}, {"en": "invasive species", "fr": "espèce invasive", "level": "B2"}, {"en": "taxonomy", "fr": "taxonomie", "level": "C1"}, {"en": "vertebrate", "fr": "vertébré", "level": "B1"}, {"en": "invertebrate", "fr": "invertébré", "level": "B1"}, {"en": "cold-blooded", "fr": "à sang froid", "level": "B1"}, {"en": "warm-blooded", "fr": "à sang chaud", "level": "B1"}, {"en": "exoskeleton", "fr": "exosquelette", "level": "B2"}, {"en": "gills", "fr": "branchies", "level": "B1"}, {"en": "blowhole", "fr": "évent (baleine)", "level": "B2"}, {"en": "talon", "fr": "serre (oiseau)", "level": "B1"}, {"en": "antler", "fr": "bois (cervidé)", "level": "B1"}, {"en": "tusk", "fr": "défense (animal)", "level": "B1"}, {"en": "pouch (marsupial)", "fr": "poche (marsupial)", "level": "B1"}, {"en": "burrow", "fr": "terrier", "level": "A2"}, {"en": "den", "fr": "tanière", "level": "A2"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'animaux') and position = 4)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'animaux'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"bioluminescence\" = ?", "options": ["taxonomy", "echolocation", "antler", "bioluminescence"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"bioluminescence\"."}'),(2, 'qcm', '{"question": "\"dormance\" = ?", "options": ["dormancy", "cold-blooded", "invasive species", "echolocation"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"dormancy\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "taxonomy", "right": "taxonomie"}, {"left": "vertebrate", "right": "vertébré"}, {"left": "invertebrate", "right": "invertébré"}, {"left": "cold-blooded", "right": "à sang froid"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "gills", "right": "branchies"}, {"left": "blowhole", "right": "évent (baleine)"}, {"left": "talon", "right": "serre (oiseau)"}, {"left": "antler", "right": "bois (cervidé)"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"poche (marsupial)\" = ", "sentence_after": "", "correct_answers": ["pouch (marsupial)"], "feedback_correct": "Correct !", "feedback_incorrect": "\"poche (marsupial)\" se dit \"pouch (marsupial)\" en anglais."}'),(6, 'true_false', '{"statement": "\"den\" veut dire \"tanière\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'animaux')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 5, 'Niveau 5', '[{"en": "anthropomorphism", "fr": "anthropomorphisme", "level": "C1"}, {"en": "zoomorphism", "fr": "zoomorphisme", "level": "C1"}, {"en": "sentience", "fr": "sensibilité (conscience)", "level": "C1"}, {"en": "cognitive ethology", "fr": "éthologie cognitive", "level": "C1"}, {"en": "biomimicry", "fr": "biomimétisme", "level": "C1"}, {"en": "rewilding", "fr": "réensauvagement", "level": "C1"}, {"en": "captive breeding", "fr": "élevage en captivité", "level": "C1"}, {"en": "genetic diversity", "fr": "diversité génétique", "level": "C1"}, {"en": "phenotype", "fr": "phénotype", "level": "C1"}, {"en": "mimicry (biology)", "fr": "mimétisme (biologie)", "level": "C1"}, {"en": "aposematism", "fr": "aposématisme", "level": "C1"}, {"en": "territorial dispute", "fr": "conflit territorial", "level": "C1"}, {"en": "dominance hierarchy", "fr": "hiérarchie de dominance", "level": "C1"}, {"en": "pack mentality", "fr": "mentalité de meute", "level": "C1"}, {"en": "social hierarchy (animal)", "fr": "hiérarchie sociale (animale)", "level": "C1"}, {"en": "interspecies", "fr": "interspécifique", "level": "C1"}, {"en": "cross-breeding", "fr": "croisement (élevage)", "level": "C1"}, {"en": "selective breeding", "fr": "sélection génétique", "level": "C1"}, {"en": "feral", "fr": "retourné à l''état sauvage", "level": "C1"}, {"en": "domestication process", "fr": "processus de domestication", "level": "C1"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'animaux') and position = 5)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'animaux'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"anthropomorphisme\" = ?", "options": ["zoomorphism", "social hierarchy (animal)", "biomimicry", "anthropomorphism"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"anthropomorphism\"."}'),(2, 'qcm', '{"question": "\"éthologie cognitive\" = ?", "options": ["cognitive ethology", "territorial dispute", "social hierarchy (animal)", "cross-breeding"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"cognitive ethology\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "captive breeding", "right": "élevage en captivité"}, {"left": "genetic diversity", "right": "diversité génétique"}, {"left": "phenotype", "right": "phénotype"}, {"left": "mimicry (biology)", "right": "mimétisme (biologie)"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "dominance hierarchy", "right": "hiérarchie de dominance"}, {"left": "pack mentality", "right": "mentalité de meute"}, {"left": "social hierarchy (animal)", "right": "hiérarchie sociale (animale)"}, {"left": "interspecies", "right": "interspécifique"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"sélection génétique\" = ", "sentence_after": "", "correct_answers": ["selective breeding"], "feedback_correct": "Correct !", "feedback_incorrect": "\"sélection génétique\" se dit \"selective breeding\" en anglais."}'),(6, 'true_false', '{"statement": "\"domestication process\" veut dire \"processus de domestication\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'fruits_legumes')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 1, 'Niveau 1', '[{"en": "pear", "fr": "poire", "level": "A1"}, {"en": "peach", "fr": "pêche", "level": "A1"}, {"en": "plum", "fr": "prune", "level": "A1"}, {"en": "cherry", "fr": "cerise", "level": "A1"}, {"en": "melon", "fr": "melon", "level": "A1"}, {"en": "pineapple", "fr": "ananas", "level": "A1"}, {"en": "mango", "fr": "mangue", "level": "A1"}, {"en": "kiwi", "fr": "kiwi", "level": "A1"}, {"en": "lemon", "fr": "citron", "level": "A1"}, {"en": "lime", "fr": "citron vert", "level": "A2"}, {"en": "cucumber", "fr": "concombre", "level": "A1"}, {"en": "onion", "fr": "oignon", "level": "A1"}, {"en": "pepper (vegetable)", "fr": "poivron", "level": "A1"}, {"en": "lettuce", "fr": "laitue", "level": "A1"}, {"en": "spinach", "fr": "épinard", "level": "A2"}, {"en": "broccoli", "fr": "brocoli", "level": "A1"}, {"en": "cauliflower", "fr": "chou-fleur", "level": "A2"}, {"en": "pumpkin", "fr": "citrouille", "level": "A1"}, {"en": "corn", "fr": "maïs", "level": "A1"}, {"en": "pea", "fr": "petit pois", "level": "A1"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'fruits_legumes') and position = 1)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'fruits_legumes'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"poire\" = ?", "options": ["melon", "plum", "pepper (vegetable)", "pear"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"pear\"."}'),(2, 'qcm', '{"question": "\"cerise\" = ?", "options": ["lettuce", "spinach", "lime", "cherry"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"cherry\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "mango", "right": "mangue"}, {"left": "kiwi", "right": "kiwi"}, {"left": "lemon", "right": "citron"}, {"left": "lime", "right": "citron vert"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "pepper (vegetable)", "right": "poivron"}, {"left": "lettuce", "right": "laitue"}, {"left": "spinach", "right": "épinard"}, {"left": "broccoli", "right": "brocoli"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"citrouille\" = ", "sentence_after": "", "correct_answers": ["pumpkin"], "feedback_correct": "Correct !", "feedback_incorrect": "\"citrouille\" se dit \"pumpkin\" en anglais."}'),(6, 'true_false', '{"statement": "\"pea\" veut dire \"petit pois\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'fruits_legumes')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 2, 'Niveau 2', '[{"en": "apricot", "fr": "abricot", "level": "A2"}, {"en": "fig", "fr": "figue", "level": "B1"}, {"en": "pomegranate", "fr": "grenade (fruit)", "level": "B1"}, {"en": "blueberry", "fr": "myrtille", "level": "A2"}, {"en": "raspberry", "fr": "framboise", "level": "A2"}, {"en": "blackberry", "fr": "mûre", "level": "A2"}, {"en": "cranberry", "fr": "canneberge", "level": "B1"}, {"en": "watermelon", "fr": "pastèque", "level": "A1"}, {"en": "cantaloupe", "fr": "cantaloup", "level": "B1"}, {"en": "zucchini", "fr": "courgette", "level": "A2"}, {"en": "eggplant", "fr": "aubergine", "level": "A2"}, {"en": "radish", "fr": "radis", "level": "A2"}, {"en": "beetroot", "fr": "betterave", "level": "B1"}, {"en": "celery", "fr": "céleri", "level": "A2"}, {"en": "asparagus", "fr": "asperge", "level": "B1"}, {"en": "artichoke", "fr": "artichaut", "level": "B1"}, {"en": "leek", "fr": "poireau", "level": "A2"}, {"en": "turnip", "fr": "navet", "level": "B1"}, {"en": "squash (vegetable)", "fr": "courge", "level": "B1"}, {"en": "kale", "fr": "chou frisé", "level": "B1"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'fruits_legumes') and position = 2)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'fruits_legumes'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"abricot\" = ?", "options": ["pomegranate", "cantaloupe", "raspberry", "apricot"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"apricot\"."}'),(2, 'qcm', '{"question": "\"myrtille\" = ?", "options": ["eggplant", "radish", "fig", "blueberry"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"blueberry\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "cranberry", "right": "canneberge"}, {"left": "watermelon", "right": "pastèque"}, {"left": "cantaloupe", "right": "cantaloup"}, {"left": "zucchini", "right": "courgette"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "beetroot", "right": "betterave"}, {"left": "celery", "right": "céleri"}, {"left": "asparagus", "right": "asperge"}, {"left": "artichoke", "right": "artichaut"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"navet\" = ", "sentence_after": "", "correct_answers": ["turnip"], "feedback_correct": "Correct !", "feedback_incorrect": "\"navet\" se dit \"turnip\" en anglais."}'),(6, 'true_false', '{"statement": "\"kale\" veut dire \"chou frisé\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'fruits_legumes')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 3, 'Niveau 3', '[{"en": "papaya", "fr": "papaye", "level": "B1"}, {"en": "guava", "fr": "goyave", "level": "B1"}, {"en": "passion fruit", "fr": "fruit de la passion", "level": "B1"}, {"en": "dragon fruit", "fr": "fruit du dragon", "level": "B1"}, {"en": "lychee", "fr": "litchi", "level": "B1"}, {"en": "persimmon", "fr": "kaki (fruit)", "level": "C1"}, {"en": "nectarine", "fr": "nectarine", "level": "B1"}, {"en": "rhubarb", "fr": "rhubarbe", "level": "B1"}, {"en": "fennel", "fr": "fenouil", "level": "B1"}, {"en": "okra", "fr": "gombo", "level": "C1"}, {"en": "chard", "fr": "blette", "level": "C1"}, {"en": "brussels sprouts", "fr": "choux de Bruxelles", "level": "B1"}, {"en": "parsnip", "fr": "panais", "level": "C1"}, {"en": "rutabaga", "fr": "rutabaga", "level": "C1"}, {"en": "endive", "fr": "endive", "level": "B1"}, {"en": "arugula", "fr": "roquette", "level": "B1"}, {"en": "watercress", "fr": "cresson", "level": "C1"}, {"en": "bok choy", "fr": "chou chinois", "level": "C1"}, {"en": "jicama", "fr": "jicama", "level": "C1"}, {"en": "kohlrabi", "fr": "chou-rave", "level": "C1"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'fruits_legumes') and position = 3)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'fruits_legumes'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"papaye\" = ?", "options": ["rhubarb", "rutabaga", "lychee", "papaya"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"papaya\"."}'),(2, 'qcm', '{"question": "\"fruit du dragon\" = ?", "options": ["kohlrabi", "dragon fruit", "passion fruit", "rhubarb"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"dragon fruit\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "nectarine", "right": "nectarine"}, {"left": "rhubarb", "right": "rhubarbe"}, {"left": "fennel", "right": "fenouil"}, {"left": "okra", "right": "gombo"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "parsnip", "right": "panais"}, {"left": "rutabaga", "right": "rutabaga"}, {"left": "endive", "right": "endive"}, {"left": "arugula", "right": "roquette"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"chou chinois\" = ", "sentence_after": "", "correct_answers": ["bok choy"], "feedback_correct": "Correct !", "feedback_incorrect": "\"chou chinois\" se dit \"bok choy\" en anglais."}'),(6, 'true_false', '{"statement": "\"kohlrabi\" veut dire \"chou-rave\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'fruits_legumes')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 4, 'Niveau 4', '[{"en": "ripen", "fr": "mûrir", "level": "B1"}, {"en": "overripe", "fr": "trop mûr", "level": "B1"}, {"en": "unripe", "fr": "pas mûr", "level": "B1"}, {"en": "seasonal produce", "fr": "produits de saison", "level": "B1"}, {"en": "orchard", "fr": "verger", "level": "A2"}, {"en": "harvest (verb)", "fr": "récolter", "level": "A2"}, {"en": "crop rotation", "fr": "rotation des cultures", "level": "B2"}, {"en": "pesticide-free", "fr": "sans pesticide", "level": "B1"}, {"en": "heirloom (produce)", "fr": "variété ancienne", "level": "C1"}, {"en": "root vegetable", "fr": "légume racine", "level": "B1"}, {"en": "leafy green", "fr": "légume-feuille", "level": "B1"}, {"en": "cruciferous", "fr": "crucifère", "level": "C1"}, {"en": "citrus", "fr": "agrumes", "level": "A2"}, {"en": "tuber", "fr": "tubercule", "level": "B1"}, {"en": "legume", "fr": "légumineuse", "level": "B1"}, {"en": "pod", "fr": "cosse/gousse", "level": "B1"}, {"en": "husk (corn)", "fr": "enveloppe (maïs)", "level": "B1"}, {"en": "rind (fruit)", "fr": "écorce (fruit)", "level": "B1"}, {"en": "core (fruit)", "fr": "trognon", "level": "A2"}, {"en": "pit (fruit)", "fr": "noyau", "level": "A2"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'fruits_legumes') and position = 4)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'fruits_legumes'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"mûrir\" = ?", "options": ["unripe", "ripen", "tuber", "leafy green"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"ripen\"."}'),(2, 'qcm', '{"question": "\"produits de saison\" = ?", "options": ["rind (fruit)", "pod", "unripe", "seasonal produce"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"seasonal produce\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "crop rotation", "right": "rotation des cultures"}, {"left": "pesticide-free", "right": "sans pesticide"}, {"left": "heirloom (produce)", "right": "variété ancienne"}, {"left": "root vegetable", "right": "légume racine"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "citrus", "right": "agrumes"}, {"left": "tuber", "right": "tubercule"}, {"left": "legume", "right": "légumineuse"}, {"left": "pod", "right": "cosse/gousse"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"écorce (fruit)\" = ", "sentence_after": "", "correct_answers": ["rind (fruit)"], "feedback_correct": "Correct !", "feedback_incorrect": "\"écorce (fruit)\" se dit \"rind (fruit)\" en anglais."}'),(6, 'true_false', '{"statement": "\"pit (fruit)\" veut dire \"noyau\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'fruits_legumes')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 5, 'Niveau 5', '[{"en": "horticulture", "fr": "horticulture", "level": "C1"}, {"en": "cultivar", "fr": "cultivar", "level": "C1"}, {"en": "grafting", "fr": "greffage", "level": "C1"}, {"en": "pollination (fruit)", "fr": "pollinisation", "level": "B1"}, {"en": "cross-pollination", "fr": "pollinisation croisée", "level": "C1"}, {"en": "monocropping", "fr": "monoculture intensive", "level": "C1"}, {"en": "agroforestry", "fr": "agroforesterie", "level": "C1"}, {"en": "biodynamic farming", "fr": "agriculture biodynamique", "level": "C1"}, {"en": "terroir", "fr": "terroir", "level": "C1"}, {"en": "varietal", "fr": "variétal", "level": "C1"}, {"en": "perishable", "fr": "périssable", "level": "B1"}, {"en": "shelf life", "fr": "durée de conservation", "level": "B1"}, {"en": "food waste", "fr": "gaspillage alimentaire", "level": "B1"}, {"en": "farm-to-table", "fr": "de la ferme à la table", "level": "B2"}, {"en": "locally sourced", "fr": "d''origine locale", "level": "B1"}, {"en": "organic certification", "fr": "certification biologique", "level": "B1"}, {"en": "GMO", "fr": "OGM", "level": "B1"}, {"en": "non-GMO", "fr": "sans OGM", "level": "B1"}, {"en": "heirloom seed", "fr": "semence ancienne", "level": "C1"}, {"en": "crop yield", "fr": "rendement agricole", "level": "C1"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'fruits_legumes') and position = 5)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'fruits_legumes'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"horticulture\" = ?", "options": ["biodynamic farming", "farm-to-table", "horticulture", "varietal"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"horticulture\"."}'),(2, 'qcm', '{"question": "\"pollinisation\" = ?", "options": ["terroir", "crop yield", "pollination (fruit)", "GMO"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"pollination (fruit)\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "agroforestry", "right": "agroforesterie"}, {"left": "biodynamic farming", "right": "agriculture biodynamique"}, {"left": "terroir", "right": "terroir"}, {"left": "varietal", "right": "variétal"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "food waste", "right": "gaspillage alimentaire"}, {"left": "farm-to-table", "right": "de la ferme à la table"}, {"left": "locally sourced", "right": "d''origine locale"}, {"left": "organic certification", "right": "certification biologique"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"sans OGM\" = ", "sentence_after": "", "correct_answers": ["non-GMO"], "feedback_correct": "Correct !", "feedback_incorrect": "\"sans OGM\" se dit \"non-GMO\" en anglais."}'),(6, 'true_false', '{"statement": "\"crop yield\" veut dire \"rendement agricole\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'sociale')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 1, 'Niveau 1', '[{"en": "friend", "fr": "ami", "level": "A1"}, {"en": "neighbor", "fr": "voisin", "level": "A1"}, {"en": "stranger", "fr": "inconnu", "level": "A1"}, {"en": "acquaintance", "fr": "connaissance", "level": "A2"}, {"en": "invite", "fr": "inviter", "level": "A1"}, {"en": "greet", "fr": "saluer", "level": "A2"}, {"en": "introduce", "fr": "présenter (quelqu''un)", "level": "A1"}, {"en": "chat", "fr": "discuter", "level": "A1"}, {"en": "gathering", "fr": "rassemblement", "level": "A2"}, {"en": "party", "fr": "fête", "level": "A1"}, {"en": "hangout", "fr": "sortie entre amis", "level": "A2"}, {"en": "host (social)", "fr": "hôte", "level": "A2"}, {"en": "guest", "fr": "invité", "level": "A1"}, {"en": "RSVP", "fr": "répondre à une invitation", "level": "B1"}, {"en": "small talk", "fr": "conversation légère", "level": "B1"}, {"en": "conversation", "fr": "conversation", "level": "A1"}, {"en": "gossip (noun)", "fr": "commérage", "level": "A2"}, {"en": "rumor", "fr": "rumeur", "level": "A2"}, {"en": "apologize", "fr": "s''excuser", "level": "A2"}, {"en": "forgive", "fr": "pardonner", "level": "A2"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'sociale') and position = 1)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'sociale'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"ami\" = ?", "options": ["forgive", "chat", "friend", "small talk"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"friend\"."}'),(2, 'qcm', '{"question": "\"connaissance\" = ?", "options": ["acquaintance", "guest", "apologize", "gossip (noun)"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"acquaintance\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "introduce", "right": "présenter (quelqu''un)"}, {"left": "chat", "right": "discuter"}, {"left": "gathering", "right": "rassemblement"}, {"left": "party", "right": "fête"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "guest", "right": "invité"}, {"left": "RSVP", "right": "répondre à une invitation"}, {"left": "small talk", "right": "conversation légère"}, {"left": "conversation", "right": "conversation"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"rumeur\" = ", "sentence_after": "", "correct_answers": ["rumor"], "feedback_correct": "Correct !", "feedback_incorrect": "\"rumeur\" se dit \"rumor\" en anglais."}'),(6, 'true_false', '{"statement": "\"forgive\" veut dire \"pardonner\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'sociale')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 2, 'Niveau 2', '[{"en": "bond (relationship)", "fr": "lien (relation)", "level": "B1"}, {"en": "trust", "fr": "confiance", "level": "A2"}, {"en": "loyalty", "fr": "loyauté", "level": "B1"}, {"en": "betrayal", "fr": "trahison", "level": "B1"}, {"en": "conflict", "fr": "conflit", "level": "A2"}, {"en": "reconcile", "fr": "se réconcilier", "level": "B1"}, {"en": "compromise (verb)", "fr": "faire un compromis", "level": "B1"}, {"en": "empathy", "fr": "empathie", "level": "B1"}, {"en": "sympathy", "fr": "sympathie/compassion", "level": "A2"}, {"en": "support (social)", "fr": "soutien", "level": "A2"}, {"en": "encourage", "fr": "encourager", "level": "A2"}, {"en": "criticize", "fr": "critiquer", "level": "A2"}, {"en": "judge (verb)", "fr": "juger", "level": "A2"}, {"en": "gossip (verb)", "fr": "cancaner", "level": "B1"}, {"en": "peer pressure", "fr": "pression sociale (pairs)", "level": "B1"}, {"en": "social circle", "fr": "cercle social", "level": "B1"}, {"en": "clique", "fr": "clan/groupe fermé", "level": "B1"}, {"en": "outcast", "fr": "paria", "level": "B1"}, {"en": "belong", "fr": "appartenir (groupe)", "level": "A2"}, {"en": "connection (social)", "fr": "connexion (sociale)", "level": "A2"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'sociale') and position = 2)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'sociale'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"lien (relation)\" = ?", "options": ["reconcile", "trust", "bond (relationship)", "betrayal"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"bond (relationship)\"."}'),(2, 'qcm', '{"question": "\"trahison\" = ?", "options": ["loyalty", "clique", "empathy", "betrayal"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"betrayal\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "compromise (verb)", "right": "faire un compromis"}, {"left": "empathy", "right": "empathie"}, {"left": "sympathy", "right": "sympathie/compassion"}, {"left": "support (social)", "right": "soutien"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "judge (verb)", "right": "juger"}, {"left": "gossip (verb)", "right": "cancaner"}, {"left": "peer pressure", "right": "pression sociale (pairs)"}, {"left": "social circle", "right": "cercle social"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"paria\" = ", "sentence_after": "", "correct_answers": ["outcast"], "feedback_correct": "Correct !", "feedback_incorrect": "\"paria\" se dit \"outcast\" en anglais."}'),(6, 'true_false', '{"statement": "\"connection (social)\" veut dire \"connexion (sociale)\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'sociale')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 3, 'Niveau 3', '[{"en": "rapport", "fr": "rapport/lien de confiance", "level": "B1"}, {"en": "camaraderie", "fr": "camaraderie", "level": "B1"}, {"en": "solidarity", "fr": "solidarité", "level": "B1"}, {"en": "alliance", "fr": "alliance", "level": "B1"}, {"en": "rivalry", "fr": "rivalité", "level": "B1"}, {"en": "feud", "fr": "querelle/conflit durable", "level": "B2"}, {"en": "reconciliation", "fr": "réconciliation", "level": "B1"}, {"en": "estrangement", "fr": "éloignement (relation)", "level": "C1"}, {"en": "confide", "fr": "se confier", "level": "B1"}, {"en": "vulnerable (social)", "fr": "vulnérable", "level": "B1"}, {"en": "boundaries (social)", "fr": "limites (personnelles)", "level": "B1"}, {"en": "assertiveness", "fr": "affirmation de soi", "level": "B1"}, {"en": "passive-aggressive", "fr": "passif-agressif", "level": "B2"}, {"en": "manipulative", "fr": "manipulateur", "level": "B1"}, {"en": "toxic relationship", "fr": "relation toxique", "level": "B1"}, {"en": "codependent", "fr": "codépendant", "level": "C1"}, {"en": "enabler", "fr": "personne qui encourage un comportement nuisible", "level": "C1"}, {"en": "ghosting", "fr": "disparition soudaine (relation)", "level": "B1"}, {"en": "catfishing", "fr": "usurpation d''identité en ligne", "level": "B1"}, {"en": "networking event", "fr": "événement de réseautage", "level": "B1"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'sociale') and position = 3)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'sociale'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"rapport/lien de confiance\" = ?", "options": ["estrangement", "feud", "rapport", "rivalry"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"rapport\"."}'),(2, 'qcm', '{"question": "\"alliance\" = ?", "options": ["codependent", "rapport", "alliance", "networking event"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"alliance\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "reconciliation", "right": "réconciliation"}, {"left": "estrangement", "right": "éloignement (relation)"}, {"left": "confide", "right": "se confier"}, {"left": "vulnerable (social)", "right": "vulnérable"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "passive-aggressive", "right": "passif-agressif"}, {"left": "manipulative", "right": "manipulateur"}, {"left": "toxic relationship", "right": "relation toxique"}, {"left": "codependent", "right": "codépendant"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"disparition soudaine (relation)\" = ", "sentence_after": "", "correct_answers": ["ghosting"], "feedback_correct": "Correct !", "feedback_incorrect": "\"disparition soudaine (relation)\" se dit \"ghosting\" en anglais."}'),(6, 'true_false', '{"statement": "\"networking event\" veut dire \"événement de réseautage\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'sociale')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 4, 'Niveau 4', '[{"en": "social capital", "fr": "capital social", "level": "C1"}, {"en": "social hierarchy", "fr": "hiérarchie sociale", "level": "B2"}, {"en": "in-group", "fr": "groupe d''appartenance", "level": "C1"}, {"en": "out-group", "fr": "groupe extérieur", "level": "C1"}, {"en": "groupthink", "fr": "pensée de groupe", "level": "C1"}, {"en": "herd mentality", "fr": "mentalité de troupeau", "level": "B2"}, {"en": "social proof", "fr": "preuve sociale", "level": "C1"}, {"en": "peer influence", "fr": "influence des pairs", "level": "B1"}, {"en": "social norm", "fr": "norme sociale", "level": "B1"}, {"en": "taboo", "fr": "tabou", "level": "B1"}, {"en": "faux pas", "fr": "impair/faux pas", "level": "B1"}, {"en": "etiquette", "fr": "étiquette (savoir-vivre)", "level": "B1"}, {"en": "decorum", "fr": "bienséance", "level": "C1"}, {"en": "social contract", "fr": "contrat social", "level": "C1"}, {"en": "reciprocity", "fr": "réciprocité", "level": "C1"}, {"en": "altruism", "fr": "altruisme", "level": "B1"}, {"en": "collectivism", "fr": "collectivisme", "level": "C1"}, {"en": "individualism", "fr": "individualisme", "level": "B1"}, {"en": "social cohesion", "fr": "cohésion sociale", "level": "C1"}, {"en": "community building", "fr": "construction communautaire", "level": "B2"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'sociale') and position = 4)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'sociale'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"capital social\" = ?", "options": ["community building", "social capital", "collectivism", "social hierarchy"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"social capital\"."}'),(2, 'qcm', '{"question": "\"groupe extérieur\" = ?", "options": ["decorum", "groupthink", "out-group", "etiquette"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"out-group\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "social proof", "right": "preuve sociale"}, {"left": "peer influence", "right": "influence des pairs"}, {"left": "social norm", "right": "norme sociale"}, {"left": "taboo", "right": "tabou"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "decorum", "right": "bienséance"}, {"left": "social contract", "right": "contrat social"}, {"left": "reciprocity", "right": "réciprocité"}, {"left": "altruism", "right": "altruisme"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"individualisme\" = ", "sentence_after": "", "correct_answers": ["individualism"], "feedback_correct": "Correct !", "feedback_incorrect": "\"individualisme\" se dit \"individualism\" en anglais."}'),(6, 'true_false', '{"statement": "\"community building\" veut dire \"construction communautaire\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

with t as (select id from vocab_themes where slug = 'sociale')
insert into vocab_theme_levels (theme_id, position, title, words)
select t.id, 5, 'Niveau 5', '[{"en": "sociality", "fr": "socialité", "level": "C1"}, {"en": "interpersonal dynamics", "fr": "dynamiques interpersonnelles", "level": "C1"}, {"en": "social stratification", "fr": "stratification sociale", "level": "C1"}, {"en": "homophily", "fr": "homophilie (affinité sociale)", "level": "C1"}, {"en": "social ostracism", "fr": "ostracisme social", "level": "C1"}, {"en": "in-group bias", "fr": "biais favorable au groupe", "level": "C1"}, {"en": "confirmation bias (social)", "fr": "biais de confirmation", "level": "C1"}, {"en": "echo chamber", "fr": "chambre d''écho (médias)", "level": "B2"}, {"en": "tribalism", "fr": "tribalisme", "level": "C1"}, {"en": "polarization (social)", "fr": "polarisation (sociale)", "level": "B2"}, {"en": "social capital erosion", "fr": "érosion du capital social", "level": "C1"}, {"en": "civic engagement", "fr": "engagement civique", "level": "B2"}, {"en": "grassroots movement", "fr": "mouvement populaire/citoyen", "level": "B2"}, {"en": "social fabric", "fr": "tissu social", "level": "C1"}, {"en": "communal identity", "fr": "identité communautaire", "level": "C1"}, {"en": "cultural assimilation", "fr": "assimilation culturelle", "level": "C1"}, {"en": "code-switching", "fr": "alternance codique", "level": "C1"}, {"en": "microaggression", "fr": "microagression", "level": "C1"}, {"en": "allyship", "fr": "solidarité active (allié)", "level": "C1"}, {"en": "intersectionality", "fr": "intersectionnalité", "level": "C1"}]'::jsonb from t;

with l as (select id from vocab_theme_levels where theme_id = (select id from vocab_themes where slug = 'sociale') and position = 5)
insert into vocab_theme_exercises (level_id, theme_id, position, type, content)
select l.id, (select id from vocab_themes where slug = 'sociale'), v.position, v.type, v.content::jsonb from l, (values
(1, 'qcm', '{"question": "\"socialité\" = ?", "options": ["cultural assimilation", "grassroots movement", "sociality", "in-group bias"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"sociality\"."}'),(2, 'qcm', '{"question": "\"homophilie (affinité sociale)\" = ?", "options": ["social capital erosion", "code-switching", "homophily", "tribalism"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"homophily\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "confirmation bias (social)", "right": "biais de confirmation"}, {"left": "echo chamber", "right": "chambre d''écho (médias)"}, {"left": "tribalism", "right": "tribalisme"}, {"left": "polarization (social)", "right": "polarisation (sociale)"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "grassroots movement", "right": "mouvement populaire/citoyen"}, {"left": "social fabric", "right": "tissu social"}, {"left": "communal identity", "right": "identité communautaire"}, {"left": "cultural assimilation", "right": "assimilation culturelle"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"microagression\" = ", "sentence_after": "", "correct_answers": ["microaggression"], "feedback_correct": "Correct !", "feedback_incorrect": "\"microagression\" se dit \"microaggression\" en anglais."}'),(6, 'true_false', '{"statement": "\"intersectionality\" veut dire \"intersectionnalité\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);
