-- ============================================
-- LUMA — Scénarios jouables : Thématique 5 (Urgence médicale) — complète
-- ============================================

update scenarios set content = '{"characters": {"doctor": "le médecin"}, "start_node": "n1", "nodes": {"n1": {"speaker": "doctor", "text": "What seems to be the problem today?", "text_fr": "Quel est le problème aujourd''hui ?", "choices": [{"text": "I have a sore throat and a slight fever.", "next": "n2"}, {"text": "My stomach has been hurting since yesterday.", "next": "n2b"}]}, "n2": {"speaker": "doctor", "text": "How long has this been going on?", "text_fr": "Depuis combien de temps ?", "choices": [{"text": "Since yesterday evening.", "next": "end_throat"}]}, "n2b": {"speaker": "doctor", "text": "Any particular food that might have caused it?", "text_fr": "Un aliment en particulier qui pourrait en être la cause ?", "choices": [{"text": "Maybe the seafood I had for lunch.", "next": "end_stomach"}]}, "end_throat": {"speaker": "doctor", "text": "Sounds like a common cold, rest and stay hydrated.", "text_fr": "Ça ressemble à un simple rhume, reposez-vous et hydratez-vous.", "end": true, "ending_label": "Diagnostic simple 🩺"}, "end_stomach": {"speaker": "doctor", "text": "Likely a mild food reaction, avoid heavy meals for a day.", "text_fr": "Probablement une réaction alimentaire légère, évitez les repas lourds un jour.", "end": true, "ending_label": "Diagnostic simple 🩺"}}}'::jsonb, is_playable = true
where title = 'Décrire un symptôme simple à un médecin'
  and theme_id = (select id from scenario_themes where position = 5 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"local": "un passant"}, "start_node": "n1", "nodes": {"n1": {"speaker": "local", "text": "Can I help you?", "text_fr": "Je peux vous aider ?", "choices": [{"text": "Yes, is there a pharmacy nearby?", "next": "n2"}]}, "n2": {"speaker": "local", "text": "Yes, there''s one two blocks down, on the left.", "text_fr": "Oui, il y en a une à deux rues d''ici, sur la gauche.", "choices": [{"text": "Thank you so much!", "next": "end_found"}]}, "end_found": {"speaker": "local", "text": "You''re welcome, I hope you feel better!", "text_fr": "De rien, j''espère que vous irez mieux !", "end": true, "ending_label": "Pharmacie trouvée 💊"}}}'::jsonb, is_playable = true
where title = 'Demander une pharmacie'
  and theme_id = (select id from scenario_themes where position = 5 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"operator": "l''opérateur d''urgence"}, "start_node": "n1", "nodes": {"n1": {"speaker": "operator", "text": "Emergency services, what''s your emergency?", "text_fr": "Services d''urgence, quelle est votre urgence ?", "choices": [{"text": "My friend just fell and can''t move their leg.", "next": "n2"}, {"text": "Someone is having trouble breathing.", "next": "n2b"}]}, "n2": {"speaker": "operator", "text": "Okay, what''s your location?", "text_fr": "D''accord, quelle est votre position ?", "choices": [{"text": "We''re at the corner of Main Street and 5th Avenue.", "next": "end_dispatched"}]}, "n2b": {"speaker": "operator", "text": "Stay calm, help is on the way. What''s your address?", "text_fr": "Restez calme, les secours arrivent. Quelle est votre adresse ?", "choices": [{"text": "123 Oak Street, second floor.", "next": "end_dispatched"}]}, "end_dispatched": {"speaker": "operator", "text": "An ambulance is on its way, stay on the line.", "text_fr": "Une ambulance arrive, restez en ligne.", "end": true, "ending_label": "Secours envoyés 🚑"}}}'::jsonb, is_playable = true
where title = 'Appeler les secours'
  and theme_id = (select id from scenario_themes where position = 5 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"doctor": "le médecin"}, "start_node": "n1", "nodes": {"n1": {"speaker": "doctor", "text": "So, what brings you in today?", "text_fr": "Alors, qu''est-ce qui vous amène aujourd''hui ?", "choices": [{"text": "I''ve had headaches for the past week.", "next": "n2"}]}, "n2": {"speaker": "doctor", "text": "Any changes in sleep or stress levels recently?", "text_fr": "Des changements dans votre sommeil ou niveau de stress récemment ?", "choices": [{"text": "Actually yes, I''ve been very stressed at work.", "next": "n3"}, {"text": "Not really, everything''s been normal.", "next": "n3b"}]}, "n3": {"speaker": "doctor", "text": "That''s likely tension headaches then. Let''s talk about stress management.", "text_fr": "Ce sont probablement des céphalées de tension. Parlons de gestion du stress.", "choices": [{"text": "That would be helpful, thank you.", "next": "n4"}]}, "n3b": {"speaker": "doctor", "text": "Let''s run a few basic checks just to be thorough.", "text_fr": "Faisons quelques vérifications de base pour être sûrs.", "choices": [{"text": "Sounds good.", "next": "n4"}]}, "n4": {"speaker": "doctor", "text": "Everything looks fine overall. Try to rest more and stay hydrated.", "text_fr": "Tout semble bien dans l''ensemble. Essayez de plus vous reposer et de bien vous hydrater.", "choices": [{"text": "I will, thank you doctor.", "next": "end_reassured"}]}, "end_reassured": {"speaker": "doctor", "text": "Come back if it doesn''t improve in a week.", "text_fr": "Revenez si ça ne s''améliore pas dans une semaine.", "end": true, "ending_label": "Consultation rassurante 🩺"}}}'::jsonb, is_playable = true
where title = 'Une visite chez le médecin complète'
  and theme_id = (select id from scenario_themes where position = 5 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"nurse": "l''infirmière"}, "start_node": "n1", "nodes": {"n1": {"speaker": "nurse", "text": "Are you allergic to any medications?", "text_fr": "Êtes-vous allergique à des médicaments ?", "choices": [{"text": "Yes, I''m allergic to penicillin, it gives me a rash.", "next": "n2"}, {"text": "I''m not sure, actually.", "next": "n2b"}]}, "n2": {"speaker": "nurse", "text": "Thank you, I''ll note that clearly in your file.", "text_fr": "Merci, je le note clairement dans votre dossier.", "choices": [{"text": "I appreciate that.", "next": "end_noted"}]}, "n2b": {"speaker": "nurse", "text": "No problem, we''ll monitor you closely just in case.", "text_fr": "Pas de souci, on vous surveillera de près par précaution.", "choices": [{"text": "That sounds reassuring, thank you.", "next": "end_noted"}]}, "end_noted": {"speaker": "nurse", "text": "Safety first — good thing you mentioned it.", "text_fr": "La sécurité avant tout — heureusement que vous l''avez mentionné.", "end": true, "ending_label": "Allergie bien notée ✅"}}}'::jsonb, is_playable = true
where title = 'Expliquer une allergie médicamenteuse'
  and theme_id = (select id from scenario_themes where position = 5 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"nurse": "l''infirmière de garde"}, "start_node": "n1", "nodes": {"n1": {"speaker": "nurse", "text": "What happened to your friend?", "text_fr": "Que s''est-il passé pour votre ami(e) ?", "choices": [{"text": "She fell down the stairs and hit her head.", "next": "n2"}]}, "n2": {"speaker": "nurse", "text": "Did she lose consciousness at any point?", "text_fr": "A-t-elle perdu connaissance à un moment ?", "choices": [{"text": "Yes, for a few seconds.", "next": "n3"}, {"text": "No, she stayed conscious the whole time.", "next": "n3b"}]}, "n3": {"speaker": "nurse", "text": "Okay, we''ll prioritize her for a scan right away.", "text_fr": "D''accord, on va la prioriser pour un scanner tout de suite.", "choices": [{"text": "Thank you, please hurry.", "next": "end_priority"}]}, "n3b": {"speaker": "nurse", "text": "Good, still we''ll check her thoroughly to be safe.", "text_fr": "Bien, on va quand même bien la vérifier par sécurité.", "choices": [{"text": "Thank you for taking care of her.", "next": "end_care"}]}, "end_priority": {"speaker": "nurse", "text": "A doctor will see her within minutes.", "text_fr": "Un médecin la verra dans quelques minutes.", "end": true, "ending_label": "Prise en charge rapide 🏥"}, "end_care": {"speaker": "nurse", "text": "She''s in good hands, please have a seat.", "text_fr": "Elle est entre de bonnes mains, veuillez vous asseoir.", "end": true, "ending_label": "Situation sous contrôle ✅"}}}'::jsonb, is_playable = true
where title = 'Accompagner un proche aux urgences'
  and theme_id = (select id from scenario_themes where position = 5 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"doctor": "le médecin", "admin": "l''administration"}, "start_node": "n1", "nodes": {"n1": {"speaker": "doctor", "text": "We''d like to keep you overnight for observation.", "text_fr": "On aimerait vous garder cette nuit en observation.", "choices": [{"text": "Okay, is my travel insurance accepted here?", "next": "n2"}]}, "n2": {"speaker": "admin", "text": "Let me check your policy — yes, it''s covered.", "text_fr": "Laissez-moi vérifier votre police — oui, c''est couvert.", "choices": [{"text": "That''s a relief, thank you.", "next": "n3"}]}, "n3": {"speaker": "doctor", "text": "You''ll need to rest, but you should be discharged by tomorrow morning.", "text_fr": "Vous devrez vous reposer, mais vous devriez sortir demain matin.", "choices": [{"text": "Understood, thank you for taking care of me.", "next": "end_discharged"}]}, "end_discharged": {"speaker": "doctor", "text": "Take care, and safe travels home.", "text_fr": "Prenez soin de vous, et bon retour.", "end": true, "ending_label": "Séjour bien géré 🏥"}}}'::jsonb, is_playable = true
where title = 'Un séjour bref à l''hôpital à l''étranger'
  and theme_id = (select id from scenario_themes where position = 5 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"stranger": "un passant", "operator": "l''opérateur"}, "start_node": "n1", "nodes": {"n1": {"speaker": "stranger", "text": "(speaking a language you don''t understand, pointing at an injured person)", "text_fr": "(parle une langue que vous ne comprenez pas, en montrant une personne blessée)", "choices": [{"text": "I''ll call emergency services right now.", "next": "n2"}, {"text": "Try using a translation app to communicate.", "next": "n2b"}]}, "n2": {"speaker": "operator", "text": "Emergency services, what''s happening?", "text_fr": "Services d''urgence, que se passe-t-il ?", "choices": [{"text": "Someone is injured, I don''t know the exact cause, but they need help urgently.", "next": "end_help"}]}, "n2b": {"speaker": "stranger", "text": "(the app translates: \"He fell off his bike, his arm looks broken.\")", "text_fr": "(l''appli traduit : \"Il est tombé de vélo, son bras semble cassé.\")", "choices": [{"text": "Thank you, now I can explain clearly to the operator.", "next": "n2"}]}, "end_help": {"speaker": "operator", "text": "Help is on the way, stay with the person.", "text_fr": "Les secours arrivent, restez avec la personne.", "end": true, "ending_label": "Communication réussie malgré la barrière 🌍"}}}'::jsonb, is_playable = true
where title = 'Gérer une urgence avec la barrière de la langue'
  and theme_id = (select id from scenario_themes where position = 5 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"doctor": "le médecin"}, "start_node": "n1", "nodes": {"n1": {"speaker": "doctor", "text": "How have you been feeling since our last appointment?", "text_fr": "Comment vous êtes-vous senti depuis notre dernier rendez-vous ?", "choices": [{"text": "Much better, the medication is working well.", "next": "n2"}, {"text": "Honestly, not much has changed.", "next": "n2b"}]}, "n2": {"speaker": "doctor", "text": "That''s great news, let''s continue the current treatment.", "text_fr": "Excellente nouvelle, continuons le traitement actuel.", "choices": [{"text": "Sounds good, thank you.", "next": "end_continue"}]}, "n2b": {"speaker": "doctor", "text": "Let''s adjust the dosage and see how that goes.", "text_fr": "Ajustons la dose et voyons comment ça évolue.", "choices": [{"text": "Okay, I''ll follow the new plan.", "next": "end_adjust"}]}, "end_continue": {"speaker": "doctor", "text": "See you in two weeks for a follow-up.", "text_fr": "On se revoit dans deux semaines pour un suivi.", "end": true, "ending_label": "Traitement efficace ✅"}, "end_adjust": {"speaker": "doctor", "text": "We''ll monitor closely and adjust as needed.", "text_fr": "On surveillera de près et ajustera si besoin.", "end": true, "ending_label": "Traitement ajusté 🩺"}}}'::jsonb, is_playable = true
where title = 'Un suivi médical sur plusieurs jours'
  and theme_id = (select id from scenario_themes where position = 5 and language_id = (select id from languages where code = 'en'));
