-- ============================================
-- LUMA — Thème 17 (Sport) : 3 scénarios COURTS x4
-- ============================================


update scenarios set content = '{"characters": {"staff": "l''employé de la salle"}, "start_node": "n1", "nodes": {"n1": {"speaker": "staff", "text": "Welcome! Are you looking for a monthly or annual membership?", "text_fr": "Bienvenue ! Vous cherchez un abonnement mensuel ou annuel ?", "choices": [{"text": "Monthly, I want to try it out first.", "text_fr": "Mensuel, je veux essayer d''abord.", "next": "n2"}, {"text": "Do you offer a free trial day?", "text_fr": "Vous offrez une journée d''essai gratuite ?", "next": "n2b"}]}, "n2": {"speaker": "staff", "text": "Sure thing, monthly is $45. Want a tour of the facilities first?", "text_fr": "Bien sûr, le mensuel est à 45$. Vous voulez une visite des installations d''abord ?", "choices": [{"text": "Yes please, I''d love to see what''s available.", "text_fr": "Oui s''il vous plaît, j''aimerais voir ce qui est disponible.", "next": "n3"}]}, "n2b": {"speaker": "staff", "text": "Yes, we do! You can try a full day for free.", "text_fr": "Oui, tout à fait ! Vous pouvez essayer une journée complète gratuitement.", "choices": [{"text": "Perfect, I''ll start with that and decide after.", "text_fr": "Parfait, je vais commencer par ça et décider après.", "next": "n3"}]}, "n3": {"speaker": "staff", "text": "Great, let me show you the weight room and cardio area.", "text_fr": "Super, laissez-moi vous montrer la salle de musculation et la zone cardio.", "choices": [{"text": "This looks great, do you offer any classes too?", "text_fr": "Ça a l''air super, vous offrez aussi des cours ?", "next": "n4"}]}, "n4": {"speaker": "staff", "text": "Yes, spin, yoga, and HIIT classes included in your membership.", "text_fr": "Oui, spinning, yoga, et cours HIIT inclus dans votre abonnement.", "choices": [{"text": "That''s a great deal, I''m definitely signing up.", "text_fr": "C''est une super affaire, je m''inscris définitivement.", "next": "n5"}]}, "n5": {"speaker": "staff", "text": "Great, here''s your membership card, welcome to the gym!", "text_fr": "Parfait, voici votre carte d''adhésion, bienvenue à la salle !", "choices": [{"text": "Thank you, I''m excited to get started!", "text_fr": "Merci, j''ai hâte de commencer !", "next": "end_signed"}]}, "end_signed": {"speaker": "staff", "text": "Let us know if you have any questions along the way!", "text_fr": "Faites-nous savoir si vous avez des questions en cours de route !", "end": true, "ending_label": "Inscription réussie à la salle de sport 🏋️✅"}}}'::jsonb, is_playable = true
where title = 'S''''inscrire dans une salle de sport'
  and theme_id = (select id from scenario_themes where position = 17 and language_id = (select id from languages where code = 'en'));


update scenarios set content = '{"characters": {"friend": "ton ami"}, "start_node": "n1", "nodes": {"n1": {"speaker": "friend", "text": "Wait, why did the referee stop the game there?", "text_fr": "Attends, pourquoi l''arbitre a arrêté le match là ?", "choices": [{"text": "That was offside, the player was ahead of the last defender.", "text_fr": "C''était hors-jeu, le joueur était devant le dernier défenseur.", "next": "n2"}, {"text": "Honestly, I''m not totally sure either.", "text_fr": "Honnêtement, je suis pas totalement sûr non plus.", "next": "n2b"}]}, "n2": {"speaker": "friend", "text": "Ah, that makes sense now. How do you know all these rules so well?", "text_fr": "Ah, ça a du sens maintenant. Comment tu connais si bien toutes ces règles ?", "choices": [{"text": "I played for years growing up, it kind of sticks with you.", "text_fr": "J''ai joué pendant des années en grandissant, ça reste un peu.", "next": "n3"}]}, "n2b": {"speaker": "friend", "text": "Let''s look it up together then, I''m curious now.", "text_fr": "Cherchons ensemble alors, je suis curieux maintenant.", "choices": [{"text": "Good idea, let''s check the replay and the rule together.", "text_fr": "Bonne idée, vérifions le replay et la règle ensemble.", "next": "n3"}]}, "n3": {"speaker": "friend", "text": "That''s cool, I never played seriously, just watched casually.", "text_fr": "C''est cool, j''ai jamais joué sérieusement, juste regardé occasionnellement.", "choices": [{"text": "Want me to explain a few more rules as the match goes on?", "text_fr": "Tu veux que je t''explique d''autres règles pendant que le match continue ?", "next": "n4"}]}, "n4": {"speaker": "friend", "text": "Actually, yes! This would make watching so much more enjoyable.", "text_fr": "En fait, oui ! Ça rendrait regarder bien plus agréable.", "choices": [{"text": "Happy to help, let''s keep watching and I''ll point things out.", "text_fr": "Content d''aider, continuons à regarder et je vais te signaler des choses.", "next": "n5"}]}, "n5": {"speaker": "friend", "text": "This is honestly making the game so much more interesting now.", "text_fr": "Ça rend honnêtement le match bien plus intéressant maintenant.", "choices": [{"text": "Glad to hear that! Football makes a lot more sense once you know the rules.", "text_fr": "Content de l''entendre ! Le foot a beaucoup plus de sens une fois qu''on connaît les règles.", "next": "end_explained"}]}, "end_explained": {"speaker": "friend", "text": "Thanks for taking the time to explain, I really appreciate it.", "text_fr": "Merci d''avoir pris le temps d''expliquer, j''apprécie vraiment.", "end": true, "ending_label": "Règles du match bien expliquées ⚽📖"}}}'::jsonb, is_playable = true
where title = 'Discuter des règles d''''un match avec un ami'
  and theme_id = (select id from scenario_themes where position = 17 and language_id = (select id from languages where code = 'en'));
