-- ============================================
-- LUMA — Scénarios jouables : Thématique 9 (Donjons & Dragons) — complète
-- ============================================

update scenarios set content = '{"characters": {"gm": "le maître du jeu"}, "start_node": "n1", "nodes": {"n1": {"speaker": "gm", "text": "Alright, adventurer! Warrior, mage, or rogue — what''s your calling?", "text_fr": "Bien, aventurier ! Guerrier, mage ou voleur — quelle est ta vocation ?", "choices": [{"text": "A warrior, strong and brave.", "next": "end_warrior"}, {"text": "A mage, master of arcane arts.", "next": "end_mage"}, {"text": "A rogue, quick and clever.", "next": "end_rogue"}]}, "end_warrior": {"speaker": "gm", "text": "A shield and sword await you, warrior!", "text_fr": "Un bouclier et une épée t''attendent, guerrier !", "end": true, "ending_label": "Guerrier créé ⚔️"}, "end_mage": {"speaker": "gm", "text": "Your spellbook glows with untapped power!", "text_fr": "Ton grimoire brille d''un pouvoir inexploité !", "end": true, "ending_label": "Mage créé 🔮"}, "end_rogue": {"speaker": "gm", "text": "Shadows will be your greatest ally!", "text_fr": "Les ombres seront ta meilleure alliée !", "end": true, "ending_label": "Voleur créé 🗡️"}}}'::jsonb, is_playable = true
where title = 'Créer son personnage et choisir sa classe'
  and theme_id = (select id from scenario_themes where position = 9 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"gm": "le maître du jeu"}, "start_node": "n1", "nodes": {"n1": {"speaker": "gm", "text": "You notice a pressure plate on the floor ahead. What do you do?", "text_fr": "Tu remarques une plaque de pression au sol devant toi. Que fais-tu ?", "choices": [{"text": "Carefully examine it before stepping near.", "next": "n2"}, {"text": "Try to jump over it.", "next": "n2b"}]}, "n2": {"speaker": "gm", "text": "You spot a thin wire connected to darts in the wall — you disarm it safely.", "text_fr": "Tu repères un fil fin relié à des fléchettes dans le mur — tu le désamorces en sécurité.", "choices": [{"text": "Continue forward carefully.", "next": "end_safe"}]}, "n2b": {"speaker": "gm", "text": "You clear it, but barely — a dart grazes your arm!", "text_fr": "Tu le franchis, mais de justesse — une fléchette t''égratigne le bras !", "choices": [{"text": "Shake it off and continue.", "next": "end_grazed"}]}, "end_safe": {"speaker": "gm", "text": "Well done, the path ahead is clear.", "text_fr": "Bien joué, le chemin est dégagé.", "end": true, "ending_label": "Piège désamorcé proprement ✅"}, "end_grazed": {"speaker": "gm", "text": "A close call, but you press on.", "text_fr": "Ça passe de justesse, mais tu continues.", "end": true, "ending_label": "Piège évité de justesse ⚡"}}}'::jsonb, is_playable = true
where title = 'Un premier piège à désamorcer'
  and theme_id = (select id from scenario_themes where position = 9 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"bandit": "un bandit"}, "start_node": "n1", "nodes": {"n1": {"speaker": "bandit", "text": "Your gold or your life, traveler!", "text_fr": "Ton or ou ta vie, voyageur !", "choices": [{"text": "I have no gold, but I could use an ally instead.", "next": "n2"}, {"text": "Draw your weapon and prepare to fight.", "next": "n2b"}]}, "n2": {"speaker": "bandit", "text": "(pauses) An ally... that''s new. What''s in it for me?", "text_fr": "(marque une pause) Un allié... ça change. Qu''est-ce que j''y gagne ?", "choices": [{"text": "A share of treasure from the dungeon ahead.", "next": "end_ally"}]}, "n2b": {"speaker": "bandit", "text": "So be it then!", "text_fr": "Qu''il en soit ainsi alors !", "choices": [{"text": "(a brief fight, you emerge victorious)", "next": "end_fight"}]}, "end_ally": {"speaker": "bandit", "text": "Deal! Lead the way, partner.", "text_fr": "Marché conclu ! Montre le chemin, partenaire.", "end": true, "ending_label": "Nouvel allié recruté 🤝"}, "end_fight": {"speaker": "bandit", "text": "You win... take my coin purse, just let me go.", "text_fr": "Tu gagnes... prends ma bourse, laisse-moi juste partir.", "end": true, "ending_label": "Bandit vaincu ⚔️"}}}'::jsonb, is_playable = true
where title = 'Une rencontre avec un PNJ hostile'
  and theme_id = (select id from scenario_themes where position = 9 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"gm": "le maître du jeu"}, "start_node": "n1", "nodes": {"n1": {"speaker": "gm", "text": "Two doors ahead: one rusted and creaking, one strangely silent. Which do you choose?", "text_fr": "Deux portes devant toi : une rouillée qui grince, une étrangement silencieuse. Laquelle choisis-tu ?", "choices": [{"text": "The rusted door, better the danger I can hear.", "next": "n2"}, {"text": "The silent door, curiosity wins.", "next": "n2b"}]}, "n2": {"speaker": "gm", "text": "Inside: a small chest guarded by two goblins.", "text_fr": "À l''intérieur : un petit coffre gardé par deux gobelins.", "choices": [{"text": "Sneak past them toward the chest.", "next": "n3"}, {"text": "Fight them directly.", "next": "n3b"}]}, "n2b": {"speaker": "gm", "text": "Inside: an eerie altar with a glowing sword floating above it.", "text_fr": "À l''intérieur : un autel inquiétant avec une épée lumineuse flottant au-dessus.", "choices": [{"text": "Approach and take the sword.", "next": "n3c"}]}, "n3": {"speaker": "gm", "text": "You succeed! The goblins never notice you.", "text_fr": "Tu réussis ! Les gobelins ne te remarquent jamais.", "choices": [{"text": "Grab the treasure and leave quietly.", "next": "end_stealth"}]}, "n3b": {"speaker": "gm", "text": "A tough fight, but you defeat them both!", "text_fr": "Un combat difficile, mais tu les vaincs tous les deux !", "choices": [{"text": "Take the chest, victorious.", "next": "end_fight"}]}, "n3c": {"speaker": "gm", "text": "The sword hums with power as it recognizes you as worthy.", "text_fr": "L''épée vibre de puissance en te reconnaissant digne.", "choices": [{"text": "Take the sword, feeling its power.", "next": "end_sword"}]}, "end_stealth": {"speaker": "gm", "text": "A flawless, stealthy victory!", "text_fr": "Une victoire furtive et parfaite !", "end": true, "ending_label": "Approche furtive réussie 🥷"}, "end_fight": {"speaker": "gm", "text": "A hard-earned victory through combat.", "text_fr": "Une victoire durement gagnée au combat.", "end": true, "ending_label": "Victoire au combat ⚔️"}, "end_sword": {"speaker": "gm", "text": "You now wield a legendary weapon!", "text_fr": "Tu brandis maintenant une arme légendaire !", "end": true, "ending_label": "Arme légendaire obtenue ✨"}}}'::jsonb, is_playable = true
where title = 'Explorer un donjon à plusieurs salles avec choix tactiques'
  and theme_id = (select id from scenario_themes where position = 9 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"dragon": "le dragon ancien"}, "start_node": "n1", "nodes": {"n1": {"speaker": "dragon", "text": "Why do you dare enter my lair, small creature?", "text_fr": "Pourquoi oses-tu entrer dans mon antre, petite créature ?", "choices": [{"text": "I come not to fight, but to seek your wisdom.", "next": "n2"}, {"text": "I demand you hand over your treasure!", "next": "n2b"}]}, "n2": {"speaker": "dragon", "text": "Wisdom, you say? Few seek that from me anymore.", "text_fr": "La sagesse, dis-tu ? Peu la cherchent encore auprès de moi.", "choices": [{"text": "Your centuries of knowledge are legendary.", "next": "end_wisdom"}]}, "n2b": {"speaker": "dragon", "text": "Bold, but foolish. That is not how one speaks to a dragon.", "text_fr": "Audacieux, mais imprudent. Ce n''est pas ainsi qu''on parle à un dragon.", "choices": [{"text": "You''re right, forgive my rudeness. I ask instead.", "next": "end_apology"}]}, "end_wisdom": {"speaker": "dragon", "text": "Very well. I shall share what I know, traveler.", "text_fr": "Très bien. Je partagerai ce que je sais, voyageur.", "end": true, "ending_label": "Sagesse du dragon obtenue 🐉"}, "end_apology": {"speaker": "dragon", "text": "Humility suits you. Perhaps we can talk after all.", "text_fr": "L''humilité te va bien. Peut-être pouvons-nous parler après tout.", "end": true, "ending_label": "Confrontation évitée avec sagesse 🕊️"}}}'::jsonb, is_playable = true
where title = 'Négocier avec un dragon plutôt que combattre'
  and theme_id = (select id from scenario_themes where position = 9 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"companion": "ton compagnon d''aventure"}, "start_node": "n1", "nodes": {"n1": {"speaker": "companion", "text": "We only have one healing potion left, and I''m badly hurt. What do we do?", "text_fr": "Il ne nous reste qu''une potion de soin, et je suis gravement blessé. Que fait-on ?", "choices": [{"text": "Take it, you need it more than me.", "next": "end_selfless"}, {"text": "Let''s save it in case things get worse ahead.", "next": "end_cautious"}]}, "end_selfless": {"speaker": "companion", "text": "Thank you... I won''t forget this kindness.", "text_fr": "Merci... je n''oublierai pas cette gentillesse.", "end": true, "ending_label": "Sacrifice généreux 💙"}, "end_cautious": {"speaker": "companion", "text": "A hard call, but I understand the strategy.", "text_fr": "Un choix difficile, mais je comprends la stratégie.", "end": true, "ending_label": "Décision stratégique prudente 🎒"}}}'::jsonb, is_playable = true
where title = 'Gérer l''inventaire et un dilemme moral'
  and theme_id = (select id from scenario_themes where position = 9 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"gm": "le maître du jeu"}, "start_node": "n1", "nodes": {"n1": {"speaker": "gm", "text": "The first dungeon, the Sunken Crypt, looms before you. Enter carefully.", "text_fr": "Le premier donjon, la Crypte Engloutie, se dresse devant toi. Entre prudemment.", "choices": [{"text": "Light a torch and proceed slowly.", "next": "n2"}]}, "n2": {"speaker": "gm", "text": "You find an ancient key, but a skeleton guardian awakens!", "text_fr": "Tu trouves une clé ancienne, mais un gardien squelette se réveille !", "choices": [{"text": "Fight the guardian.", "next": "n3"}, {"text": "Try to sneak past with the key.", "next": "n3b"}]}, "n3": {"speaker": "gm", "text": "Victory! You claim the key and move to the second dungeon: the Frozen Spire.", "text_fr": "Victoire ! Tu récupères la clé et te diriges vers le second donjon : la Flèche Gelée.", "choices": [{"text": "Press onward into the cold.", "next": "n4"}]}, "n3b": {"speaker": "gm", "text": "You slip past unnoticed, key in hand, heading to the Frozen Spire.", "text_fr": "Tu te faufiles sans être remarqué, clé en main, vers la Flèche Gelée.", "choices": [{"text": "Press onward into the cold.", "next": "n4"}]}, "n4": {"speaker": "gm", "text": "At the peak, a final trial awaits: the Sealed Vault.", "text_fr": "Au sommet, une dernière épreuve t''attend : le Coffre Scellé.", "choices": [{"text": "Use the key to open the vault.", "next": "n5"}]}, "n5": {"speaker": "gm", "text": "Inside lies the artifact you sought all along — the campaign''s climax!", "text_fr": "À l''intérieur repose l''artefact que tu cherchais depuis le début — l''apogée de la campagne !", "choices": [{"text": "Claim the artifact and complete the journey.", "next": "end_campaign"}]}, "end_campaign": {"speaker": "gm", "text": "Your legend will be told for generations, adventurer!", "text_fr": "Ta légende sera racontée pendant des générations, aventurier !", "end": true, "ending_label": "Campagne épique achevée 🏆"}}}'::jsonb, is_playable = true
where title = 'Une campagne complète sur plusieurs donjons'
  and theme_id = (select id from scenario_themes where position = 9 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"companion": "ton compagnon"}, "start_node": "n1", "nodes": {"n1": {"speaker": "companion", "text": "I... I have to confess. I''ve been reporting our movements to the enemy.", "text_fr": "Je... je dois avouer. J''ai rapporté nos déplacements à l''ennemi.", "choices": [{"text": "Why would you betray us like this?", "next": "n2"}, {"text": "I already suspected — what changed your mind now?", "next": "n2b"}]}, "n2": {"speaker": "companion", "text": "They threatened my family. I had no choice... I''m so sorry.", "text_fr": "Ils ont menacé ma famille. Je n''avais pas le choix... je suis désolé.", "choices": [{"text": "Then let''s find a way to protect your family together.", "next": "end_forgive"}, {"text": "I understand, but trust will take time to rebuild.", "next": "end_cautious"}]}, "n2b": {"speaker": "companion", "text": "Guilt, mostly. I couldn''t keep lying to you.", "text_fr": "Surtout la culpabilité. Je ne pouvais plus continuer à te mentir.", "choices": [{"text": "Your honesty now means something. Let''s fix this together.", "next": "end_forgive"}]}, "end_forgive": {"speaker": "companion", "text": "Thank you... I''ll make this right, I promise.", "text_fr": "Merci... je vais réparer ça, je te le promets.", "end": true, "ending_label": "Confiance reconstruite 💙"}, "end_cautious": {"speaker": "companion", "text": "That''s fair. I''ll prove myself over time.", "text_fr": "C''est juste. Je te prouverai ma valeur avec le temps.", "end": true, "ending_label": "Trahison gérée avec prudence ⚠️"}}}'::jsonb, is_playable = true
where title = 'Une trahison au sein du groupe à gérer'
  and theme_id = (select id from scenario_themes where position = 9 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"boss": "le seigneur liche"}, "start_node": "n1", "nodes": {"n1": {"speaker": "boss", "text": "You''ve come far, mortal. But none survive my final chamber.", "text_fr": "Tu es venu de loin, mortel. Mais personne ne survit à ma chambre finale.", "choices": [{"text": "Attack directly with your weapon.", "next": "n2"}, {"text": "Use a spell to weaken his defenses first.", "next": "n2b"}, {"text": "Search the room for a weakness before engaging.", "next": "n2c"}]}, "n2": {"speaker": "boss", "text": "A direct assault — bold, but predictable!", "text_fr": "Un assaut direct — audacieux, mais prévisible !", "choices": [{"text": "Adapt your strategy mid-fight.", "next": "end_direct"}]}, "n2b": {"speaker": "boss", "text": "You dare weaken me with magic? Impressive, actually.", "text_fr": "Tu oses m''affaiblir avec de la magie ? Impressionnant, en fait.", "choices": [{"text": "Press the advantage while he''s weakened.", "next": "end_magic"}]}, "n2c": {"speaker": "boss", "text": "You found the phylactery! My power wanes!", "text_fr": "Tu as trouvé le phylactère ! Mon pouvoir décline !", "choices": [{"text": "Destroy the phylactery to end the fight.", "next": "end_smart"}]}, "end_direct": {"speaker": "boss", "text": "Impossible... defeated by sheer will.", "text_fr": "Impossible... vaincu par pure volonté.", "end": true, "ending_label": "Victoire par la force 💪"}, "end_magic": {"speaker": "boss", "text": "Clever... your magic was my undoing.", "text_fr": "Astucieux... ta magie a causé ma perte.", "end": true, "ending_label": "Victoire tactique par magie 🔮"}, "end_smart": {"speaker": "boss", "text": "You found my true weakness... well played, adventurer.", "text_fr": "Tu as trouvé ma vraie faiblesse... bien joué, aventurier.", "end": true, "ending_label": "Victoire la plus intelligente 🧠🏆"}}}'::jsonb, is_playable = true
where title = 'Un combat de boss final avec plusieurs stratégies possibles'
  and theme_id = (select id from scenario_themes where position = 9 and language_id = (select id from languages where code = 'en'));
