-- ============================================
-- LUMA — Livre du domaine public : 'The Gift of the Magi' (O. Henry, 1905)
-- Nouvelle complète, texte original, domaine public
-- ============================================


with lang as (select id from languages where code = 'en')
insert into books (language_id, title, theme, description, cecr_level, cover_emoji, total_pages, position)
select id, 'The Gift of the Magi', 'Classique • O. Henry (1905)', 'Une nouvelle intemporelle sur l''amour et le sacrifice : Della et Jim, un jeune couple sans le sou, chacun vend son bien le plus précieux pour offrir à l''autre un cadeau de Noël parfait. Domaine public.', 'C1', '🎁', 5, 10
from lang;


with b as (select id from books where title = 'The Gift of the Magi' and language_id = (select id from languages where code = 'en'))
insert into book_pages (book_id, page_number, sentences)
select b.id, 1, '[{"en": "One dollar and eighty-seven cents. That was all. And sixty cents of it was in pennies.", "fr": "Un dollar et quatre-vingt-sept cents. C''était tout. Et soixante cents étaient en petites pièces."}, {"en": "Three times Della counted it. One dollar and eighty-seven cents. And the next day would be Christmas.", "fr": "Della les compta trois fois. Un dollar et quatre-vingt-sept cents. Et le lendemain serait Noël."}, {"en": "There was clearly nothing to do but flop down on the shabby little couch and howl. So Della did it.", "fr": "Il n''y avait clairement rien d''autre à faire que de s''effondrer sur le petit canapé miteux et de sangloter. C''est ce que fit Della."}, {"en": "A furnished flat at $8 per week — it did not exactly beggar description, but it certainly looked poor.", "fr": "Un appartement meublé à 8 dollars par semaine — cela ne défiait pas exactement toute description, mais avait certainement l''air pauvre."}, {"en": "Tomorrow would be Christmas Day, and she had only $1.87 with which to buy Jim a present.", "fr": "Demain serait le jour de Noël, et elle n''avait que 1,87 dollar pour acheter un cadeau à Jim."}, {"en": "She had been saving every penny she could for months, with this poor result.", "fr": "Elle avait économisé chaque centime possible pendant des mois, pour ce maigre résultat."}]'::jsonb from b;


with b as (select id from books where title = 'The Gift of the Magi' and language_id = (select id from languages where code = 'en'))
insert into book_pages (book_id, page_number, sentences)
select b.id, 2, '[{"en": "Now, there were two possessions of the Youngs in which they both took a mighty pride: Jim''s gold watch, and Della''s hair.", "fr": "Or, il y avait deux possessions des Young dont ils étaient tous deux immensément fiers : la montre en or de Jim, et les cheveux de Della."}, {"en": "Della''s beautiful hair fell about her, rippling and shining like a cascade of brown waters, reaching below her knee.", "fr": "Les beaux cheveux de Della tombaient autour d''elle, ondoyants et brillants comme une cascade d''eaux brunes, descendant sous son genou."}, {"en": "Suddenly she whirled from the window, pulled down her hair, and let it fall to its full length.", "fr": "Soudain elle se détourna de la fenêtre, défit ses cheveux, et les laissa tomber sur toute leur longueur."}, {"en": "On went her old brown jacket and hat. She fluttered out the door and down the stairs to the street.", "fr": "Elle enfila sa vieille veste et son chapeau marron. Elle s''élança par la porte et descendit les escaliers vers la rue."}, {"en": "Where she stopped, the sign read: ''Mme. Sofronie. Hair Goods of All Kinds.''", "fr": "Là où elle s''arrêta, l''enseigne disait : ''Mme Sofronie. Articles capillaires en tout genre.''"}, {"en": "''Will you buy my hair?'' asked Della. ''I buy hair,'' said Madame. ''Twenty dollars,'' she said, lifting the mass.", "fr": "''Voulez-vous acheter mes cheveux ?'' demanda Della. ''J''achète des cheveux,'' dit Madame. ''Vingt dollars,'' dit-elle, soulevant la masse."}]'::jsonb from b;


with b as (select id from books where title = 'The Gift of the Magi' and language_id = (select id from languages where code = 'en'))
insert into book_pages (book_id, page_number, sentences)
select b.id, 3, '[{"en": "The next two hours tripped by on rosy wings as she ransacked the stores for Jim''s present.", "fr": "Les deux heures suivantes s''envolèrent sur des ailes roses tandis qu''elle fouillait les magasins à la recherche du cadeau de Jim."}, {"en": "She found it at last: a platinum fob chain, simple and chaste in design, worthy of The Watch.", "fr": "Elle le trouva enfin : une chaîne de montre en platine, simple et sobre dans son dessin, digne de La Montre."}, {"en": "Twenty-one dollars they took from her for it, and she hurried home with the eighty-seven cents.", "fr": "On lui prit vingt-et-un dollars pour cela, et elle rentra en hâte avec les quatre-vingt-sept cents restants."}, {"en": "She worked for forty minutes with her curling irons, repairing the ravages made by generosity added to love.", "fr": "Elle travailla quarante minutes avec ses fers à friser, réparant les dégâts causés par la générosité ajoutée à l''amour."}, {"en": "''If Jim doesn''t kill me before he takes a second look at me, he''ll say I look like a Coney Island chorus girl,'' she said to herself.", "fr": "''Si Jim ne me tue pas avant de me regarder une seconde fois, il dira que j''ai l''air d''une danseuse de Coney Island,'' se dit-elle."}, {"en": "At seven o''clock, Della sat waiting, whispering a little prayer: ''Please God, make him think I am still pretty.''", "fr": "À sept heures, Della était assise à attendre, murmurant une petite prière : ''Je vous en prie mon Dieu, faites qu''il me trouve encore jolie.''"}]'::jsonb from b;


with b as (select id from books where title = 'The Gift of the Magi' and language_id = (select id from languages where code = 'en'))
insert into book_pages (book_id, page_number, sentences)
select b.id, 4, '[{"en": "The door opened and Jim stepped in. He stopped immovable, staring at her with an expression she could not read, and it terrified her.", "fr": "La porte s''ouvrit et Jim entra. Il s''arrêta net, la fixant avec une expression qu''elle ne pouvait déchiffrer, et cela la terrifia."}, {"en": "''Jim, darling,'' she cried, ''I had my hair cut off and sold because I couldn''t have lived through Christmas without giving you a present.''", "fr": "''Jim, chéri,'' s''écria-t-elle, ''j''ai fait couper et vendre mes cheveux parce que je n''aurais pas pu supporter Noël sans te faire de cadeau.''"}, {"en": "''You''ve cut off your hair?'' asked Jim, as if he had not yet arrived at that fact even after the hardest mental labor.", "fr": "''Tu as coupé tes cheveux ?'' demanda Jim, comme s''il n''était pas encore parvenu à ce constat malgré le plus dur des efforts mentaux."}, {"en": "Out of his trance Jim seemed to wake. He enfolded his Della, then drew a package from his overcoat pocket and threw it upon the table.", "fr": "Jim sembla sortir de sa transe. Il enlaça sa Della, puis tira un paquet de la poche de son manteau et le jeta sur la table."}, {"en": "Della tore at the string and paper — there lay The Combs, the set she had worshipped long in a Broadway window, pure tortoise shell with jewelled rims.", "fr": "Della déchira la ficelle et le papier — là se trouvaient Les Peignes, l''ensemble qu''elle avait admiré si longtemps dans une vitrine de Broadway, en écaille pure aux bords sertis de bijoux."}, {"en": "But the tresses that should have adorned the coveted adornments were gone. ''My hair grows so fast, Jim!'' she said with a smile.", "fr": "Mais les tresses qui auraient dû orner ces parures tant convoitées avaient disparu. ''Mes cheveux repoussent si vite, Jim !'' dit-elle avec un sourire."}]'::jsonb from b;


with b as (select id from books where title = 'The Gift of the Magi' and language_id = (select id from languages where code = 'en'))
insert into book_pages (book_id, page_number, sentences)
select b.id, 5, '[{"en": "Then Della remembered her own gift and held out the platinum chain eagerly. ''Isn''t it a dandy, Jim? Give me your watch, I want to see how it looks.''", "fr": "Puis Della se souvint de son propre cadeau et tendit la chaîne de platine avec impatience. ''N''est-elle pas magnifique, Jim ? Donne-moi ta montre, je veux voir comment elle rend.''"}, {"en": "Instead of obeying, Jim tumbled down on the couch, put his hands under his head, and smiled.", "fr": "Au lieu d''obéir, Jim se laissa tomber sur le canapé, mit ses mains derrière sa tête, et sourit."}, {"en": "''Dell,'' said he, ''let''s put our Christmas presents away a while. I sold the watch to get the money to buy your combs.''", "fr": "''Dell,'' dit-il, ''rangeons nos cadeaux de Noël un moment. J''ai vendu la montre pour avoir l''argent d''acheter tes peignes.''"}, {"en": "The magi, as you know, were wise men who brought gifts to the Babe in the manger. They invented the art of giving Christmas presents.", "fr": "Les mages, comme vous le savez, étaient des hommes sages qui apportèrent des cadeaux à l''Enfant dans la crèche. Ils inventèrent l''art d''offrir des cadeaux de Noël."}, {"en": "Here I have related the uneventful chronicle of two foolish children who most unwisely sacrificed for each other the greatest treasures of their house.", "fr": "J''ai ici relaté la chronique sans éclat de deux enfants naïfs qui, bien imprudemment, sacrifièrent l''un pour l''autre les plus grands trésors de leur foyer."}, {"en": "But of all who give and receive gifts, such as they are the wisest. Everywhere they are the wisest. They are the magi.", "fr": "Mais de tous ceux qui donnent et reçoivent des cadeaux, ceux-là sont les plus sages. Partout, ils sont les plus sages. Ce sont les mages."}]'::jsonb from b;
