-- ============================================
-- LUMA — Livre du domaine public : 'A Scandal in Bohemia' (Arthur Conan Doyle, 1891)
-- Nouvelle complète de Sherlock Holmes, texte original, domaine public
-- ============================================


with lang as (select id from languages where code = 'en')
insert into books (language_id, title, theme, description, cecr_level, cover_emoji, total_pages, position)
select id, 'A Scandal in Bohemia', 'Classique • Arthur Conan Doyle (1891)', 'La toute première enquête de Sherlock Holmes publiée : un roi déguisé, une photographie compromettante, et la seule femme à avoir jamais déjoué le grand détective. Domaine public.', 'B2', '🔍', 5, 9
from lang;


with b as (select id from books where title = 'A Scandal in Bohemia' and language_id = (select id from languages where code = 'en'))
insert into book_pages (book_id, page_number, sentences)
select b.id, 1, '[{"en": "To Sherlock Holmes she is always the woman. I have seldom heard him mention her under any other name.", "fr": "Pour Sherlock Holmes, elle est toujours la femme. Je l''ai rarement entendu la mentionner sous un autre nom."}, {"en": "It was not that he felt any emotion akin to love for Irene Adler. All emotions were abhorrent to his cold, precise mind.", "fr": "Ce n''est pas qu''il ressentait une émotion proche de l''amour pour Irene Adler. Toute émotion était odieuse pour son esprit froid et précis."}, {"en": "He was, I take it, the most perfect reasoning and observing machine that the world has seen.", "fr": "Il était, je crois, la machine à raisonner et à observer la plus parfaite que le monde ait vue."}, {"en": "One night in March 1888, I found myself passing through Baker Street, and was seized with a keen desire to see Holmes again.", "fr": "Un soir de mars 1888, je me retrouvai à passer par Baker Street, et fus saisi d''un vif désir de revoir Holmes."}, {"en": "His rooms were brilliantly lit, and I saw his tall figure pacing swiftly, his head sunk upon his chest.", "fr": "Ses appartements étaient brillamment éclairés, et je vis sa silhouette élancée arpenter la pièce rapidement, la tête penchée sur sa poitrine."}, {"en": "''Wedlock suits you,'' he remarked. ''I think, Watson, that you have put on seven pounds since I saw you.''", "fr": "''Le mariage vous réussit,'' remarqua-t-il. ''Je pense, Watson, que vous avez pris trois kilos depuis que je vous ai vu.''"}]'::jsonb from b;


with b as (select id from books where title = 'A Scandal in Bohemia' and language_id = (select id from languages where code = 'en'))
insert into book_pages (book_id, page_number, sentences)
select b.id, 2, '[{"en": "''It is simplicity itself,'' said he. ''My eyes tell me that on the inside of your left shoe, the leather is scored by cuts.''", "fr": "''C''est d''une simplicité enfantine,'' dit-il. ''Mes yeux me disent qu''à l''intérieur de votre chaussure gauche, le cuir est marqué d''entailles.''"}, {"en": "''You see, but you do not observe,'' Holmes explained. ''The distinction is clear.''", "fr": "''Vous regardez, mais vous n''observez pas,'' expliqua Holmes. ''La distinction est claire.''"}, {"en": "A note had arrived announcing a mysterious visitor who wished to consult Holmes on a matter of the deepest importance, and who would wear a mask.", "fr": "Un billet était arrivé annonçant un mystérieux visiteur qui souhaitait consulter Holmes sur une affaire de la plus haute importance, et qui porterait un masque."}, {"en": "Holmes deduced from the paper alone that the writer was a German from Bohemia. ''And here he comes,'' said he, ''to resolve all our doubts.''", "fr": "Holmes déduisit du papier seul que l''auteur était un Allemand de Bohême. ''Et le voici,'' dit-il, ''pour résoudre tous nos doutes.''"}, {"en": "A giant of a man entered wearing a mask, calling himself Count Von Kramm. But Holmes said dryly, ''I was aware it was not exactly your own.''", "fr": "Un homme gigantesque entra portant un masque, se présentant comme le comte Von Kramm. Mais Holmes dit sèchement : ''Je savais que ce n''était pas tout à fait le vôtre.''"}, {"en": "The visitor tore off his mask in agitation. ''You are right,'' he cried, ''I am the King! Why should I attempt to conceal it?''", "fr": "Le visiteur arracha son masque avec agitation. ''Vous avez raison,'' s''écria-t-il, ''je suis le Roi ! Pourquoi tenterais-je de le cacher ?''"}]'::jsonb from b;


with b as (select id from books where title = 'A Scandal in Bohemia' and language_id = (select id from languages where code = 'en'))
insert into book_pages (book_id, page_number, sentences)
select b.id, 3, '[{"en": "The King of Bohemia explained: he had once loved the adventuress Irene Adler, and now she possessed a photograph that could ruin his coming marriage.", "fr": "Le Roi de Bohême expliqua : il avait autrefois aimé l''aventurière Irene Adler, et elle possédait maintenant une photographie qui pourrait ruiner son mariage à venir."}, {"en": "''She has threatened to send the photograph on the day my engagement is announced,'' said the King. ''That will be next Monday.''", "fr": "''Elle a menacé d''envoyer la photographie le jour où mes fiançailles seront annoncées,'' dit le Roi. ''Ce sera lundi prochain.''"}, {"en": "Holmes agreed to take the case. ''Then, good-night, your Majesty, and I trust that we shall soon have some good news for you.''", "fr": "Holmes accepta l''affaire. ''Alors, bonne nuit, Votre Majesté, et j''espère que nous aurons bientôt de bonnes nouvelles pour vous.''"}, {"en": "The next day, Holmes disguised himself as a groom to learn about Irene Adler''s house and habits, gathering information from local stable hands.", "fr": "Le lendemain, Holmes se déguisa en palefrenier pour se renseigner sur la maison et les habitudes d''Irene Adler, recueillant des informations auprès des palefreniers locaux."}, {"en": "He learned that Irene had a frequent visitor, a lawyer named Godfrey Norton, who called on her almost daily.", "fr": "Il apprit qu''Irene recevait souvent la visite d''un avocat nommé Godfrey Norton, qui venait la voir presque quotidiennement."}, {"en": "To his great surprise, Holmes found himself swept along to a church, where he was made a witness at the sudden wedding of Irene Adler to Godfrey Norton.", "fr": "À sa grande surprise, Holmes se retrouva entraîné vers une église, où il fut fait témoin du mariage soudain d''Irene Adler avec Godfrey Norton."}]'::jsonb from b;


with b as (select id from books where title = 'A Scandal in Bohemia' and language_id = (select id from languages where code = 'en'))
insert into book_pages (book_id, page_number, sentences)
select b.id, 4, '[{"en": "That evening, Holmes disguised himself as an elderly clergyman and staged a fake street brawl outside Irene''s house.", "fr": "Ce soir-là, Holmes se déguisa en vieux pasteur et organisa une fausse bagarre de rue devant la maison d''Irene."}, {"en": "Pretending to be injured, he was carried inside, where Watson threw a smoke-rocket through the window shouting ''Fire!''", "fr": "Faisant semblant d''être blessé, il fut porté à l''intérieur, où Watson lança une fusée fumigène par la fenêtre en criant ''Au feu !''"}, {"en": "''When a woman thinks her house is on fire, her instinct is to rush to the thing she values most,'' Holmes explained. ''She showed me exactly where the photograph was hidden.''", "fr": "''Quand une femme pense que sa maison brûle, son instinct est de se précipiter vers ce qu''elle chérit le plus,'' expliqua Holmes. ''Elle m''a montré exactement où la photographie était cachée.''"}, {"en": "The next morning, Holmes and the King went to retrieve the photograph, but found the house empty. Irene Adler had fled to the Continent with her new husband.", "fr": "Le lendemain matin, Holmes et le Roi allèrent récupérer la photographie, mais trouvèrent la maison vide. Irene Adler s''était enfuie sur le continent avec son nouveau mari."}, {"en": "In her place, she had left a letter for Holmes, along with her own photograph instead of the compromising one.", "fr": "À sa place, elle avait laissé une lettre pour Holmes, accompagnée de sa propre photographie au lieu de celle qui était compromettante."}, {"en": "''You really did it very well,'' she had written. ''You took me in completely... but I have been trained as an actress myself.''", "fr": "''Vous avez vraiment très bien fait cela,'' avait-elle écrit. ''Vous m''avez complètement trompée... mais j''ai moi-même été formée comme actrice.''"}]'::jsonb from b;


with b as (select id from books where title = 'A Scandal in Bohemia' and language_id = (select id from languages where code = 'en'))
insert into book_pages (book_id, page_number, sentences)
select b.id, 5, '[{"en": "''I love and am loved by a better man than he,'' she wrote of the King. ''He may do what he will without hindrance from one whom he has cruelly wronged.''", "fr": "''J''aime et je suis aimée par un homme meilleur que lui,'' écrivit-elle à propos du Roi. ''Il peut faire ce qu''il veut sans entrave de la part de celle qu''il a cruellement trahie.''"}, {"en": "The King was astonished. ''What a woman! Would she not have made an admirable queen?''", "fr": "Le Roi était stupéfait. ''Quelle femme ! N''aurait-elle pas fait une reine admirable ?''"}, {"en": "Holmes asked for nothing but Irene''s photograph as payment, and kept it always in memory of the one woman who had ever outwitted him.", "fr": "Holmes ne demanda rien d''autre que la photographie d''Irene comme paiement, et la garda toujours en mémoire de la seule femme qui l''ait jamais surpassé."}, {"en": "And that was how the best plans of Mr. Sherlock Holmes were beaten by a woman''s wit. He speaks of her still only as ''the woman.''", "fr": "Et voilà comment les meilleurs plans de M. Sherlock Holmes furent déjoués par l''esprit d''une femme. Il ne parle encore d''elle que comme ''la femme.''"}]'::jsonb from b;
