-- ============================================
-- LUMA — Scénarios jouables : Thématique 10 (Enquête policière) — complète
-- ============================================

update scenarios set content = '{"characters": {"witness": "un témoin"}, "start_node": "n1", "nodes": {"n1": {"speaker": "witness", "text": "I saw someone leave the building around midnight, but it was dark.", "text_fr": "J''ai vu quelqu''un quitter le bâtiment vers minuit, mais il faisait sombre.", "choices": [{"text": "Can you describe anything about their appearance?", "next": "n2"}, {"text": "Did you notice which direction they went?", "next": "n2b"}]}, "n2": {"speaker": "witness", "text": "Tall, wearing a dark coat, that''s all I could make out.", "text_fr": "Grand, portant un manteau sombre, c''est tout ce que j''ai pu voir.", "choices": [{"text": "That''s helpful, thank you.", "next": "end_desc"}]}, "n2b": {"speaker": "witness", "text": "Toward the parking lot, I think.", "text_fr": "Vers le parking, je crois.", "choices": [{"text": "Good, I''ll check for camera footage there.", "next": "end_direction"}]}, "end_desc": {"speaker": "witness", "text": "I hope that helps find who did this.", "text_fr": "J''espère que ça aidera à trouver le coupable.", "end": true, "ending_label": "Description obtenue 🔍"}, "end_direction": {"speaker": "witness", "text": "Good luck with the investigation, detective.", "text_fr": "Bonne chance pour l''enquête, détective.", "end": true, "ending_label": "Piste de direction obtenue 🔍"}}}'::jsonb, is_playable = true
where title = 'Interroger un premier témoin'
  and theme_id = (select id from scenario_themes where position = 10 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"partner": "ton partenaire détective"}, "start_node": "n1", "nodes": {"n1": {"speaker": "partner", "text": "Anything stand out to you in this room?", "text_fr": "Quelque chose te frappe dans cette pièce ?", "choices": [{"text": "That drawer is open, but nothing seems taken.", "next": "n2"}, {"text": "There''s a muddy footprint near the window.", "next": "n2b"}]}, "n2": {"speaker": "partner", "text": "Strange — maybe they were looking for something specific.", "text_fr": "Étrange — peut-être qu''ils cherchaient quelque chose de précis.", "choices": [{"text": "Let''s check what was normally kept there.", "next": "end_drawer"}]}, "n2b": {"speaker": "partner", "text": "Good eye! That means they entered through the window.", "text_fr": "Bon œil ! Ça veut dire qu''ils sont entrés par la fenêtre.", "choices": [{"text": "Let''s photograph it before it''s disturbed.", "next": "end_footprint"}]}, "end_drawer": {"speaker": "partner", "text": "Solid lead, let''s follow up on this.", "text_fr": "Bonne piste, suivons ça.", "end": true, "ending_label": "Indice clé repéré 🔍"}, "end_footprint": {"speaker": "partner", "text": "This could break the case wide open.", "text_fr": "Ça pourrait vraiment faire avancer l''enquête.", "end": true, "ending_label": "Indice clé repéré 🔍"}}}'::jsonb, is_playable = true
where title = 'Repérer un indice sur une scène de crime'
  and theme_id = (select id from scenario_themes where position = 10 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"partner": "ton partenaire"}, "start_node": "n1", "nodes": {"n1": {"speaker": "partner", "text": "The victim''s watch stopped at 9:47. What does that tell you?", "text_fr": "La montre de la victime s''est arrêtée à 21h47. Qu''est-ce que ça te dit ?", "choices": [{"text": "That''s likely the time of the incident.", "next": "n2"}, {"text": "It might just be a coincidence, watches stop for many reasons.", "next": "n2b"}]}, "n2": {"speaker": "partner", "text": "Exactly what I was thinking. Let''s cross-reference with the alibi timelines.", "text_fr": "Exactement ce que je pensais. Croisons ça avec les emplois du temps des alibis.", "choices": [{"text": "Good idea, let''s check who was where at that time.", "next": "end_correct"}]}, "n2b": {"speaker": "partner", "text": "True, but combined with other evidence, it''s still worth checking.", "text_fr": "C''est vrai, mais combiné aux autres preuves, ça vaut le coup de vérifier.", "choices": [{"text": "Fair point, let''s not rule it out.", "next": "end_cautious"}]}, "end_correct": {"speaker": "partner", "text": "This narrows our suspect list significantly.", "text_fr": "Ça réduit considérablement notre liste de suspects.", "end": true, "ending_label": "Déduction précise 🧠"}, "end_cautious": {"speaker": "partner", "text": "Careful analysis, as always.", "text_fr": "Analyse prudente, comme toujours.", "end": true, "ending_label": "Prudence méthodique 🔍"}}}'::jsonb, is_playable = true
where title = 'Une déduction rapide'
  and theme_id = (select id from scenario_themes where position = 10 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"suspect1": "premier suspect", "suspect2": "deuxième suspect"}, "start_node": "n1", "nodes": {"n1": {"speaker": "suspect1", "text": "I was at home all night, ask my neighbor if you don''t believe me.", "text_fr": "J''étais chez moi toute la nuit, demandez à mon voisin si vous ne me croyez pas.", "choices": [{"text": "I will. What time did you get home?", "next": "n2"}]}, "n2": {"speaker": "suspect1", "text": "Around 8pm, and I didn''t leave after that.", "text_fr": "Vers 20h, et je ne suis pas ressorti après.", "choices": [{"text": "Thank you, I''ll verify that.", "next": "n3"}]}, "n3": {"speaker": "suspect2", "text": "I saw him leave his apartment around 10pm actually.", "text_fr": "En fait, je l''ai vu quitter son appartement vers 22h.", "choices": [{"text": "That contradicts his statement — I need to confront him with this.", "next": "n4"}]}, "n4": {"speaker": "suspect1", "text": "(confronted) Okay, fine, I did go out briefly — but I didn''t do anything wrong!", "text_fr": "(confronté) D''accord, bon, je suis sorti brièvement — mais je n''ai rien fait de mal !", "choices": [{"text": "Then tell me exactly where you went.", "next": "end_confession"}]}, "end_confession": {"speaker": "suspect1", "text": "I just went for a walk, I swear. Check the corner store cameras.", "text_fr": "Je suis juste allé marcher, je le jure. Vérifiez les caméras du magasin du coin.", "end": true, "ending_label": "Contradiction révélée 🕵️"}}}'::jsonb, is_playable = true
where title = 'Interroger plusieurs suspects et croiser les indices'
  and theme_id = (select id from scenario_themes where position = 10 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"partner": "ton partenaire (radio)"}, "start_node": "n1", "nodes": {"n1": {"speaker": "partner", "text": "He''s heading into the alley — do you still have eyes on him?", "text_fr": "Il se dirige vers la ruelle — tu l''as toujours à vue ?", "choices": [{"text": "Yes, following at a safe distance.", "next": "n2"}, {"text": "I lost him for a second, moving closer.", "next": "n2b"}]}, "n2": {"speaker": "partner", "text": "Good, stay careful, this area is known to be risky.", "text_fr": "Bien, reste prudent, ce quartier est connu pour être risqué.", "choices": [{"text": "Understood, staying alert.", "next": "n3"}]}, "n2b": {"speaker": "partner", "text": "Be careful, don''t blow your cover.", "text_fr": "Fais attention, ne te fais pas repérer.", "choices": [{"text": "Got it, I see him again now.", "next": "n3"}]}, "n3": {"speaker": "partner", "text": "He''s meeting someone! Can you identify the second person?", "text_fr": "Il rencontre quelqu''un ! Tu peux identifier la deuxième personne ?", "choices": [{"text": "Taking a photo now, discreetly.", "next": "end_success"}]}, "end_success": {"speaker": "partner", "text": "Perfect, that''s a major break in the case.", "text_fr": "Parfait, c''est une avancée majeure dans l''affaire.", "end": true, "ending_label": "Filature réussie 📸"}}}'::jsonb, is_playable = true
where title = 'Une filature qui tourne mal'
  and theme_id = (select id from scenario_themes where position = 10 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"suspect": "le suspect principal"}, "start_node": "n1", "nodes": {"n1": {"speaker": "suspect", "text": "I already told you, I wasn''t there that night.", "text_fr": "Je vous l''ai déjà dit, je n''étais pas là ce soir-là.", "choices": [{"text": "Then explain why your car was caught on camera near the scene.", "next": "n2"}]}, "n2": {"speaker": "suspect", "text": "(pauses, visibly shaken) ...Fine. I was there, but I didn''t do it.", "text_fr": "(marque une pause, visiblement troublé) ...D''accord. J''y étais, mais je n''ai rien fait.", "choices": [{"text": "Then tell me what really happened.", "next": "n3"}]}, "n3": {"speaker": "suspect", "text": "I saw someone else there — I was too scared to say anything before.", "text_fr": "J''ai vu quelqu''un d''autre là-bas — j''avais trop peur pour le dire avant.", "choices": [{"text": "Describe exactly what you saw.", "next": "end_breakthrough"}]}, "end_breakthrough": {"speaker": "suspect", "text": "It was someone in a security uniform, I''m sure of it.", "text_fr": "C''était quelqu''un en uniforme de sécurité, j''en suis sûr.", "end": true, "ending_label": "Percée majeure dans l''enquête 🎯"}}}'::jsonb, is_playable = true
where title = 'Confronter un suspect avec des preuves'
  and theme_id = (select id from scenario_themes where position = 10 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"suspect1": "suspect A", "suspect2": "suspect B", "real": "le vrai coupable"}, "start_node": "n1", "nodes": {"n1": {"speaker": "suspect1", "text": "It wasn''t me! I had every reason to want him gone, sure, but I didn''t do it!", "text_fr": "Ce n''était pas moi ! J''avais toutes les raisons de vouloir qu''il disparaisse, certes, mais je ne l''ai pas fait !", "choices": [{"text": "Where were you at the time of the incident?", "next": "n2"}]}, "n2": {"speaker": "suspect1", "text": "At a bar, dozens of people saw me.", "text_fr": "Dans un bar, des dizaines de gens m''ont vu.", "choices": [{"text": "That alibi checks out. Let''s look elsewhere.", "next": "n3"}]}, "n3": {"speaker": "suspect2", "text": "You think it was me? I barely knew the guy!", "text_fr": "Vous pensez que c''était moi ? Je le connaissais à peine !", "choices": [{"text": "Your fingerprints were found at the scene, though.", "next": "n4"}]}, "n4": {"speaker": "suspect2", "text": "I was there earlier that day for a delivery, that''s all!", "text_fr": "J''étais là plus tôt dans la journée pour une livraison, c''est tout !", "choices": [{"text": "That also checks out. There must be someone else.", "next": "n5"}]}, "n5": {"speaker": "real", "text": "(nervously) I... I can explain everything.", "text_fr": "(nerveusement) Je... je peux tout expliquer.", "choices": [{"text": "Your story doesn''t match the evidence. It was you, wasn''t it?", "next": "end_solved"}]}, "end_solved": {"speaker": "real", "text": "(breaks down) Yes... it was me. I panicked.", "text_fr": "(craque) Oui... c''était moi. J''ai paniqué.", "end": true, "ending_label": "Vrai coupable démasqué 🎯"}}}'::jsonb, is_playable = true
where title = 'Une enquête complète avec plusieurs faux coupables'
  and theme_id = (select id from scenario_themes where position = 10 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"friend": "ton ami proche"}, "start_node": "n1", "nodes": {"n1": {"speaker": "friend", "text": "I know how this looks, but you have to believe me, I had nothing to do with it.", "text_fr": "Je sais comment ça a l''air, mais tu dois me croire, je n''ai rien à voir avec ça.", "choices": [{"text": "I want to believe you, but I have to follow the evidence.", "next": "n2"}, {"text": "I trust you completely — let''s find the real truth together.", "next": "n2b"}]}, "n2": {"speaker": "friend", "text": "I understand... do what you have to do.", "text_fr": "Je comprends... fais ce que tu dois faire.", "choices": [{"text": "Let''s go through everything carefully, for your sake.", "next": "n3"}]}, "n2b": {"speaker": "friend", "text": "Thank you... that means everything to me right now.", "text_fr": "Merci... ça compte énormément pour moi en ce moment.", "choices": [{"text": "Let''s clear your name properly.", "next": "n3"}]}, "n3": {"speaker": "friend", "text": "(later, new evidence surfaces) You found it — proof I was set up!", "text_fr": "(plus tard, une nouvelle preuve apparaît) Tu l''as trouvée — la preuve que j''ai été piégé !", "choices": [{"text": "I never gave up on finding the truth.", "next": "end_cleared"}]}, "end_cleared": {"speaker": "friend", "text": "I''ll never forget what you did for me.", "text_fr": "Je n''oublierai jamais ce que tu as fait pour moi.", "end": true, "ending_label": "Innocence prouvée 💙"}}}'::jsonb, is_playable = true
where title = 'Une affaire qui implique un proche du personnage'
  and theme_id = (select id from scenario_themes where position = 10 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"judge": "la juge"}, "start_node": "n1", "nodes": {"n1": {"speaker": "judge", "text": "Detective, please present your final conclusion to the court.", "text_fr": "Détective, veuillez présenter votre conclusion finale au tribunal.", "choices": [{"text": "Based on the timeline and physical evidence, the defendant is guilty.", "next": "n2"}, {"text": "The evidence points to reasonable doubt — I cannot conclude guilt.", "next": "n2b"}]}, "n2": {"speaker": "judge", "text": "A bold conclusion. Can you walk the court through your reasoning?", "text_fr": "Une conclusion audacieuse. Pouvez-vous détailler votre raisonnement au tribunal ?", "choices": [{"text": "(present the timeline, fingerprints, and witness testimony clearly)", "next": "end_guilty"}]}, "n2b": {"speaker": "judge", "text": "A careful stance. Explain the gaps you found in the evidence.", "text_fr": "Une position prudente. Expliquez les failles que vous avez trouvées dans les preuves.", "choices": [{"text": "(explain the inconsistencies and alternative explanations)", "next": "end_doubt"}]}, "end_guilty": {"speaker": "judge", "text": "The evidence is compelling. The court finds the defendant guilty.", "text_fr": "Les preuves sont convaincantes. Le tribunal déclare l''accusé coupable.", "end": true, "ending_label": "Verdict de culpabilité obtenu ⚖️"}, "end_doubt": {"speaker": "judge", "text": "Given the reasonable doubt presented, the court finds the defendant not guilty.", "text_fr": "Compte tenu du doute raisonnable présenté, le tribunal déclare l''accusé non coupable.", "end": true, "ending_label": "Justice rendue avec prudence ⚖️"}}}'::jsonb, is_playable = true
where title = 'Un procès final où l''utilisateur plaide sa déduction'
  and theme_id = (select id from scenario_themes where position = 10 and language_id = (select id from languages where code = 'en'));
