-- ============================================
-- LUMA — Thème 12 (Musée) : 3 scénarios COURTS x4
-- ============================================


update scenarios set content = '{"characters": {"guide": "le guide"}, "start_node": "n1", "nodes": {"n1": {"speaker": "guide", "text": "Welcome everyone! We''ll begin our tour in the Renaissance wing. Follow me, please.", "text_fr": "Bienvenue à tous ! On commence notre visite dans l''aile Renaissance. Suivez-moi, s''il vous plaît.", "choices": [{"text": "(Follow closely, eager to learn about the art.)", "text_fr": "(Suis de près, impatient d''apprendre sur l''art.)", "next": "n2"}, {"text": "Excuse me, how long does the tour usually last?", "text_fr": "Excusez-moi, la visite dure combien de temps généralement ?", "next": "n2b"}]}, "n2": {"speaker": "guide", "text": "This painting here dates back to 1503, one of the finest examples of the period.", "text_fr": "Cette peinture ici date de 1503, l''un des plus beaux exemples de l''époque.", "choices": [{"text": "What technique makes it so significant?", "text_fr": "Quelle technique la rend si significative ?", "next": "n3"}]}, "n2b": {"speaker": "guide", "text": "About 45 minutes, covering the main highlights of this wing.", "text_fr": "Environ 45 minutes, couvrant les points forts principaux de cette aile.", "choices": [{"text": "Perfect, that sounds manageable. Please continue.", "text_fr": "Parfait, ça semble gérable. Continuez s''il vous plaît.", "next": "n3"}]}, "n3": {"speaker": "guide", "text": "The artist pioneered a new perspective technique that revolutionized depth in painting.", "text_fr": "L''artiste a été le pionnier d''une nouvelle technique de perspective qui a révolutionné la profondeur en peinture.", "choices": [{"text": "That''s fascinating, I never noticed that detail before.", "text_fr": "C''est fascinant, j''avais jamais remarqué ce détail avant.", "next": "n4"}]}, "n4": {"speaker": "guide", "text": "Most visitors miss it, but once you see it, you can''t unsee it in other works too!", "text_fr": "La plupart des visiteurs le manquent, mais une fois que vous le voyez, vous pouvez plus l''ignorer dans d''autres œuvres non plus !", "choices": [{"text": "Thank you for pointing that out, this tour is really insightful.", "text_fr": "Merci de l''avoir signalé, cette visite est vraiment instructive.", "next": "end_learned"}]}, "end_learned": {"speaker": "guide", "text": "That''s exactly why I love giving these tours. Shall we continue to the next piece?", "text_fr": "C''est exactement pour ça que j''adore donner ces visites. On continue vers la prochaine œuvre ?", "end": true, "ending_label": "Visite guidée suivie avec intérêt 🖼️👥"}}}'::jsonb, is_playable = true
where title = 'Suivre une visite guidée courte'
  and theme_id = (select id from scenario_themes where position = 12 and language_id = (select id from languages where code = 'en'));


update scenarios set content = '{"characters": {"mediator": "le médiateur"}, "start_node": "n1", "nodes": {"n1": {"speaker": "mediator", "text": "(Standing near a striking sculpture) Take your time, feel free to ask if you have questions.", "text_fr": "(Debout près d''une sculpture frappante) Prenez votre temps, n''hésitez pas si vous avez des questions.", "choices": [{"text": "Actually yes — what inspired this particular sculpture?", "text_fr": "En fait oui — qu''est-ce qui a inspiré cette sculpture en particulier ?", "next": "n2"}, {"text": "This is beautiful. How long did it take to create?", "text_fr": "C''est magnifique. Combien de temps ça a pris à créer ?", "next": "n2b"}]}, "n2": {"speaker": "mediator", "text": "The artist was inspired by a personal loss, channeling grief into this powerful form.", "text_fr": "L''artiste s''est inspiré d''une perte personnelle, canalisant le chagrin dans cette forme puissante.", "choices": [{"text": "That adds so much depth to how I see it now.", "text_fr": "Ça ajoute tellement de profondeur à la façon dont je le vois maintenant.", "next": "n3"}]}, "n2b": {"speaker": "mediator", "text": "Nearly two years, working with a single block of marble.", "text_fr": "Près de deux ans, en travaillant avec un seul bloc de marbre.", "choices": [{"text": "That''s an incredible amount of dedication.", "text_fr": "C''est une quantité incroyable de dévouement.", "next": "n3"}]}, "n3": {"speaker": "mediator", "text": "It really does. Art often carries stories far beyond what we initially see.", "text_fr": "C''est vraiment le cas. L''art porte souvent des histoires bien au-delà de ce qu''on voit initialement.", "choices": [{"text": "Thank you for sharing that, it really enriched my visit.", "text_fr": "Merci d''avoir partagé ça, ça a vraiment enrichi ma visite.", "next": "end_enriched"}]}, "end_enriched": {"speaker": "mediator", "text": "That''s exactly why I love this job. Enjoy the rest of your visit!", "text_fr": "C''est exactement pour ça que j''adore ce travail. Profitez du reste de votre visite !", "end": true, "ending_label": "Œuvre appréciée avec un nouveau regard 🗿💬"}}}'::jsonb, is_playable = true
where title = 'Poser une question sur une œuvre'
  and theme_id = (select id from scenario_themes where position = 12 and language_id = (select id from languages where code = 'en'));
