-- ============================================
-- LUMA — Exercices pratiques pour les 8 fiches de grammaire A2
-- 7 exercices par fiche, même méthode qu'A1.
-- ============================================

with f as (select id from grammar_fiches where cecr_level = 'A2' and position = 9)
insert into grammar_fiche_exercises (fiche_id, position, type, content)
select f.id, v.position, v.type, v.content::jsonb from f, (values
(1, 'qcm', '{"question": "Complète : Look at those clouds! It ___ rain. (preuve visible)", "options": ["will", "is going to", "go", "goes"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"is going to\"."}'),(2, 'qcm', '{"question": "Complète : I think she ___ like this gift. (opinion/prédiction)", "options": ["will", "is going to", "likes", "liked"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"will\"."}'),(3, 'fill_blank', '{"sentence_before": "I ", "sentence_after": " you tomorrow. (décision spontanée, call)", "correct_answers": ["will call", "''ll call"], "feedback_correct": "Correct !", "feedback_incorrect": "Décision prise à l''instant → will + base verbale."}'),(4, 'fill_blank', '{"sentence_before": "We ", "sentence_after": " Rome next summer. (projet déjà organisé, visit)", "correct_answers": ["are going to visit", "''re going to visit"], "feedback_correct": "Correct !", "feedback_incorrect": "Projet déjà décidé → be going to."}'),(5, 'true_false', '{"statement": "''Going to'' and ''will'' are always 100% interchangeable.", "correct_answer": false, "feedback_correct": "Correct !", "feedback_incorrect": "Ils ont des usages différents : intention/preuve (going to) vs décision spontanée/prédiction (will)."}'),(6, 'reorder', '{"words": ["She", "is", "going", "to", "study", "medicine."], "correct_sentence": "She is going to study medicine."}'),(7, 'error_correction', '{"wrong_sentence": "I will to call you later.", "correct_sentence": "I will call you later.", "error_word": "to", "feedback_correct": "Bien vu !", "feedback_incorrect": "Regarde le mot en rouge.", "explanation": "\"will\" est un modal → jamais suivi de \"to\" + verbe."}')
) as v(position, type, content);

with f as (select id from grammar_fiches where cecr_level = 'A2' and position = 10)
insert into grammar_fiche_exercises (fiche_id, position, type, content)
select f.id, v.position, v.type, v.content::jsonb from f, (values
(1, 'qcm', '{"question": "Complète : This book is ___ than that one.", "options": ["interesting", "more interesting", "most interesting", "interestinger"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"more interesting\"."}'),(2, 'qcm', '{"question": "Complète : She is the ___ student in the class.", "options": ["good", "better", "best", "goodest"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"best\"."}'),(3, 'fill_blank', '{"sentence_before": "This city is ", "sentence_after": " than mine. (big, comparatif court)", "correct_answers": ["bigger"], "feedback_correct": "Correct !", "feedback_incorrect": "Adjectif court (1 syllabe) → -er."}'),(4, 'fill_blank', '{"sentence_before": "It''s the ", "sentence_after": " day of my life. (bad, superlatif)", "correct_answers": ["worst"], "feedback_correct": "Correct !", "feedback_incorrect": "bad est irrégulier → the worst."}'),(5, 'true_false', '{"statement": "The comparative of ''bad'' is ''badder''.", "correct_answer": false, "feedback_correct": "Correct !", "feedback_incorrect": "''bad'' est irrégulier : worse (comparatif), worst (superlatif)."}'),(6, 'reorder', '{"words": ["This", "is", "the", "tallest", "building", "in", "the", "city."], "correct_sentence": "This is the tallest building in the city."}'),(7, 'error_correction', '{"wrong_sentence": "She is more tall than her brother.", "correct_sentence": "She is taller than her brother.", "error_word": "more", "feedback_correct": "Bien vu !", "feedback_incorrect": "Regarde le mot en rouge.", "explanation": "Adjectif court (1 syllabe) → -er, pas \"more\" + adjectif."}')
) as v(position, type, content);

with f as (select id from grammar_fiches where cecr_level = 'A2' and position = 11)
insert into grammar_fiche_exercises (fiche_id, position, type, content)
select f.id, v.position, v.type, v.content::jsonb from f, (values
(1, 'qcm', '{"question": "Complète : You ___ wear a seatbelt. It''s the law.", "options": ["can", "must", "should", "could"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"must\"."}'),(2, 'qcm', '{"question": "Complète : You ___ see a doctor if you feel worse.", "options": ["must", "mustn''t", "should", "can"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"should\"."}'),(3, 'fill_blank', '{"sentence_before": "You ", "sentence_after": " smoke here. (interdiction)", "correct_answers": ["mustn''t", "must not"], "feedback_correct": "Correct !", "feedback_incorrect": "Interdiction → mustn''t."}'),(4, 'fill_blank', '{"sentence_before": "I ", "sentence_after": " speak three languages. (capacité)", "correct_answers": ["can"], "feedback_correct": "Correct !", "feedback_incorrect": "Capacité → can."}'),(5, 'true_false', '{"statement": "''Mustn''t'' means the same thing as ''don''t have to''.", "correct_answer": false, "feedback_correct": "Correct !", "feedback_incorrect": "''mustn''t'' = interdiction. ''don''t have to'' = absence d''obligation. Ce sont deux choses différentes."}'),(6, 'reorder', '{"words": ["You", "should", "see", "a", "dentist."], "correct_sentence": "You should see a dentist."}'),(7, 'error_correction', '{"wrong_sentence": "She can to swim very well.", "correct_sentence": "She can swim very well.", "error_word": "to", "feedback_correct": "Bien vu !", "feedback_incorrect": "Regarde le mot en rouge.", "explanation": "\"can\" est un modal → jamais suivi de \"to\"."}')
) as v(position, type, content);

with f as (select id from grammar_fiches where cecr_level = 'A2' and position = 12)
insert into grammar_fiche_exercises (fiche_id, position, type, content)
select f.id, v.position, v.type, v.content::jsonb from f, (values
(1, 'qcm', '{"question": "Complète : I have never ___ sushi.", "options": ["eat", "ate", "eaten", "eating"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"eaten\"."}'),(2, 'qcm', '{"question": "Complète : She ___ lived here for ten years.", "options": ["has", "have", "is", "did"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"has\"."}'),(3, 'fill_blank', '{"sentence_before": "I ", "sentence_after": " that movie three times. (résultat, see)", "correct_answers": ["have seen", "''ve seen"], "feedback_correct": "Correct !", "feedback_incorrect": "Résultat/expérience de vie → present perfect."}'),(4, 'fill_blank', '{"sentence_before": "She ", "sentence_after": " her homework yet. (not, finish)", "correct_answers": ["hasn''t finished", "has not finished"], "feedback_correct": "Correct !", "feedback_incorrect": "Négation present perfect + yet."}'),(5, 'true_false', '{"statement": "The present perfect is always used with a specific past time like ''yesterday''.", "correct_answer": false, "feedback_correct": "Correct !", "feedback_incorrect": "C''est l''inverse : le present perfect est INCOMPATIBLE avec un marqueur temporel précis. ''Yesterday'' impose le past simple."}'),(6, 'reorder', '{"words": ["Have", "you", "ever", "been", "to", "Japan?"], "correct_sentence": "Have you ever been to Japan?"}'),(7, 'error_correction', '{"wrong_sentence": "I have seen him yesterday.", "correct_sentence": "I saw him yesterday.", "error_word": "have", "feedback_correct": "Bien vu !", "feedback_incorrect": "Regarde le mot en rouge.", "explanation": "\"yesterday\" est un marqueur temporel précis → past simple, pas present perfect."}')
) as v(position, type, content);

with f as (select id from grammar_fiches where cecr_level = 'A2' and position = 13)
insert into grammar_fiche_exercises (fiche_id, position, type, content)
select f.id, v.position, v.type, v.content::jsonb from f, (values
(1, 'qcm', '{"question": "Complète : The meeting is ___ 3pm.", "options": ["in", "on", "at", "by"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"at\"."}'),(2, 'qcm', '{"question": "Complète : My birthday is ___ June.", "options": ["in", "on", "at", "by"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"in\"."}'),(3, 'fill_blank', '{"sentence_before": "See you ", "sentence_after": " Monday! (jour précis)", "correct_answers": ["on"], "feedback_correct": "Correct !", "feedback_incorrect": "Jour précis → on."}'),(4, 'fill_blank', '{"sentence_before": "The cat is ", "sentence_after": " the box. (à l''intérieur)", "correct_answers": ["in"], "feedback_correct": "Correct !", "feedback_incorrect": "À l''intérieur → in."}'),(5, 'true_false', '{"statement": "''At'' is used for exact clock times, like ''at 5pm''.", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Relis la règle."}'),(6, 'reorder', '{"words": ["I", "was", "born", "in", "1998."], "correct_sentence": "I was born in 1998."}'),(7, 'error_correction', '{"wrong_sentence": "The meeting is in 3pm.", "correct_sentence": "The meeting is at 3pm.", "error_word": "in", "feedback_correct": "Bien vu !", "feedback_incorrect": "Regarde le mot en rouge.", "explanation": "Heure précise → at, pas in."}')
) as v(position, type, content);

with f as (select id from grammar_fiches where cecr_level = 'A2' and position = 14)
insert into grammar_fiche_exercises (fiche_id, position, type, content)
select f.id, v.position, v.type, v.content::jsonb from f, (values
(1, 'qcm', '{"question": "Complète : She ___ arrives late. (elle n''est presque jamais en retard)", "options": ["always", "rarely", "usually", "never"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"rarely\"."}'),(2, 'qcm', '{"question": "Complète : He speaks English ___.", "options": ["fluent", "fluently", "fluence", "more fluent"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"fluently\"."}'),(3, 'fill_blank', '{"sentence_before": "She sings ", "sentence_after": ". (beautiful, adverbe)", "correct_answers": ["beautifully"], "feedback_correct": "Correct !", "feedback_incorrect": "Modifie le verbe \"sings\" → adverbe : beautifully."}'),(4, 'fill_blank', '{"sentence_before": "He runs very ", "sentence_after": ". (rapide, irrégulier)", "correct_answers": ["fast"], "feedback_correct": "Correct !", "feedback_incorrect": "\"fast\" est son propre adverbe, jamais \"fastly\"."}'),(5, 'true_false', '{"statement": "The adverb of ''good'' is ''goodly''.", "correct_answer": false, "feedback_correct": "Correct !", "feedback_incorrect": "''good'' est irrégulier : son adverbe est ''well'', pas ''goodly''."}'),(6, 'reorder', '{"words": ["I", "always", "drink", "coffee", "in", "the", "morning."], "correct_sentence": "I always drink coffee in the morning."}'),(7, 'error_correction', '{"wrong_sentence": "She drives very careful.", "correct_sentence": "She drives very carefully.", "error_word": "careful", "feedback_correct": "Bien vu !", "feedback_incorrect": "Regarde le mot en rouge.", "explanation": "Modifie le verbe \"drives\" → adverbe (carefully), pas adjectif (careful)."}')
) as v(position, type, content);

with f as (select id from grammar_fiches where cecr_level = 'A2' and position = 15)
insert into grammar_fiche_exercises (fiche_id, position, type, content)
select f.id, v.position, v.type, v.content::jsonb from f, (values
(1, 'qcm', '{"question": "Complète : ___ the window, please.", "options": ["Close", "Closes", "Closing", "To close"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"Close\"."}'),(2, 'qcm', '{"question": "Quelle formule propose une activité commune ?", "options": ["Let''s go to the beach!", "You go to the beach.", "Going to the beach.", "Beach."], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"Let''s go to the beach!\"."}'),(3, 'fill_blank', '{"sentence_before": "", "sentence_after": " be late! (négation, impératif)", "correct_answers": ["Don''t"], "feedback_correct": "Correct !", "feedback_incorrect": "Impératif négatif : Don''t + base verbale."}'),(4, 'fill_blank', '{"sentence_before": "", "sentence_after": " we start now? (suggestion)", "correct_answers": ["Shall"], "feedback_correct": "Correct !", "feedback_incorrect": "Suggestion polie : Shall we... ?"}'),(5, 'true_false', '{"statement": "''Let''s'' always includes both the speaker and the listener.", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Relis la règle."}'),(6, 'reorder', '{"words": ["Please,", "don''t", "touch", "that."], "correct_sentence": "Please, don''t touch that."}'),(7, 'error_correction', '{"wrong_sentence": "Lets go to the party!", "correct_sentence": "Let''s go to the party!", "error_word": "Lets", "feedback_correct": "Bien vu !", "feedback_incorrect": "Regarde le mot en rouge.", "explanation": "\"Let''s\" est la contraction de \"let us\" → apostrophe obligatoire."}')
) as v(position, type, content);

with f as (select id from grammar_fiches where cecr_level = 'A2' and position = 16)
insert into grammar_fiche_exercises (fiche_id, position, type, content)
select f.id, v.position, v.type, v.content::jsonb from f, (values
(1, 'qcm', '{"question": "\"Turn off the light\" veut dire :", "options": ["Éteindre", "Allumer", "Ouvrir", "Chercher"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"Éteindre\"."}'),(2, 'qcm', '{"question": "Laquelle est correcte, avec un pronom ?", "options": ["Turn it off", "Turn off it", "Turn off the it", "Off turn it"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"Turn it off\"."}'),(3, 'fill_blank', '{"sentence_before": "Please ", "sentence_after": " the lights, it''s dark. (turn on)", "correct_answers": ["turn on"], "feedback_correct": "Correct !", "feedback_incorrect": "Allumer = turn on."}'),(4, 'fill_blank', '{"sentence_before": "I need to ", "sentence_after": " my keys. (chercher, look)", "correct_answers": ["look for"], "feedback_correct": "Correct !", "feedback_incorrect": "Chercher = look for."}'),(5, 'true_false', '{"statement": "With a pronoun, separable phrasal verbs must be split (turn it off, not turn off it).", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Relis la règle."}'),(6, 'reorder', '{"words": ["Please", "turn", "off", "the", "radio."], "correct_sentence": "Please turn off the radio."}'),(7, 'error_correction', '{"wrong_sentence": "I need to look after my keys, I lost them.", "correct_sentence": "I need to look for my keys, I lost them.", "error_word": "after", "feedback_correct": "Bien vu !", "feedback_incorrect": "Regarde le mot en rouge.", "explanation": "\"look after\" (s''occuper de) ≠ \"look for\" (chercher) — ici on cherche des clés perdues."}')
) as v(position, type, content);
