-- ============================================
-- LUMA — Scénarios jouables : Thématique 13 (Networking) — complète
-- ============================================

update scenarios set content = '{"characters": {"stranger": "un inconnu au cocktail"}, "start_node": "n1", "nodes": {"n1": {"speaker": "stranger", "text": "Hi, I don''t think we''ve met. I''m James, I work in fintech.", "text_fr": "Salut, je ne crois pas qu''on se soit rencontrés. Je m''appelle James, je travaille dans la fintech.", "choices": [{"text": "Nice to meet you, James! I''m in marketing, actually.", "next": "n2"}, {"text": "Great to meet you! What brings you to this event?", "next": "n2b"}]}, "n2": {"speaker": "stranger", "text": "Marketing, nice! Any specific industry?", "text_fr": "Marketing, sympa ! Un secteur en particulier ?", "choices": [{"text": "Mostly tech startups, it''s been an exciting field.", "next": "end_connect"}]}, "n2b": {"speaker": "stranger", "text": "Looking for potential partnerships, actually. And you?", "text_fr": "Je cherche des partenariats potentiels, en fait. Et toi ?", "choices": [{"text": "Same goal, always good to expand my network.", "next": "end_connect"}]}, "end_connect": {"speaker": "stranger", "text": "We should definitely stay in touch.", "text_fr": "On devrait vraiment rester en contact.", "end": true, "ending_label": "Première connexion établie 🤝"}}}'::jsonb, is_playable = true
where title = 'Se présenter à un inconnu lors d''un cocktail'
  and theme_id = (select id from scenario_themes where position = 13 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"contact": "un contact professionnel"}, "start_node": "n1", "nodes": {"n1": {"speaker": "contact", "text": "It was great talking with you. Do you have a business card?", "text_fr": "C''était vraiment agréable de discuter. Vous avez une carte de visite ?", "choices": [{"text": "Of course, here you go.", "next": "n2"}]}, "n2": {"speaker": "contact", "text": "Perfect, and here''s mine. Let''s connect on LinkedIn too.", "text_fr": "Parfait, et voici la mienne. Connectons-nous aussi sur LinkedIn.", "choices": [{"text": "Sounds great, I''ll send a request today.", "next": "end_exchanged"}]}, "end_exchanged": {"speaker": "contact", "text": "Looking forward to staying in touch!", "text_fr": "J''ai hâte de rester en contact !", "end": true, "ending_label": "Contact professionnel établi 💼"}}}'::jsonb, is_playable = true
where title = 'Échanger une carte de visite'
  and theme_id = (select id from scenario_themes where position = 13 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"speaker_p": "l''intervenant"}, "start_node": "n1", "nodes": {"n1": {"speaker": "speaker_p", "text": "Great talk, thank you all! Any questions from the audience?", "text_fr": "Merci pour votre écoute ! Des questions du public ?", "choices": [{"text": "Yes — how do you see this trend evolving in the next five years?", "next": "n2"}]}, "n2": {"speaker": "speaker_p", "text": "Great question! I believe we''ll see significant automation in this space.", "text_fr": "Excellente question ! Je pense qu''on verra beaucoup d''automatisation dans ce domaine.", "choices": [{"text": "That''s really insightful, thank you for sharing.", "next": "end_answered"}]}, "end_answered": {"speaker": "speaker_p", "text": "Thanks for the thoughtful question!", "text_fr": "Merci pour cette question réfléchie !", "end": true, "ending_label": "Question pertinente posée 🎤"}}}'::jsonb, is_playable = true
where title = 'Poser une question after une conférence'
  and theme_id = (select id from scenario_themes where position = 13 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"person1": "premier contact", "person2": "deuxième contact"}, "start_node": "n1", "nodes": {"n1": {"speaker": "person1", "text": "So, what industry are you in?", "text_fr": "Alors, vous êtes dans quel secteur ?", "choices": [{"text": "Software development, mostly mobile apps.", "next": "n2"}]}, "n2": {"speaker": "person1", "text": "Interesting, you should meet my colleague over there, she''s in the same space.", "text_fr": "Intéressant, vous devriez rencontrer ma collègue là-bas, elle est dans le même domaine.", "choices": [{"text": "I''d love an introduction, thank you.", "next": "n3"}]}, "n3": {"speaker": "person2", "text": "Hi! I heard you''re in mobile development — we''re actually hiring.", "text_fr": "Salut ! J''ai entendu dire que vous êtes dans le développement mobile — on recrute justement.", "choices": [{"text": "That''s exciting, I''d love to hear more.", "next": "end_opportunity"}]}, "end_opportunity": {"speaker": "person2", "text": "Let''s schedule a proper call this week.", "text_fr": "Programmons un vrai appel cette semaine.", "end": true, "ending_label": "Opportunité découverte 💼"}}}'::jsonb, is_playable = true
where title = 'Naviguer une soirée networking avec plusieurs interlocuteurs'
  and theme_id = (select id from scenario_themes where position = 13 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"moderator": "le modérateur"}, "start_node": "n1", "nodes": {"n1": {"speaker": "moderator", "text": "As a panelist, what''s your take on remote work''s future?", "text_fr": "En tant que panéliste, quel est votre avis sur l''avenir du travail à distance ?", "choices": [{"text": "I believe hybrid models will become the clear standard.", "next": "n2"}, {"text": "I think it depends heavily on the industry involved.", "next": "n2b"}]}, "n2": {"speaker": "moderator", "text": "Interesting stance, can you elaborate on why?", "text_fr": "Position intéressante, pouvez-vous développer pourquoi ?", "choices": [{"text": "It balances flexibility with the value of in-person collaboration.", "next": "end_thoughtful"}]}, "n2b": {"speaker": "moderator", "text": "A nuanced view, appreciated by the audience I''m sure.", "text_fr": "Une vision nuancée, appréciée du public j''en suis sûr.", "choices": [{"text": "Thank you, it''s a complex topic.", "next": "end_thoughtful"}]}, "end_thoughtful": {"speaker": "moderator", "text": "Great insight, thank you for contributing to the panel.", "text_fr": "Excellente réflexion, merci de votre contribution au panel.", "end": true, "ending_label": "Contribution au panel appréciée 🎙️"}}}'::jsonb, is_playable = true
where title = 'Participer à un panel de questions-réponses'
  and theme_id = (select id from scenario_themes where position = 13 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"contact": "un contact potentiel"}, "start_node": "n1", "nodes": {"n1": {"speaker": "contact", "text": "Your company''s work sounds impressive. What are you exploring these days?", "text_fr": "Le travail de votre entreprise semble impressionnant. Que cherchez-vous en ce moment ?", "choices": [{"text": "Actually, I think our companies could collaborate on something.", "next": "n2"}]}, "n2": {"speaker": "contact", "text": "I''m intrigued — what did you have in mind?", "text_fr": "Je suis intrigué — qu''aviez-vous en tête ?", "choices": [{"text": "A joint project combining our strengths in your target market.", "next": "n3"}]}, "n3": {"speaker": "contact", "text": "That actually aligns with our roadmap. Let''s set up a proper meeting.", "text_fr": "Ça correspond en fait à notre feuille de route. Organisons une vraie réunion.", "choices": [{"text": "Perfect, I''ll follow up this week.", "next": "end_collab"}]}, "end_collab": {"speaker": "contact", "text": "Looking forward to exploring this together.", "text_fr": "J''ai hâte d''explorer ça ensemble.", "end": true, "ending_label": "Collaboration amorcée 🤝"}}}'::jsonb, is_playable = true
where title = 'Proposer une collaboration'
  and theme_id = (select id from scenario_themes where position = 13 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"contact1": "un contact du jour 1", "contact2": "un contact du jour 2"}, "start_node": "n1", "nodes": {"n1": {"speaker": "contact1", "text": "Day one was intense! Did you attend the keynote?", "text_fr": "Le premier jour était intense ! Vous avez assisté au discours d''ouverture ?", "choices": [{"text": "Yes, it really changed my perspective on the industry.", "next": "n2"}]}, "n2": {"speaker": "contact1", "text": "Same here! Let''s grab coffee tomorrow and discuss more.", "text_fr": "Pareil pour moi ! Prenons un café demain pour en discuter davantage.", "choices": [{"text": "I''d love that, see you tomorrow.", "next": "n3"}]}, "n3": {"speaker": "contact2", "text": "(day two) I heard you''re the one who asked that great question yesterday!", "text_fr": "(jour deux) J''ai entendu dire que c''est vous qui avez posé cette excellente question hier !", "choices": [{"text": "That was me! Great to meet someone who noticed.", "next": "end_network"}]}, "end_network": {"speaker": "contact2", "text": "Your reputation is already growing at this conference!", "text_fr": "Votre réputation grandit déjà lors de cette conférence !", "end": true, "ending_label": "Réseau étendu sur deux jours 🌟"}}}'::jsonb, is_playable = true
where title = 'Une conférence sur deux jours avec plusieurs rencontres clés'
  and theme_id = (select id from scenario_themes where position = 13 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"exec": "une dirigeante d''entreprise"}, "start_node": "n1", "nodes": {"n1": {"speaker": "exec", "text": "We''re interested in partnering, but we need exclusivity in this region.", "text_fr": "On est intéressés par un partenariat, mais on a besoin d''exclusivité dans cette région.", "choices": [{"text": "We could offer a 12-month exclusive trial period.", "next": "n2"}, {"text": "Exclusivity is tough for us, but we can offer priority terms instead.", "next": "n2b"}]}, "n2": {"speaker": "exec", "text": "That''s a reasonable compromise. Let''s draft terms this week.", "text_fr": "C''est un compromis raisonnable. Rédigeons les termes cette semaine.", "choices": [{"text": "Excellent, I''ll have our team prepare the paperwork.", "next": "end_deal"}]}, "n2b": {"speaker": "exec", "text": "Priority terms could work if the conditions are strong enough.", "text_fr": "Des conditions prioritaires pourraient fonctionner si elles sont assez solides.", "choices": [{"text": "We''ll make sure the terms reflect real value for you.", "next": "end_deal"}]}, "end_deal": {"speaker": "exec", "text": "Looking forward to a strong partnership ahead.", "text_fr": "J''ai hâte de ce partenariat solide qui s''annonce.", "end": true, "ending_label": "Partenariat négocié 🤝"}}}'::jsonb, is_playable = true
where title = 'Négocier un partenariat lors de l''événement'
  and theme_id = (select id from scenario_themes where position = 13 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"audience": "le public"}, "start_node": "n1", "nodes": {"n1": {"speaker": "audience", "text": "So, tell us — what problem does your project actually solve?", "text_fr": "Alors, dites-nous — quel problème votre projet résout-il vraiment ?", "choices": [{"text": "It streamlines a process that currently takes hours into just minutes.", "next": "n2"}]}, "n2": {"speaker": "audience", "text": "Impressive. What makes your approach different from competitors?", "text_fr": "Impressionnant. Qu''est-ce qui rend votre approche différente de la concurrence ?", "choices": [{"text": "We focus on simplicity and user experience above all else.", "next": "n3"}]}, "n3": {"speaker": "audience", "text": "That''s compelling. We''d love to learn more after this session.", "text_fr": "C''est convaincant. On aimerait en savoir plus après cette session.", "choices": [{"text": "I''d be thrilled to continue the conversation.", "next": "end_success"}]}, "end_success": {"speaker": "audience", "text": "(applause) Great presentation!", "text_fr": "(applaudissements) Excellente présentation !", "end": true, "ending_label": "Présentation réussie 👏"}}}'::jsonb, is_playable = true
where title = 'Présenter son propre projet devant un public'
  and theme_id = (select id from scenario_themes where position = 13 and language_id = (select id from languages where code = 'en'));
