-- ============================================
-- LUMA — Rendre 4 scénarios jouables (contenu complet)
-- ============================================


update scenarios set content = '{"characters": {"tom": "Tom (serveur)"}, "start_node": "n1", "nodes": {"n1": {"speaker": "tom", "text": "Hi there! Are you ready to order, or do you need a few more minutes?", "choices": [{"text": "I''m ready, thank you.", "next": "n2"}, {"text": "Could I have a few more minutes, please?", "next": "n1b"}]}, "n1b": {"speaker": "tom", "text": "No problem, take your time! (Tom comes back a minute later)", "choices": [{"text": "(Continuer)", "next": "n2"}]}, "n2": {"speaker": "tom", "text": "Great, what can I get you?", "choices": [{"text": "I''ll have the grilled chicken, please.", "next": "n3"}, {"text": "What do you recommend?", "next": "n2b"}]}, "n2b": {"speaker": "tom", "text": "The grilled chicken is very popular today!", "choices": [{"text": "Sounds great, I''ll have that.", "next": "n3"}, {"text": "I''ll stick with the pasta instead, please.", "next": "n3"}]}, "n3": {"speaker": "tom", "text": "Perfect choice. Anything to drink?", "choices": [{"text": "Just water, please.", "next": "end_water"}, {"text": "A glass of orange juice, please.", "next": "end_juice"}]}, "end_water": {"speaker": "tom", "text": "Coming right up! By the way, tap water is free here, but bottled water is charged extra.", "end": true, "ending_label": "Repas commandé avec succès 🎉"}, "end_juice": {"speaker": "tom", "text": "One orange juice, coming right up! I''ll bring your order shortly.", "end": true, "ending_label": "Repas commandé avec succès 🎉"}}}'::jsonb, is_playable = true
where title = 'Commander un plat simple'
  and theme_id = (select id from scenario_themes where position = 1 and language_id = (select id from languages where code = 'en'));


update scenarios set content = '{"characters": {"gareth": "Gareth (garde du village)"}, "start_node": "n1", "nodes": {"n1": {"speaker": "gareth", "text": "Halt! What business do you have in these parts, traveler?", "choices": [{"text": "I''m looking for the path to the Enchanted Forest.", "next": "end_direct"}, {"text": "Just passing through.", "next": "n1b"}, {"text": "I''m on a quest to find a lost artifact.", "next": "end_quest"}]}, "n1b": {"speaker": "gareth", "text": "Passing through, you say? These woods aren''t for wandering souls. State your purpose clearly.", "choices": [{"text": "Fine — I seek the path to the Enchanted Forest.", "next": "end_direct"}, {"text": "I mean no harm, I promise.", "next": "end_neutral"}]}, "end_direct": {"speaker": "gareth", "text": "The Enchanted Forest lies beyond the old bridge. Beware — strange creatures roam there after dusk.", "end": true, "ending_label": "Chemin obtenu clairement 🗺️"}, "end_quest": {"speaker": "gareth", "text": "A lost artifact, you say? Then you''ll need to head north, past the old bridge. I''ll mark it on your map myself.", "end": true, "ending_label": "Confiance gagnée ⭐"}, "end_neutral": {"speaker": "gareth", "text": "Hmph. Very well. The forest is north of here. Stay alert.", "end": true, "ending_label": "Passage autorisé, méfiance restante 😐"}}}'::jsonb, is_playable = true
where title = 'Demander son chemin à un garde du village'
  and theme_id = (select id from scenario_themes where position = 8 and language_id = (select id from languages where code = 'en'));


update scenarios set content = '{"characters": {"jess": "Jess (amie)"}, "start_node": "n1", "nodes": {"n1": {"speaker": "jess", "text": "Where are you? I can''t see you anywhere!", "choices": [{"text": "I''m right next to the food truck with the red sign, near the main stage.", "next": "end_precise"}, {"text": "I''m near the stage.", "next": "n1b"}, {"text": "Let''s just meet at the big fountain in ten minutes.", "next": "end_meetup"}]}, "n1b": {"speaker": "jess", "text": "There are like five stages here! Can you be more specific?", "choices": [{"text": "Sorry! I''m at the smaller stage on the east side, by the food trucks.", "next": "end_precise"}, {"text": "Actually, let''s just meet at the fountain instead.", "next": "end_meetup"}]}, "end_precise": {"speaker": "jess", "text": "Got it, I see you now! Be right there!", "end": true, "ending_label": "Retrouvailles rapides ✅"}, "end_meetup": {"speaker": "jess", "text": "Perfect, see you at the fountain in ten!", "end": true, "ending_label": "Point de rendez-vous fixé ✅"}}}'::jsonb, is_playable = true
where title = 'Retrouver des amis dans la foule'
  and theme_id = (select id from scenario_themes where position = 11 and language_id = (select id from languages where code = 'en'));


update scenarios set content = '{"characters": {"peggy": "Peggy (serveuse)"}, "start_node": "n1", "nodes": {"n1": {"speaker": "peggy", "text": "What can I get you, hon?", "choices": [{"text": "I''ll have the classic burger with fries, please.", "next": "end_classic"}, {"text": "What''s the special today?", "next": "n1b"}, {"text": "Can I get the burger with extra cheese and bacon?", "next": "end_custom"}]}, "n1b": {"speaker": "peggy", "text": "Today''s special is meatloaf with mashed potatoes and gravy!", "choices": [{"text": "That sounds great, I''ll have that.", "next": "end_special"}, {"text": "I think I''ll stick with the classic burger.", "next": "end_classic"}]}, "end_classic": {"speaker": "peggy", "text": "One classic burger with fries, coming right up, hon!", "end": true, "ending_label": "Commande passée 🍔"}, "end_custom": {"speaker": "peggy", "text": "Extra cheese and bacon, got it! That''ll be a little extra, is that okay?", "end": true, "ending_label": "Commande personnalisée 🍔"}, "end_special": {"speaker": "peggy", "text": "Great choice! One meatloaf special, coming right up!", "end": true, "ending_label": "Plat du jour choisi 🍽️"}}}'::jsonb, is_playable = true
where title = 'Commander dans un diner américain'
  and theme_id = (select id from scenario_themes where position = 14 and language_id = (select id from languages where code = 'en'));
