-- ============================================
-- LUMA — Exercices pratiques pour les 8 fiches de grammaire B1
-- 7 exercices par fiche, même méthode qu'A1/A2.
-- ============================================

with f as (select id from grammar_fiches where cecr_level = 'B1' and position = 17)
insert into grammar_fiche_exercises (fiche_id, position, type, content)
select f.id, v.position, v.type, v.content::jsonb from f, (values
(1, 'qcm', '{"question": "Complète : I have ___ studying for three hours.", "options": ["be", "been", "being", "was"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"been\"."}'),(2, 'qcm', '{"question": "Complète : She''s tired because she ___ running.", "options": ["has been", "have been", "is", "was"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"has been\"."}'),(3, 'fill_blank', '{"sentence_before": "It ", "sentence_after": " all day. (rain, durée en cours)", "correct_answers": ["has been raining"], "feedback_correct": "Correct !", "feedback_incorrect": "Action longue, toujours en cours → has been + verbe-ing."}'),(4, 'fill_blank', '{"sentence_before": "How long have you been ", "sentence_after": "? (wait)", "correct_answers": ["waiting"], "feedback_correct": "Correct !", "feedback_incorrect": "have been + verbe-ing pour la durée."}'),(5, 'true_false', '{"statement": "''Know'' and ''believe'' can be used in the present perfect continuous.", "correct_answer": false, "feedback_correct": "Correct !", "feedback_incorrect": "Ce sont des verbes d''état, ils n''ont pas de forme continue."}'),(6, 'reorder', '{"words": ["She", "has", "been", "working", "here", "for", "months."], "correct_sentence": "She has been working here for months."}'),(7, 'error_correction', '{"wrong_sentence": "I have been knowing her for years.", "correct_sentence": "I have known her for years.", "error_word": "knowing", "feedback_correct": "Bien vu !", "feedback_incorrect": "Regarde le mot en rouge.", "explanation": "\"know\" est un verbe d''état → present perfect simple (known), jamais continu."}')
) as v(position, type, content);

with f as (select id from grammar_fiches where cecr_level = 'B1' and position = 18)
insert into grammar_fiche_exercises (fiche_id, position, type, content)
select f.id, v.position, v.type, v.content::jsonb from f, (values
(1, 'qcm', '{"question": "Complète : I ___ TV when she called.", "options": ["watch", "watched", "was watching", "am watching"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"was watching\"."}'),(2, 'qcm', '{"question": "Complète : While I ___ dinner, the phone rang.", "options": ["cooked", "was cooking", "cook", "am cooking"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"was cooking\"."}'),(3, 'fill_blank', '{"sentence_before": "The sun ", "sentence_after": " when we left. (shine, action de fond)", "correct_answers": ["was shining"], "feedback_correct": "Correct !", "feedback_incorrect": "Action de fond en cours → past continuous."}'),(4, 'fill_blank', '{"sentence_before": "She ", "sentence_after": " while I was sleeping. (arrive)", "correct_answers": ["arrived"], "feedback_correct": "Correct !", "feedback_incorrect": "Action ponctuelle qui interrompt → past simple."}'),(5, 'true_false', '{"statement": "The past continuous describes the background action, and the past simple describes the interrupting action.", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Relis la règle."}'),(6, 'reorder', '{"words": ["I", "was", "sleeping", "when", "the", "alarm", "rang."], "correct_sentence": "I was sleeping when the alarm rang."}'),(7, 'error_correction', '{"wrong_sentence": "I was watch TV when she called.", "correct_sentence": "I was watching TV when she called.", "error_word": "watch", "feedback_correct": "Bien vu !", "feedback_incorrect": "Regarde le mot en rouge.", "explanation": "past continuous = was/were + verbe-ing."}')
) as v(position, type, content);

with f as (select id from grammar_fiches where cecr_level = 'B1' and position = 19)
insert into grammar_fiche_exercises (fiche_id, position, type, content)
select f.id, v.position, v.type, v.content::jsonb from f, (values
(1, 'qcm', '{"question": "Complète : If it rains, I ___ stay home.", "options": ["will", "would", "stay", "stayed"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"will\"."}'),(2, 'qcm', '{"question": "Complète : If I ___ rich, I would travel the world.", "options": ["am", "was", "were", "will be"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"were\"."}'),(3, 'fill_blank', '{"sentence_before": "If you study, you ", "sentence_after": " the exam. (pass, first conditional)", "correct_answers": ["will pass"], "feedback_correct": "Correct !", "feedback_incorrect": "Possibilité réaliste future → if + présent, will + base."}'),(4, 'fill_blank', '{"sentence_before": "If I ", "sentence_after": " wings, I would fly. (have, impossible)", "correct_answers": ["had"], "feedback_correct": "Correct !", "feedback_incorrect": "Situation hypothétique irréelle → if + passé simple."}'),(5, 'true_false', '{"statement": "The first conditional talks about a realistic future possibility.", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Relis la règle."}'),(6, 'reorder', '{"words": ["If", "it", "rains,", "we", "will", "cancel", "the", "picnic."], "correct_sentence": "If it rains, we will cancel the picnic."}'),(7, 'error_correction', '{"wrong_sentence": "If I win the lottery, I will bought a house.", "correct_sentence": "If I win the lottery, I will buy a house.", "error_word": "bought", "feedback_correct": "Bien vu !", "feedback_incorrect": "Regarde le mot en rouge.", "explanation": "will + base verbale, jamais will + participe passé."}')
) as v(position, type, content);

with f as (select id from grammar_fiches where cecr_level = 'B1' and position = 20)
insert into grammar_fiche_exercises (fiche_id, position, type, content)
select f.id, v.position, v.type, v.content::jsonb from f, (values
(1, 'qcm', '{"question": "Complète : The letter ___ by John.", "options": ["wrote", "was written", "is write", "written"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"was written\"."}'),(2, 'qcm', '{"question": "Complète : This song ___ by millions of people.", "options": ["loves", "is loved", "loved", "loving"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"is loved\"."}'),(3, 'fill_blank', '{"sentence_before": "The house ", "sentence_after": " in 1990. (build, passif passé)", "correct_answers": ["was built"], "feedback_correct": "Correct !", "feedback_incorrect": "Passif passé = was/were + participe passé."}'),(4, 'fill_blank', '{"sentence_before": "English ", "sentence_after": " all over the world. (speak, passif présent)", "correct_answers": ["is spoken"], "feedback_correct": "Correct !", "feedback_incorrect": "Passif présent = is/are + participe passé."}'),(5, 'true_false', '{"statement": "The passive voice always mentions who did the action with ''by''.", "correct_answer": false, "feedback_correct": "Correct !", "feedback_incorrect": "Le complément d''agent (by...) est souvent omis quand il est inconnu, évident ou sans intérêt."}'),(6, 'reorder', '{"words": ["The", "cake", "was", "made", "by", "my", "mother."], "correct_sentence": "The cake was made by my mother."}'),(7, 'error_correction', '{"wrong_sentence": "The window was broke by the storm.", "correct_sentence": "The window was broken by the storm.", "error_word": "broke", "feedback_correct": "Bien vu !", "feedback_incorrect": "Regarde le mot en rouge.", "explanation": "passif = be + participe passé (broken), pas le prétérit (broke)."}')
) as v(position, type, content);

with f as (select id from grammar_fiches where cecr_level = 'B1' and position = 21)
insert into grammar_fiche_exercises (fiche_id, position, type, content)
select f.id, v.position, v.type, v.content::jsonb from f, (values
(1, 'qcm', '{"question": "''I am tired,'' she said. → She said ___", "options": ["she was tired", "she is tired", "she will be tired", "she has been tired"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"she was tired\"."}'),(2, 'qcm', '{"question": "''Where do you live?'' he asked. → He asked ___", "options": ["where I lived", "where did I live", "where I live", "where do I live"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"where I lived\"."}'),(3, 'fill_blank', '{"sentence_before": "''I will call you,'' she said. → She said she ", "sentence_after": " me. (call, recul)", "correct_answers": ["would call"], "feedback_correct": "Correct !", "feedback_incorrect": "will recule en would au discours rapporté."}'),(4, 'fill_blank', '{"sentence_before": "''Are you ready?'' he asked. → He asked ", "sentence_after": " I was ready.", "correct_answers": ["if"], "feedback_correct": "Correct !", "feedback_incorrect": "Question fermée rapportée → if/whether."}'),(5, 'true_false', '{"statement": "Reported yes/no questions never use a question mark and never invert the subject and verb.", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Relis la règle."}'),(6, 'reorder', '{"words": ["She", "said", "that", "she", "was", "tired."], "correct_sentence": "She said that she was tired."}'),(7, 'error_correction', '{"wrong_sentence": "He asked me where did I live.", "correct_sentence": "He asked me where I lived.", "error_word": "did", "feedback_correct": "Bien vu !", "feedback_incorrect": "Regarde le mot en rouge.", "explanation": "Discours rapporté indirect = ordre affirmatif, pas d''inversion avec did."}')
) as v(position, type, content);

with f as (select id from grammar_fiches where cecr_level = 'B1' and position = 22)
insert into grammar_fiche_exercises (fiche_id, position, type, content)
select f.id, v.position, v.type, v.content::jsonb from f, (values
(1, 'qcm', '{"question": "Complète : This is the man ___ helped me.", "options": ["who", "which", "whose", "where"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"who\"."}'),(2, 'qcm', '{"question": "Complète : The book ___ I read was great.", "options": ["who", "which", "whose", "where"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"which\"."}'),(3, 'fill_blank', '{"sentence_before": "This is the house ", "sentence_after": " I grew up. (où)", "correct_answers": ["where"], "feedback_correct": "Correct !", "feedback_incorrect": "Lieu → where."}'),(4, 'fill_blank', '{"sentence_before": "She''s the woman ", "sentence_after": " car was stolen. (dont)", "correct_answers": ["whose"], "feedback_correct": "Correct !", "feedback_incorrect": "Possession → whose."}'),(5, 'true_false', '{"statement": "A non-defining relative clause gives essential information about the noun.", "correct_answer": false, "feedback_correct": "Correct !", "feedback_incorrect": "C''est l''inverse : la non-déterminative donne une information EXTRA, pas essentielle (la déterminative, elle, est essentielle)."}'),(6, 'reorder', '{"words": ["This", "is", "the", "book", "that", "I", "love."], "correct_sentence": "This is the book that I love."}'),(7, 'error_correction', '{"wrong_sentence": "This is the man which helped me.", "correct_sentence": "This is the man who helped me.", "error_word": "which", "feedback_correct": "Bien vu !", "feedback_incorrect": "Regarde le mot en rouge.", "explanation": "Pour une personne → who/that, jamais which."}')
) as v(position, type, content);

with f as (select id from grammar_fiches where cecr_level = 'B1' and position = 23)
insert into grammar_fiche_exercises (fiche_id, position, type, content)
select f.id, v.position, v.type, v.content::jsonb from f, (values
(1, 'qcm', '{"question": "Complète : I enjoy ___ books.", "options": ["read", "to read", "reading", "reads"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"reading\"."}'),(2, 'qcm', '{"question": "Complète : She decided ___ home early.", "options": ["go", "to go", "going", "goes"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"to go\"."}'),(3, 'fill_blank', '{"sentence_before": "I want ", "sentence_after": " Spanish. (learn)", "correct_answers": ["to learn"], "feedback_correct": "Correct !", "feedback_incorrect": "want + infinitif (to + base)."}'),(4, 'fill_blank', '{"sentence_before": "He avoids ", "sentence_after": " sugar. (eat)", "correct_answers": ["eating"], "feedback_correct": "Correct !", "feedback_incorrect": "avoid + gérondif (-ing)."}'),(5, 'true_false', '{"statement": "''Remember to do'' and ''remember doing'' mean exactly the same thing.", "correct_answer": false, "feedback_correct": "Correct !", "feedback_incorrect": "''remember to do'' = ne pas oublier de faire (futur). ''remember doing'' = se souvenir d''avoir fait (passé). Sens différents."}'),(6, 'reorder', '{"words": ["I", "love", "playing", "the", "guitar."], "correct_sentence": "I love playing the guitar."}'),(7, 'error_correction', '{"wrong_sentence": "She enjoys to swim in the sea.", "correct_sentence": "She enjoys swimming in the sea.", "error_word": "to", "feedback_correct": "Bien vu !", "feedback_incorrect": "Regarde le mot en rouge.", "explanation": "\"enjoy\" est toujours suivi du gérondif (-ing), jamais de l''infinitif."}')
) as v(position, type, content);

with f as (select id from grammar_fiches where cecr_level = 'B1' and position = 24)
insert into grammar_fiche_exercises (fiche_id, position, type, content)
select f.id, v.position, v.type, v.content::jsonb from f, (values
(1, 'qcm', '{"question": "Complète : He''s not answering. He ___ be asleep.", "options": ["must", "mustn''t", "can''t", "should"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"must\"."}'),(2, 'qcm', '{"question": "Complète : She ___ have taken the wrong bus, she''s very late.", "options": ["must", "can''t", "might", "should"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"might\"."}'),(3, 'fill_blank', '{"sentence_before": "I ", "sentence_after": " have listened to you. (should, regret)", "correct_answers": ["should"], "feedback_correct": "Correct !", "feedback_incorrect": "Regret d''une action passée → should have."}'),(4, 'fill_blank', '{"sentence_before": "It ", "sentence_after": " have been him, he was with me. (can''t, impossibilité)", "correct_answers": ["can''t"], "feedback_correct": "Correct !", "feedback_incorrect": "Impossibilité logique → can''t have."}'),(5, 'true_false', '{"statement": "''Must have'' expresses a strong logical deduction about the past.", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Relis la règle."}'),(6, 'reorder', '{"words": ["She", "must", "have", "forgotten", "her", "keys."], "correct_sentence": "She must have forgotten her keys."}'),(7, 'error_correction', '{"wrong_sentence": "I should has called her yesterday.", "correct_sentence": "I should have called her yesterday.", "error_word": "has", "feedback_correct": "Bien vu !", "feedback_incorrect": "Regarde le mot en rouge.", "explanation": "should have + participe passé, jamais \"has\"."}')
) as v(position, type, content);
