-- ============================================
-- LUMA — Scénarios jouables : Thématique 7 (Shopping) — complète
-- ============================================

update scenarios set content = '{"characters": {"clerk": "la vendeuse"}, "start_node": "n1", "nodes": {"n1": {"speaker": "clerk", "text": "Can I help you find anything?", "text_fr": "Je peux vous aider à trouver quelque chose ?", "choices": [{"text": "Yes, do you have this in a medium?", "next": "n2"}, {"text": "Do you have this in a smaller size?", "next": "n2b"}]}, "n2": {"speaker": "clerk", "text": "Let me check... yes, here you go.", "text_fr": "Je vérifie... oui, voici.", "choices": [{"text": "Perfect, thank you!", "next": "end_found"}]}, "n2b": {"speaker": "clerk", "text": "We have a small left, want to try it?", "text_fr": "Il nous reste un petit, vous voulez l''essayer ?", "choices": [{"text": "Yes, please.", "next": "end_found"}]}, "end_found": {"speaker": "clerk", "text": "The fitting room is right there.", "text_fr": "La cabine d''essayage est juste là.", "end": true, "ending_label": "Taille trouvée 👕"}}}'::jsonb, is_playable = true
where title = 'Demander une taille'
  and theme_id = (select id from scenario_themes where position = 7 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"vendor": "le vendeur du marché"}, "start_node": "n1", "nodes": {"n1": {"speaker": "vendor", "text": "These scarves are $20 each, beautiful quality!", "text_fr": "Ces écharpes sont à 20$ chacune, belle qualité !", "choices": [{"text": "Would you do $15 if I buy two?", "next": "n2"}, {"text": "That''s a bit pricey for me, sorry.", "next": "n2b"}]}, "n2": {"speaker": "vendor", "text": "For two, I can do $17 each, final offer.", "text_fr": "Pour deux, je peux faire 17$ chacune, dernière offre.", "choices": [{"text": "Deal, I''ll take two.", "next": "end_deal"}]}, "n2b": {"speaker": "vendor", "text": "Wait, for you, $16, special price!", "text_fr": "Attendez, pour vous, 16$, prix spécial !", "choices": [{"text": "Alright, I''ll take one at that price.", "next": "end_deal"}]}, "end_deal": {"speaker": "vendor", "text": "Great choice, enjoy!", "text_fr": "Excellent choix, profitez-en !", "end": true, "ending_label": "Négociation réussie 💰"}}}'::jsonb, is_playable = true
where title = 'Négocier un prix au marché'
  and theme_id = (select id from scenario_themes where position = 7 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"clerk": "le vendeur du service client"}, "start_node": "n1", "nodes": {"n1": {"speaker": "clerk", "text": "How can I help you today?", "text_fr": "Comment puis-je vous aider aujourd''hui ?", "choices": [{"text": "This jacket has a broken zipper, I''d like a refund.", "next": "n2"}, {"text": "Could I exchange this for a working one instead?", "next": "n2b"}]}, "n2": {"speaker": "clerk", "text": "Do you have your receipt?", "text_fr": "Avez-vous votre reçu ?", "choices": [{"text": "Yes, right here.", "next": "end_refund"}]}, "n2b": {"speaker": "clerk", "text": "Sure, let me check if we have one in stock.", "text_fr": "Bien sûr, je vérifie si on en a en stock.", "choices": [{"text": "Thank you, I appreciate it.", "next": "end_exchange"}]}, "end_refund": {"speaker": "clerk", "text": "Perfect, your refund is processed.", "text_fr": "Parfait, votre remboursement est traité.", "end": true, "ending_label": "Remboursement obtenu 💳"}, "end_exchange": {"speaker": "clerk", "text": "Good news, we have one — here''s a working replacement.", "text_fr": "Bonne nouvelle, on en a une — voici un remplacement fonctionnel.", "end": true, "ending_label": "Échange réussi ✅"}}}'::jsonb, is_playable = true
where title = 'Retourner un article défectueux'
  and theme_id = (select id from scenario_themes where position = 7 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"friend": "ton ami(e) de shopping"}, "start_node": "n1", "nodes": {"n1": {"speaker": "friend", "text": "This dress is gorgeous, but it''s $80. What''s your budget today?", "text_fr": "Cette robe est magnifique, mais elle fait 80$. Quel est ton budget aujourd''hui ?", "choices": [{"text": "Honestly, I only have $50 to spend total.", "next": "n2"}]}, "n2": {"speaker": "friend", "text": "Let''s check the sale rack then, might find something similar.", "text_fr": "Regardons le rayon soldes alors, on pourrait trouver quelque chose de similaire.", "choices": [{"text": "Good idea, let''s look.", "next": "n3"}]}, "n3": {"speaker": "friend", "text": "Look, this one is only $35 and it''s really similar!", "text_fr": "Regarde, celle-ci est seulement à 35$ et elle est vraiment similaire !", "choices": [{"text": "I love it, and it fits my budget perfectly.", "next": "end_saved"}]}, "end_saved": {"speaker": "friend", "text": "Great find, and you saved money too!", "text_fr": "Belle trouvaille, et tu as économisé en plus !", "end": true, "ending_label": "Achat malin dans le budget 💡"}}}'::jsonb, is_playable = true
where title = 'Faire du shopping avec un budget serré'
  and theme_id = (select id from scenario_themes where position = 7 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"clerk": "le vendeur"}, "start_node": "n1", "nodes": {"n1": {"speaker": "clerk", "text": "These two laptops are popular — what will you mainly use it for?", "text_fr": "Ces deux ordinateurs sont populaires — vous allez l''utiliser pour quoi principalement ?", "choices": [{"text": "Mostly work and some video editing.", "next": "n2"}, {"text": "Just browsing and emails, nothing intensive.", "next": "n2b"}]}, "n2": {"speaker": "clerk", "text": "Then I''d recommend this one, it has a much better processor.", "text_fr": "Alors je recommande celui-ci, il a un bien meilleur processeur.", "choices": [{"text": "That makes sense, I''ll go with that one.", "next": "end_chosen"}]}, "n2b": {"speaker": "clerk", "text": "In that case, the cheaper one would suit you just fine.", "text_fr": "Dans ce cas, le moins cher vous conviendrait très bien.", "choices": [{"text": "Perfect, no need to overspend then.", "next": "end_chosen"}]}, "end_chosen": {"speaker": "clerk", "text": "Great choice for your needs!", "text_fr": "Excellent choix pour vos besoins !", "end": true, "ending_label": "Bon conseil suivi 💻"}}}'::jsonb, is_playable = true
where title = 'Comparer deux produits avec un vendeur'
  and theme_id = (select id from scenario_themes where position = 7 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"clerk": "le vendeur"}, "start_node": "n1", "nodes": {"n1": {"speaker": "clerk", "text": "You seem to be in a hurry, can I help?", "text_fr": "Vous semblez pressé, je peux vous aider ?", "choices": [{"text": "Yes! I need a birthday gift for my sister, she loves candles and books.", "next": "n2"}]}, "n2": {"speaker": "clerk", "text": "We have a lovely candle gift set, or this bestselling novel.", "text_fr": "On a un joli coffret de bougies, ou ce roman best-seller.", "choices": [{"text": "I''ll take both, better safe than sorry!", "next": "end_both"}, {"text": "The candle set sounds perfect, I''ll take that.", "next": "end_candle"}]}, "end_both": {"speaker": "clerk", "text": "Great choice, she''ll love having options!", "text_fr": "Excellent choix, elle va adorer avoir le choix !", "end": true, "ending_label": "Cadeau trouvé à temps 🎁"}, "end_candle": {"speaker": "clerk", "text": "Perfect, let me gift wrap it for you.", "text_fr": "Parfait, je vous l''emballe cadeau.", "end": true, "ending_label": "Cadeau trouvé à temps 🎁"}}}'::jsonb, is_playable = true
where title = 'Un cadeau à trouver dans l''urgence'
  and theme_id = (select id from scenario_themes where position = 7 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"friend": "ton ami(e)"}, "start_node": "n1", "nodes": {"n1": {"speaker": "friend", "text": "Where should we start, shoes or clothes?", "text_fr": "On commence par où, chaussures ou vêtements ?", "choices": [{"text": "Let''s do shoes first, I need new sneakers.", "next": "n2"}, {"text": "Clothes first, I want to check the new collection.", "next": "n2b"}]}, "n2": {"speaker": "friend", "text": "These sneakers look great on you! What do you think?", "text_fr": "Ces baskets te vont super bien ! Qu''en penses-tu ?", "choices": [{"text": "I love them, let''s get these.", "next": "n3"}]}, "n2b": {"speaker": "friend", "text": "This jacket would look amazing with your style.", "text_fr": "Cette veste irait super bien avec ton style.", "choices": [{"text": "You''re right, let''s try it on.", "next": "n3"}]}, "n3": {"speaker": "friend", "text": "Okay, one more stop — the accessories shop?", "text_fr": "D''accord, un dernier arrêt — la boutique d''accessoires ?", "choices": [{"text": "Sure, let''s see what they have.", "next": "n4"}]}, "n4": {"speaker": "friend", "text": "This has been such a productive shopping trip!", "text_fr": "Cette session shopping a été super productive !", "choices": [{"text": "Definitely, I found everything I needed.", "next": "end_success"}]}, "end_success": {"speaker": "friend", "text": "Time for coffee to celebrate our finds!", "text_fr": "L''heure du café pour célébrer nos trouvailles !", "end": true, "ending_label": "Journée shopping réussie 🛍️"}}}'::jsonb, is_playable = true
where title = 'Une session shopping avec plusieurs boutiques et décisions'
  and theme_id = (select id from scenario_themes where position = 7 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"agent": "l''agent du service client"}, "start_node": "n1", "nodes": {"n1": {"speaker": "agent", "text": "How can I help you today?", "text_fr": "Comment puis-je vous aider aujourd''hui ?", "choices": [{"text": "I was charged twice for the same order, I''d like a refund.", "next": "n2"}]}, "n2": {"speaker": "agent", "text": "I''m sorry about that. Let me pull up your order details.", "text_fr": "Désolé pour ce désagrément. Laissez-moi consulter votre commande.", "choices": [{"text": "Thank you, here''s my order number.", "next": "n3"}]}, "n3": {"speaker": "agent", "text": "I see the duplicate charge, I''ll refund it right away.", "text_fr": "Je vois le double prélèvement, je vous rembourse tout de suite.", "choices": [{"text": "I appreciate the quick resolution.", "next": "n4"}]}, "n4": {"speaker": "agent", "text": "You should see the refund in 3-5 business days.", "text_fr": "Vous devriez voir le remboursement sous 3 à 5 jours ouvrés.", "choices": [{"text": "Perfect, thank you for your help.", "next": "end_resolved"}]}, "end_resolved": {"speaker": "agent", "text": "Sorry again for the inconvenience, have a great day!", "text_fr": "Encore désolé pour ce désagrément, bonne journée !", "end": true, "ending_label": "Litige résolu 💳"}}}'::jsonb, is_playable = true
where title = 'Un litige avec le service client'
  and theme_id = (select id from scenario_themes where position = 7 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"stylist": "la conseillère en image"}, "start_node": "n1", "nodes": {"n1": {"speaker": "stylist", "text": "So, what''s the event and what vibe are you going for?", "text_fr": "Alors, c''est quel événement et quelle ambiance tu recherches ?", "choices": [{"text": "A wedding, I want something elegant but not too formal.", "next": "n2"}, {"text": "A job interview, I need to look professional and confident.", "next": "n2b"}]}, "n2": {"speaker": "stylist", "text": "This navy suit with a lighter shirt would be perfect.", "text_fr": "Ce costume bleu marine avec une chemise plus claire serait parfait.", "choices": [{"text": "I love that combination, let''s go with it.", "next": "n3"}]}, "n2b": {"speaker": "stylist", "text": "A tailored blazer with simple, clean lines would work great.", "text_fr": "Un blazer ajusté avec des lignes simples et nettes fonctionnerait très bien.", "choices": [{"text": "That sounds exactly right for the tone I want.", "next": "n3"}]}, "n3": {"speaker": "stylist", "text": "Let''s add the right accessories to complete the look.", "text_fr": "Ajoutons les bons accessoires pour compléter le look.", "choices": [{"text": "Perfect, I trust your judgment here.", "next": "end_complete"}]}, "end_complete": {"speaker": "stylist", "text": "You''re going to look fantastic!", "text_fr": "Tu vas être fantastique !", "end": true, "ending_label": "Garde-robe complète 👔"}}}'::jsonb, is_playable = true
where title = 'Préparer une garde-robe pour un événement'
  and theme_id = (select id from scenario_themes where position = 7 and language_id = (select id from languages where code = 'en'));
