-- ============================================
-- LUMA — Thème 7 (Shopping) : 3 scénarios COURTS x4
-- ============================================


update scenarios set content = '{"characters": {"clerk": "le vendeur"}, "start_node": "n1", "nodes": {"n1": {"speaker": "clerk", "text": "Hi there, can I help you find something?", "text_fr": "Bonjour, je peux vous aider à trouver quelque chose ?", "choices": [{"text": "Yes, do you have this shirt in a medium?", "text_fr": "Oui, vous avez cette chemise en taille M ?", "next": "n2"}, {"text": "I''m looking for this in a smaller size, do you have it?", "text_fr": "Je cherche ça dans une taille plus petite, vous avez ça ?", "next": "n2b"}]}, "n2": {"speaker": "clerk", "text": "Let me check the back — one moment, please.", "text_fr": "Laissez-moi vérifier en réserve — un instant, s''il vous plaît.", "choices": [{"text": "Take your time, thank you.", "text_fr": "Prenez votre temps, merci.", "next": "n3"}]}, "n2b": {"speaker": "clerk", "text": "Sure, what size are you currently looking at?", "text_fr": "Bien sûr, quelle taille regardez-vous actuellement ?", "choices": [{"text": "This is a large, I''d like to try a medium instead.", "text_fr": "C''est un L, j''aimerais essayer un M à la place.", "next": "n3"}]}, "n3": {"speaker": "clerk", "text": "(Returns) Here you go, we had one left in that size.", "text_fr": "(Revient) Voici, il nous en restait un dans cette taille.", "choices": [{"text": "Perfect, thank you so much. Where are the fitting rooms?", "text_fr": "Parfait, merci beaucoup. Où sont les cabines d''essayage ?", "next": "n4"}, {"text": "Great, I''ll take it, thank you!", "text_fr": "Super, je le prends, merci !", "next": "n4b"}]}, "n4": {"speaker": "clerk", "text": "Right over there, to your left.", "text_fr": "Juste là-bas, sur votre gauche.", "choices": [{"text": "Thank you, I''ll go try it on.", "text_fr": "Merci, je vais aller l''essayer.", "next": "n5"}]}, "n4b": {"speaker": "clerk", "text": "Great choice! Anything else I can help you find?", "text_fr": "Excellent choix ! Autre chose que je peux vous aider à trouver ?", "choices": [{"text": "No, that''s everything, thank you!", "text_fr": "Non, c''est tout, merci !", "next": "end_found"}]}, "n5": {"speaker": "you_thought", "text": "(You try it on and it fits perfectly.)", "text_fr": "(Vous l''essayez et ça vous va parfaitement.)", "choices": [{"text": "This fits great, I''ll take it!", "text_fr": "Ça me va super, je le prends !", "next": "end_found"}]}, "end_found": {"speaker": "clerk", "text": "Perfect, let''s get you checked out then!", "text_fr": "Parfait, allons vous encaisser alors !", "end": true, "ending_label": "Bonne taille trouvée sans souci 👕✅"}}}'::jsonb, is_playable = true
where title = 'Demander une taille'
  and theme_id = (select id from scenario_themes where position = 7 and language_id = (select id from languages where code = 'en'));


update scenarios set content = '{"characters": {"vendor": "le vendeur du marché"}, "start_node": "n1", "nodes": {"n1": {"speaker": "vendor", "text": "Ah, you like this necklace? Beautiful handmade piece, only $40.", "text_fr": "Ah, ce collier vous plaît ? Belle pièce faite main, seulement 40$.", "choices": [{"text": "It''s lovely, but that''s a bit more than I wanted to spend. Could you do $25?", "text_fr": "Il est adorable, mais c''est un peu plus que ce que je voulais dépenser. Vous pourriez faire 25$ ?", "next": "n2"}, {"text": "Beautiful indeed! Is there any flexibility on the price?", "text_fr": "Vraiment beau ! Il y a de la flexibilité sur le prix ?", "next": "n2b"}]}, "n2": {"speaker": "vendor", "text": "Oh, $25 is too low for me, but I could do $35 for you.", "text_fr": "Oh, 25$ c''est trop bas pour moi, mais je pourrais faire 35$ pour vous.", "choices": [{"text": "How about we meet in the middle, at $30?", "text_fr": "Et si on se rencontrait à mi-chemin, à 30$ ?", "next": "n3"}, {"text": "That''s still a bit much, could you do $28?", "text_fr": "C''est encore un peu trop, vous pourriez faire 28$ ?", "next": "n3"}]}, "n2b": {"speaker": "vendor", "text": "For you, maybe a little. What price were you thinking?", "text_fr": "Pour vous, peut-être un peu. Vous pensiez à quel prix ?", "choices": [{"text": "I was hoping for around $25 to $30.", "text_fr": "J''espérais autour de 25 à 30$.", "next": "n3"}]}, "n3": {"speaker": "vendor", "text": "(Laughs) You drive a hard bargain! Okay, $30, final offer.", "text_fr": "(Rit) Vous négociez dur ! D''accord, 30$, dernière offre.", "choices": [{"text": "Deal! Thank you, I love it.", "text_fr": "Marché conclu ! Merci, je l''adore.", "next": "n4"}]}, "n4": {"speaker": "vendor", "text": "Wonderful choice, let me wrap it up for you.", "text_fr": "Excellent choix, laissez-moi vous l''emballer.", "choices": [{"text": "Thank you so much, have a great day!", "text_fr": "Merci beaucoup, bonne journée !", "next": "end_negotiated"}]}, "end_negotiated": {"speaker": "vendor", "text": "You too! Come back anytime.", "text_fr": "Vous aussi ! Revenez quand vous voulez.", "end": true, "ending_label": "Prix négocié avec succès 💰🤝"}}}'::jsonb, is_playable = true
where title = 'Négocier un prix au marché'
  and theme_id = (select id from scenario_themes where position = 7 and language_id = (select id from languages where code = 'en'));
