-- ============================================
-- LUMA — Scénarios jouables : Thématique 12 (Musée) — complète
-- ============================================

update scenarios set content = '{"characters": {"guide": "le guide"}, "start_node": "n1", "nodes": {"n1": {"speaker": "guide", "text": "Welcome! This painting dates back to the 17th century. Any questions so far?", "text_fr": "Bienvenue ! Ce tableau date du 17e siècle. Des questions jusqu''ici ?", "choices": [{"text": "Yes, who was the artist?", "next": "n2"}, {"text": "No questions yet, please continue.", "next": "n2b"}]}, "n2": {"speaker": "guide", "text": "A little-known painter named Willem de Vries, fascinating story actually.", "text_fr": "Un peintre peu connu nommé Willem de Vries, une histoire fascinante en fait.", "choices": [{"text": "I''d love to hear more about that.", "next": "end_engaged"}]}, "n2b": {"speaker": "guide", "text": "Great, let''s move to the next room.", "text_fr": "Parfait, passons à la salle suivante.", "choices": [{"text": "Sounds good.", "next": "end_continue"}]}, "end_engaged": {"speaker": "guide", "text": "I love sharing these stories with curious visitors!", "text_fr": "J''adore partager ces histoires avec des visiteurs curieux !", "end": true, "ending_label": "Visite enrichissante 🖼️"}, "end_continue": {"speaker": "guide", "text": "Right this way, more treasures await.", "text_fr": "Par ici, d''autres trésors vous attendent.", "end": true, "ending_label": "Visite guidée suivie ✅"}}}'::jsonb, is_playable = true
where title = 'Suivre une visite guidée courte'
  and theme_id = (select id from scenario_themes where position = 12 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"staff": "un membre du personnel"}, "start_node": "n1", "nodes": {"n1": {"speaker": "staff", "text": "Can I help you with this piece?", "text_fr": "Je peux vous aider avec cette œuvre ?", "choices": [{"text": "What technique did the artist use here?", "next": "n2"}, {"text": "Is this the original or a replica?", "next": "n2b"}]}, "n2": {"speaker": "staff", "text": "This is oil on canvas, layered over several months.", "text_fr": "C''est de l''huile sur toile, appliquée sur plusieurs mois.", "choices": [{"text": "That''s incredible patience. Thank you!", "next": "end_learned"}]}, "n2b": {"speaker": "staff", "text": "This is the original, kept in carefully controlled conditions.", "text_fr": "C''est l''original, conservé dans des conditions soigneusement contrôlées.", "choices": [{"text": "Amazing to see it in person then. Thank you.", "next": "end_learned"}]}, "end_learned": {"speaker": "staff", "text": "My pleasure, enjoy the rest of your visit!", "text_fr": "Avec plaisir, bonne suite de visite !", "end": true, "ending_label": "Curiosité satisfaite 🎨"}}}'::jsonb, is_playable = true
where title = 'Poser une question sur une œuvre'
  and theme_id = (select id from scenario_themes where position = 12 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"clerk": "l''agent de la billetterie"}, "start_node": "n1", "nodes": {"n1": {"speaker": "clerk", "text": "Would you like the standard ticket or the combo with the special exhibition?", "text_fr": "Vous voulez le billet standard ou le combiné avec l''exposition spéciale ?", "choices": [{"text": "The combo ticket, please.", "next": "end_combo"}, {"text": "Just the standard one for now.", "next": "end_standard"}]}, "end_combo": {"speaker": "clerk", "text": "Great choice, that exhibition is stunning right now.", "text_fr": "Excellent choix, cette exposition est magnifique en ce moment.", "end": true, "ending_label": "Billet combiné acheté 🎟️"}, "end_standard": {"speaker": "clerk", "text": "Sure thing, here''s your ticket.", "text_fr": "Bien sûr, voici votre billet.", "end": true, "ending_label": "Billet standard acheté 🎟️"}}}'::jsonb, is_playable = true
where title = 'Acheter un billet combiné'
  and theme_id = (select id from scenario_themes where position = 12 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"audioguide": "l''audioguide"}, "start_node": "n1", "nodes": {"n1": {"speaker": "audioguide", "text": "Welcome. Press 1 for the history of this room, or 2 to skip ahead.", "text_fr": "Bienvenue. Appuyez sur 1 pour l''histoire de cette salle, ou 2 pour passer.", "choices": [{"text": "Press 1, I want to learn the history.", "next": "n2"}, {"text": "Press 2, skip to the highlights.", "next": "n2b"}]}, "n2": {"speaker": "audioguide", "text": "This wing was built in 1890 to house the royal collection.", "text_fr": "Cette aile a été construite en 1890 pour abriter la collection royale.", "choices": [{"text": "Fascinating, continue to the next piece.", "next": "n3"}]}, "n2b": {"speaker": "audioguide", "text": "Ahead you''ll find the museum''s most famous sculpture.", "text_fr": "Plus loin, vous trouverez la sculpture la plus célèbre du musée.", "choices": [{"text": "Let''s go see it.", "next": "n3"}]}, "n3": {"speaker": "audioguide", "text": "You''ve reached the final stop of this self-guided tour.", "text_fr": "Vous avez atteint le dernier arrêt de cette visite libre.", "choices": [{"text": "That was a great experience overall.", "next": "end_complete"}]}, "end_complete": {"speaker": "audioguide", "text": "Thank you for visiting, we hope to see you again!", "text_fr": "Merci de votre visite, à bientôt !", "end": true, "ending_label": "Visite libre complétée 🎧"}}}'::jsonb, is_playable = true
where title = 'Une visite libre avec un audioguide interactif'
  and theme_id = (select id from scenario_themes where position = 12 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"curator": "le conservateur"}, "start_node": "n1", "nodes": {"n1": {"speaker": "curator", "text": "This piece took me years to authenticate — want to hear the story?", "text_fr": "Cette pièce m''a pris des années à authentifier — vous voulez entendre l''histoire ?", "choices": [{"text": "Absolutely, please tell me!", "next": "n2"}]}, "n2": {"speaker": "curator", "text": "It was thought to be a forgery for decades, until we found this signature detail.", "text_fr": "On l''a crue être un faux pendant des décennies, jusqu''à ce qu''on trouve ce détail de signature.", "choices": [{"text": "That''s incredible detective work.", "next": "n3"}]}, "n3": {"speaker": "curator", "text": "It''s my favorite part of this job — uncovering hidden truths in art.", "text_fr": "C''est ma partie préférée de ce métier — dévoiler des vérités cachées dans l''art.", "choices": [{"text": "Your passion really shows, thank you for sharing.", "next": "end_inspired"}]}, "end_inspired": {"speaker": "curator", "text": "Thank you for listening so attentively.", "text_fr": "Merci de m''avoir écouté si attentivement.", "end": true, "ending_label": "Passion partagée 🖼️"}}}'::jsonb, is_playable = true
where title = 'Une discussion avec un conservateur passionné'
  and theme_id = (select id from scenario_themes where position = 12 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"instructor": "l''animateur de l''atelier"}, "start_node": "n1", "nodes": {"n1": {"speaker": "instructor", "text": "Today we''re recreating a classic sketching technique. Ready to try?", "text_fr": "Aujourd''hui on recrée une technique de croquis classique. Prêt à essayer ?", "choices": [{"text": "Yes, I''ve never done this before but I''m excited!", "next": "n2"}]}, "n2": {"speaker": "instructor", "text": "Perfect attitude! Start with light strokes, don''t worry about mistakes.", "text_fr": "Parfaite attitude ! Commencez par des traits légers, ne vous inquiétez pas des erreurs.", "choices": [{"text": "(sketch enthusiastically, embracing the imperfections)", "next": "n3"}]}, "n3": {"speaker": "instructor", "text": "That''s a wonderful first attempt, you really captured the movement!", "text_fr": "C''est un magnifique premier essai, vous avez vraiment capturé le mouvement !", "choices": [{"text": "Thank you, I really enjoyed this.", "next": "end_learned"}]}, "end_learned": {"speaker": "instructor", "text": "You should keep practicing, you have a natural eye for this!", "text_fr": "Vous devriez continuer à pratiquer, vous avez un œil naturel pour ça !", "end": true, "ending_label": "Nouvelle compétence acquise 🎨"}}}'::jsonb, is_playable = true
where title = 'Participer à un atelier ponctuel'
  and theme_id = (select id from scenario_themes where position = 12 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"guide": "le guide numérique"}, "start_node": "n1", "nodes": {"n1": {"speaker": "guide", "text": "Welcome to the Ocean Room — sounds and lights simulate the deep sea. Ready?", "text_fr": "Bienvenue dans la Salle Océan — sons et lumières simulent les profondeurs marines. Prêt ?", "choices": [{"text": "Yes, let''s dive in!", "next": "n2"}]}, "n2": {"speaker": "guide", "text": "Incredible, right? Next is the Desert Room, with real sand and heat lamps.", "text_fr": "Incroyable, non ? Ensuite, la Salle Désert, avec du vrai sable et des lampes chauffantes.", "choices": [{"text": "I''m ready for the next experience.", "next": "n3"}]}, "n3": {"speaker": "guide", "text": "Finally, the Space Room — a full 360° projection of the galaxy.", "text_fr": "Enfin, la Salle Espace — une projection à 360° de la galaxie.", "choices": [{"text": "This has been an unforgettable journey.", "next": "end_immersive"}]}, "end_immersive": {"speaker": "guide", "text": "Thank you for exploring all three worlds with us today!", "text_fr": "Merci d''avoir exploré ces trois mondes avec nous aujourd''hui !", "end": true, "ending_label": "Exposition immersive vécue pleinement 🌌"}}}'::jsonb, is_playable = true
where title = 'Une exposition immersive avec plusieurs salles thématiques'
  and theme_id = (select id from scenario_themes where position = 12 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"guide": "l''animateur du jeu"}, "start_node": "n1", "nodes": {"n1": {"speaker": "guide", "text": "Your first clue: ''Find the queen who never smiles.'' Any idea?", "text_fr": "Premier indice : ''Trouvez la reine qui ne sourit jamais.'' Une idée ?", "choices": [{"text": "That must be the portrait in room 3!", "next": "n2"}]}, "n2": {"speaker": "guide", "text": "Correct! Next clue: ''Where time stands still, made of gears.''", "text_fr": "Correct ! Indice suivant : ''Là où le temps s''arrête, fait d''engrenages.''", "choices": [{"text": "The antique clock exhibit, of course!", "next": "n3"}]}, "n3": {"speaker": "guide", "text": "You''re on a roll! Final clue: ''The final resting place of a pharaoh.''", "text_fr": "Vous êtes en forme ! Dernier indice : ''Le lieu de repos final d''un pharaon.''", "choices": [{"text": "The Egyptian sarcophagus room — I''m sure of it!", "next": "end_won"}]}, "end_won": {"speaker": "guide", "text": "You solved it all! Congratulations, treasure hunter champion!", "text_fr": "Vous avez tout résolu ! Félicitations, champion de la chasse au trésor !", "end": true, "ending_label": "Chasse au trésor gagnée 🏆"}}}'::jsonb, is_playable = true
where title = 'Une chasse au trésor culturelle dans le musée'
  and theme_id = (select id from scenario_themes where position = 12 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"guide": "le guide historien"}, "start_node": "n1", "nodes": {"n1": {"speaker": "guide", "text": "Some historians argue this artifact''s origin story is a myth. What do you think?", "text_fr": "Certains historiens pensent que l''origine de cet artefact est un mythe. Qu''en pensez-vous ?", "choices": [{"text": "I think the evidence supporting the myth is actually quite strong.", "next": "n2"}, {"text": "I lean toward skepticism — myths often get exaggerated over time.", "next": "n2b"}]}, "n2": {"speaker": "guide", "text": "Interesting perspective! The carbon dating does align with the legend''s timeline.", "text_fr": "Perspective intéressante ! La datation au carbone correspond bien à la chronologie de la légende.", "choices": [{"text": "Exactly, that''s what convinces me.", "next": "end_engaged"}]}, "n2b": {"speaker": "guide", "text": "A fair point — historical storytelling does tend to embellish facts.", "text_fr": "Un point valable — les récits historiques ont tendance à enjoliver les faits.", "choices": [{"text": "It''s fascinating to debate, either way.", "next": "end_engaged"}]}, "end_engaged": {"speaker": "guide", "text": "This is exactly the kind of thinking that keeps history alive!", "text_fr": "C''est exactement ce genre de réflexion qui garde l''histoire vivante !", "end": true, "ending_label": "Débat historique passionnant 🏛️"}}}'::jsonb, is_playable = true
where title = 'Un débat historique animé avec un guide'
  and theme_id = (select id from scenario_themes where position = 12 and language_id = (select id from languages where code = 'en'));
