-- ============================================
-- LUMA — Thème 15 (Londres) : 3 scénarios COURTS x4
-- ============================================


update scenarios set content = '{"characters": {"staff": "l''employé du métro"}, "start_node": "n1", "nodes": {"n1": {"speaker": "staff", "text": "Morning! First time on the Underground?", "text_fr": "Bonjour ! Première fois dans le métro ?", "choices": [{"text": "Yes, actually. How do I buy a ticket?", "text_fr": "Oui, en fait. Comment j''achète un billet ?", "next": "n2"}, {"text": "Yes, is it easy to use a contactless card instead of tickets?", "text_fr": "Oui, c''est facile d''utiliser une carte sans contact plutôt que des billets ?", "next": "n2b"}]}, "n2": {"speaker": "staff", "text": "Easiest way is to just tap a contactless card at the gates, no ticket needed.", "text_fr": "Le plus simple c''est de juste toucher une carte sans contact aux portillons, pas besoin de billet.", "choices": [{"text": "Oh, that''s convenient! I''ll use my card then.", "text_fr": "Oh, c''est pratique ! Je vais utiliser ma carte alors.", "next": "n3"}]}, "n2b": {"speaker": "staff", "text": "Very easy, actually! Just tap in and out, and it calculates the fare automatically.", "text_fr": "Très facile, en fait ! Touchez juste en entrant et sortant, et ça calcule le tarif automatiquement.", "choices": [{"text": "Perfect, that sounds much simpler than buying tickets.", "text_fr": "Parfait, ça semble bien plus simple qu''acheter des billets.", "next": "n3"}]}, "n3": {"speaker": "staff", "text": "Exactly, and it caps your daily spending too, so you never overpay!", "text_fr": "Exactement, et ça plafonne vos dépenses quotidiennes aussi, donc vous payez jamais trop !", "choices": [{"text": "That''s brilliant, thank you for explaining!", "text_fr": "C''est génial, merci d''avoir expliqué !", "next": "n4"}]}, "n4": {"speaker": "staff", "text": "No problem at all, enjoy exploring London!", "text_fr": "Aucun problème, profitez de l''exploration de Londres !", "choices": [{"text": "Thank you, I will!", "text_fr": "Merci, je vais le faire !", "next": "end_learned"}]}, "end_learned": {"speaker": "staff", "text": "Mind the gap, and have a great day!", "text_fr": "Attention à la marche, et bonne journée !", "end": true, "ending_label": "Système du métro londonien compris 🚇✅"}}}'::jsonb, is_playable = true
where title = 'Prendre le métro londonien'
  and theme_id = (select id from scenario_themes where position = 15 and language_id = (select id from languages where code = 'en'));


update scenarios set content = '{"characters": {"bartender": "le barman"}, "start_node": "n1", "nodes": {"n1": {"speaker": "bartender", "text": "What can I get you?", "text_fr": "Je vous sers quoi ?", "choices": [{"text": "Could I get a pint of lager, please?", "text_fr": "Je pourrais avoir une pinte de blonde, s''il vous plaît ?", "next": "n2"}, {"text": "What do you recommend for someone who doesn''t usually drink beer?", "text_fr": "Vous recommandez quoi pour quelqu''un qui boit pas de bière d''habitude ?", "next": "n2b"}]}, "n2": {"speaker": "bartender", "text": "Coming right up! Running a tab, or paying now?", "text_fr": "Tout de suite ! Vous ouvrez une ardoise, ou vous payez maintenant ?", "choices": [{"text": "I''ll pay now, thank you.", "text_fr": "Je vais payer maintenant, merci.", "next": "n3"}]}, "n2b": {"speaker": "bartender", "text": "Our cider is quite popular, nice and refreshing if you''re not into beer.", "text_fr": "Notre cidre est assez populaire, agréable et rafraîchissant si vous aimez pas la bière.", "choices": [{"text": "That sounds perfect, I''ll try that instead.", "text_fr": "Ça a l''air parfait, je vais essayer ça plutôt.", "next": "n3"}]}, "n3": {"speaker": "bartender", "text": "Here you go! Let me know if you''d like a menu for food too.", "text_fr": "Voilà ! Dites-moi si vous voulez un menu pour manger aussi.", "choices": [{"text": "Actually yes, I''d love to see the food menu.", "text_fr": "En fait oui, j''aimerais voir le menu à manger.", "next": "n4"}, {"text": "Not right now, thank you though.", "text_fr": "Pas maintenant, merci quand même.", "next": "n4"}]}, "n4": {"speaker": "bartender", "text": "No worries, just wave me down at the bar whenever you''re ready to order more.", "text_fr": "T''inquiète, faites-moi juste signe au bar quand vous êtes prêt à commander plus.", "choices": [{"text": "Will do, thank you!", "text_fr": "C''est noté, merci !", "next": "end_ordered"}]}, "end_ordered": {"speaker": "bartender", "text": "Cheers, enjoy!", "text_fr": "Santé, profitez-en !", "end": true, "ending_label": "Commande passée façon pub anglais 🍺✅"}}}'::jsonb, is_playable = true
where title = 'Commander dans un pub'
  and theme_id = (select id from scenario_themes where position = 15 and language_id = (select id from languages where code = 'en'));
