-- ============================================
-- LUMA — Scénarios jouables : Thématique 15 (Londres) — complète (15.9 déjà fait)
-- ============================================

update scenarios set content = '{"characters": {"staff": "un agent du métro"}, "start_node": "n1", "nodes": {"n1": {"speaker": "staff", "text": "Do you need help with the Underground?", "text_fr": "Besoin d''aide avec le métro ?", "choices": [{"text": "Yes, which line goes to King''s Cross?", "next": "n2"}, {"text": "How do I top up an Oyster card?", "next": "n2b"}]}, "n2": {"speaker": "staff", "text": "Take the Piccadilly line, four stops from here.", "text_fr": "Prenez la ligne Piccadilly, quatre arrêts d''ici.", "choices": [{"text": "Perfect, thank you!", "next": "end_directions"}]}, "n2b": {"speaker": "staff", "text": "There''s a machine right there, or you can tap a contactless card directly.", "text_fr": "Il y a une machine juste là, ou vous pouvez taper une carte sans contact directement.", "choices": [{"text": "Even easier, thanks!", "next": "end_directions"}]}, "end_directions": {"speaker": "staff", "text": "Mind the gap, enjoy your trip!", "text_fr": "Attention à la marche, bon voyage !", "end": true, "ending_label": "Métro maîtrisé 🚇"}}}'::jsonb, is_playable = true
where title = 'Prendre le métro londonien'
  and theme_id = (select id from scenario_themes where position = 15 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"bartender": "le barman"}, "start_node": "n1", "nodes": {"n1": {"speaker": "bartender", "text": "What can I get you?", "text_fr": "Qu''est-ce que je vous sers ?", "choices": [{"text": "A pint of your local ale, please.", "next": "n2"}, {"text": "What would you recommend for someone new to British ales?", "next": "n2b"}]}, "n2": {"speaker": "bartender", "text": "Great choice, coming right up.", "text_fr": "Excellent choix, tout de suite.", "choices": [{"text": "Thanks, cheers!", "next": "end_served"}]}, "n2b": {"speaker": "bartender", "text": "I''d suggest starting with a light bitter, easy on the palate.", "text_fr": "Je suggère de commencer par une bitter légère, douce en bouche.", "choices": [{"text": "Sounds perfect, I''ll try that.", "next": "end_served"}]}, "end_served": {"speaker": "bartender", "text": "There you go, enjoy!", "text_fr": "Voilà, profitez-en !", "end": true, "ending_label": "Pinte servie 🍺"}}}'::jsonb, is_playable = true
where title = 'Commander dans un pub'
  and theme_id = (select id from scenario_themes where position = 15 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"guard": "un agent d''accueil"}, "start_node": "n1", "nodes": {"n1": {"speaker": "guard", "text": "Good morning, can I help?", "text_fr": "Bonjour, je peux vous aider ?", "choices": [{"text": "Yes, what time does the Tower of London open?", "next": "n2"}]}, "n2": {"speaker": "guard", "text": "It opens at 9am, but I''d recommend arriving early to avoid queues.", "text_fr": "Il ouvre à 9h, mais je recommande d''arriver tôt pour éviter les files d''attente.", "choices": [{"text": "Thanks for the tip, I''ll be there early.", "next": "end_info"}]}, "end_info": {"speaker": "guard", "text": "Enjoy your visit!", "text_fr": "Bonne visite !", "end": true, "ending_label": "Information obtenue 🏰"}}}'::jsonb, is_playable = true
where title = 'Demander l''heure d''ouverture d''un monument'
  and theme_id = (select id from scenario_themes where position = 15 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"friend": "ton ami de voyage"}, "start_node": "n1", "nodes": {"n1": {"speaker": "friend", "text": "Big Ben or the London Eye first? We can''t do both before lunch.", "text_fr": "Big Ben ou le London Eye en premier ? On ne peut pas faire les deux avant le déjeuner.", "choices": [{"text": "Let''s do Big Ben first, it''s closer.", "next": "n2"}, {"text": "The London Eye, I want to beat the crowds.", "next": "n2b"}]}, "n2": {"speaker": "friend", "text": "Good call, and Westminster Abbey is right nearby too.", "text_fr": "Bonne idée, et l''abbaye de Westminster est juste à côté aussi.", "choices": [{"text": "Let''s fit that in as well then.", "next": "n3"}]}, "n2b": {"speaker": "friend", "text": "Smart, we got great views with barely any wait!", "text_fr": "Malin, on a eu de belles vues sans presque aucune attente !", "choices": [{"text": "Worth the early start for sure.", "next": "n3"}]}, "n3": {"speaker": "friend", "text": "What a productive day of sightseeing!", "text_fr": "Quelle journée productive de tourisme !", "choices": [{"text": "Definitely, London has so much to offer.", "next": "end_day"}]}, "end_day": {"speaker": "friend", "text": "Let''s celebrate with fish and chips tonight!", "text_fr": "Célébrons avec du fish and chips ce soir !", "end": true, "ending_label": "Journée touristique réussie 🎡"}}}'::jsonb, is_playable = true
where title = 'Une journée touristique avec plusieurs arrêts et choix d''itinéraire'
  and theme_id = (select id from scenario_themes where position = 15 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"local": "un habitué du pub"}, "start_node": "n1", "nodes": {"n1": {"speaker": "local", "text": "First time in London, or a regular visitor?", "text_fr": "Première fois à Londres, ou visiteur régulier ?", "choices": [{"text": "First time actually, loving it so far!", "next": "n2"}]}, "n2": {"speaker": "local", "text": "Welcome! Have you tried a proper Sunday roast yet?", "text_fr": "Bienvenue ! Vous avez déjà essayé un vrai Sunday roast ?", "choices": [{"text": "Not yet, any recommendations?", "next": "n3"}]}, "n3": {"speaker": "local", "text": "There''s a brilliant place just around the corner, I''ll show you.", "text_fr": "Il y a un endroit génial juste au coin, je vais vous montrer.", "choices": [{"text": "That would be amazing, thank you!", "next": "end_local"}]}, "end_local": {"speaker": "local", "text": "This is what London hospitality is all about!", "text_fr": "C''est ça, l''hospitalité londonienne !", "end": true, "ending_label": "Rencontre authentique 🍻"}}}'::jsonb, is_playable = true
where title = 'Une rencontre avec un Londonien dans un pub'
  and theme_id = (select id from scenario_themes where position = 15 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"local": "un passant"}, "start_node": "n1", "nodes": {"n1": {"speaker": "local", "text": "Typical London weather, huh? Didn''t bring an umbrella?", "text_fr": "Typique météo londonienne, hein ? Pas de parapluie ?", "choices": [{"text": "Nope! Any nearby shop where I could buy one?", "next": "n2"}, {"text": "I''ll just find a café to wait it out.", "next": "n2b"}]}, "n2": {"speaker": "local", "text": "There''s a shop just around the corner, sells cheap ones.", "text_fr": "Il y a une boutique juste au coin, qui en vend des pas chers.", "choices": [{"text": "Perfect, thanks for the tip!", "next": "end_prepared"}]}, "n2b": {"speaker": "local", "text": "Good call, that café over there has great tea too.", "text_fr": "Bonne idée, ce café là-bas a aussi un très bon thé.", "choices": [{"text": "Sounds like a plan!", "next": "end_prepared"}]}, "end_prepared": {"speaker": "local", "text": "You''ll get used to the rain if you stay long enough!", "text_fr": "Vous vous habituerez à la pluie si vous restez assez longtemps !", "end": true, "ending_label": "Imprévu météo bien géré ☔"}}}'::jsonb, is_playable = true
where title = 'Un imprévu météo à gérer'
  and theme_id = (select id from scenario_themes where position = 15 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"friend": "ton ami de voyage"}, "start_node": "n1", "nodes": {"n1": {"speaker": "friend", "text": "Day one, museums! Which one first, the British Museum or the Natural History Museum?", "text_fr": "Jour un, musées ! Lequel en premier, le British Museum ou le Natural History Museum ?", "choices": [{"text": "British Museum, I want to see the Rosetta Stone.", "next": "n2"}]}, "n2": {"speaker": "friend", "text": "(days pass) We''ve covered museums, markets, and parks. Final day, what''s left?", "text_fr": "(les jours passent) On a fait musées, marchés et parcs. Dernier jour, qu''est-ce qu''il reste ?", "choices": [{"text": "Let''s do something spontaneous, wander Notting Hill.", "next": "n3"}]}, "n3": {"speaker": "friend", "text": "Best idea all week — this neighborhood is gorgeous!", "text_fr": "Meilleure idée de la semaine — ce quartier est magnifique !", "choices": [{"text": "What an incredible week this has been.", "next": "end_week"}]}, "end_week": {"speaker": "friend", "text": "London really has given us everything this week.", "text_fr": "Londres nous a vraiment tout donné cette semaine.", "end": true, "ending_label": "Semaine complète et mémorable 🇬🇧"}}}'::jsonb, is_playable = true
where title = 'Un séjour complet d''une semaine avec plusieurs journées thématiques'
  and theme_id = (select id from scenario_themes where position = 15 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"passerby1": "premier passant", "passerby2": "deuxième passant"}, "start_node": "n1", "nodes": {"n1": {"speaker": "passerby1", "text": "You look a bit lost, can I help?", "text_fr": "Vous semblez un peu perdu, je peux vous aider ?", "choices": [{"text": "Yes, I''m trying to find Camden Market but I think I took a wrong turn.", "next": "n2"}]}, "n2": {"speaker": "passerby1", "text": "Ah, you''re quite far actually. Ask that shopkeeper, she''ll know better.", "text_fr": "Ah, vous êtes assez loin en fait. Demandez à cette commerçante, elle saura mieux.", "choices": [{"text": "Thank you, I''ll ask her.", "next": "n3"}]}, "n3": {"speaker": "passerby2", "text": "Camden Market? Take the tube from that station, two stops north.", "text_fr": "Camden Market ? Prenez le métro depuis cette station, deux arrêts au nord.", "choices": [{"text": "That''s much clearer now, thank you both!", "next": "end_found"}]}, "end_found": {"speaker": "passerby2", "text": "Londoners always help each other out, no worries!", "text_fr": "Les Londoniens s''entraident toujours, pas de souci !", "end": true, "ending_label": "Chemin retrouvé grâce à l''entraide 🧭"}}}'::jsonb, is_playable = true
where title = 'Se perdre et retrouver son chemin en interagissant avec plusieurs habitants'
  and theme_id = (select id from scenario_themes where position = 15 and language_id = (select id from languages where code = 'en'));
