-- ============================================
-- LUMA — Treasure Island Tome 5 : Chapitres XXII-XXVII (L'aventure en mer de Jim, Israel Hands)
-- Texte original, domaine public
-- ============================================


with s as (select id from books where title = 'Treasure Island' and is_series = true),
     lang as (select id from languages where code = 'en')
insert into books (language_id, title, theme, description, cecr_level, cover_emoji, total_pages, position, series_id, volume_number)
select lang.id, 'Tome 5 : L''aventure en mer', 'Classique • Robert Louis Stevenson (1883)', 'Jim s''échappe seul en mer sur le coracle de Ben Gunn, reprend l''Hispaniola aux pirates, affronte le redoutable Israel Hands, puis tombe droit dans les griffes de Silver.', 'B1-B2', '🌊', 3, 2, s.id, 5
from lang, s;


with b as (select id from books where title = 'Tome 5 : L''aventure en mer' and series_id = (select id from books where title = 'Treasure Island' and is_series = true))
insert into book_pages (book_id, page_number, sentences)
select b.id, 1, '[{"en": "With the mutineers driven off, Jim grew restless in the stockade and secretly filled his pockets with biscuit, deciding to seek Ben Gunn''s hidden boat.", "fr": "Avec les mutins repoussés, Jim devint agité dans la palissade et remplit secrètement ses poches de biscuits, décidant de chercher le bateau caché de Ben Gunn."}, {"en": "He slipped away unseen and found the tiny goatskin coracle hidden beneath a white rock, exactly as Ben Gunn had described.", "fr": "Il s''éclipsa sans être vu et trouva le minuscule coracle en peau de chèvre caché sous un rocher blanc, exactement comme Ben Gunn l''avait décrit."}, {"en": "As night fell, Jim paddled out to the Hispaniola and, working up his courage, cut through the anchor cable one strand at a time.", "fr": "À la tombée de la nuit, Jim pagaya jusqu''à l''Hispaniola et, rassemblant son courage, coupa le câble de l''ancre brin par brin."}, {"en": "Through the cabin window, he glimpsed Israel Hands and another pirate locked in a furious, drunken fight, each with a hand at the other''s throat.", "fr": "À travers la fenêtre de la cabine, il aperçut Israel Hands et un autre pirate engagés dans une bagarre furieuse et ivre, chacun tenant l''autre à la gorge."}, {"en": "The current swept the ship and the tiny coracle out to sea together. Exhausted, Jim eventually fell asleep, dreaming of home.", "fr": "Le courant emporta le navire et le minuscule coracle vers le large ensemble. Épuisé, Jim finit par s''endormir, rêvant de chez lui."}, {"en": "Jim awoke tossing off the island''s coast. After a perilous morning navigating the coracle through rolling swells, he spotted the Hispaniola sailing erratically nearby.", "fr": "Jim se réveilla ballotté au large de l''île. Après une matinée périlleuse à naviguer avec le coracle à travers une houle mouvante, il repéra l''Hispaniola naviguant de façon erratique à proximité."}]'::jsonb from b;


with b as (select id from books where title = 'Tome 5 : L''aventure en mer' and series_id = (select id from books where title = 'Treasure Island' and is_series = true))
insert into book_pages (book_id, page_number, sentences)
select b.id, 2, '[{"en": "Realizing no one was steering, he paddled hard, caught the jib-boom as the ship lurched close, and scrambled safely aboard, his coracle crushed beneath the hull.", "fr": "Réalisant que personne ne barrait, il pagaya avec force, attrapa le bout-dehors alors que le navire se rapprochait, et grimpa à bord en sécurité, son coracle écrasé sous la coque."}, {"en": "On deck, Jim found the pirate in the red cap dead, and Israel Hands gravely wounded, both having stabbed each other in their drunken quarrel.", "fr": "Sur le pont, Jim trouva le pirate au bonnet rouge mort, et Israel Hands gravement blessé, tous deux s''étant poignardés dans leur querelle d''ivrognes."}, {"en": "''Come aboard, Mr. Hands,'' Jim said. Hands, too weak to resist, struck a bargain: he would help sail the ship in exchange for food, drink, and bandages.", "fr": "''Montez à bord, M. Hands,'' dit Jim. Hands, trop faible pour résister, conclut un marché : il aiderait à naviguer le navire en échange de nourriture, de boisson et de bandages."}, {"en": "Jim struck down the pirate flag and declared himself captain. Together, he and the treacherous Hands began sailing toward North Inlet to beach the ship.", "fr": "Jim abattit le drapeau pirate et se déclara capitaine. Ensemble, lui et le perfide Hands commencèrent à naviguer vers l''Anse Nord pour échouer le navire."}, {"en": "Hands tried to trick Jim into fetching wine below deck, secretly retrieving a hidden dirk to attack him. But Jim, suspicious, caught him in the act.", "fr": "Hands essaya de piéger Jim pour qu''il aille chercher du vin sous le pont, récupérant secrètement un poignard caché pour l''attaquer. Mais Jim, méfiant, le surprit en pleine action."}, {"en": "As the ship ran aground, both men were thrown down. Hands lunged with his dirk, but Jim scrambled up the rigging just in time.", "fr": "Alors que le navire s''échouait, les deux hommes furent projetés au sol. Hands se jeta avec son poignard, mais Jim grimpa dans le gréement juste à temps."}]'::jsonb from b;


with b as (select id from books where title = 'Tome 5 : L''aventure en mer' and series_id = (select id from books where title = 'Treasure Island' and is_series = true))
insert into book_pages (book_id, page_number, sentences)
select b.id, 3, '[{"en": "''One more step, Mr. Hands, and I''ll blow your brains out!'' Jim warned, now armed with reloaded pistols. Hands, cornered, hurled his dirk instead.", "fr": "''Un pas de plus, M. Hands, et je vous fais sauter la cervelle !'' avertit Jim, désormais armé de pistolets rechargés. Hands, acculé, lança plutôt son poignard."}, {"en": "The blade pinned Jim''s shoulder to the mast, but in the shock, both his pistols fired at once. Hands lost his grip and plunged into the sea, dead.", "fr": "La lame cloua l''épaule de Jim au mât, mais sous le choc, ses deux pistolets tirèrent en même temps. Hands perdit prise et tomba dans la mer, mort."}, {"en": "Wounded but alive, Jim freed himself from the dirk and threw O''Brien''s body overboard too, finally alone and master of the abandoned ship.", "fr": "Blessé mais vivant, Jim se libéra du poignard et jeta aussi le corps d''O''Brien par-dessus bord, enfin seul et maître du navire abandonné."}, {"en": "He waded ashore and made his way back toward the stockade in the moonlight, proud of having recaptured the Hispaniola single-handed.", "fr": "Il pataugea jusqu''au rivage et se dirigea vers la palissade au clair de lune, fier d''avoir repris l''Hispaniola à lui seul."}, {"en": "But creeping into the dark log-house, he was startled by Silver''s parrot screeching ''Pieces of eight!'' — and found himself surrounded by pirates, not friends. ''Who goes?'' roared Silver''s voice in the dark.", "fr": "Mais en se glissant dans la sombre cabane, il fut surpris par le perroquet de Silver criant ''Pièces de huit !''—et se retrouva entouré de pirates, pas d''amis. ''Qui va là ?'' rugit la voix de Silver dans le noir."}]'::jsonb from b;
