-- ============================================
-- LUMA — Contenu des 10 thèmes de vocabulaire (mots + exercices)
-- ============================================

update vocab_themes set words = '[{"en": "ingredient", "fr": "ingrédient", "level": "A2"}, {"en": "recipe", "fr": "recette", "level": "A2"}, {"en": "spicy", "fr": "épicé", "level": "A2"}, {"en": "delicious", "fr": "délicieux", "level": "A1"}, {"en": "boil", "fr": "bouillir", "level": "A2"}, {"en": "roast", "fr": "rôtir", "level": "B1"}, {"en": "blend", "fr": "mixer", "level": "B1"}, {"en": "leftovers", "fr": "restes", "level": "B1"}, {"en": "appetizer", "fr": "entrée", "level": "B1"}, {"en": "dessert", "fr": "dessert", "level": "A1"}, {"en": "garlic", "fr": "ail", "level": "A2"}, {"en": "dough", "fr": "pâte", "level": "B1"}, {"en": "simmer", "fr": "mijoter", "level": "B2"}, {"en": "seasoning", "fr": "assaisonnement", "level": "B1"}, {"en": "homemade", "fr": "fait maison", "level": "A2"}, {"en": "mouthwatering", "fr": "qui met l''eau à la bouche", "level": "C1"}]'::jsonb where slug = 'cuisine';
with t as (select id from vocab_themes where slug = 'cuisine')
insert into vocab_theme_exercises (theme_id, position, type, content)
select t.id, v.position, v.type, v.content::jsonb from t, (values
(1, 'qcm', '{"question": "\"ingrédient\" = ?", "options": ["dough", "recipe", "ingredient", "blend"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"ingredient\"."}'),(2, 'qcm', '{"question": "\"épicé\" = ?", "options": ["boil", "homemade", "delicious", "spicy"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"spicy\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "boil", "right": "bouillir"}, {"left": "roast", "right": "rôtir"}, {"left": "blend", "right": "mixer"}, {"left": "leftovers", "right": "restes"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "dessert", "right": "dessert"}, {"left": "garlic", "right": "ail"}, {"left": "dough", "right": "pâte"}, {"left": "simmer", "right": "mijoter"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"fait maison\" = ", "sentence_after": "", "correct_answers": ["homemade"], "feedback_correct": "Correct !", "feedback_incorrect": "\"fait maison\" se dit \"homemade\" en anglais."}'),(6, 'true_false', '{"statement": "\"mouthwatering\" veut dire \"qui met l''eau à la bouche\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

update vocab_themes set words = '[{"en": "app", "fr": "application", "level": "A1"}, {"en": "screen", "fr": "écran", "level": "A1"}, {"en": "battery", "fr": "batterie", "level": "A2"}, {"en": "download", "fr": "télécharger", "level": "A2"}, {"en": "wireless", "fr": "sans fil", "level": "B1"}, {"en": "charger", "fr": "chargeur", "level": "A2"}, {"en": "update", "fr": "mise à jour", "level": "A2"}, {"en": "password", "fr": "mot de passe", "level": "A2"}, {"en": "device", "fr": "appareil", "level": "B1"}, {"en": "cloud", "fr": "cloud (stockage)", "level": "B1"}, {"en": "glitch", "fr": "bug", "level": "B2"}, {"en": "upload", "fr": "téléverser", "level": "B1"}, {"en": "browser", "fr": "navigateur", "level": "B1"}, {"en": "notification", "fr": "notification", "level": "A2"}, {"en": "malware", "fr": "logiciel malveillant", "level": "C1"}, {"en": "backup", "fr": "sauvegarde", "level": "B1"}]'::jsonb where slug = 'technologie';
with t as (select id from vocab_themes where slug = 'technologie')
insert into vocab_theme_exercises (theme_id, position, type, content)
select t.id, v.position, v.type, v.content::jsonb from t, (values
(1, 'qcm', '{"question": "\"application\" = ?", "options": ["app", "notification", "password", "browser"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"app\"."}'),(2, 'qcm', '{"question": "\"batterie\" = ?", "options": ["notification", "battery", "download", "malware"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"battery\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "wireless", "right": "sans fil"}, {"left": "charger", "right": "chargeur"}, {"left": "update", "right": "mise à jour"}, {"left": "password", "right": "mot de passe"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "cloud", "right": "cloud (stockage)"}, {"left": "glitch", "right": "bug"}, {"left": "upload", "right": "téléverser"}, {"left": "browser", "right": "navigateur"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"logiciel malveillant\" = ", "sentence_after": "", "correct_answers": ["malware"], "feedback_correct": "Correct !", "feedback_incorrect": "\"logiciel malveillant\" se dit \"malware\" en anglais."}'),(6, 'true_false', '{"statement": "\"backup\" veut dire \"sauvegarde\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

update vocab_themes set words = '[{"en": "coach", "fr": "entraîneur", "level": "A2"}, {"en": "teammate", "fr": "coéquipier", "level": "A2"}, {"en": "referee", "fr": "arbitre", "level": "A2"}, {"en": "score", "fr": "score", "level": "A1"}, {"en": "championship", "fr": "championnat", "level": "B1"}, {"en": "warm-up", "fr": "échauffement", "level": "B1"}, {"en": "stretch", "fr": "s''étirer", "level": "A2"}, {"en": "stamina", "fr": "endurance", "level": "B2"}, {"en": "injury", "fr": "blessure", "level": "A2"}, {"en": "opponent", "fr": "adversaire", "level": "B1"}, {"en": "victory", "fr": "victoire", "level": "A2"}, {"en": "defeat", "fr": "défaite", "level": "B1"}, {"en": "gym", "fr": "salle de sport", "level": "A1"}, {"en": "workout", "fr": "séance d''entraînement", "level": "A2"}, {"en": "sprint", "fr": "sprint", "level": "B1"}, {"en": "marathon", "fr": "marathon", "level": "A2"}]'::jsonb where slug = 'sport';
with t as (select id from vocab_themes where slug = 'sport')
insert into vocab_theme_exercises (theme_id, position, type, content)
select t.id, v.position, v.type, v.content::jsonb from t, (values
(1, 'qcm', '{"question": "\"entraîneur\" = ?", "options": ["opponent", "coach", "referee", "score"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"coach\"."}'),(2, 'qcm', '{"question": "\"arbitre\" = ?", "options": ["injury", "referee", "victory", "sprint"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"referee\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "championship", "right": "championnat"}, {"left": "warm-up", "right": "échauffement"}, {"left": "stretch", "right": "s''étirer"}, {"left": "stamina", "right": "endurance"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "opponent", "right": "adversaire"}, {"left": "victory", "right": "victoire"}, {"left": "defeat", "right": "défaite"}, {"left": "gym", "right": "salle de sport"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"sprint\" = ", "sentence_after": "", "correct_answers": ["sprint"], "feedback_correct": "Correct !", "feedback_incorrect": "\"sprint\" se dit \"sprint\" en anglais."}'),(6, 'true_false', '{"statement": "\"marathon\" veut dire \"marathon\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

update vocab_themes set words = '[{"en": "journey", "fr": "voyage/trajet", "level": "A2"}, {"en": "luggage", "fr": "bagages", "level": "A1"}, {"en": "passport", "fr": "passeport", "level": "A1"}, {"en": "itinerary", "fr": "itinéraire", "level": "B1"}, {"en": "layover", "fr": "escale", "level": "B1"}, {"en": "souvenir", "fr": "souvenir (objet)", "level": "A2"}, {"en": "jet lag", "fr": "décalage horaire", "level": "B1"}, {"en": "sightseeing", "fr": "visite touristique", "level": "A2"}, {"en": "currency", "fr": "devise", "level": "B1"}, {"en": "backpacker", "fr": "routard", "level": "B1"}, {"en": "hostel", "fr": "auberge de jeunesse", "level": "A2"}, {"en": "landmark", "fr": "monument/repère", "level": "B1"}, {"en": "customs", "fr": "douane", "level": "B1"}, {"en": "boarding", "fr": "embarquement", "level": "A2"}, {"en": "excursion", "fr": "excursion", "level": "B1"}, {"en": "wanderlust", "fr": "envie irrépressible de voyager", "level": "C1"}]'::jsonb where slug = 'voyage';
with t as (select id from vocab_themes where slug = 'voyage')
insert into vocab_theme_exercises (theme_id, position, type, content)
select t.id, v.position, v.type, v.content::jsonb from t, (values
(1, 'qcm', '{"question": "\"voyage/trajet\" = ?", "options": ["souvenir", "jet lag", "currency", "journey"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"journey\"."}'),(2, 'qcm', '{"question": "\"passeport\" = ?", "options": ["souvenir", "passport", "jet lag", "wanderlust"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"passport\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "layover", "right": "escale"}, {"left": "souvenir", "right": "souvenir (objet)"}, {"left": "jet lag", "right": "décalage horaire"}, {"left": "sightseeing", "right": "visite touristique"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "backpacker", "right": "routard"}, {"left": "hostel", "right": "auberge de jeunesse"}, {"left": "landmark", "right": "monument/repère"}, {"left": "customs", "right": "douane"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"excursion\" = ", "sentence_after": "", "correct_answers": ["excursion"], "feedback_correct": "Correct !", "feedback_incorrect": "\"excursion\" se dit \"excursion\" en anglais."}'),(6, 'true_false', '{"statement": "\"wanderlust\" veut dire \"envie irrépressible de voyager\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

update vocab_themes set words = '[{"en": "wildlife", "fr": "faune sauvage", "level": "B1"}, {"en": "rainforest", "fr": "forêt tropicale", "level": "B1"}, {"en": "pollution", "fr": "pollution", "level": "A2"}, {"en": "recycle", "fr": "recycler", "level": "A2"}, {"en": "ecosystem", "fr": "écosystème", "level": "B1"}, {"en": "drought", "fr": "sécheresse", "level": "B1"}, {"en": "endangered", "fr": "en voie d''extinction", "level": "B1"}, {"en": "sustainable", "fr": "durable", "level": "B2"}, {"en": "greenhouse", "fr": "effet de serre (gas)", "level": "B2"}, {"en": "habitat", "fr": "habitat naturel", "level": "B1"}, {"en": "conservation", "fr": "protection de l''environnement", "level": "B1"}, {"en": "renewable", "fr": "renouvelable", "level": "B1"}, {"en": "biodiversity", "fr": "biodiversité", "level": "B2"}, {"en": "deforestation", "fr": "déforestation", "level": "B1"}, {"en": "climate", "fr": "climat", "level": "A2"}, {"en": "wilderness", "fr": "nature sauvage", "level": "B2"}]'::jsonb where slug = 'nature';
with t as (select id from vocab_themes where slug = 'nature')
insert into vocab_theme_exercises (theme_id, position, type, content)
select t.id, v.position, v.type, v.content::jsonb from t, (values
(1, 'qcm', '{"question": "\"faune sauvage\" = ?", "options": ["greenhouse", "wildlife", "sustainable", "habitat"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"wildlife\"."}'),(2, 'qcm', '{"question": "\"pollution\" = ?", "options": ["wildlife", "pollution", "habitat", "greenhouse"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"pollution\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "ecosystem", "right": "écosystème"}, {"left": "drought", "right": "sécheresse"}, {"left": "endangered", "right": "en voie d''extinction"}, {"left": "sustainable", "right": "durable"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "habitat", "right": "habitat naturel"}, {"left": "conservation", "right": "protection de l''environnement"}, {"left": "renewable", "right": "renouvelable"}, {"left": "biodiversity", "right": "biodiversité"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"climat\" = ", "sentence_after": "", "correct_answers": ["climate"], "feedback_correct": "Correct !", "feedback_incorrect": "\"climat\" se dit \"climate\" en anglais."}'),(6, 'true_false', '{"statement": "\"wilderness\" veut dire \"nature sauvage\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

update vocab_themes set words = '[{"en": "outfit", "fr": "tenue", "level": "A2"}, {"en": "trendy", "fr": "à la mode", "level": "B1"}, {"en": "discount", "fr": "réduction", "level": "A2"}, {"en": "fitting room", "fr": "cabine d''essayage", "level": "A2"}, {"en": "bargain", "fr": "bonne affaire", "level": "B1"}, {"en": "accessory", "fr": "accessoire", "level": "A2"}, {"en": "fabric", "fr": "tissu", "level": "A2"}, {"en": "checkout", "fr": "caisse", "level": "A1"}, {"en": "receipt", "fr": "ticket de caisse", "level": "A2"}, {"en": "refund", "fr": "remboursement", "level": "B1"}, {"en": "size chart", "fr": "guide des tailles", "level": "B1"}, {"en": "wardrobe", "fr": "garde-robe", "level": "B1"}, {"en": "stylish", "fr": "élégant, stylé", "level": "B1"}, {"en": "secondhand", "fr": "d''occasion", "level": "B1"}, {"en": "splurge", "fr": "se faire plaisir (dépense)", "level": "C1"}, {"en": "browse", "fr": "parcourir/regarder", "level": "A2"}]'::jsonb where slug = 'mode';
with t as (select id from vocab_themes where slug = 'mode')
insert into vocab_theme_exercises (theme_id, position, type, content)
select t.id, v.position, v.type, v.content::jsonb from t, (values
(1, 'qcm', '{"question": "\"tenue\" = ?", "options": ["wardrobe", "outfit", "stylish", "size chart"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"outfit\"."}'),(2, 'qcm', '{"question": "\"réduction\" = ?", "options": ["accessory", "discount", "checkout", "wardrobe"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"discount\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "bargain", "right": "bonne affaire"}, {"left": "accessory", "right": "accessoire"}, {"left": "fabric", "right": "tissu"}, {"left": "checkout", "right": "caisse"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "refund", "right": "remboursement"}, {"left": "size chart", "right": "guide des tailles"}, {"left": "wardrobe", "right": "garde-robe"}, {"left": "stylish", "right": "élégant, stylé"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"se faire plaisir (dépense)\" = ", "sentence_after": "", "correct_answers": ["splurge"], "feedback_correct": "Correct !", "feedback_incorrect": "\"se faire plaisir (dépense)\" se dit \"splurge\" en anglais."}'),(6, 'true_false', '{"statement": "\"browse\" veut dire \"parcourir/regarder\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

update vocab_themes set words = '[{"en": "symptom", "fr": "symptôme", "level": "A2"}, {"en": "prescription", "fr": "ordonnance", "level": "B1"}, {"en": "appointment", "fr": "rendez-vous", "level": "A2"}, {"en": "injury", "fr": "blessure", "level": "A2"}, {"en": "recovery", "fr": "guérison", "level": "B1"}, {"en": "dizzy", "fr": "étourdi", "level": "A2"}, {"en": "nauseous", "fr": "nauséeux", "level": "B1"}, {"en": "allergy", "fr": "allergie", "level": "A2"}, {"en": "checkup", "fr": "examen médical de routine", "level": "B1"}, {"en": "bandage", "fr": "pansement", "level": "A2"}, {"en": "immune", "fr": "immunitaire", "level": "B1"}, {"en": "exhausted", "fr": "épuisé", "level": "A2"}, {"en": "sprain", "fr": "entorse", "level": "B1"}, {"en": "fever", "fr": "fièvre", "level": "A1"}, {"en": "remedy", "fr": "remède", "level": "B1"}, {"en": "wellbeing", "fr": "bien-être", "level": "B2"}]'::jsonb where slug = 'sante';
with t as (select id from vocab_themes where slug = 'sante')
insert into vocab_theme_exercises (theme_id, position, type, content)
select t.id, v.position, v.type, v.content::jsonb from t, (values
(1, 'qcm', '{"question": "\"symptôme\" = ?", "options": ["remedy", "exhausted", "sprain", "symptom"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"symptom\"."}'),(2, 'qcm', '{"question": "\"rendez-vous\" = ?", "options": ["allergy", "recovery", "bandage", "appointment"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"appointment\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "recovery", "right": "guérison"}, {"left": "dizzy", "right": "étourdi"}, {"left": "nauseous", "right": "nauséeux"}, {"left": "allergy", "right": "allergie"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "bandage", "right": "pansement"}, {"left": "immune", "right": "immunitaire"}, {"left": "exhausted", "right": "épuisé"}, {"left": "sprain", "right": "entorse"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"remède\" = ", "sentence_after": "", "correct_answers": ["remedy"], "feedback_correct": "Correct !", "feedback_incorrect": "\"remède\" se dit \"remedy\" en anglais."}'),(6, 'true_false', '{"statement": "\"wellbeing\" veut dire \"bien-être\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

update vocab_themes set words = '[{"en": "deadline", "fr": "date limite", "level": "A2"}, {"en": "colleague", "fr": "collègue", "level": "A1"}, {"en": "promotion", "fr": "promotion", "level": "A2"}, {"en": "salary", "fr": "salaire", "level": "A2"}, {"en": "resign", "fr": "démissionner", "level": "B1"}, {"en": "workload", "fr": "charge de travail", "level": "B1"}, {"en": "meeting", "fr": "réunion", "level": "A1"}, {"en": "overtime", "fr": "heures supplémentaires", "level": "B1"}, {"en": "feedback", "fr": "retour/avis", "level": "B1"}, {"en": "teamwork", "fr": "travail d''équipe", "level": "A2"}, {"en": "spreadsheet", "fr": "tableur", "level": "B1"}, {"en": "negotiate", "fr": "négocier", "level": "B1"}, {"en": "internship", "fr": "stage", "level": "B1"}, {"en": "résumé", "fr": "CV", "level": "A2"}, {"en": "freelance", "fr": "indépendant/freelance", "level": "B1"}, {"en": "burnout", "fr": "épuisement professionnel", "level": "C1"}]'::jsonb where slug = 'travail';
with t as (select id from vocab_themes where slug = 'travail')
insert into vocab_theme_exercises (theme_id, position, type, content)
select t.id, v.position, v.type, v.content::jsonb from t, (values
(1, 'qcm', '{"question": "\"date limite\" = ?", "options": ["workload", "negotiate", "feedback", "deadline"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"deadline\"."}'),(2, 'qcm', '{"question": "\"promotion\" = ?", "options": ["feedback", "promotion", "résumé", "workload"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"promotion\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "resign", "right": "démissionner"}, {"left": "workload", "right": "charge de travail"}, {"left": "meeting", "right": "réunion"}, {"left": "overtime", "right": "heures supplémentaires"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "teamwork", "right": "travail d''équipe"}, {"left": "spreadsheet", "right": "tableur"}, {"left": "negotiate", "right": "négocier"}, {"left": "internship", "right": "stage"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"indépendant/freelance\" = ", "sentence_after": "", "correct_answers": ["freelance"], "feedback_correct": "Correct !", "feedback_incorrect": "\"indépendant/freelance\" se dit \"freelance\" en anglais."}'),(6, 'true_false', '{"statement": "\"burnout\" veut dire \"épuisement professionnel\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

update vocab_themes set words = '[{"en": "furniture", "fr": "meubles", "level": "A1"}, {"en": "cozy", "fr": "confortable/douillet", "level": "A2"}, {"en": "spacious", "fr": "spacieux", "level": "B1"}, {"en": "renovate", "fr": "rénover", "level": "B1"}, {"en": "landlord", "fr": "propriétaire (bailleur)", "level": "B1"}, {"en": "lease", "fr": "bail", "level": "B1"}, {"en": "décor", "fr": "décoration", "level": "A2"}, {"en": "cluttered", "fr": "encombré", "level": "B1"}, {"en": "tidy up", "fr": "ranger", "level": "A2"}, {"en": "moving in", "fr": "emménagement", "level": "A2"}, {"en": "utilities", "fr": "charges (eau, élec...)", "level": "B1"}, {"en": "balcony", "fr": "balcon", "level": "A1"}, {"en": "storage", "fr": "rangement", "level": "A2"}, {"en": "minimalist", "fr": "minimaliste", "level": "B1"}, {"en": "fixer-upper", "fr": "maison à rénover", "level": "C1"}, {"en": "housewarming", "fr": "pendaison de crémaillère", "level": "B2"}]'::jsonb where slug = 'maison';
with t as (select id from vocab_themes where slug = 'maison')
insert into vocab_theme_exercises (theme_id, position, type, content)
select t.id, v.position, v.type, v.content::jsonb from t, (values
(1, 'qcm', '{"question": "\"meubles\" = ?", "options": ["renovate", "balcony", "furniture", "décor"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"furniture\"."}'),(2, 'qcm', '{"question": "\"spacieux\" = ?", "options": ["housewarming", "furniture", "spacious", "storage"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"spacious\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "landlord", "right": "propriétaire (bailleur)"}, {"left": "lease", "right": "bail"}, {"left": "décor", "right": "décoration"}, {"left": "cluttered", "right": "encombré"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "moving in", "right": "emménagement"}, {"left": "utilities", "right": "charges (eau, élec...)"}, {"left": "balcony", "right": "balcon"}, {"left": "storage", "right": "rangement"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"maison à rénover\" = ", "sentence_after": "", "correct_answers": ["fixer-upper"], "feedback_correct": "Correct !", "feedback_incorrect": "\"maison à rénover\" se dit \"fixer-upper\" en anglais."}'),(6, 'true_false', '{"statement": "\"housewarming\" veut dire \"pendaison de crémaillère\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);

update vocab_themes set words = '[{"en": "stubborn", "fr": "têtu", "level": "B1"}, {"en": "generous", "fr": "généreux", "level": "A2"}, {"en": "anxious", "fr": "anxieux", "level": "A2"}, {"en": "confident", "fr": "confiant", "level": "A2"}, {"en": "overwhelmed", "fr": "submergé/dépassé", "level": "B1"}, {"en": "grateful", "fr": "reconnaissant", "level": "A2"}, {"en": "curious", "fr": "curieux", "level": "A1"}, {"en": "patient", "fr": "patient", "level": "A1"}, {"en": "jealous", "fr": "jaloux", "level": "A2"}, {"en": "ambitious", "fr": "ambitieux", "level": "B1"}, {"en": "sensitive", "fr": "sensible", "level": "A2"}, {"en": "easygoing", "fr": "facile à vivre", "level": "B1"}, {"en": "moody", "fr": "lunatique", "level": "B1"}, {"en": "empathetic", "fr": "empathique", "level": "B2"}, {"en": "resilient", "fr": "résilient", "level": "B2"}, {"en": "humble", "fr": "humble", "level": "B1"}]'::jsonb where slug = 'emotions';
with t as (select id from vocab_themes where slug = 'emotions')
insert into vocab_theme_exercises (theme_id, position, type, content)
select t.id, v.position, v.type, v.content::jsonb from t, (values
(1, 'qcm', '{"question": "\"têtu\" = ?", "options": ["generous", "grateful", "confident", "stubborn"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"stubborn\"."}'),(2, 'qcm', '{"question": "\"anxieux\" = ?", "options": ["stubborn", "humble", "ambitious", "anxious"], "correct_index": 3, "feedback_correct": "Correct !", "feedback_incorrect": "La bonne réponse est \"anxious\"."}'),(3, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "overwhelmed", "right": "submergé/dépassé"}, {"left": "grateful", "right": "reconnaissant"}, {"left": "curious", "right": "curieux"}, {"left": "patient", "right": "patient"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(4, 'matching', '{"instruction": "Relie le mot anglais à sa traduction.", "pairs": [{"left": "ambitious", "right": "ambitieux"}, {"left": "sensitive", "right": "sensible"}, {"left": "easygoing", "right": "facile à vivre"}, {"left": "moody", "right": "lunatique"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les mots."}'),(5, 'fill_blank', '{"sentence_before": "\"résilient\" = ", "sentence_after": "", "correct_answers": ["resilient"], "feedback_correct": "Correct !", "feedback_incorrect": "\"résilient\" se dit \"resilient\" en anglais."}'),(6, 'true_false', '{"statement": "\"humble\" veut dire \"humble\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Regarde bien la traduction."}')
) as v(position, type, content);
