-- ============================================
-- LUMA — Scénarios jouables : Thématique 8 (Fantastique) — complète (8.1 déjà fait)
-- ============================================

update scenarios set content = '{"characters": {"merchant": "Old Tam (marchand)"}, "start_node": "n1", "nodes": {"n1": {"speaker": "merchant", "text": "This healing potion? Twenty gold coins, finest in the land!", "text_fr": "Cette potion de soin ? Vingt pièces d''or, la meilleure du royaume !", "choices": [{"text": "Fifteen, and I''ll also buy this dagger.", "next": "n2"}, {"text": "That''s too much for my purse, I''m afraid.", "next": "n2b"}]}, "n2": {"speaker": "merchant", "text": "Ha! Clever bargain — deal, seventeen for both.", "text_fr": "Ha ! Marchandage habile — marché conclu, dix-sept pour les deux.", "choices": [{"text": "Agreed, here''s your gold.", "next": "end_deal"}]}, "n2b": {"speaker": "merchant", "text": "For a fellow traveler, fifteen then, final offer.", "text_fr": "Pour un voyageur comme vous, quinze alors, dernière offre.", "choices": [{"text": "Fair enough, I''ll take it.", "next": "end_deal"}]}, "end_deal": {"speaker": "merchant", "text": "A pleasure doing business with you, traveler!", "text_fr": "Un plaisir de faire affaire avec vous, voyageur !", "end": true, "ending_label": "Marché conclu ⚔️"}}}'::jsonb, is_playable = true
where title = 'Négocier avec un marchand ambulant'
  and theme_id = (select id from scenario_themes where position = 8 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"elder": "l''ancien du village"}, "start_node": "n1", "nodes": {"n1": {"speaker": "elder", "text": "Strange lights were seen near the old tower last night. Will you investigate?", "text_fr": "D''étranges lumières ont été vues près de la vieille tour hier soir. Allez-vous enquêter ?", "choices": [{"text": "Tell me more about this tower first.", "next": "n2"}, {"text": "I''ll head there right away.", "next": "n2b"}]}, "n2": {"speaker": "elder", "text": "It''s said to be cursed, abandoned for a hundred years... until now.", "text_fr": "On dit qu''elle est maudite, abandonnée depuis cent ans... jusqu''à maintenant.", "choices": [{"text": "Then I''ll be careful. I''ll go investigate.", "next": "end_curious"}]}, "n2b": {"speaker": "elder", "text": "Brave choice — may fortune favor you.", "text_fr": "Choix courageux — que la fortune vous sourie.", "choices": [{"text": "I''ll return with answers.", "next": "end_bold"}]}, "end_curious": {"speaker": "elder", "text": "Wise to learn before you leap. Good luck.", "text_fr": "Sage d''apprendre avant de se lancer. Bonne chance.", "end": true, "ending_label": "Quête entamée avec prudence 🔍"}, "end_bold": {"speaker": "elder", "text": "Your courage will be remembered, traveler.", "text_fr": "Votre courage sera retenu, voyageur.", "end": true, "ending_label": "Quête entamée avec audace ⚡"}}}'::jsonb, is_playable = true
where title = 'Un premier indice mystérieux'
  and theme_id = (select id from scenario_themes where position = 8 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"voice": "une voix mystérieuse"}, "start_node": "n1", "nodes": {"n1": {"speaker": "voice", "text": "The path splits here, traveler. Left leads to whispers, right to light.", "text_fr": "Le chemin se divise ici, voyageur. La gauche mène aux murmures, la droite à la lumière.", "choices": [{"text": "I''ll follow the whispers, curiosity calls.", "next": "n2"}, {"text": "I''ll head toward the light, it feels safer.", "next": "n2b"}]}, "n2": {"speaker": "voice", "text": "The whispers speak of a hidden spring with healing waters.", "text_fr": "Les murmures parlent d''une source cachée aux eaux guérisseuses.", "choices": [{"text": "I''ll seek out this spring.", "next": "n3"}]}, "n2b": {"speaker": "voice", "text": "The light reveals a clearing with ancient standing stones.", "text_fr": "La lumière révèle une clairière avec d''anciennes pierres dressées.", "choices": [{"text": "I''ll examine these stones closely.", "next": "n3b"}]}, "n3": {"speaker": "voice", "text": "You find it — the water glows softly, restoring your strength.", "text_fr": "Vous la trouvez — l''eau brille doucement, restaurant vos forces.", "choices": [{"text": "I feel renewed, I''ll continue my journey.", "next": "end_spring"}]}, "n3b": {"speaker": "voice", "text": "The stones hum with ancient magic as you approach.", "text_fr": "Les pierres bourdonnent d''une magie ancienne à votre approche.", "choices": [{"text": "I''ll listen closely to what they reveal.", "next": "end_stones"}]}, "end_spring": {"speaker": "voice", "text": "The forest smiles upon you, traveler.", "text_fr": "La forêt vous sourit, voyageur.", "end": true, "ending_label": "Source guérisseuse trouvée 💧"}, "end_stones": {"speaker": "voice", "text": "You''ve unlocked an ancient secret of this land.", "text_fr": "Vous avez percé un secret ancien de cette terre.", "end": true, "ending_label": "Secret ancien découvert 🗿"}}}'::jsonb, is_playable = true
where title = 'Explorer une forêt enchantée avec des choix de chemin'
  and theme_id = (select id from scenario_themes where position = 8 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"sprite": "un esprit des bois"}, "start_node": "n1", "nodes": {"n1": {"speaker": "sprite", "text": "You seek passage through my forest? What do you offer in return?", "text_fr": "Vous cherchez à traverser ma forêt ? Que m''offrez-vous en retour ?", "choices": [{"text": "I offer this silver coin, a token of respect.", "next": "n2"}, {"text": "I offer a song, if you''ll allow me to sing.", "next": "n2b"}]}, "n2": {"speaker": "sprite", "text": "Silver is fine, but I prefer true kindness. Still, I accept.", "text_fr": "L''argent c''est bien, mais je préfère la vraie gentillesse. Néanmoins, j''accepte.", "choices": [{"text": "Then let me also help mend this broken branch nearby.", "next": "end_kind"}]}, "n2b": {"speaker": "sprite", "text": "(the sprite listens, delighted) A gift of the heart — rare indeed.", "text_fr": "(l''esprit écoute, ravi) Un cadeau du cœur — rare en effet.", "choices": [{"text": "I''m glad it pleases you.", "next": "end_song"}]}, "end_kind": {"speaker": "sprite", "text": "Your kindness has earned you safe passage, always.", "text_fr": "Votre gentillesse vous a valu un passage sûr, à jamais.", "end": true, "ending_label": "Passage éternel accordé 🌿"}, "end_song": {"speaker": "sprite", "text": "Your song shall echo in these woods forever. Pass freely.", "text_fr": "Votre chant résonnera dans ces bois à jamais. Passez librement.", "end": true, "ending_label": "Faveur de l''esprit gagnée 🎵"}}}'::jsonb, is_playable = true
where title = 'Négocier avec une créature magique'
  and theme_id = (select id from scenario_themes where position = 8 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"guardian": "le gardien du temple"}, "start_node": "n1", "nodes": {"n1": {"speaker": "guardian", "text": "\"I speak without a mouth and hear without ears. What am I?\"", "text_fr": "\"Je parle sans bouche et entends sans oreilles. Que suis-je ?\"", "choices": [{"text": "An echo!", "next": "end_correct"}, {"text": "The wind?", "next": "n2b"}]}, "n2b": {"speaker": "guardian", "text": "A clever guess, but not quite. Think again — sound reflecting back.", "text_fr": "Une supposition astucieuse, mais pas tout à fait. Réfléchissez encore — un son qui se répète.", "choices": [{"text": "Ah, of course — an echo!", "next": "end_correct"}]}, "end_correct": {"speaker": "guardian", "text": "Correct! The temple doors open before you.", "text_fr": "Correct ! Les portes du temple s''ouvrent devant vous.", "end": true, "ending_label": "Énigme résolue 🧩"}}}'::jsonb, is_playable = true
where title = 'Résoudre une énigme de temple'
  and theme_id = (select id from scenario_themes where position = 8 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"sage": "le sage du village", "guardian": "le gardien de la caverne"}, "start_node": "n1", "nodes": {"n1": {"speaker": "sage", "text": "The Amulet of Light was stolen and hidden in the Whispering Caves. Will you retrieve it?", "text_fr": "L''Amulette de Lumière a été volée et cachée dans les Grottes Murmurantes. Irez-vous la récupérer ?", "choices": [{"text": "Tell me what dangers await inside.", "next": "n2"}, {"text": "I accept, I''ll leave at once.", "next": "n2b"}]}, "n2": {"speaker": "sage", "text": "A guardian protects it, one who values wisdom over strength.", "text_fr": "Un gardien la protège, qui valorise la sagesse plutôt que la force.", "choices": [{"text": "Then I''ll prepare my mind, not just my sword.", "next": "n3"}]}, "n2b": {"speaker": "sage", "text": "Bold as ever. May the light guide you.", "text_fr": "Toujours aussi audacieux. Que la lumière vous guide.", "choices": [{"text": "I won''t disappoint you.", "next": "n3"}]}, "n3": {"speaker": "guardian", "text": "Halt! Only those who answer truthfully may pass. Why do you seek the amulet?", "text_fr": "Halte ! Seuls ceux qui répondent avec vérité peuvent passer. Pourquoi cherchez-vous l''amulette ?", "choices": [{"text": "To restore light and hope to my village.", "next": "n4"}, {"text": "For the glory and reward it would bring me.", "next": "n4b"}]}, "n4": {"speaker": "guardian", "text": "A pure heart. The amulet is yours to take.", "text_fr": "Un cœur pur. L''amulette est à vous.", "choices": [{"text": "Thank you, guardian. I won''t misuse it.", "next": "end_pure"}]}, "n4b": {"speaker": "guardian", "text": "Honesty, at least. Perhaps that is enough.", "text_fr": "L''honnêteté, au moins. Peut-être est-ce suffisant.", "choices": [{"text": "I appreciate the chance you''re giving me.", "next": "end_honest"}]}, "end_pure": {"speaker": "guardian", "text": "Go, and let the light shine upon your village once more.", "text_fr": "Allez, et que la lumière brille de nouveau sur votre village.", "end": true, "ending_label": "Quête accomplie avec honneur 🏆"}, "end_honest": {"speaker": "guardian", "text": "Take it, but remember what true worth means.", "text_fr": "Prenez-la, mais souvenez-vous de ce que vaut vraiment la vraie valeur.", "end": true, "ending_label": "Quête accomplie avec réserve 🔶"}}}'::jsonb, is_playable = true
where title = 'Une quête complète pour retrouver un artefact'
  and theme_id = (select id from scenario_themes where position = 8 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"king": "le roi Aldric", "queen": "la reine Yssa"}, "start_node": "n1", "nodes": {"n1": {"speaker": "king", "text": "Our kingdoms have been at odds for years. What do you propose to unite us?", "text_fr": "Nos royaumes sont en conflit depuis des années. Que proposez-vous pour nous unir ?", "choices": [{"text": "A trade agreement that benefits both lands equally.", "next": "n2"}, {"text": "A shared defense pact against the coming threat from the north.", "next": "n2b"}]}, "n2": {"speaker": "king", "text": "Interesting. Queen Yssa, what say you?", "text_fr": "Intéressant. Reine Yssa, qu''en dites-vous ?", "choices": [{"text": "(wait for the queen''s response)", "next": "n3"}]}, "n2b": {"speaker": "king", "text": "The northern threat is real indeed. Queen Yssa, your thoughts?", "text_fr": "La menace du nord est bien réelle. Reine Yssa, votre avis ?", "choices": [{"text": "(wait for the queen''s response)", "next": "n3b"}]}, "n3": {"speaker": "queen", "text": "Trade is wise, but I worry it won''t hold in times of true crisis.", "text_fr": "Le commerce est sage, mais je crains que ça ne tienne pas en cas de vraie crise.", "choices": [{"text": "Then let''s combine trade with a mutual defense clause.", "next": "end_full"}]}, "n3b": {"speaker": "queen", "text": "A defense pact alone may create distrust without shared prosperity.", "text_fr": "Un pacte de défense seul pourrait créer de la méfiance sans prospérité partagée.", "choices": [{"text": "Agreed — let''s add trade terms to strengthen the bond.", "next": "end_full"}]}, "end_full": {"speaker": "king", "text": "A wise compromise. Let this alliance be sealed today.", "text_fr": "Un compromis sage. Que cette alliance soit scellée aujourd''hui.", "end": true, "ending_label": "Alliance historique scellée 🤝"}}}'::jsonb, is_playable = true
where title = 'Une alliance à nouer entre plusieurs royaumes'
  and theme_id = (select id from scenario_themes where position = 8 and language_id = (select id from languages where code = 'en'));

update scenarios set content = '{"characters": {"villain": "le seigneur des ombres"}, "start_node": "n1", "nodes": {"n1": {"speaker": "villain", "text": "So, you''ve come at last. Will you fight, or will you try to reason with me?", "text_fr": "Alors, vous voilà enfin. Allez-vous vous battre, ou tenter de me raisonner ?", "choices": [{"text": "I''ll try to understand what drove you to this darkness.", "next": "n2"}, {"text": "I''m ready to fight, if that''s what it takes.", "next": "n2b"}]}, "n2": {"speaker": "villain", "text": "(pauses) ...No one has asked me that in a very long time.", "text_fr": "(marque une pause) ...Personne ne m''a demandé ça depuis très longtemps.", "choices": [{"text": "It''s not too late to choose a different path.", "next": "end_redeemed"}]}, "n2b": {"speaker": "villain", "text": "Then let us settle this the old way!", "text_fr": "Alors réglons cela à l''ancienne !", "choices": [{"text": "(a fierce battle follows, and you emerge victorious)", "next": "end_victory"}]}, "end_redeemed": {"speaker": "villain", "text": "Perhaps... perhaps there is another way. Thank you, traveler.", "text_fr": "Peut-être... peut-être y a-t-il une autre voie. Merci, voyageur.", "end": true, "ending_label": "Rédemption inattendue 🌅"}, "end_victory": {"speaker": "villain", "text": "You have won... this land is free once more.", "text_fr": "Vous avez gagné... cette terre est de nouveau libre.", "end": true, "ending_label": "Victoire héroïque ⚔️"}}}'::jsonb, is_playable = true
where title = 'Un affrontement final avec plusieurs issues'
  and theme_id = (select id from scenario_themes where position = 8 and language_id = (select id from languages where code = 'en'));
