-- ============================================
-- LUMA — Intégration des premières vraies images (remplace les emoji)
-- Leçon 3 (animaux) : 6/6 mots remplacés par de vraies images
-- Leçon 8 (objets maison) : 6 mots remplacés + 5 mots bonus ajoutés
-- Leçon 13 (transports) : 6 mots remplacés + 6 mots bonus ajoutés
-- ============================================

update lessons set content = jsonb_set(content, '{table}', '[{"subject": "dog", "affirmative": "chien", "negative": "/images/vocab/dog.png"}, {"subject": "cat", "affirmative": "chat", "negative": "/images/vocab/cat.png"}, {"subject": "bird", "affirmative": "oiseau", "negative": "/images/vocab/bird.png"}, {"subject": "fish", "affirmative": "poisson", "negative": "/images/vocab/fish.png"}, {"subject": "rabbit", "affirmative": "lapin", "negative": "/images/vocab/rabbit.png"}, {"subject": "horse", "affirmative": "cheval", "negative": "/images/vocab/horse.png"}]'::jsonb)
where unit_id = (select id from units where cecr_level = 'A0' and position = 0) and position = 3;

update lessons set content = jsonb_set(content, '{table}', '[{"subject": "table", "affirmative": "table", "negative": "/images/vocab/table.png"}, {"subject": "chair", "affirmative": "chaise", "negative": "/images/vocab/chair.png"}, {"subject": "bed", "affirmative": "lit", "negative": "/images/vocab/bed.png"}, {"subject": "door", "affirmative": "porte", "negative": "🚪"}, {"subject": "window", "affirmative": "fenêtre", "negative": "🪟"}, {"subject": "key", "affirmative": "clé", "negative": "/images/vocab/key.png"}, {"subject": "sofa", "affirmative": "canapé", "negative": "/images/vocab/sofa.png"}, {"subject": "wardrobe", "affirmative": "armoire", "negative": "/images/vocab/wardrobe.png"}, {"subject": "lamp", "affirmative": "lampe", "negative": "/images/vocab/lamp.png"}, {"subject": "plant", "affirmative": "plante", "negative": "/images/vocab/plant.png"}, {"subject": "mug", "affirmative": "tasse", "negative": "/images/vocab/mug.png"}]'::jsonb)
where unit_id = (select id from units where cecr_level = 'A0' and position = 0) and position = 8;

with l as (select lessons.id from lessons join units on units.id = lessons.unit_id where units.cecr_level = 'A0' and units.position = 0 and lessons.position = 8)
insert into exercises (lesson_id, type, position, content)
select l.id, v.position, v.type, v.content::jsonb from l, (values
(10, 'matching', '{"instruction": "Relie l''image au bon mot.", "pairs": [{"left": "/images/vocab/sofa.png", "right": "sofa", "speak": "sofa"}, {"left": "/images/vocab/wardrobe.png", "right": "wardrobe", "speak": "wardrobe"}, {"left": "/images/vocab/lamp.png", "right": "lamp", "speak": "lamp"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les images."}'),(11, 'qcm', '{"image": "/images/vocab/sofa.png", "question": "Quel est ce mot ?", "options": ["sofa", "chair", "bed", "lamp"], "correct_index": 0, "feedback_correct": "Correct !", "feedback_incorrect": "C''était \"sofa\" (canapé)."}'),(12, 'qcm', '{"image": "/images/vocab/plant.png", "question": "Quel est ce mot ?", "options": ["mug", "plant", "lamp", "wardrobe"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "C''était \"plant\" (plante)."}'),(13, 'qcm', '{"image": "/images/vocab/mug.png", "question": "Quel est ce mot ?", "options": ["sofa", "wardrobe", "mug", "plant"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "C''était \"mug\" (tasse)."}'),(14, 'true_false', '{"statement": "\"Wardrobe\" veut dire \"armoire\".", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Si, \"wardrobe\" veut bien dire \"armoire\"."}')
) as v(position, type, content);

update lessons set content = jsonb_set(content, '{table}', '[{"subject": "car", "affirmative": "voiture", "negative": "/images/vocab/car.png"}, {"subject": "bus", "affirmative": "bus", "negative": "/images/vocab/bus.png"}, {"subject": "train", "affirmative": "train", "negative": "/images/vocab/train.png"}, {"subject": "bike", "affirmative": "vélo", "negative": "/images/vocab/bike.png"}, {"subject": "plane", "affirmative": "avion", "negative": "/images/vocab/plane.png"}, {"subject": "boat", "affirmative": "bateau", "negative": "/images/vocab/boat.png"}, {"subject": "motorcycle", "affirmative": "moto", "negative": "/images/vocab/motorcycle.png"}, {"subject": "taxi", "affirmative": "taxi", "negative": "/images/vocab/taxi.png"}, {"subject": "truck", "affirmative": "camion", "negative": "/images/vocab/truck.png"}, {"subject": "scooter", "affirmative": "scooter", "negative": "/images/vocab/scooter.png"}, {"subject": "cruise ship", "affirmative": "paquebot", "negative": "/images/vocab/cruise_ship.png"}, {"subject": "helicopter", "affirmative": "hélicoptère", "negative": "/images/vocab/helicopter.png"}]'::jsonb)
where unit_id = (select id from units where cecr_level = 'A0' and position = 0) and position = 13;

with l as (select lessons.id from lessons join units on units.id = lessons.unit_id where units.cecr_level = 'A0' and units.position = 0 and lessons.position = 13)
insert into exercises (lesson_id, type, position, content)
select l.id, v.position, v.type, v.content::jsonb from l, (values
(10, 'matching', '{"instruction": "Relie l''image au bon mot.", "pairs": [{"left": "/images/vocab/motorcycle.png", "right": "motorcycle", "speak": "motorcycle"}, {"left": "/images/vocab/taxi.png", "right": "taxi", "speak": "taxi"}, {"left": "/images/vocab/truck.png", "right": "truck", "speak": "truck"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les images."}'),(11, 'matching', '{"instruction": "Relie l''image au bon mot.", "pairs": [{"left": "/images/vocab/scooter.png", "right": "scooter", "speak": "scooter"}, {"left": "/images/vocab/cruise_ship.png", "right": "cruise ship", "speak": "cruise ship"}, {"left": "/images/vocab/helicopter.png", "right": "helicopter", "speak": "helicopter"}], "feedback_correct": "Bravo !", "feedback_incorrect": "Regarde bien les images."}'),(12, 'qcm', '{"image": "/images/vocab/truck.png", "question": "Quel est ce mot ?", "options": ["taxi", "truck", "scooter", "motorcycle"], "correct_index": 1, "feedback_correct": "Correct !", "feedback_incorrect": "C''était \"truck\" (camion)."}'),(13, 'qcm', '{"image": "/images/vocab/helicopter.png", "question": "Quel est ce mot ?", "options": ["cruise ship", "scooter", "helicopter", "taxi"], "correct_index": 2, "feedback_correct": "Correct !", "feedback_incorrect": "C''était \"helicopter\" (hélicoptère)."}'),(14, 'true_false', '{"statement": "\"Taxi\" se dit \"taxi\" en anglais, comme en français.", "correct_answer": true, "feedback_correct": "Correct !", "feedback_incorrect": "Si, c''est le même mot dans les deux langues."}')
) as v(position, type, content);
