-- ============================================
-- LUMA — Série 'Treasure Island' (Robert Louis Stevenson, 1883)
-- Livre-série (conteneur) + Tome 1 : Chapitres I-VI 'The Old Buccaneer'
-- Texte original, domaine public
-- ============================================


with lang as (select id from languages where code = 'en')
insert into books (language_id, title, theme, description, cecr_level, cover_emoji, total_pages, position, is_series)
select id, 'Treasure Island', 'Classique • Robert Louis Stevenson (1883)', 'L''histoire complète de Jim Hawkins, d''une carte au trésor, et de la quête du butin du capitaine Flint, en plusieurs tomes. Domaine public.', 'B1-B2', '🏴‍☠️', 0, 8, true
from lang;


with s as (select id from books where title = 'Treasure Island' and is_series = true),
     lang as (select id from languages where code = 'en')
insert into books (language_id, title, theme, description, cecr_level, cover_emoji, total_pages, position, series_id, volume_number)
select lang.id, 'Tome 1 : Le vieux flibustier', 'Classique • Robert Louis Stevenson (1883)', 'Le jeune Jim Hawkins rencontre un mystérieux vieux marin, échappe à des flibustiers, et découvre une carte au trésor.', 'B1-B2', '🏴‍☠️', 6, 1, s.id, 1
from lang, s;


with b as (select id from books where title = 'Tome 1 : Le vieux flibustier' and series_id = (select id from books where title = 'Treasure Island' and is_series = true))
insert into book_pages (book_id, page_number, sentences)
select b.id, 1, '[{"en": "I remember him as if it were yesterday, as he came plodding to the inn door, his sea-chest following behind him.", "fr": "Je me souviens de lui comme si c''était hier, arrivant d''un pas lourd à la porte de l''auberge, son coffre de marin le suivant."}, {"en": "A tall, strong, heavy man, his tarry pigtail falling over the shoulder of his soiled blue coat, with a sabre cut across one cheek.", "fr": "Un homme grand, fort, robuste, sa tresse goudronnée tombant sur l''épaule de son manteau bleu sali, avec une balafre de sabre sur une joue."}, {"en": "''This is a handy cove,'' says he at length, ''and a pleasant sittyated grog-shop. Much company, mate?''", "fr": "''Voilà une crique bien commode,'' dit-il enfin, ''et une taverne agréablement située. Beaucoup de monde, l''ami ?''"}, {"en": "My father told him no, very little company, the more was the pity.", "fr": "Mon père lui dit que non, très peu de monde, ce qui était bien dommage."}, {"en": "''Well, then,'' said he, ''this is the berth for me. I''m a plain man; rum and bacon and eggs is what I want.''", "fr": "''Eh bien alors,'' dit-il, ''voici ma place. Je suis un homme simple ; du rhum, du bacon et des œufs, voilà ce qu''il me faut.''"}, {"en": "And indeed bad as his clothes were, he had none of the appearance of a common sailor, but seemed like a mate or skipper accustomed to be obeyed.", "fr": "Et en effet, malgré ses vêtements usés, il n''avait rien de l''apparence d''un simple marin, mais ressemblait plutôt à un second ou un capitaine habitué à être obéi."}]'::jsonb from b;


with b as (select id from books where title = 'Tome 1 : Le vieux flibustier' and series_id = (select id from books where title = 'Treasure Island' and is_series = true))
insert into book_pages (book_id, page_number, sentences)
select b.id, 2, '[{"en": "He had taken me aside one day and promised me a silver fourpenny if I would keep my ''weather-eye open for a seafaring man with one leg.''", "fr": "Il m''avait pris à part un jour et m''avait promis quatre pence d''argent si je gardais ''l''œil ouvert pour un marin avec une seule jambe.''"}, {"en": "How that personage haunted my dreams, I need scarcely tell you. On stormy nights I would see him in a thousand diabolical forms.", "fr": "Combien ce personnage hantait mes rêves, j''ai à peine besoin de le dire. Les nuits d''orage, je le voyais sous mille formes diaboliques."}, {"en": "His stories were what frightened people worst of all — dreadful stories about hanging, and walking the plank, and storms at sea.", "fr": "Ses histoires étaient ce qui effrayait le plus les gens — des histoires terribles de pendaisons, de marche sur la planche, et de tempêtes en mer."}, {"en": "All the time he lived with us the captain made no change whatever in his dress, and the great sea-chest none of us had ever seen open.", "fr": "Pendant tout le temps qu''il vécut chez nous, le capitaine ne changea jamais sa tenue, et personne n''avait jamais vu son grand coffre de marin ouvert."}, {"en": "One evening, Dr. Livesey came to see my sick father, and the captain, far gone in rum, began to pipe up his eternal song about the dead man''s chest.", "fr": "Un soir, le Dr Livesey vint voir mon père malade, et le capitaine, bien avancé dans le rhum, se mit à entonner son éternelle chanson sur le coffre de l''homme mort."}, {"en": "The doctor warned him calmly: ''If you keep on drinking rum, the world will soon be quit of a very dirty scoundrel!''", "fr": "Le docteur l''avertit calmement : ''Si vous continuez à boire du rhum, le monde sera bientôt débarrassé d''un très sale coquin !''"}]'::jsonb from b;


with b as (select id from books where title = 'Tome 1 : Le vieux flibustier' and series_id = (select id from books where title = 'Treasure Island' and is_series = true))
insert into book_pages (book_id, page_number, sentences)
select b.id, 3, '[{"en": "A pale, tallowy creature, wanting two fingers of the left hand, stepped into the parlour one morning and asked for ''my mate Bill.''", "fr": "Une créature pâle et blafarde, à qui manquaient deux doigts de la main gauche, entra dans le salon un matin et demanda ''mon camarade Bill.''"}, {"en": "When the captain returned and saw him, all the brown had gone out of his face. ''Black Dog!'' said he.", "fr": "Quand le capitaine revint et le vit, tout le bronzage disparut de son visage. ''Chien Noir !'' dit-il."}, {"en": "The two men talked, then suddenly there was a tremendous explosion of oaths, a clash of steel, and a cry of pain.", "fr": "Les deux hommes discutèrent, puis soudain il y eut une explosion terrible de jurons, un cliquetis d''acier, et un cri de douleur."}, {"en": "Black Dog fled in full flight, the captain hotly pursuing, both with drawn cutlasses. Black Dog disappeared over the hill.", "fr": "Chien Noir s''enfuit à toutes jambes, le capitaine le poursuivant avec ardeur, tous deux sabre au clair. Chien Noir disparut par-delà la colline."}, {"en": "The captain, weak and excited, begged me for rum, cursing the doctor. ''I''ve got to have my rum, Jim, I tell you,'' he said.", "fr": "Le capitaine, faible et agité, me supplia de lui apporter du rhum, maudissant le docteur. ''Il me faut mon rhum, Jim, je te dis,'' dit-il."}, {"en": "He told me of a blind beggar and a black spot — a summons among sailors that meant terrible trouble.", "fr": "Il me parla d''un mendiant aveugle et d''une marque noire — une convocation chez les marins qui signifiait de terribles ennuis."}]'::jsonb from b;


with b as (select id from books where title = 'Tome 1 : Le vieux flibustier' and series_id = (select id from books where title = 'Treasure Island' and is_series = true))
insert into book_pages (book_id, page_number, sentences)
select b.id, 4, '[{"en": "A blind man tapped his way to the inn one afternoon, gripped my hand like a vise, and demanded to be taken to the captain.", "fr": "Un aveugle vint jusqu''à l''auberge en tapotant le sol un après-midi, saisit ma main comme un étau, et exigea d''être conduit au capitaine."}, {"en": "He pressed something into the captain''s hand, then vanished as quickly as he had come.", "fr": "Il pressa quelque chose dans la main du capitaine, puis disparut aussi vite qu''il était venu."}, {"en": "The captain looked at what was in his palm and cried, ''Ten o''clock! Six hours. We''ll do them yet!'' Then he sprang up and fell dead.", "fr": "Le capitaine regarda ce qu''il avait dans la paume et s''écria : ''Dix heures ! Six heures. On les aura encore !'' Puis il se leva d''un bond et tomba mort."}, {"en": "He had been struck dead by thundering apoplexy, right there on the parlour floor.", "fr": "Il avait été frappé mort par une apoplexie foudroyante, là même sur le sol du salon."}, {"en": "My mother and I, in danger and alone, went to the sea-chest and found the key hanging on a string around the dead captain''s neck.", "fr": "Ma mère et moi, en danger et seuls, allâmes au coffre de marin et trouvâmes la clé pendue à une ficelle autour du cou du capitaine mort."}, {"en": "Inside were gold coins of every country, and at the bottom, a bundle wrapped in oilcloth, and a bag that jingled with gold.", "fr": "À l''intérieur se trouvaient des pièces d''or de tous les pays, et au fond, un paquet enveloppé de toile cirée, et un sac qui tintait d''or."}]'::jsonb from b;


with b as (select id from books where title = 'Tome 1 : Le vieux flibustier' and series_id = (select id from books where title = 'Treasure Island' and is_series = true))
insert into book_pages (book_id, page_number, sentences)
select b.id, 5, '[{"en": "Just then we heard the tap-tapping of the blind man''s stick upon the frozen road, drawing nearer and nearer.", "fr": "C''est alors que nous entendîmes le tapotement de la canne de l''aveugle sur la route gelée, se rapprochant de plus en plus."}, {"en": "We fled into the night with the money and the oilskin packet, hiding beneath a bridge as our pursuers searched for us.", "fr": "Nous fuîmes dans la nuit avec l''argent et le paquet en toile cirée, nous cachant sous un pont pendant que nos poursuivants nous cherchaient."}, {"en": "Seven or eight men, led by the terrible blind beggar Pew, ransacked the inn searching for us and the papers.", "fr": "Sept ou huit hommes, menés par le terrible mendiant aveugle Pew, fouillèrent l''auberge à notre recherche et à celle des papiers."}, {"en": "A whistle sounded from the hillside, warning the buccaneers of approaching danger, and they scattered in every direction.", "fr": "Un sifflement retentit depuis la colline, avertissant les flibustiers d''un danger approchant, et ils se dispersèrent dans toutes les directions."}, {"en": "Pew, abandoned by his companions, ran straight under the hooves of galloping horses and was trampled to death.", "fr": "Pew, abandonné par ses compagnons, courut droit sous les sabots de chevaux au galop et fut piétiné à mort."}, {"en": "The riders were revenue officers who had come to help us, saving my mother and me from certain danger.", "fr": "Les cavaliers étaient des officiers des douanes venus nous aider, sauvant ma mère et moi d''un danger certain."}]'::jsonb from b;


with b as (select id from books where title = 'Tome 1 : Le vieux flibustier' and series_id = (select id from books where title = 'Treasure Island' and is_series = true))
insert into book_pages (book_id, page_number, sentences)
select b.id, 6, '[{"en": "At Dr. Livesey''s house, I gave him the oilskin packet, which contained a book of accounts and a sealed map.", "fr": "Chez le Dr Livesey, je lui donnai le paquet de toile cirée, qui contenait un livre de comptes et une carte scellée."}, {"en": "The map showed an island with three red crosses marking where Captain Flint had buried his treasure.", "fr": "La carte montrait une île avec trois croix rouges indiquant où le capitaine Flint avait enterré son trésor."}, {"en": "Squire Trelawney declared, ''Tomorrow I start for Bristol. We''ll have the best ship, and Hawkins shall come as cabin-boy!''", "fr": "Le châtelain Trelawney déclara : ''Demain je pars pour Bristol. Nous aurons le meilleur navire, et Hawkins viendra comme mousse !''"}, {"en": "And so began our voyage — Jim Hawkins, Dr. Livesey, and Squire Trelawney — in search of Treasure Island.", "fr": "Et ainsi commença notre voyage — Jim Hawkins, le Dr Livesey, et le châtelain Trelawney — à la recherche de l''Île au trésor."}]'::jsonb from b;
