-- ============================================
-- LUMA — Thème 16 (Australie/WHV) : 3 scénarios COURTS x4
-- ============================================


update scenarios set content = '{"characters": {"receptionist": "la réceptionniste"}, "start_node": "n1", "nodes": {"n1": {"speaker": "receptionist", "text": "G''day! Looking for a bed for the night, or something longer term?", "text_fr": "Salut ! Vous cherchez un lit pour la nuit, ou quelque chose de plus long terme ?", "choices": [{"text": "Just tonight, do you have any dorm beds free?", "text_fr": "Juste ce soir, il vous reste des lits en dortoir ?", "next": "n2"}, {"text": "Actually, I''m looking for a weekly rate, I''ll be job hunting.", "text_fr": "En fait, je cherche un tarif hebdomadaire, je vais chercher du travail.", "next": "n2b"}]}, "n2": {"speaker": "receptionist", "text": "Yep, one bed left in the 6-share dorm, $35 for the night.", "text_fr": "Ouais, il reste un lit dans le dortoir de 6, 35$ la nuit.", "choices": [{"text": "Perfect, I''ll take it. Is breakfast included?", "text_fr": "Parfait, je le prends. Le petit-déjeuner est inclus ?", "next": "n3"}]}, "n2b": {"speaker": "receptionist", "text": "We''ve got a weekly rate, $210, and we post local job ads on the noticeboard too.", "text_fr": "On a un tarif hebdomadaire, 210$, et on affiche des offres d''emploi locales sur le tableau aussi.", "choices": [{"text": "That''s really helpful, I''ll take the weekly rate then.", "text_fr": "C''est vraiment utile, je vais prendre le tarif hebdomadaire alors.", "next": "n3"}]}, "n3": {"speaker": "receptionist", "text": "Basic toast and coffee, yeah, included every morning.", "text_fr": "Du pain grillé basique et du café, ouais, inclus chaque matin.", "choices": [{"text": "Perfect, that works for me.", "text_fr": "Parfait, ça me convient.", "next": "n4"}, {"text": "Great, and is there a kitchen I could use for other meals?", "text_fr": "Super, et il y a une cuisine que je pourrais utiliser pour d''autres repas ?", "next": "n4"}]}, "n4": {"speaker": "receptionist", "text": "Yep, shared kitchen''s down the hall, free for guests to use anytime.", "text_fr": "Ouais, la cuisine commune est au bout du couloir, libre d''utilisation pour les clients à tout moment.", "choices": [{"text": "Perfect, that''ll save me some money on food.", "text_fr": "Parfait, ça va m''économiser de l''argent sur la nourriture.", "next": "n5"}]}, "n5": {"speaker": "receptionist", "text": "Here''s your key, dorm''s just down the hall on the left.", "text_fr": "Voici votre clé, le dortoir est juste au bout du couloir à gauche.", "choices": [{"text": "Thank you so much for all the info!", "text_fr": "Merci beaucoup pour toutes ces infos !", "next": "end_settled"}]}, "end_settled": {"speaker": "receptionist", "text": "No worries, welcome to Sydney, mate!", "text_fr": "Aucun souci, bienvenue à Sydney !", "end": true, "ending_label": "Logement trouvé, bien installé 🏨🇦🇺"}}}'::jsonb, is_playable = true
where title = 'Trouver une auberge de jeunesse à Sydney'
  and theme_id = (select id from scenario_themes where position = 16 and language_id = (select id from languages where code = 'en'));


update scenarios set content = '{"characters": {"farmer": "le fermier"}, "start_node": "n1", "nodes": {"n1": {"speaker": "farmer", "text": "So you''re after fruit picking work? Ever done it before?", "text_fr": "Donc vous cherchez du travail de cueillette ? Vous en avez déjà fait ?", "choices": [{"text": "No, but I''m a fast learner and used to physical work.", "text_fr": "Non, mais j''apprends vite et je suis habitué au travail physique.", "next": "n2"}, {"text": "Yes, I picked grapes back home for a season.", "text_fr": "Oui, j''ai cueilli des raisins chez moi pendant une saison.", "next": "n2b"}]}, "n2": {"speaker": "farmer", "text": "Fair enough, we''ll start you slow and see how you go.", "text_fr": "D''accord, on va vous démarrer doucement et voir comment ça se passe.", "choices": [{"text": "Sounds good, I''m ready to work hard.", "text_fr": "Ça marche, je suis prêt à travailler dur.", "next": "n3"}]}, "n2b": {"speaker": "farmer", "text": "Even better, that experience will help a lot here.", "text_fr": "Encore mieux, cette expérience va bien aider ici.", "choices": [{"text": "Great, when can I start?", "text_fr": "Super, je peux commencer quand ?", "next": "n3"}]}, "n3": {"speaker": "farmer", "text": "What about accommodation, sorted or do you need farm housing?", "text_fr": "Et pour le logement, réglé ou vous avez besoin du logement de la ferme ?", "choices": [{"text": "I''d need farm housing, if that''s available.", "text_fr": "J''aurais besoin du logement de la ferme, si c''est disponible.", "next": "n4"}, {"text": "I''ve got that sorted already, staying in town nearby.", "text_fr": "J''ai déjà réglé ça, je loge en ville à proximité.", "next": "n4"}]}, "n4": {"speaker": "farmer", "text": "No worries, we''ve got a shed set up for workers, basic but comfortable.", "text_fr": "Aucun souci, on a un abri aménagé pour les travailleurs, basique mais confortable.", "choices": [{"text": "That sounds perfect, thank you.", "text_fr": "Ça a l''air parfait, merci.", "next": "n5"}]}, "n5": {"speaker": "farmer", "text": "Start tomorrow at 6am, bring a hat and sunscreen!", "text_fr": "Vous commencez demain à 6h, apportez un chapeau et de la crème solaire !", "choices": [{"text": "Will do, thank you for the opportunity!", "text_fr": "C''est noté, merci pour l''opportunité !", "next": "end_hired"}]}, "end_hired": {"speaker": "farmer", "text": "No worries, welcome aboard, mate!", "text_fr": "Aucun souci, bienvenue à bord !", "end": true, "ending_label": "Job saisonnier obtenu 🍇🚜"}}}'::jsonb, is_playable = true
where title = 'Postuler à un job saisonnier dans une ferme'
  and theme_id = (select id from scenario_themes where position = 16 and language_id = (select id from languages where code = 'en'));
